import { Benefit } from '../types';

export const BIZNES: Benefit[] = [
  {
    id: 'ulga-na-start', nazwa: 'Ulga na Start', kategoria: 'BIZNES',
    kwota: 'ok. 1 927 PLN/mies. oszczednosci (brak skladek spolecznych)', kwotaMin: 1927, kwotaMax: 1927,
    czestotliwosc: 'miesiecznie (6 pelnych miesiecy)',
    wymagania: { prowadzDzialalnosc: true, pierwszaDzialalnosc: true },
    wykluczenia: [
      { opis: 'Prowadziles dzialalnosc gospodarcza w ciagu ostatnich 60 miesiecy', sprawdz: 'biznes_60_miesiecy' },
      { opis: 'Wykonujesz dzialalnosc na rzecz bylego pracodawcy', sprawdz: 'byly_pracodawca' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'], formularz: 'ZUS ZZA',
      dokumenty: ['Potwierdzenie rejestracji w CEIDG', 'Dowod osobisty'],
      kroki: [
        'Zarejestruj dzialalnosc w CEIDG (biznes.gov.pl)',
        'Zaloguj sie na PUE ZUS',
        'Zglos sie do ubezpieczenia zdrowotnego na formularzu ZUS ZZA',
        'NIE zglaszaj sie do ubezpieczen spolecznych -- to jest istota ulgi',
        'Przez 6 pelnych miesiecy placisz TYLKO skladke zdrowotna',
      ],
      terminRealizacji: 'Automatycznie od dnia rejestracji',
      pulapki: [
        'PULAPKA: Jesli miałes JAKAKOLWIEK dzialalnosc w ostatnich 60 miesiacach (nawet zawieszona) -- nie kwalifikujesz sie',
        'Liczy sie 6 PELNYCH miesiecy -- jesli zaczynasz w polowie miesiaca, ten miesiac sie nie liczy',
        'Nie mozesz wykonywac uslug na rzecz bylego pracodawcy (u ktorego pracowales w tym lub poprzednim roku)',
      ],
      odwolanie: 'Odwolanie do Sadu Pracy',
    },
    zrodloUrl: 'https://www.biznes.gov.pl/pl/portal/00271',
    zrodloNazwa: 'biznes.gov.pl', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'preferencyjny-zus', nazwa: 'Preferencyjny ZUS (maly ZUS)', kategoria: 'BIZNES',
    kwota: 'ok. 456 PLN/mies. zamiast ok. 1 600 PLN/mies.', kwotaMin: 456, kwotaMax: 456,
    czestotliwosc: 'miesiecznie (24 pelne miesiace)',
    wymagania: { prowadzDzialalnosc: true, miesiaceDzialalnosci: { min: 6, max: 30 } },
    wykluczenia: [{ opis: 'Wykonujesz dzialalnosc na rzecz bylego pracodawcy', sprawdz: 'byly_pracodawca' }],
    wniosek: {
      kanal: ['PUE_ZUS'], formularz: 'ZUS ZUA + ZUS DRA',
      dokumenty: ['Potwierdzenie zakonczenia Ulgi na Start (lub 6 mies. dzialalnosci)'],
      kroki: [
        'Po zakonczeniu Ulgi na Start (lub od razu jesli nie korzystales)',
        'Wyrejestruj sie z ZUS ZZA i zarejestruj na ZUS ZUA z kodem 05 70',
        'Podstawa wyliczenia: 30% minimalnego wynagrodzenia (1441,80 PLN w 2026)',
        'Skladka spoleczna z chorobowym: ok. 456 PLN/mies.',
      ],
      terminRealizacji: 'Od nastepnego miesiaca po zgloszeniu',
      pulapki: ['Trwa 24 PELNE miesiace -- potem przechodzisz na pelny ZUS lub Maly ZUS Plus', 'Mozna uzyc od razu (bez Ulgi na Start) -- ale tracisz 6 miesiecy darmowych'],
      odwolanie: 'Odwolanie do Sadu Pracy',
    },
    zrodloUrl: 'https://www.biznes.gov.pl/pl/portal/00126',
    zrodloNazwa: 'biznes.gov.pl', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'maly-zus-plus', nazwa: 'Maly ZUS Plus', kategoria: 'BIZNES',
    kwota: 'skladki proporcjonalne do przychodu', czestotliwosc: 'miesiecznie (36 miesiecy w ciagu 60)',
    wymagania: { prowadzDzialalnosc: true },
    wykluczenia: [
      { opis: 'Przychod roczny przekroczyl 120 000 PLN', sprawdz: 'przychod_120k' },
      { opis: 'Swiadczysz uslugi na rzecz bylego pracodawcy', sprawdz: 'byly_pracodawca' },
      { opis: 'Rozliczasz sie karta podatkowa z VAT', sprawdz: 'karta_podatkowa_vat' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'], formularz: 'ZUS DRA cz. II lub ZUS RCA cz. II',
      dokumenty: ['Przychod z poprzedniego roku kalendarzowego'],
      kroki: [
        'Sprawdz czy Twoj przychod za poprzedni rok nie przekroczyl 120 000 PLN',
        'Zgloszenie do Malego ZUS Plus do 31 stycznia (nowi: w ciagu 7 dni od spelnienia warunkow)',
        'Wypelnij ZUS DRA cz. II z danymi o przychodzie',
        'Skladki oblicza sie od podstawy proporcjonalnej do przychodu',
      ],
      terminRealizacji: 'Od miesiaca zgloszenia',
      pulapki: ['Mozna korzystac max 36 miesiecy w ciagu 60 -- potem 24 miesiace pelnego ZUS', 'Termin zgloszenia: do 31 stycznia -- jesli spoznisz, musisz czekac rok'],
      odwolanie: 'Odwolanie do Sadu Pracy',
    },
    zrodloUrl: 'https://www.zus.pl/firmy/przedsiebiorco-to-ciebie-dotyczy/maly-zus-plus',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'wakacje-skladkowe', nazwa: 'Wakacje skladkowe (1 miesiac wolny od ZUS)', kategoria: 'BIZNES',
    kwota: 'ok. 1 600 PLN oszczednosci (1 miesiac)', kwotaMin: 1600, kwotaMax: 1600,
    czestotliwosc: 'rocznie (1 miesiac)',
    wymagania: { prowadzDzialalnosc: true },
    wykluczenia: [
      { opis: 'Wiecej niz 9 pracownikow', sprawdz: 'pracownicy_9' },
      { opis: 'Przychod w poprzednim roku przekroczyl 2 mln EUR', sprawdz: 'przychod_2mln_eur' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      dokumenty: ['Wniosek RWS (przez PUE ZUS)'],
      kroki: [
        'Zaloguj sie na PUE ZUS',
        'Zloz wniosek RWS -- wybierz miesiac, w ktorym chcesz skorzystac',
        'Wniosek nalezy zlozyc w miesiacu POPRZEDZAJACYM wybrany miesiac',
        'W wybranym miesiacu nie placisz skladek spolecznych (zdrowotna nadal obowiazuje)',
      ],
      terminRealizacji: 'Decyzja w ciagu 40 dni',
      pulapki: ['Wniosek trzeba zlozyc MIESIAC WCZESNIEJ', 'Mozna skorzystac tylko 1 raz w roku', 'Limit 9 pracownikow (wraz z samozatrudnionym)'],
      odwolanie: 'Odwolanie do Prezesa ZUS',
    },
    zrodloUrl: 'https://www.zus.pl/firmy/wakacje-od-zus',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'ryczalt', nazwa: 'Ryczalt od przychodow ewidencjonowanych', kategoria: 'BIZNES',
    kwota: 'stawki 2-17% zamiast 12-32% PIT', czestotliwosc: 'rocznie',
    wymagania: { prowadzDzialalnosc: true },
    wykluczenia: [{ opis: 'Nie mozna przy niektorych rodzajach dzialalnosci (np. apteki, lombardy)', sprawdz: 'pkd_ryczalt' }],
    wniosek: {
      kanal: ['URZAD_SKARBOWY'],
      dokumenty: ['Oswiadczenie o wyborze ryczaltu'],
      kroki: [
        'Do 20 dnia miesiaca nastepujacego po pierwszym przychodzie -- zloz oswiadczenie o wyborze ryczaltu',
        'Lub przy rejestracji firmy w CEIDG -- zaznacz ryczalt jako forme opodatkowania',
        'Stawka zalezy od PKD: IT = 12%, wynajem = 8,5%, produkcja = 5,5%',
      ],
      terminRealizacji: 'Od nastepnego miesiaca',
      pulapki: ['Nie odliczysz kosztow uzyskania przychodu -- placisz od przychodu, nie od dochodu', 'Stawka zalezy od rodzaju dzialalnosci (PKD)'],
      odwolanie: 'Zmiana formy opodatkowania do 20 lutego nastepnego roku',
    },
    zrodloUrl: 'https://www.podatki.gov.pl/pit/ryczalt-od-przychodow-ewidencjonowanych/',
    zrodloNazwa: 'Ministerstwo Finansow', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'ulga-robotyzacja', nazwa: 'Ulga na robotyzacje', kategoria: 'BIZNES',
    kwota: 'dodatkowe 50% odliczenia kosztow robotyzacji', czestotliwosc: 'rocznie (do 2026)',
    wymagania: { prowadzDzialalnosc: true },
    wykluczenia: [{ opis: 'Dotyczy robotow przemyslowych i oprogramowania do ich sterowania', sprawdz: 'robot_przemyslowy' }],
    wniosek: {
      kanal: ['URZAD_SKARBOWY'], formularz: 'PIT-36/PIT-36L z zalacznikiem',
      dokumenty: ['Faktury za roboty przemyslowe i oprogramowanie', 'Ewidencja srodkow trwalych'],
      kroki: [
        'Zakup robota przemyslowego lub oprogramowania sterujacego',
        'Ujmij w ewidencji srodkow trwalych',
        'Przy rozliczeniu PIT odlicz dodatkowe 50% kosztow nabycia',
      ],
      terminRealizacji: 'Przy rozliczeniu rocznym',
      pulapki: ['Program dziala do konca 2026 roku', 'Dotyczy TYLKO robotow przemyslowych w rozumieniu ISO 8373'],
      odwolanie: 'Odwolanie od decyzji US',
    },
    zrodloUrl: 'https://www.podatki.gov.pl/cit/ulgi-i-odliczenia/ulga-na-robotyzacje/',
    zrodloNazwa: 'Ministerstwo Finansow', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
];
