import { Benefit } from '../types';

export const BIZNES: Benefit[] = [
  {
    id: 'ulga-na-start', nazwa: 'Ulga na Start', kategoria: 'BIZNES',
    kwota: 'ok. 1 927 PLN/mies. oszczędności (brak składek społecznych)', kwotaMin: 1927, kwotaMax: 1927,
    czestotliwosc: 'miesięcznie (6 pełnych miesięcy)',
    wymagania: { prowadzDzialalnosc: true, pierwszaDzialalnosc: true },
    wykluczenia: [
      { opis: 'Prowadziłeś działalność gospodarczą w ciągu ostatnich 60 miesięcy', sprawdz: 'biznes_60_miesiecy' },
      { opis: 'Wykonujesz działalność na rzecz byłego pracodawcy', sprawdz: 'byly_pracodawca' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'], formularz: 'ZUS ZZA',
      dokumenty: ['Potwierdzenie rejestracji w CEIDG', 'Dowód osobisty'],
      kroki: [
        'Zarejestruj działalność w CEIDG (biznes.gov.pl)',
        'Zaloguj się na PUE ZUS',
        'Zgłoś się do ubezpieczenia zdrowotnego na formularzu ZUS ZZA',
        'NIE zgłaszaj się do ubezpieczeń społecznych -- to jest istota ulgi',
        'Przez 6 pełnych miesięcy płacisz TYLKO składkę zdrowotną',
      ],
      terminRealizacji: 'Automatycznie od dnia rejestracji',
      pulapki: [
        'PUŁAPKA: Jeśli miałeś JAKAKOLWIEK działalność w ostatnich 60 miesiącach (nawet zawieszona) -- nie kwalifikujesz się',
        'Liczy się 6 PEŁNYCH miesięcy -- jeśli zaczynasz w połowie miesiąca, ten miesiąc się nie liczy',
        'Nie możesz wykonywać usług na rzecz byłego pracodawcy (u którego pracowałeś w tym lub poprzednim roku)',
      ],
      odwolanie: 'Odwołanie do Sądu Pracy',
    },
    zrodloUrl: 'https://www.biznes.gov.pl/pl/portal/00271',
    zrodloNazwa: 'biznes.gov.pl', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'preferencyjny-zus', nazwa: 'Preferencyjny ZUS (mały ZUS)', kategoria: 'BIZNES',
    kwota: 'ok. 456 PLN/mies. zamiast ok. 1 600 PLN/mies.', kwotaMin: 456, kwotaMax: 456,
    czestotliwosc: 'miesięcznie (24 pełne miesiące)',
    wymagania: { prowadzDzialalnosc: true, miesiaceDzialalnosci: { min: 6, max: 30 } },
    wykluczenia: [{ opis: 'Wykonujesz działalność na rzecz byłego pracodawcy', sprawdz: 'byly_pracodawca' }],
    wniosek: {
      kanal: ['PUE_ZUS'], formularz: 'ZUS ZUA + ZUS DRA',
      dokumenty: ['Potwierdzenie zakończenia Ulgi na Start (lub 6 mies. działalności)'],
      kroki: [
        'Po zakończeniu Ulgi na Start (lub od razu jeśli nie korzystałeś)',
        'Wyrejestruj się z ZUS ZZA i zarejestruj na ZUS ZUA z kodem 05 70',
        'Podstawa wyliczenia: 30% minimalnego wynagrodzenia (1441,80 PLN w 2026)',
        'Składka społeczna z chorobowym: ok. 456 PLN/mies.',
      ],
      terminRealizacji: 'Od następnego miesiąca po zgłoszeniu',
      pulapki: ['Trwa 24 PEŁNE miesiące -- potem przechodzisz na pełny ZUS lub Mały ZUS Plus', 'Można użyć od razu (bez Ulgi na Start) -- ale tracisz 6 miesięcy darmowych'],
      odwolanie: 'Odwołanie do Sądu Pracy',
    },
    zrodloUrl: 'https://www.biznes.gov.pl/pl/portal/00126',
    zrodloNazwa: 'biznes.gov.pl', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'maly-zus-plus', nazwa: 'Mały ZUS Plus', kategoria: 'BIZNES',
    kwota: 'składki proporcjonalne do przychodu', czestotliwosc: 'miesięcznie (36 miesięcy w ciągu 60)',
    wymagania: { prowadzDzialalnosc: true },
    wykluczenia: [
      { opis: 'Przychód roczny przekroczył 120 000 PLN', sprawdz: 'przychod_120k' },
      { opis: 'Świadczysz usługi na rzecz byłego pracodawcy', sprawdz: 'byly_pracodawca' },
      { opis: 'Rozliczasz się kartą podatkową z VAT', sprawdz: 'karta_podatkowa_vat' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'], formularz: 'ZUS DRA cz. II lub ZUS RCA cz. II',
      dokumenty: ['Przychód z poprzedniego roku kalendarzowego'],
      kroki: [
        'Sprawdź czy Twój przychód za poprzedni rok nie przekroczył 120 000 PLN',
        'Zgłoszenie do Małego ZUS Plus do 31 stycznia (nowi: w ciągu 7 dni od spełnienia warunków)',
        'Wypełnij ZUS DRA cz. II z danymi o przychodzie',
        'Składki oblicza się od podstawy proporcjonalnej do przychodu',
      ],
      terminRealizacji: 'Od miesiąca zgłoszenia',
      pulapki: ['Można korzystać max 36 miesięcy w ciągu 60 -- potem 24 miesiące pełnego ZUS', 'Termin zgłoszenia: do 31 stycznia -- jeśli spóźnisz, musisz czekać rok'],
      odwolanie: 'Odwołanie do Sądu Pracy',
    },
    zrodloUrl: 'https://www.zus.pl/firmy/przedsiebiorco-to-ciebie-dotyczy/maly-zus-plus',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'wakacje-skladkowe', nazwa: 'Wakacje składkowe (1 miesiąc wolny od ZUS)', kategoria: 'BIZNES',
    kwota: 'ok. 1 600 PLN oszczędności (1 miesiąc)', kwotaMin: 1600, kwotaMax: 1600,
    czestotliwosc: 'rocznie (1 miesiąc)',
    wymagania: { prowadzDzialalnosc: true },
    wykluczenia: [
      { opis: 'Więcej niż 9 pracowników', sprawdz: 'pracownicy_9' },
      { opis: 'Przychód w poprzednim roku przekroczył 2 mln EUR', sprawdz: 'przychod_2mln_eur' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      dokumenty: ['Wniosek RWS (przez PUE ZUS)'],
      kroki: [
        'Zaloguj się na PUE ZUS',
        'Złóż wniosek RWS -- wybierz miesiąc, w którym chcesz skorzystać',
        'Wniosek należy złożyć w miesiącu POPRZEDZAJĄCYM wybrany miesiąc',
        'W wybranym miesiącu nie płacisz składek społecznych (zdrowotna nadal obowiązuje)',
      ],
      terminRealizacji: 'Decyzja w ciągu 40 dni',
      pulapki: ['Wniosek trzeba złożyć MIESIĄC WCZEŚNIEJ', 'Można skorzystać tylko 1 raz w roku', 'Limit 9 pracowników (wraz z samozatrudnionym)'],
      odwolanie: 'Odwołanie do Prezesa ZUS',
    },
    zrodloUrl: 'https://www.zus.pl/firmy/wakacje-od-zus',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'ryczalt', nazwa: 'Ryczałt od przychodów ewidencjonowanych', kategoria: 'BIZNES',
    kwota: 'stawki 2-17% zamiast 12-32% PIT', czestotliwosc: 'rocznie',
    wymagania: { prowadzDzialalnosc: true },
    wykluczenia: [{ opis: 'Nie można przy niektórych rodzajach działalności (np. apteki, lombardy)', sprawdz: 'pkd_ryczalt' }],
    wniosek: {
      kanal: ['URZAD_SKARBOWY'],
      dokumenty: ['Oświadczenie o wyborze ryczałtu'],
      kroki: [
        'Do 20 dnia miesiąca następującego po pierwszym przychodzie -- złóż oświadczenie o wyborze ryczałtu',
        'Lub przy rejestracji firmy w CEIDG -- zaznacz ryczałt jako formę opodatkowania',
        'Stawka zależy od PKD: IT = 12%, wynajem = 8,5%, produkcja = 5,5%',
      ],
      terminRealizacji: 'Od następnego miesiąca',
      pulapki: ['Nie odliczysz kosztów uzyskania przychodu -- płacisz od przychodu, nie od dochodu', 'Stawka zależy od rodzaju działalności (PKD)'],
      odwolanie: 'Zmiana formy opodatkowania do 20 lutego następnego roku',
    },
    zrodloUrl: 'https://www.podatki.gov.pl/pit/ryczalt-od-przychodow-ewidencjonowanych/',
    zrodloNazwa: 'Ministerstwo Finansów', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'ulga-robotyzacja', nazwa: 'Ulga na robotyzację', kategoria: 'BIZNES',
    kwota: 'dodatkowe 50% odliczenia kosztów robotyzacji', czestotliwosc: 'rocznie (do 2026)',
    wymagania: { prowadzDzialalnosc: true },
    wykluczenia: [{ opis: 'Dotyczy robotów przemysłowych i oprogramowania do ich sterowania', sprawdz: 'robot_przemyslowy' }],
    wniosek: {
      kanal: ['URZAD_SKARBOWY'], formularz: 'PIT-36/PIT-36L z załącznikiem',
      dokumenty: ['Faktury za roboty przemysłowe i oprogramowanie', 'Ewidencja środków trwałych'],
      kroki: [
        'Zakup robota przemysłowego lub oprogramowania sterującego',
        'Ujmij w ewidencji środków trwałych',
        'Przy rozliczeniu PIT odlicz dodatkowe 50% kosztów nabycia',
      ],
      terminRealizacji: 'Przy rozliczeniu rocznym',
      pulapki: ['Program działa do końca 2026 roku', 'Dotyczy TYLKO robotów przemysłowych w rozumieniu ISO 8373'],
      odwolanie: 'Odwołanie od decyzji US',
    },
    zrodloUrl: 'https://www.podatki.gov.pl/cit/ulgi-i-odliczenia/ulga-na-robotyzacje/',
    zrodloNazwa: 'Ministerstwo Finansów', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
];
