import { Benefit } from '../types';

export const EDUKACJA: Benefit[] = [
  {
    id: 'stypendium-socjalne', nazwa: 'Stypendium socjalne', kategoria: 'EDUKACJA',
    kwota: '1000-2500 PLN miesiecznie (zalezy od uczelni)', kwotaMin: 1000, kwotaMax: 2500,
    czestotliwosc: 'miesiecznie (10 miesiecy w roku akademickim)',
    wymagania: { student: true, dochodMax: 1908.90 },
    wykluczenia: [
      { opis: 'Dochod netto na osobe w rodzinie przekracza 1908,90 PLN miesiecznie', sprawdz: 'dochod_na_osobe' },
      { opis: 'Student pobiera juz stypendium socjalne na innym kierunku', sprawdz: 'podwojne_stypendium' },
    ],
    wniosek: {
      kanal: ['UCZELNIA'], formularz: 'Wniosek o stypendium socjalne (formularz uczelniany)',
      dokumenty: [
        'Zaswiadczenie z urzedu skarbowego o dochodach rodziny za poprzedni rok',
        'Zaswiadczenie z ZUS/KRUS o skladkach zdrowotnych',
        'Oswiadczenie o liczbie czlonkow rodziny',
        'Zaswiadczenie o uczeniu sie/studiowaniu rodzenstwa',
        'Akt urodzenia rodzenstwa ponizej 7 roku zycia',
      ],
      kroki: [
        'Zbierz dokumenty dochodowe rodziny za poprzedni rok podatkowy',
        'Wypelnij wniosek w systemie elektronicznym uczelni lub pobierz formularz',
        'Dolacz wszystkie wymagane zalaczniki',
        'Zloz wniosek w dziekanacie lub biurze stypendialnym',
        'Komisja stypendialna rozpatrzy wniosek w ciagu 30 dni',
      ],
      terminRealizacji: '30 dni od zlozenia kompletnego wniosku',
      pulapki: [
        'Prog dochodowy 1908,90 PLN netto na osobe -- nawet uczelnia nie moze go podwyzszc',
        'Laczna kwota stypendium socjalnego i rektora nie moze przekroczyc 3560,60 PLN miesiecznie',
        'Przy dochodzie ponizej 600 PLN na osobe musisz dolaczyc zaswiadczenie z osrodka pomocy spolecznej',
        'Termin skladania wnioskow ustala uczelnia -- zwykle poczatek semestru',
      ],
      odwolanie: 'Odwolanie do rektora w ciagu 14 dni od decyzji komisji stypendialnej',
    },
    zrodloUrl: 'https://www.gov.pl/web/nauka/swiadczenia-dla-studentow-w-roku-akademickim-2025-2026',
    zrodloNazwa: 'Ministerstwo Nauki i Szkolnictwa Wyzszego', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'stypendium-rektora', nazwa: 'Stypendium rektora', kategoria: 'EDUKACJA',
    kwota: '850-1700 PLN miesiecznie (zalezy od uczelni)', kwotaMin: 850, kwotaMax: 1700,
    czestotliwosc: 'miesiecznie (10 miesiecy w roku akademickim)',
    wymagania: { student: true },
    wykluczenia: [
      { opis: 'Nie mozna otrzymac na pierwszym roku studiow I stopnia (z wyjatkiem laureatow olimpiad)', sprawdz: 'rok_studiow' },
      { opis: 'Stypendium rektora moze otrzymac maksymalnie 10% studentow danego kierunku', sprawdz: 'limit_procentowy' },
    ],
    wniosek: {
      kanal: ['UCZELNIA'], formularz: 'Wniosek o stypendium rektora (formularz uczelniany)',
      dokumenty: [
        'Zaswiadczenie o sredniej ocen za poprzedni rok',
        'Dokumenty potwierdzajace osiagniecia naukowe, artystyczne lub sportowe',
        'Zaswiadczenia o udziale w olimpiadach (dla studentow I roku)',
      ],
      kroki: [
        'Sprawdz regulamin stypendialny swojej uczelni -- progi sredniej sie roznia',
        'Przygotuj dokumenty potwierdzajace osiagniecia',
        'Wypelnij wniosek w systemie uczelnianym lub na formularzu',
        'Zloz wniosek w terminie wyznaczonym przez uczelnie (zwykle pazdziernik)',
        'Komisja stypendialna ustali liste rankingowa',
      ],
      terminRealizacji: '30 dni od zakonczenia naboru wnioskow',
      pulapki: [
        'Kazda uczelnia ustala wlasne kwoty i progi -- sprawdz regulamin swojej uczelni',
        'Na I roku studiow I stopnia tylko laureaci i finalisci olimpiad miedzynarodowych',
        'Laczna kwota stypendium rektora i socjalnego nie moze przekroczyc 3560,60 PLN',
        'Wymagana jest rejestracja na kolejny semestr -- urlop dziekanski wyklucza',
      ],
      odwolanie: 'Odwolanie do rektora w ciagu 14 dni od decyzji komisji stypendialnej',
    },
    zrodloUrl: 'https://www.gov.pl/web/nauka/swiadczenia-dla-studentow-w-roku-akademickim-2025-2026',
    zrodloNazwa: 'Ministerstwo Nauki i Szkolnictwa Wyzszego', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'kredyt-studencki', nazwa: 'Kredyt studencki', kategoria: 'EDUKACJA',
    kwota: '400-1000 PLN miesiecznie (do wyboru: 400, 600, 800 lub 1000 PLN)', kwotaMin: 400, kwotaMax: 1000,
    czestotliwosc: 'miesiecznie (10 miesiecy w roku, maks. 6 lat studiow)',
    wymagania: { student: true, wiekMax: 30, dochodMax: 4000 },
    wykluczenia: [
      { opis: 'Dochod na osobe w rodzinie przekracza 4000 PLN netto', sprawdz: 'dochod_na_osobe' },
      { opis: 'Wiek powyzej 30 lat (studenci) lub 35 lat (doktoranci)', sprawdz: 'wiek' },
    ],
    wniosek: {
      kanal: ['BANK'], formularz: 'Wniosek o kredyt studencki (formularz bankowy)',
      dokumenty: [
        'Zaswiadczenie z uczelni o statusie studenta',
        'Dokumenty potwierdzajace dochod rodziny',
        'Dowod osobisty',
        'Poreczenie (rodzice lub Bank Gospodarstwa Krajowego)',
      ],
      kroki: [
        'Wybierz bank: PKO BP, Pekao SA lub Bank Spoldzielczy',
        'Wnioski mozna skladac od 15 lipca do 20 pazdziernika',
        'Zloz wniosek w oddziale banku lub elektronicznie',
        'Bank oceni zdolnosc kredytowa i dochod rodziny',
        'Po pozytywnej decyzji transza wplywaja co miesiac na konto',
      ],
      terminRealizacji: '30 dni od zlozenia kompletnego wniosku',
      pulapki: [
        'Splata rozpoczyna sie dopiero 2 lata po ukonczeniu studiow',
        'Oprocentowanie preferencyjne -- platisz polowe odsetek, reszte doplaca BGK',
        'Mozliwe umorzenie 50% kredytu dla najlepszych absolwentow (top 1%)',
        'Mozliwe umorzenie 35% dla absolwentow w top 5% i 20% w top 10%',
        'Poreczenie BGK dostepne dla studentow o dochodzie ponizej 2500 PLN na osobe',
      ],
      odwolanie: 'Reklamacja do banku, nastepnie do Rzecznika Finansowego',
    },
    zrodloUrl: 'https://www.gov.pl/web/nauka/kredyty-studenckie',
    zrodloNazwa: 'Ministerstwo Nauki i Szkolnictwa Wyzszego', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'stypendium-szkolne', nazwa: 'Stypendium szkolne', kategoria: 'EDUKACJA',
    kwota: '99,20-248 PLN miesiecznie', kwotaMin: 99.20, kwotaMax: 248,
    czestotliwosc: 'miesiecznie (maks. 10 miesiecy w roku szkolnym)',
    wymagania: { wiekMin: 6, wiekMax: 24, dochodMax: 823 },
    wykluczenia: [
      { opis: 'Dochod netto na osobe w rodzinie przekracza 823 PLN', sprawdz: 'dochod_na_osobe' },
    ],
    wniosek: {
      kanal: ['URZAD_GMINY', 'MOPS'], formularz: 'Wniosek o stypendium szkolne (formularz gminny)',
      dokumenty: [
        'Zaswiadczenie o dochodach rodziny',
        'Zaswiadczenie ze szkoly o uczniu',
        'Dowod osobisty rodzica/opiekuna',
        'Rachunki lub faktury za wydatki edukacyjne (do rozliczenia)',
      ],
      kroki: [
        'Zloz wniosek w urzedzie gminy lub MOPS do 15 wrzesnia danego roku szkolnego',
        'Dolacz dokumenty potwierdzajace dochod rodziny',
        'Po przyznaniu -- zbieraj rachunki za podreczniki, przybory, mundurek, zajecia dodatkowe',
        'Rozlicz stypendium przedstawiajac faktury w urzedzie',
      ],
      terminRealizacji: '30 dni od zlozenia wniosku',
      pulapki: [
        'Termin skladania: do 15 wrzesnia -- po tym terminie gmina moze odrzucic wniosek',
        'Stypendium najczesciej wypacane jako zwrot kosztow -- musisz miec rachunki',
        'Kwota zalezy od dochodu: do 411,50 PLN na osobe -- 176 PLN/mies., 411,50-823 PLN -- 106 PLN/mies.',
        'Lacznie w roku szkolnym mozna otrzymac maks. 2480 PLN',
      ],
      odwolanie: 'Odwolanie do Samorzadowego Kolegium Odwolawczego w ciagu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/edukacja/stypendium-szkolne-oraz-zasilek-szkolny',
    zrodloNazwa: 'Ministerstwo Edukacji Narodowej', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'zasilek-szkolny', nazwa: 'Zasilek szkolny', kategoria: 'EDUKACJA',
    kwota: 'do 620 PLN jednorazowo', kwotaMin: 1, kwotaMax: 620,
    czestotliwosc: 'jednorazowo (mozliwe kilka razy w roku, lacznie do 6200 PLN)',
    wymagania: { wiekMin: 6, wiekMax: 24 },
    wykluczenia: [
      { opis: 'Brak zdarzenia losowego powodujacego przejsciowe pogorszenie sytuacji materialnej', sprawdz: 'zdarzenie_losowe' },
    ],
    wniosek: {
      kanal: ['URZAD_GMINY', 'MOPS'], formularz: 'Wniosek o zasilek szkolny (formularz gminny)',
      dokumenty: [
        'Dokumenty potwierdzajace zdarzenie losowe (np. akt zgonu, zaswiadczenie o pozarze, zwolnienie z pracy)',
        'Zaswiadczenie ze szkoly o uczniu',
        'Dowod osobisty rodzica/opiekuna',
      ],
      kroki: [
        'Zloz wniosek w ciagu 2 miesiecy od zdarzenia losowego',
        'Opisz zdarzenie i jego wplyw na sytuacje materialna ucznia',
        'Dolacz dokumenty potwierdzajace zdarzenie',
        'Gmina wyda decyzje w ciagu 30 dni',
      ],
      terminRealizacji: '30 dni od zlozenia wniosku',
      pulapki: [
        'Wniosek trzeba zlozyc w ciagu 2 miesiecy od zdarzenia -- potem przepada',
        'Nie jest wymagane kryterium dochodowe -- liczy sie zdarzenie losowe',
        'Moze byc przyznany kilka razy w roku (maks. 6200 PLN rocznie)',
        'Zdarzenie losowe: smierc rodzica, pozar, powodz, utrata pracy rodzica, choroba',
      ],
      odwolanie: 'Odwolanie do Samorzadowego Kolegium Odwolawczego w ciagu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/edukacja/stypendium-szkolne-oraz-zasilek-szkolny',
    zrodloNazwa: 'Ministerstwo Edukacji Narodowej', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'wyprawka-szkolna', nazwa: 'Wyprawka szkolna (dofinansowanie podrecznikow)', kategoria: 'EDUKACJA',
    kwota: '225-445 PLN jednorazowo (zalezy od typu szkoly i niepelnosprawnosci)', kwotaMin: 225, kwotaMax: 445,
    czestotliwosc: 'jednorazowo (raz w roku szkolnym)',
    wymagania: { wiekMin: 6, wiekMax: 24 },
    wykluczenia: [
      { opis: 'Uczen nie posiada orzeczenia o potrzebie ksztalcenia specjalnego', sprawdz: 'orzeczenie_ksztalcenie_specjalne' },
    ],
    wniosek: {
      kanal: ['URZAD_GMINY'], formularz: 'Wniosek o dofinansowanie zakupu podrecznikow (Wyprawka szkolna)',
      dokumenty: [
        'Orzeczenie o potrzebie ksztalcenia specjalnego',
        'Dowod zakupu podrecznikow (faktura lub rachunek)',
        'Wniosek rodzica/opiekuna prawnego',
      ],
      kroki: [
        'Sprawdz czy dziecko ma orzeczenie o potrzebie ksztalcenia specjalnego',
        'Zloz wniosek do dyrektora szkoly do 8 wrzesnia',
        'Kup podreczniki i zachowaj dowody zakupu (faktury, paragony)',
        'Dyrektor szkoly przekaze wniosek do urzedu gminy',
        'Gmina zwroci koszty do wysokosci limitu',
      ],
      terminRealizacji: 'Zwrot do konca listopada danego roku szkolnego',
      pulapki: [
        'Termin skladania wnioskow: do 8 wrzesnia -- po terminie brak mozliwosci',
        'Dofinansowanie do 225 PLN (umiarkowana/znaczna niepelnosprawnosc intelektualna)',
        'Dofinansowanie do 390 PLN (szkoly branżowe, materialy do nauki zawodu)',
        'Dofinansowanie do 445 PLN (liceum, technikum -- niepelnosprawnosc wzroku, sluchu, ruchowa, autyzm)',
        'Brak kryterium dochodowego -- liczy sie orzeczenie o ksztalceniu specjalnym',
      ],
      odwolanie: 'Odwolanie do wojta/burmistrza/prezydenta miasta',
    },
    zrodloUrl: 'https://www.gov.pl/web/edukacja/rzadowy-program-pomocy-uczniom-niepelnosprawnym-w-formie-dofinansowania-zakupu-podrecznikow-materialow-edukacyjnych-i-materialow-cwiczeniowych-w-latach-20232025',
    zrodloNazwa: 'Ministerstwo Edukacji Narodowej', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'stypendium-mnisw', nazwa: 'Stypendium Ministra Nauki za znaczace osiagniecia', kategoria: 'EDUKACJA',
    kwota: '17 000 PLN jednorazowo', kwotaMin: 17000, kwotaMax: 17000,
    czestotliwosc: 'jednorazowo (raz w roku akademickim)',
    wymagania: { student: true },
    wykluczenia: [
      { opis: 'Brak znaczacych osiagniec naukowych, artystycznych lub sportowych', sprawdz: 'osiagniecia_wybitne' },
      { opis: 'Student na ostatnim roku studiow II stopnia lub jednolitych magisterskich nie moze aplikowac', sprawdz: 'rok_studiow' },
    ],
    wniosek: {
      kanal: ['UCZELNIA', 'ONLINE'], formularz: 'Wniosek o stypendium ministra (system OSF)',
      dokumenty: [
        'Dokumenty potwierdzajace osiagniecia naukowe (publikacje, patenty, nagrody)',
        'Dokumenty potwierdzajace osiagniecia artystyczne (wystawy, koncerty, nagrody)',
        'Dokumenty potwierdzajace osiagniecia sportowe (wyniki na zawodach miedzynarodowych)',
        'Opinia rektora uczelni',
      ],
      kroki: [
        'Przygotuj dokumentacje osiagniec z ostatniego roku akademickiego',
        'Wniosek sklada rektor uczelni w imieniu studenta -- zgloszenie do dziekanatu',
        'Rektor przesyla wniosek przez system OSF do ministerstwa (termin: pazdziernik)',
        'Minister oglosza liste stypendystow (zwykle grudzien-styczen)',
        'Stypendium wyplacane jednorazowo przez uczelnie',
      ],
      terminRealizacji: '3-4 miesiace od zlozenia wniosku przez rektora',
      pulapki: [
        'Wniosek sklada rektor, nie student -- musisz sie zglosic do dziekanatu wczesniej',
        'Rocznie przyznawanych jest ok. 400 stypendiow w calej Polsce',
        'Wymagane sa wybitne osiagniecia -- sama dobra srednia nie wystarczy',
        'Osiagniecia musza dotyczyc ostatniego roku akademickiego',
        'Stypendium jest zwolnione z podatku dochodowego',
      ],
      odwolanie: 'Wniosek o ponowne rozpatrzenie do Ministra Nauki w ciagu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/nauka/stypendia-ministra-dla-studentow-za-znaczace-osiagniecia',
    zrodloNazwa: 'Ministerstwo Nauki i Szkolnictwa Wyzszego', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
];
