import { Benefit } from '../types';

export const EDUKACJA: Benefit[] = [
  {
    id: 'stypendium-socjalne', nazwa: 'Stypendium socjalne',
    opis: 'Stypendium socjalne to comiesięczne wsparcie dla studentów z rodzin o niskich dochodach. Próg: 1908,90 PLN netto na osobę w rodzinie (ustawowy, uczelnia nie może go zmienić). Kwota 1000-2500 PLN/mies. przez 10 miesięcy (zależy od uczelni i poziomu dochodu). Przy dochodzie poniżej 600 PLN/os. wymagane zaświadczenie z ośrodka pomocy społecznej o sytuacji rodziny. Łączna kwota stypendium socjalnego + rektora nie może przekroczyć 3560,60 PLN/mies. Nie można pobierać na dwóch kierunkach jednocześnie. Wniosek na początku semestru w dziekanacie lub biurze stypendialnym.',
    kategoria: 'EDUKACJA',
    kwota: '1000-2500 PLN miesięcznie (zależy od uczelni)', kwotaMin: 1000, kwotaMax: 2500,
    czestotliwosc: 'miesięcznie (10 miesięcy w roku akademickim)',
    wymagania: { student: true, dochodMax: 1908.90 },
    wykluczenia: [
      { opis: 'Dochód netto na osobę w rodzinie przekracza 1908,90 PLN miesięcznie', sprawdz: 'dochod_na_osobe' },
      { opis: 'Student pobiera już stypendium socjalne na innym kierunku', sprawdz: 'podwojne_stypendium' },
    ],
    wniosek: {
      kanal: ['UCZELNIA'], formularz: 'Wniosek o stypendium socjalne (formularz uczelniany)',
      dokumenty: [
        'Zaświadczenie z urzędu skarbowego o dochodach rodziny za poprzedni rok',
        'Zaświadczenie z ZUS/KRUS o składkach zdrowotnych',
        'Oświadczenie o liczbie członków rodziny',
        'Zaświadczenie o uczeniu się/studiowaniu rodzeństwa',
        'Akt urodzenia rodzeństwa poniżej 7 roku życia',
      ],
      kroki: [
        'Zbierz dokumenty dochodowe rodziny za poprzedni rok podatkowy',
        'Wypełnij wniosek w systemie elektronicznym uczelni lub pobierz formularz',
        'Dołącz wszystkie wymagane załączniki',
        'Złóż wniosek w dziekanacie lub biurze stypendialnym',
        'Komisja stypendialna rozpatrzy wniosek w ciągu 30 dni',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'Próg dochodowy 1908,90 PLN netto na osobę, nawet uczelnia nie może go podwyższyć',
        'Łączna kwota stypendium socjalnego i rektora nie może przekroczyć 3560,60 PLN miesięcznie',
        'Przy dochodzie poniżej 600 PLN na osobę musisz dołączyć zaświadczenie z ośrodka pomocy społecznej',
        'Termin składania wniosków ustala uczelnia, zwykle początek semestru',
      ],
      odwolanie: 'Odwołanie do rektora w ciągu 14 dni od decyzji komisji stypendialnej',
    },
    zrodloUrl: 'https://www.gov.pl/web/nauka/swiadczenia-dla-studentow-w-roku-akademickim-2025-2026',
    zrodloNazwa: 'Ministerstwo Nauki i Szkolnictwa Wyższego', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'stypendium-rektora', nazwa: 'Stypendium rektora',
    opis: 'Stypendium rektora za wyróżniające wyniki w nauce, osiągnięcia naukowe, artystyczne lub sportowe. Kwota 850-1700 PLN/mies. przez 10 miesięcy (zależy od uczelni). Może otrzymać max 10% studentów danego kierunku. Nie przysługuje na I roku studiów I stopnia (wyjątek: laureaci olimpiad międzynarodowych). Każda uczelnia ustala własne progi średniej i kryteria. Łączna kwota z socjalnym max 3560,60 PLN. Urlop dziekański wyklucza z ubiegania się. Wniosek zwykle w październiku.',
    kategoria: 'EDUKACJA',
    kwota: '850-1700 PLN miesięcznie (zależy od uczelni)', kwotaMin: 850, kwotaMax: 1700,
    czestotliwosc: 'miesięcznie (10 miesięcy w roku akademickim)',
    wymagania: { student: true },
    wykluczenia: [
      { opis: 'Nie można otrzymać na pierwszym roku studiów I stopnia (z wyjątkiem laureatów olimpiad)', sprawdz: 'rok_studiow' },
      { opis: 'Stypendium rektora może otrzymać maksymalnie 10% studentów danego kierunku', sprawdz: 'limit_procentowy' },
    ],
    wniosek: {
      kanal: ['UCZELNIA'], formularz: 'Wniosek o stypendium rektora (formularz uczelniany)',
      dokumenty: [
        'Zaświadczenie o średniej ocen za poprzedni rok',
        'Dokumenty potwierdzające osiągnięcia naukowe, artystyczne lub sportowe',
        'Zaświadczenia o udziale w olimpiadach (dla studentów I roku)',
      ],
      kroki: [
        'Sprawdź regulamin stypendialny swojej uczelni, progi średniej się różnią',
        'Przygotuj dokumenty potwierdzające osiągnięcia',
        'Wypełnij wniosek w systemie uczelnianym lub na formularzu',
        'Złóż wniosek w terminie wyznaczonym przez uczelnię (zwykle październik)',
        'Komisja stypendialna ustali listę rankingową',
      ],
      terminRealizacji: '30 dni od zakończenia naboru wniosków',
      pulapki: [
        'Każda uczelnia ustala własne kwoty i progi, sprawdź regulamin swojej uczelni',
        'Na I roku studiów I stopnia tylko laureaci i finaliści olimpiad międzynarodowych',
        'Łączna kwota stypendium rektora i socjalnego nie może przekroczyć 3560,60 PLN',
        'Wymagana jest rejestracja na kolejny semestr, urlop dziekański wyklucza',
      ],
      odwolanie: 'Odwołanie do rektora w ciągu 14 dni od decyzji komisji stypendialnej',
    },
    zrodloUrl: 'https://www.gov.pl/web/nauka/swiadczenia-dla-studentow-w-roku-akademickim-2025-2026',
    zrodloNazwa: 'Ministerstwo Nauki i Szkolnictwa Wyższego', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'kredyt-studencki', nazwa: 'Kredyt studencki',
    opis: 'Kredyt studencki z dopłatą państwa: student wybiera transzę 400/600/800/1000 PLN miesięcznie, wypłacaną przez 10 mies./rok, max 6 lat studiów. Spłata zaczyna się dopiero 2 lata po ukończeniu studiów. Oprocentowanie preferencyjne (płacisz połowę odsetek, resztę dopłaca BGK). Możliwe umorzenie: 50% dla top 1% absolwentów, 35% top 5%, 20% top 10%. Banki: PKO BP, Pekao SA, Banki Spółdzielcze. Poręczenie BGK dla dochodu poniżej 2500 PLN/os. Wiek do 30 lat (studenci) lub 35 (doktoranci). Próg dochodowy: 4000 PLN/os. Wnioski: 15 lipca-20 października.',
    kategoria: 'EDUKACJA',
    kwota: '400-1000 PLN miesięcznie (do wyboru: 400, 600, 800 lub 1000 PLN)', kwotaMin: 400, kwotaMax: 1000,
    czestotliwosc: 'miesięcznie (10 miesięcy w roku, maks. 6 lat studiów)',
    wymagania: { student: true, wiekMax: 30, dochodMax: 4000 },
    wykluczenia: [
      { opis: 'Dochód na osobę w rodzinie przekracza 4000 PLN netto', sprawdz: 'dochod_na_osobe' },
      { opis: 'Wiek powyżej 30 lat (studenci) lub 35 lat (doktoranci)', sprawdz: 'wiek' },
    ],
    wniosek: {
      kanal: ['BANK'], formularz: 'Wniosek o kredyt studencki (formularz bankowy)',
      dokumenty: [
        'Zaświadczenie z uczelni o statusie studenta',
        'Dokumenty potwierdzające dochód rodziny',
        'Dowód osobisty',
        'Poręczenie (rodzice lub Bank Gospodarstwa Krajowego)',
      ],
      kroki: [
        'Wybierz bank: PKO BP, Pekao SA lub Bank Spółdzielczy',
        'Wnioski można składać od 15 lipca do 20 października',
        'Złóż wniosek w oddziale banku lub elektronicznie',
        'Bank oceni zdolność kredytową i dochód rodziny',
        'Po pozytywnej decyzji transze wpływają co miesiąc na konto',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'Spłata rozpoczyna się dopiero 2 lata po ukończeniu studiów',
        'Oprocentowanie preferencyjne, płacisz połowę odsetek, resztę dopłaca BGK',
        'Możliwe umorzenie 50% kredytu dla najlepszych absolwentów (top 1%)',
        'Możliwe umorzenie 35% dla absolwentów w top 5% i 20% w top 10%',
        'Poręczenie BGK dostępne dla studentów o dochodzie poniżej 2500 PLN na osobę',
      ],
      odwolanie: 'Reklamacja do banku, następnie do Rzecznika Finansowego',
    },
    zrodloUrl: 'https://www.gov.pl/web/nauka/kredyty-studenckie',
    zrodloNazwa: 'Ministerstwo Nauki i Szkolnictwa Wyższego', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'stypendium-szkolne', nazwa: 'Stypendium szkolne',
    opis: 'Stypendium szkolne dla uczniów z rodzin o niskich dochodach (do 823 PLN/os.). Kwota 99-248 PLN/mies., max 10 mies. w roku szkolnym, łącznie do 2480 PLN/rok. Najczęściej wypłacane jako zwrot kosztów: musisz kupić podręczniki, przybory, mundurek, opłacić zajęcia dodatkowe i przedstawić rachunki. Termin składania: do 15 września, po tym gmina może odrzucić. Dotyczy uczniów 6-24 lat. Wniosek w urzędzie gminy lub MOPS.',
    kategoria: 'EDUKACJA',
    kwota: '99,20-248 PLN miesięcznie', kwotaMin: 99.20, kwotaMax: 248,
    czestotliwosc: 'miesięcznie (maks. 10 miesięcy w roku szkolnym)',
    wymagania: { wiekMin: 6, wiekMax: 24, dochodMax: 823 },
    wykluczenia: [
      { opis: 'Dochód netto na osobę w rodzinie przekracza 823 PLN', sprawdz: 'dochod_na_osobe' },
    ],
    wniosek: {
      kanal: ['URZAD_GMINY', 'MOPS'], formularz: 'Wniosek o stypendium szkolne (formularz gminny)',
      dokumenty: [
        'Zaświadczenie o dochodach rodziny',
        'Zaświadczenie ze szkoły o uczniu',
        'Dowód osobisty rodzica/opiekuna',
        'Rachunki lub faktury za wydatki edukacyjne (do rozliczenia)',
      ],
      kroki: [
        'Złóż wniosek w urzędzie gminy lub MOPS do 15 września danego roku szkolnego',
        'Dołącz dokumenty potwierdzające dochód rodziny',
        'Po przyznaniu, zbieraj rachunki za podręczniki, przybory, mundurek, zajęcia dodatkowe',
        'Rozlicz stypendium przedstawiając faktury w urzędzie',
      ],
      terminRealizacji: '30 dni od złożenia wniosku',
      pulapki: [
        'Termin składania: do 15 września, po tym terminie gmina może odrzucić wniosek',
        'Stypendium najczęściej wypłacane jako zwrot kosztów, musisz mieć rachunki',
        'Kwota zależy od dochodu: do 411,50 PLN na osobę, 176 PLN/mies., 411,50-823 PLN, 106 PLN/mies.',
        'Łącznie w roku szkolnym można otrzymać maks. 2480 PLN',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/edukacja/stypendium-szkolne-oraz-zasilek-szkolny',
    zrodloNazwa: 'Ministerstwo Edukacji Narodowej', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'zasilek-szkolny', nazwa: 'Zasiłek szkolny',
    opis: 'Zasiłek szkolny to jednorazowa pomoc (do 620 PLN) dla ucznia, którego rodzina doświadczyła zdarzenia losowego: śmierć rodzica, pożar, powódź, utrata pracy rodzica, ciężka choroba. Nie wymaga spełnienia kryterium dochodowego, liczy się zdarzenie losowe. Wniosek w ciągu 2 miesięcy od zdarzenia, potem przepada. Może być przyznany kilka razy w roku (max 6200 PLN rocznie). Dotyczy uczniów 6-24 lat.',
    kategoria: 'EDUKACJA',
    kwota: 'do 620 PLN jednorazowo', kwotaMin: 1, kwotaMax: 620,
    czestotliwosc: 'jednorazowo (możliwe kilka razy w roku, łącznie do 6200 PLN)',
    wymagania: { wiekMin: 6, wiekMax: 24 },
    wykluczenia: [
      { opis: 'Brak zdarzenia losowego powodującego przejściowe pogorszenie sytuacji materialnej', sprawdz: 'zdarzenie_losowe' },
    ],
    wniosek: {
      kanal: ['URZAD_GMINY', 'MOPS'], formularz: 'Wniosek o zasiłek szkolny (formularz gminny)',
      dokumenty: [
        'Dokumenty potwierdzające zdarzenie losowe (np. akt zgonu, zaświadczenie o pożarze, zwolnienie z pracy)',
        'Zaświadczenie ze szkoły o uczniu',
        'Dowód osobisty rodzica/opiekuna',
      ],
      kroki: [
        'Złóż wniosek w ciągu 2 miesięcy od zdarzenia losowego',
        'Opisz zdarzenie i jego wpływ na sytuację materialną ucznia',
        'Dołącz dokumenty potwierdzające zdarzenie',
        'Gmina wyda decyzję w ciągu 30 dni',
      ],
      terminRealizacji: '30 dni od złożenia wniosku',
      pulapki: [
        'Wniosek trzeba złożyć w ciągu 2 miesięcy od zdarzenia, potem przepada',
        'Nie jest wymagane kryterium dochodowe, liczy się zdarzenie losowe',
        'Może być przyznany kilka razy w roku (maks. 6200 PLN rocznie)',
        'Zdarzenie losowe: śmierć rodzica, pożar, powódź, utrata pracy rodzica, choroba',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/edukacja/stypendium-szkolne-oraz-zasilek-szkolny',
    zrodloNazwa: 'Ministerstwo Edukacji Narodowej', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'wyprawka-szkolna', nazwa: 'Wyprawka szkolna (dofinansowanie podręczników)',
    opis: 'Dofinansowanie zakupu podręczników dla uczniów z orzeczeniem o potrzebie kształcenia specjalnego. Kwota 225-445 PLN jednorazowo, zależy od typu szkoły i rodzaju niepełnosprawności. Brak kryterium dochodowego, liczy się orzeczenie. Termin: do 8 września, wniosek do dyrektora szkoły. Kup podręczniki, zachowaj faktury, gmina zwróci koszty do końca listopada. Dotyczy uczniów ze: znaczną/umiarkowaną niepełnosprawnością intelektualną, niepełnosprawnością wzroku, słuchu, ruchową, autyzmem.',
    kategoria: 'EDUKACJA',
    kwota: '225-445 PLN jednorazowo (zależy od typu szkoły i niepełnosprawności)', kwotaMin: 225, kwotaMax: 445,
    czestotliwosc: 'jednorazowo (raz w roku szkolnym)',
    wymagania: { wiekMin: 6, wiekMax: 24 },
    wykluczenia: [
      { opis: 'Uczeń nie posiada orzeczenia o potrzebie kształcenia specjalnego', sprawdz: 'orzeczenie_ksztalcenie_specjalne' },
    ],
    wniosek: {
      kanal: ['URZAD_GMINY'], formularz: 'Wniosek o dofinansowanie zakupu podręczników (Wyprawka szkolna)',
      dokumenty: [
        'Orzeczenie o potrzebie kształcenia specjalnego',
        'Dowód zakupu podręczników (faktura lub rachunek)',
        'Wniosek rodzica/opiekuna prawnego',
      ],
      kroki: [
        'Sprawdź czy dziecko ma orzeczenie o potrzebie kształcenia specjalnego',
        'Złóż wniosek do dyrektora szkoły do 8 września',
        'Kup podręczniki i zachowaj dowody zakupu (faktury, paragony)',
        'Dyrektor szkoły przekaże wniosek do urzędu gminy',
        'Gmina zwróci koszty do wysokości limitu',
      ],
      terminRealizacji: 'Zwrot do końca listopada danego roku szkolnego',
      pulapki: [
        'Termin składania wniosków: do 8 września, po terminie brak możliwości',
        'Dofinansowanie do 225 PLN (umiarkowana/znaczna niepełnosprawność intelektualna)',
        'Dofinansowanie do 390 PLN (szkoły branżowe, materiały do nauki zawodu)',
        'Dofinansowanie do 445 PLN (liceum, technikum, niepełnosprawność wzroku, słuchu, ruchowa, autyzm)',
        'Brak kryterium dochodowego, liczy się orzeczenie o kształceniu specjalnym',
      ],
      odwolanie: 'Odwołanie do wójta/burmistrza/prezydenta miasta',
    },
    zrodloUrl: 'https://www.gov.pl/web/edukacja/rzadowy-program-pomocy-uczniom-niepelnosprawnym-w-formie-dofinansowania-zakupu-podrecznikow-materialow-edukacyjnych-i-materialow-cwiczeniowych-w-latach-20232025',
    zrodloNazwa: 'Ministerstwo Edukacji Narodowej', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'stypendium-mnisw', nazwa: 'Stypendium Ministra Nauki za znaczące osiągnięcia',
    opis: 'Jednorazowe stypendium 17 000 PLN za wybitne osiągnięcia naukowe, artystyczne lub sportowe. Rocznie ok. 400 stypendiów w całej Polsce. Wniosek składa rektor uczelni (nie student), musisz się zgłosić do dziekanatu wcześniej. Osiągnięcia muszą dotyczyć ostatniego roku akademickiego: publikacje, patenty, nagrody, wystawy, koncerty, wyniki na zawodach międzynarodowych. Nie dotyczy ostatniego roku studiów II stopnia. Stypendium zwolnione z podatku.',
    kategoria: 'EDUKACJA',
    kwota: '17 000 PLN jednorazowo', kwotaMin: 17000, kwotaMax: 17000,
    czestotliwosc: 'jednorazowo (raz w roku akademickim)',
    wymagania: { student: true },
    wykluczenia: [
      { opis: 'Brak znaczących osiągnięć naukowych, artystycznych lub sportowych', sprawdz: 'osiagniecia_wybitne' },
      { opis: 'Student na ostatnim roku studiów II stopnia lub jednolitych magisterskich nie może aplikować', sprawdz: 'rok_studiow' },
    ],
    wniosek: {
      kanal: ['UCZELNIA', 'ONLINE'], formularz: 'Wniosek o stypendium ministra (system OSF)',
      dokumenty: [
        'Dokumenty potwierdzające osiągnięcia naukowe (publikacje, patenty, nagrody)',
        'Dokumenty potwierdzające osiągnięcia artystyczne (wystawy, koncerty, nagrody)',
        'Dokumenty potwierdzające osiągnięcia sportowe (wyniki na zawodach międzynarodowych)',
        'Opinia rektora uczelni',
      ],
      kroki: [
        'Przygotuj dokumentację osiągnięć z ostatniego roku akademickiego',
        'Wniosek składa rektor uczelni w imieniu studenta, zgłoszenie do dziekanatu',
        'Rektor przesyła wniosek przez system OSF do ministerstwa (termin: październik)',
        'Minister ogłasza listę stypendystów (zwykle grudzień-styczeń)',
        'Stypendium wypłacane jednorazowo przez uczelnię',
      ],
      terminRealizacji: '3-4 miesiące od złożenia wniosku przez rektora',
      pulapki: [
        'Wniosek składa rektor, nie student, musisz się zgłosić do dziekanatu wcześniej',
        'Rocznie przyznawanych jest ok. 400 stypendiów w całej Polsce',
        'Wymagane są wybitne osiągnięcia, sama dobra średnia nie wystarczy',
        'Osiągnięcia muszą dotyczyć ostatniego roku akademickiego',
        'Stypendium jest zwolnione z podatku dochodowego',
      ],
      odwolanie: 'Wniosek o ponowne rozpatrzenie do Ministra Nauki w ciągu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/nauka/stypendia-ministra-dla-studentow-za-znaczace-osiagniecia',
    zrodloNazwa: 'Ministerstwo Nauki i Szkolnictwa Wyższego', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
];
