import { Benefit } from '../types';

export const EKOLOGIA: Benefit[] = [
  {
    id: 'czyste-powietrze', nazwa: 'Czyste Powietrze', kategoria: 'EKOLOGIA',
    kwota: 'do 66 000 PLN (podstawowy), do 99 000 PLN (podwyzszony), do 135 000 PLN (najwyzszy)',
    kwotaMin: 0, kwotaMax: 135000,
    czestotliwosc: 'jednorazowo',
    wymagania: { wlasnosc: ['dom'] },
    wykluczenia: [
      { opis: 'Dotyczy wylacznie budynkow jednorodzinnych', sprawdz: 'typ_budynku' },
      { opis: 'Od 31.03.2025 kotly gazowe i olejowe wykluczone z dofinansowania', sprawdz: 'zrodlo_ciepla' },
    ],
    wniosek: {
      kanal: ['WFOSIGW', 'ONLINE'],
      dokumenty: [
        'Dowod osobisty',
        'PIT za ostatni rok podatkowy',
        'Akt wlasnosci lub odpis z ksiegi wieczystej',
        'Audyt energetyczny budynku (wymagany od 31.03.2025)',
        'Zaswiadczenie o dochodach z urzedu gminy (poziom podwyzszony/najwyzszy)',
      ],
      kroki: [
        'Okresl poziom dofinansowania: podstawowy (dochod roczny do 135 000 PLN, do 40% kosztow), podwyzszony (dochod do 2250 PLN/os. lub 3150 PLN jednoosobowo, do 70%), najwyzszy (dochod do 1300 PLN/os. lub 1800 PLN jednoosobowo, do 100%)',
        'Zlec audyt energetyczny budynku (obowiazkowy od 31.03.2025)',
        'Przygotuj dokumenty: PIT, akt wlasnosci, audyt',
        'Zloz wniosek przez Generator Wnioskow o Dofinansowanie (GWD) na czystepowietrze.gov.pl lub w WFOSiGW',
        'Po akceptacji wniosku zrealizuj inwestycje (termomodernizacja, wymiana zrodla ciepla)',
        'Zloz wniosek o platnosc z fakturami i protokolem odbioru',
      ],
      terminRealizacji: '30 dni na rozpatrzenie wniosku, do 36 miesiecy na realizacje inwestycji',
      pulapki: [
        'Progi dochodowe: podstawowy -- dochod roczny do 135 000 PLN; podwyzszony -- do 2250 PLN/os. miesiecznie (wieloosobowe) lub 3150 PLN (jednoosobowe); najwyzszy -- do 1300 PLN/os. lub 1800 PLN',
        'Audyt energetyczny jest obowiazkowy od 31.03.2025 -- bez niego wniosek zostanie odrzucony',
        'Kotly gazowe i olejowe wykluczone od 31.03.2025 -- tylko pompy ciepla, kotly na biomase, podlaczenie do sieci cieplowniczej',
        'Koszty poniesione przed zloeniem wniosku nie beda refundowane (z wyjatkiem audytu)',
        'Budynek musi byc oddany do uzytkowania -- nie dotyczy budynkow w budowie',
      ],
      odwolanie: 'Odwolanie do WFOSiGW w ciagu 14 dni od decyzji',
    },
    zrodloUrl: 'https://czystepowietrze.gov.pl',
    zrodloNazwa: 'NFOSiGW -- Program Czyste Powietrze', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'moj-prad', nazwa: 'Moj Prad', kategoria: 'EKOLOGIA',
    kwota: 'do 7000 PLN na fotowoltaike, do 16 000 PLN na magazyn energii, do 28 000 PLN lacznie',
    kwotaMin: 0, kwotaMax: 28000,
    czestotliwosc: 'jednorazowo',
    wymagania: {},
    wykluczenia: [
      { opis: 'Dofinansowanie do 50% kosztow kwalifikowanych', sprawdz: 'procent_kosztow' },
      { opis: 'Mikroinstalacja PV od 2 kW do 20 kW mocy', sprawdz: 'moc_instalacji' },
    ],
    wniosek: {
      kanal: ['ONLINE'],
      dokumenty: [
        'Dowod osobisty',
        'Faktura za zakup i montaz instalacji PV',
        'Zaswiadczenie OSD o przyaczeniu mikroinstalacji do sieci',
        'Numer konta bankowego',
        'Umowa z operatorem systemu dystrybucji (OSD)',
      ],
      kroki: [
        'Zainstaluj mikroinstalacje fotowoltaiczna (2-20 kW) i opcjonalnie magazyn energii (min. 2 kWh) lub magazyn ciepla (min. 20 dm3)',
        'Uzyskaj zaswiadczenie o przylaczeniu mikroinstalacji do sieci od OSD',
        'Zloz wniosek online przez Generator Wnioskow na mojprad.gov.pl',
        'Dolacz faktury, zaswiadczenie OSD i dane do przelewu',
        'Oczekuj na weryfikacje i wyplate refundacji na konto bankowe',
      ],
      terminRealizacji: '90 dni od zlozenia kompletnego wniosku',
      pulapki: [
        'Program refundacyjny -- najpierw placisz, potem otrzymujesz zwrot do 50% kosztow',
        'Fotowoltaika: do 6000 PLN (sama PV) lub do 7000 PLN (PV + magazyn energii lub ciepla)',
        'Magazyn energii elektrycznej: do 16 000 PLN (min. pojemnosc 2 kWh)',
        'Magazyn ciepla: do 5000 PLN (min. pojemnosc 20 dm3)',
        'Nabor ograniczony budzetem -- po wyczerpaniu srodkow nabor zostaje zamkniety',
      ],
      odwolanie: 'Wniosek o ponowne rozpatrzenie do NFOSiGW',
    },
    zrodloUrl: 'https://mojprad.gov.pl',
    zrodloNazwa: 'NFOSiGW -- Program Moj Prad', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'moje-cieplo', nazwa: 'Moje Cieplo', kategoria: 'EKOLOGIA',
    kwota: 'do 7000 PLN (pompa powietrzna), do 21 000 PLN (pompa gruntowa)',
    kwotaMin: 0, kwotaMax: 21000,
    czestotliwosc: 'jednorazowo',
    wymagania: { wlasnosc: ['dom'] },
    wykluczenia: [
      { opis: 'Dotyczy wylacznie nowych budynkow jednorodzinnych (pozwolenie na budowe po 01.01.2021)', sprawdz: 'data_budowy' },
      { opis: 'Budynek musi spelniac podwyzszony standard energetyczny', sprawdz: 'standard_energetyczny' },
    ],
    wniosek: {
      kanal: ['ONLINE'],
      dokumenty: [
        'Dowod osobisty',
        'Charakterystyka energetyczna budynku lub swiadectwo',
        'Faktura za zakup i montaz pompy ciepla',
        'Karta Duzej Rodziny (jesli dotyczy -- podwyzszony poziom dofinansowania)',
        'Akt wlasnosci lub odpis z ksiegi wieczystej',
      ],
      kroki: [
        'Upewnij sie, ze budynek jednorodzinny ma pozwolenie na budowe wydane po 01.01.2021',
        'Zainstaluj pompe ciepla (powietrzna lub gruntowa) jako glowne zrodlo ciepla',
        'Zloz wniosek elektronicznie przez Generator Wnioskow na mojecieplo.gov.pl',
        'Dolacz fakture, charakterystyke energetyczna budynku, akt wlasnosci',
        'Oczekuj na weryfikacje i wyplate dotacji (do 30% lub 45% kosztow z Karta Duzej Rodziny)',
      ],
      terminRealizacji: '90 dni od zlozenia kompletnego wniosku, nabor do 31.12.2026 lub wyczerpania srodkow',
      pulapki: [
        'Pompa powietrze/powietrze lub powietrze/woda: do 7000 PLN; pompa gruntowa: do 21 000 PLN',
        'Standardowe dofinansowanie: do 30% kosztow kwalifikowanych; z Karta Duzej Rodziny: do 45%',
        'Dotyczy WYLACZNIE nowych budynkow -- pozwolenie na budowe po 01.01.2021',
        'Pompa ciepla musi byc glownym i jedynym zrodlem ciepla w budynku',
        'Budzet programu: 600 mln PLN -- po wyczerpaniu nabor zostanie zamkniety',
      ],
      odwolanie: 'Wniosek o ponowne rozpatrzenie do NFOSiGW w ciagu 14 dni',
    },
    zrodloUrl: 'https://mojecieplo.gov.pl',
    zrodloNazwa: 'NFOSiGW -- Program Moje Cieplo', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'cieple-mieszkanie', nazwa: 'Cieple Mieszkanie', kategoria: 'EKOLOGIA',
    kwota: 'do 16 500 PLN (podstawowy), do 27 500 PLN (podwyzszony), do 41 000 PLN (najwyzszy)',
    kwotaMin: 0, kwotaMax: 41000,
    czestotliwosc: 'jednorazowo',
    wymagania: { wlasnosc: ['mieszkanie'] },
    wykluczenia: [
      { opis: 'Dotyczy wylacznie lokali w budynkach wielorodzinnych', sprawdz: 'typ_budynku' },
      { opis: 'Koszty kwalifikowane do 31.12.2025, wyplaty do 31.12.2026', sprawdz: 'termin_programu' },
    ],
    wniosek: {
      kanal: ['URZAD_GMINY'],
      dokumenty: [
        'Dowod osobisty',
        'Akt wlasnosci lokalu mieszkalnego',
        'PIT za ostatni rok podatkowy',
        'Zaswiadczenie o dochodach (poziom podwyzszony/najwyzszy)',
        'Kosztorys planowanych prac termomodernizacyjnych',
      ],
      kroki: [
        'Sprawdz, czy Twoja gmina przystapila do programu Cieple Mieszkanie',
        'Okresl poziom dofinansowania: podstawowy (dochod roczny do 135 000 PLN, do 30%), podwyzszony (dochod do 1894 PLN/os. wieloosobowe lub 2651 PLN jednoosobowe, do 60%), najwyzszy (dochod do 1090 PLN/os. lub 1526 PLN jednoosobowe, do 90%)',
        'Zloz wniosek w urzedzie gminy wraz z wymaganymi dokumentami',
        'Po akceptacji zrealizuj wymiane zrodla ciepla i/lub termomodernizacje lokalu',
        'Zloz rozliczenie z fakturami i protokolem odbioru',
      ],
      terminRealizacji: '30-60 dni na rozpatrzenie wniosku przez gmine',
      pulapki: [
        'Program realizowany przez gminy -- nie kazda gmina przystapila do programu',
        'Mieszkancy gmin o najwyzszym zanieczyszczeniu powietrza moga uzyskac dodatkowe 5% dofinansowania',
        'Wspolnoty mieszkaniowe moga uzyskac do 375 000 PLN na budynek (z pompa ciepla)',
        'Koszty kwalifikowane tylko do 31.12.2025 -- po tym terminie nowe wydatki nie beda refundowane',
        'Progi dochodowe: podstawowy -- do 135 000 PLN rocznie; podwyzszony -- do 1894 PLN/os.; najwyzszy -- do 1090 PLN/os.',
      ],
      odwolanie: 'Odwolanie do gminy lub WFOSiGW',
    },
    zrodloUrl: 'https://czystepowietrze.gov.pl/inne-programy/cieple-mieszkanie',
    zrodloNazwa: 'NFOSiGW -- Program Cieple Mieszkanie', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'stop-smog', nazwa: 'Stop Smog', kategoria: 'EKOLOGIA',
    kwota: 'do 53 000 PLN na budynek (100% kosztow)',
    kwotaMin: 0, kwotaMax: 53000,
    czestotliwosc: 'jednorazowo',
    wymagania: { wlasnosc: ['dom'], dochodMax: 2342 },
    wykluczenia: [
      { opis: 'PROGRAM ZAKONCZONY -- nabor wnioskow zamkniety z koncem 2024 roku. Niewykorzystane srodki (ok. 150 mln PLN) przeznaczone na termomodernizacje budynkow wielorodzinnych.', sprawdz: 'program_aktywny' },
      { opis: 'Dotyczy wylacznie gmin objetych uchwala antysmogowa, ktore podpisaly porozumienie z NFOSiGW', sprawdz: 'gmina_stop_smog' },
      { opis: 'Mieszkaniec musi posiadac co najmniej polowe udzialu we wlasnosci budynku', sprawdz: 'udzial_wlasnosci' },
    ],
    wniosek: {
      kanal: ['URZAD_GMINY'],
      dokumenty: [
        'Dowod osobisty',
        'Akt wlasnosci budynku jednorodzinnego',
        'Zaswiadczenie o dochodach (dochod do 175% minimalnej emerytury na osobe -- jednoosobowe, lub 125% -- wieloosobowe)',
        'Oswiadczenie o majatku nieprzekraczajacym 53 000 PLN (z wylaczeniem wartosci budynku)',
      ],
      kroki: [
        'UWAGA: Program zakonczony z koncem 2024 roku -- ponizsze kroki dotycza archiwalnej procedury',
        'Sprawdz, czy gmina przystapila do programu Stop Smog i podpisala porozumienie z NFOSiGW',
        'Zloz wniosek w urzedzie gminy z dokumentami dochodowymi i majatkowymi',
        'Gmina organizuje i finansuje termomodernizacje -- mieszkaniec nie ponosi kosztow',
        'Po realizacji: budynek musi utrzymac efekt ekologiczny przez 10 lat',
      ],
      terminRealizacji: 'Program zakonczony -- brak nowych naborow',
      pulapki: [
        'Program zamkniety z koncem 2024 -- nowe wnioski nie sa przyjmowane',
        'Progi dochodowe: do 2342 PLN netto/os. (jednoosobowe) lub do 1873 PLN netto/os. (wieloosobowe)',
        'Majatek wnioskodawcy nie mogl przekraczac 53 000 PLN (bez wartosci budynku)',
        'Gmina finansowala 30% kosztow ze srodkow wlasnych, 70% z budzetu panstwa',
        'Obowiazek utrzymania efektow termomodernizacji przez 10 lat po realizacji',
      ],
      odwolanie: 'Nie dotyczy -- program zakonczony',
    },
    zrodloUrl: 'https://czystepowietrze.gov.pl/inne-programy/stop-smog',
    zrodloNazwa: 'NFOSiGW -- Program Stop Smog (zakonczony)', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'dodatek-oslonowy', nazwa: 'Dodatek oslonowy', kategoria: 'EKOLOGIA',
    kwota: '228,80-822,25 PLN (ostatnia edycja 2024)',
    kwotaMin: 228, kwotaMax: 822,
    czestotliwosc: 'jednorazowo (rocznie, ostatnia edycja 2024)',
    wymagania: { dochodMax: 2500 },
    wykluczenia: [
      { opis: 'PROGRAM ZAKONCZONY -- ostatnia edycja w 2024 roku, rzad nie przedluzyl na 2025/2026', sprawdz: 'program_aktywny' },
      { opis: 'Program mial charakter przejsciowy -- odpowiedz na kyzys energetyczny 2022-2023', sprawdz: 'status_programu' },
    ],
    wniosek: {
      kanal: ['MOPS', 'URZAD_GMINY'],
      dokumenty: [
        'Dowod osobisty',
        'Zaswiadczenie o dochodach lub PIT',
        'Numer konta bankowego',
      ],
      kroki: [
        'UWAGA: Program zakonczony -- ostatnie wnioski przyjmowano do 30.04.2024, wyplaty do 30.06.2024',
        'Zlozenie wniosku w MOPS lub urzedzie gminy wlasciwym dla miejsca zamieszkania',
        'Kwoty zalezaly od liczby osob w gospodarstwie: 1 os. -- 228,80 PLN, 2-3 os. -- 343,20 PLN, 4-5 os. -- 486,20 PLN, 6+ os. -- 657,80 PLN',
        'Przy ogrzewaniu weglem stawki podwyzszone: 1 os. -- 286 PLN, 2-3 os. -- 429 PLN, 4-5 os. -- 607,75 PLN, 6+ os. -- 822,25 PLN',
      ],
      terminRealizacji: 'Program zakonczony -- brak nowych naborow',
      pulapki: [
        'Program zakonczony z koncem 2024 -- nowe wnioski nie sa przyjmowane',
        'Progi dochodowe w ostatniej edycji: do 2500 PLN netto/os. (jednoosobowe) lub 1700 PLN/os. (wieloosobowe)',
        'Kwota minimalna wyplaty wynosila 20 PLN -- ponizej tej kwoty swiadczenie nie przysugiwalo',
        'Dodatek nie podlegal opodatkowaniu -- nie wykazywany w PIT',
      ],
      odwolanie: 'Nie dotyczy -- program zakonczony',
    },
    zrodloUrl: 'https://www.gov.pl/web/klimat/dodatek-oslonowy',
    zrodloNazwa: 'Ministerstwo Klimatu i Srodowiska (program zakonczony)', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
];
