import { Benefit } from '../types';

export const EKOLOGIA: Benefit[] = [
  {
    id: 'czyste-powietrze', nazwa: 'Czyste Powietrze', kategoria: 'EKOLOGIA',
    kwota: 'do 66 000 PLN (podstawowy), do 99 000 PLN (podwyższony), do 135 000 PLN (najwyższy)',
    kwotaMin: 0, kwotaMax: 135000,
    czestotliwosc: 'jednorazowo',
    wymagania: { wlasnosc: ['dom'] },
    wykluczenia: [
      { opis: 'Dotyczy wyłącznie budynków jednorodzinnych', sprawdz: 'typ_budynku' },
      { opis: 'Od 31.03.2025 kotły gazowe i olejowe wykluczone z dofinansowania', sprawdz: 'zrodlo_ciepla' },
    ],
    wniosek: {
      kanal: ['WFOSIGW', 'ONLINE'],
      dokumenty: [
        'Dowód osobisty',
        'PIT za ostatni rok podatkowy',
        'Akt własności lub odpis z księgi wieczystej',
        'Audyt energetyczny budynku (wymagany od 31.03.2025)',
        'Zaświadczenie o dochodach z urzędu gminy (poziom podwyższony/najwyższy)',
      ],
      kroki: [
        'Określ poziom dofinansowania: podstawowy (dochód roczny do 135 000 PLN, do 40% kosztów), podwyższony (dochód do 2250 PLN/os. lub 3150 PLN jednoosobowo, do 70%), najwyższy (dochód do 1300 PLN/os. lub 1800 PLN jednoosobowo, do 100%)',
        'Zleć audyt energetyczny budynku (obowiązkowy od 31.03.2025)',
        'Przygotuj dokumenty: PIT, akt własności, audyt',
        'Złóż wniosek przez Generator Wniosków o Dofinansowanie (GWD) na czystepowietrze.gov.pl lub w WFOSiGW',
        'Po akceptacji wniosku zrealizuj inwestycję (termomodernizacja, wymiana źródła ciepła)',
        'Złóż wniosek o płatność z fakturami i protokołem odbioru',
      ],
      terminRealizacji: '30 dni na rozpatrzenie wniosku, do 36 miesięcy na realizację inwestycji',
      pulapki: [
        'Progi dochodowe: podstawowy, dochód roczny do 135 000 PLN; podwyższony, do 2250 PLN/os. miesięcznie (wieloosobowe) lub 3150 PLN (jednoosobowe); najwyższy, do 1300 PLN/os. lub 1800 PLN',
        'Audyt energetyczny jest obowiązkowy od 31.03.2025. Bez niego wniosek zostanie odrzucony',
        'Kotły gazowe i olejowe wykluczone od 31.03.2025. Dopuszczone: pompy ciepła, kotły na biomasę, podłączenie do sieci ciepłowniczej',
        'Koszty poniesione przed złożeniem wniosku nie będą refundowane (z wyjątkiem audytu)',
        'Budynek musi być oddany do użytkowania (nie dotyczy budynków w budowie)',
      ],
      odwolanie: 'Odwołanie do WFOSiGW w ciągu 14 dni od decyzji',
    },
    zrodloUrl: 'https://czystepowietrze.gov.pl',
    zrodloNazwa: 'NFOŚiGW, Program Czyste Powietrze', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'moj-prad', nazwa: 'Mój Prąd', kategoria: 'EKOLOGIA',
    kwota: 'do 7000 PLN na fotowoltaikę, do 16 000 PLN na magazyn energii, do 28 000 PLN łącznie',
    kwotaMin: 0, kwotaMax: 28000,
    czestotliwosc: 'jednorazowo',
    wymagania: {},
    wykluczenia: [
      { opis: 'Dofinansowanie do 50% kosztów kwalifikowanych', sprawdz: 'procent_kosztow' },
      { opis: 'Mikroinstalacja PV od 2 kW do 20 kW mocy', sprawdz: 'moc_instalacji' },
    ],
    wniosek: {
      kanal: ['ONLINE'],
      dokumenty: [
        'Dowód osobisty',
        'Faktura za zakup i montaż instalacji PV',
        'Zaświadczenie OSD o przyłączeniu mikroinstalacji do sieci',
        'Numer konta bankowego',
        'Umowa z operatorem systemu dystrybucji (OSD)',
      ],
      kroki: [
        'Zainstaluj mikroinstalację fotowoltaiczną (2-20 kW) i opcjonalnie magazyn energii (min. 2 kWh) lub magazyn ciepła (min. 20 dm3)',
        'Uzyskaj zaświadczenie o przyłączeniu mikroinstalacji do sieci od OSD',
        'Złóż wniosek online przez Generator Wniosków na mojprad.gov.pl',
        'Dołącz faktury, zaświadczenie OSD i dane do przelewu',
        'Oczekuj na weryfikację i wypłatę refundacji na konto bankowe',
      ],
      terminRealizacji: '90 dni od złożenia kompletnego wniosku',
      pulapki: [
        'Program refundacyjny: najpierw płacisz, potem otrzymujesz zwrot do 50% kosztów',
        'Fotowoltaika: do 6000 PLN (sama PV) lub do 7000 PLN (PV + magazyn energii lub ciepła)',
        'Magazyn energii elektrycznej: do 16 000 PLN (min. pojemność 2 kWh)',
        'Magazyn ciepła: do 5000 PLN (min. pojemność 20 dm3)',
        'Nabór ograniczony budżetem. Po wyczerpaniu środków nabór zostaje zamknięty',
      ],
      odwolanie: 'Wniosek o ponowne rozpatrzenie do NFOŚiGW',
    },
    zrodloUrl: 'https://mojprad.gov.pl',
    zrodloNazwa: 'NFOŚiGW, Program Mój Prąd', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'moje-cieplo', nazwa: 'Moje Ciepło', kategoria: 'EKOLOGIA',
    kwota: 'do 7000 PLN (pompa powietrzna), do 21 000 PLN (pompa gruntowa)',
    kwotaMin: 0, kwotaMax: 21000,
    czestotliwosc: 'jednorazowo',
    wymagania: { wlasnosc: ['dom'] },
    wykluczenia: [
      { opis: 'Dotyczy wyłącznie nowych budynków jednorodzinnych (pozwolenie na budowę po 01.01.2021)', sprawdz: 'data_budowy' },
      { opis: 'Budynek musi spełniać podwyższony standard energetyczny', sprawdz: 'standard_energetyczny' },
    ],
    wniosek: {
      kanal: ['ONLINE'],
      dokumenty: [
        'Dowód osobisty',
        'Charakterystyka energetyczna budynku lub świadectwo',
        'Faktura za zakup i montaż pompy ciepła',
        'Karta Dużej Rodziny (jeśli dotyczy, podwyższony poziom dofinansowania)',
        'Akt własności lub odpis z księgi wieczystej',
      ],
      kroki: [
        'Upewnij się, że budynek jednorodzinny ma pozwolenie na budowę wydane po 01.01.2021',
        'Zainstaluj pompę ciepła (powietrzną lub gruntową) jako główne źródło ciepła',
        'Złóż wniosek elektronicznie przez Generator Wniosków na mojecieplo.gov.pl',
        'Dołącz fakturę, charakterystykę energetyczną budynku, akt własności',
        'Oczekuj na weryfikację i wypłatę dotacji (do 30% lub 45% kosztów z Kartą Dużej Rodziny)',
      ],
      terminRealizacji: '90 dni od złożenia kompletnego wniosku, nabór do 31.12.2026 lub wyczerpania środków',
      pulapki: [
        'Pompa powietrze/powietrze lub powietrze/woda: do 7000 PLN; pompa gruntowa: do 21 000 PLN',
        'Standardowe dofinansowanie: do 30% kosztów kwalifikowanych; z Kartą Dużej Rodziny: do 45%',
        'Dotyczy WYŁĄCZNIE nowych budynków (pozwolenie na budowę po 01.01.2021)',
        'Pompa ciepła musi być głównym i jedynym źródłem ciepła w budynku',
        'Budżet programu: 600 mln PLN. Po wyczerpaniu nabór zostanie zamknięty',
      ],
      odwolanie: 'Wniosek o ponowne rozpatrzenie do NFOŚiGW w ciągu 14 dni',
    },
    zrodloUrl: 'https://mojecieplo.gov.pl',
    zrodloNazwa: 'NFOŚiGW, Program Moje Ciepło', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'cieple-mieszkanie', nazwa: 'Ciepłe Mieszkanie', kategoria: 'EKOLOGIA',
    kwota: 'do 16 500 PLN (podstawowy), do 27 500 PLN (podwyższony), do 41 000 PLN (najwyższy)',
    kwotaMin: 0, kwotaMax: 41000,
    czestotliwosc: 'jednorazowo',
    wymagania: { wlasnosc: ['mieszkanie'] },
    wykluczenia: [
      { opis: 'Dotyczy wyłącznie lokali w budynkach wielorodzinnych', sprawdz: 'typ_budynku' },
      { opis: 'Koszty kwalifikowane do 31.12.2025, wypłaty do 31.12.2026', sprawdz: 'termin_programu' },
    ],
    wniosek: {
      kanal: ['URZAD_GMINY'],
      dokumenty: [
        'Dowód osobisty',
        'Akt własności lokalu mieszkalnego',
        'PIT za ostatni rok podatkowy',
        'Zaświadczenie o dochodach (poziom podwyższony/najwyższy)',
        'Kosztorys planowanych prac termomodernizacyjnych',
      ],
      kroki: [
        'Sprawdź, czy Twoja gmina przystąpiła do programu Ciepłe Mieszkanie',
        'Określ poziom dofinansowania: podstawowy (dochód roczny do 135 000 PLN, do 30%), podwyższony (dochód do 1894 PLN/os. wieloosobowe lub 2651 PLN jednoosobowe, do 60%), najwyższy (dochód do 1090 PLN/os. lub 1526 PLN jednoosobowe, do 90%)',
        'Złóż wniosek w urzędzie gminy wraz z wymaganymi dokumentami',
        'Po akceptacji zrealizuj wymianę źródła ciepła i/lub termomodernizację lokalu',
        'Złóż rozliczenie z fakturami i protokołem odbioru',
      ],
      terminRealizacji: '30-60 dni na rozpatrzenie wniosku przez gminę',
      pulapki: [
        'Program realizowany przez gminy. Nie każda gmina przystąpiła do programu',
        'Mieszkańcy gmin o najwyższym zanieczyszczeniu powietrza mogą uzyskać dodatkowe 5% dofinansowania',
        'Wspólnoty mieszkaniowe mogą uzyskać do 375 000 PLN na budynek (z pompą ciepła)',
        'Koszty kwalifikowane tylko do 31.12.2025. Po tym terminie nowe wydatki nie będą refundowane',
        'Progi dochodowe: podstawowy, do 135 000 PLN rocznie; podwyższony, do 1894 PLN/os.; najwyższy, do 1090 PLN/os.',
      ],
      odwolanie: 'Odwołanie do gminy lub WFOŚiGW',
    },
    zrodloUrl: 'https://czystepowietrze.gov.pl/inne-programy/cieple-mieszkanie',
    zrodloNazwa: 'NFOŚiGW, Program Ciepłe Mieszkanie', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'stop-smog', nazwa: 'Stop Smog', kategoria: 'EKOLOGIA',
    kwota: 'do 53 000 PLN na budynek (100% kosztów)',
    kwotaMin: 0, kwotaMax: 53000,
    czestotliwosc: 'jednorazowo',
    wymagania: { wlasnosc: ['dom'], dochodMax: 2342 },
    wykluczenia: [
      { opis: 'PROGRAM ZAKOŃCZONY. Nabór wniosków zamknięty z końcem 2024 roku. Niewykorzystane środki (ok. 150 mln PLN) przeznaczone na termomodernizację budynków wielorodzinnych.', sprawdz: 'program_aktywny' },
      { opis: 'Dotyczy wyłącznie gmin objętych uchwałą antysmogową, które podpisały porozumienie z NFOŚiGW', sprawdz: 'gmina_stop_smog' },
      { opis: 'Mieszkaniec musi posiadać co najmniej połowę udziału we własności budynku', sprawdz: 'udzial_wlasnosci' },
    ],
    wniosek: {
      kanal: ['URZAD_GMINY'],
      dokumenty: [
        'Dowód osobisty',
        'Akt własności budynku jednorodzinnego',
        'Zaświadczenie o dochodach (dochód do 175% minimalnej emerytury na osobę dla jednoosobowych, lub 125% dla wieloosobowych)',
        'Oświadczenie o majątku nieprzekraczającym 53 000 PLN (z wyłączeniem wartości budynku)',
      ],
      kroki: [
        'UWAGA: Program zakończony z końcem 2024 roku. Poniższe kroki dotyczą archiwalnej procedury',
        'Sprawdź, czy gmina przystąpiła do programu Stop Smog i podpisała porozumienie z NFOŚiGW',
        'Złóż wniosek w urzędzie gminy z dokumentami dochodowymi i majątkowymi',
        'Gmina organizuje i finansuje termomodernizację, mieszkaniec nie ponosi kosztów',
        'Po realizacji: budynek musi utrzymać efekt ekologiczny przez 10 lat',
      ],
      terminRealizacji: 'Program zakończony, brak nowych naborów',
      pulapki: [
        'Program zamknięty z końcem 2024. Nowe wnioski nie są przyjmowane',
        'Progi dochodowe: do 2342 PLN netto/os. (jednoosobowe) lub do 1873 PLN netto/os. (wieloosobowe)',
        'Majątek wnioskodawcy nie mógł przekraczać 53 000 PLN (bez wartości budynku)',
        'Gmina finansowała 30% kosztów ze środków własnych, 70% z budżetu państwa',
        'Obowiązek utrzymania efektów termomodernizacji przez 10 lat po realizacji',
      ],
      odwolanie: 'Nie dotyczy (program zakończony)',
    },
    zrodloUrl: 'https://czystepowietrze.gov.pl/inne-programy/stop-smog',
    zrodloNazwa: 'NFOŚiGW, Program Stop Smog (zakończony)', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'dodatek-oslonowy', nazwa: 'Dodatek osłonowy', kategoria: 'EKOLOGIA',
    kwota: '228,80-822,25 PLN (ostatnia edycja 2024)',
    kwotaMin: 228, kwotaMax: 822,
    czestotliwosc: 'jednorazowo (rocznie, ostatnia edycja 2024)',
    wymagania: { dochodMax: 2500 },
    wykluczenia: [
      { opis: 'PROGRAM ZAKOŃCZONY. Ostatnia edycja w 2024 roku, rząd nie przedłużył na 2025/2026', sprawdz: 'program_aktywny' },
      { opis: 'Program miał charakter przejściowy (odpowiedź na kryzys energetyczny 2022-2023)', sprawdz: 'status_programu' },
    ],
    wniosek: {
      kanal: ['MOPS', 'URZAD_GMINY'],
      dokumenty: [
        'Dowód osobisty',
        'Zaświadczenie o dochodach lub PIT',
        'Numer konta bankowego',
      ],
      kroki: [
        'UWAGA: Program zakończony. Ostatnie wnioski przyjmowano do 30.04.2024, wypłaty do 30.06.2024',
        'Złożenie wniosku w MOPS lub urzędzie gminy właściwym dla miejsca zamieszkania',
        'Kwoty zależały od liczby osób w gospodarstwie: 1 os. 228,80 PLN, 2-3 os. 343,20 PLN, 4-5 os. 486,20 PLN, 6+ os. 657,80 PLN',
        'Przy ogrzewaniu węglem stawki podwyższone: 1 os. 286 PLN, 2-3 os. 429 PLN, 4-5 os. 607,75 PLN, 6+ os. 822,25 PLN',
      ],
      terminRealizacji: 'Program zakończony, brak nowych naborów',
      pulapki: [
        'Program zakończony z końcem 2024, nowe wnioski nie są przyjmowane',
        'Progi dochodowe w ostatniej edycji: do 2500 PLN netto/os. (jednoosobowe) lub 1700 PLN/os. (wieloosobowe)',
        'Kwota minimalna wypłaty wynosiła 20 PLN. Poniżej tej kwoty świadczenie nie przysługiwało',
        'Dodatek nie podlegał opodatkowaniu, nie wykazywany w PIT',
      ],
      odwolanie: 'Nie dotyczy (program zakończony)',
    },
    zrodloUrl: 'https://www.gov.pl/web/klimat/dodatek-oslonowy',
    zrodloNazwa: 'Ministerstwo Klimatu i Środowiska (program zakończony)', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
];
