import { Benefit } from '../types';

export const EKOLOGIA: Benefit[] = [
  {
    id: 'czyste-powietrze', nazwa: 'Czyste Powietrze',
    opis: 'Czyste Powietrze to największy w Europie program termomodernizacji budynków jednorodzinnych. Dofinansowanie obejmuje wymianę źródła ciepła (stary piec na pompę ciepła, kocioł na biomasę lub podłączenie do sieci ciepłowniczej) oraz ocieplenie budynku (izolacja ścian, dachu, wymiana okien i drzwi). Trzy poziomy dofinansowania: podstawowy,dochód roczny do 135 000 PLN, do 40% kosztów (max 66 000 PLN); podwyższony,dochód do 2250 PLN/os. miesięcznie (wieloosobowe) lub 3150 PLN (jednoosobowe), do 70% (max 99 000 PLN); najwyższy,dochód do 1300 PLN/os. lub 1800 PLN (jednoosobowe), do 100% (max 135 000 PLN). Od 31.03.2025 obowiązkowy audyt energetyczny budynku i wykluczone kotły gazowe i olejowe. Dotyczy WYŁĄCZNIE istniejących budynków jednorodzinnych (nie mieszkań w blokach). Częsty błąd: ponoszenie kosztów przed złożeniem wniosku,wydatki sprzed złożenia wniosku nie są refundowane (wyjątek: audyt energetyczny). Praktyczna rada: zacznij od audytu energetycznego, który pokaże optymalne rozwiązania i pozwoli uniknąć przepłacania.',
    kategoria: 'EKOLOGIA',
    kwota: 'do 66 000 PLN (podstawowy), do 99 000 PLN (podwyższony), do 135 000 PLN (najwyższy)',
    kwotaMin: 0, kwotaMax: 135000,
    czestotliwosc: 'jednorazowo',
    wymagania: { wlasnosc: ['dom'] },
    wykluczenia: [
      { opis: 'Dotyczy wyłącznie budynków jednorodzinnych', sprawdz: 'typ_budynku' },
      { opis: 'Od 31.03.2025 kotły gazowe i olejowe wykluczone z dofinansowania', sprawdz: 'zrodlo_ciepla' },
    ],
    wniosek: {
      kanal: ['WFOSIGW', 'ONLINE'],
      dokumenty: [
        'Dowód osobisty',
        'PIT za ostatni rok podatkowy',
        'Akt własności lub odpis z księgi wieczystej',
        'Audyt energetyczny budynku (wymagany od 31.03.2025)',
        'Zaświadczenie o dochodach z urzędu gminy (poziom podwyższony/najwyższy)',
      ],
      kroki: [
        'Określ poziom dofinansowania: podstawowy (dochód roczny do 135 000 PLN, do 40% kosztów), podwyższony (dochód do 2250 PLN/os. lub 3150 PLN jednoosobowo, do 70%), najwyższy (dochód do 1300 PLN/os. lub 1800 PLN jednoosobowo, do 100%)',
        'Zleć audyt energetyczny budynku (obowiązkowy od 31.03.2025)',
        'Przygotuj dokumenty: PIT, akt własności, audyt',
        'Złóż wniosek przez Generator Wniosków o Dofinansowanie (GWD) na czystepowietrze.gov.pl lub w WFOSiGW',
        'Po akceptacji wniosku zrealizuj inwestycję (termomodernizacja, wymiana źródła ciepła)',
        'Złóż wniosek o płatność z fakturami i protokołem odbioru',
      ],
      terminRealizacji: '30 dni na rozpatrzenie wniosku, do 36 miesięcy na realizację inwestycji',
      pulapki: [
        'Progi dochodowe: podstawowy, dochód roczny do 135 000 PLN; podwyższony, do 2250 PLN/os. miesięcznie (wieloosobowe) lub 3150 PLN (jednoosobowe); najwyższy, do 1300 PLN/os. lub 1800 PLN',
        'Audyt energetyczny jest obowiązkowy od 31.03.2025. Bez niego wniosek zostanie odrzucony',
        'Kotły gazowe i olejowe wykluczone od 31.03.2025. Dopuszczone: pompy ciepła, kotły na biomasę, podłączenie do sieci ciepłowniczej',
        'Koszty poniesione przed złożeniem wniosku nie będą refundowane (z wyjątkiem audytu)',
        'Budynek musi być oddany do użytkowania (nie dotyczy budynków w budowie)',
      ],
      odwolanie: 'Odwołanie do WFOSiGW w ciągu 14 dni od decyzji',
    },
    zrodloUrl: 'https://czystepowietrze.gov.pl',
    zrodloNazwa: 'NFOŚiGW, Program Czyste Powietrze', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'moj-prad', nazwa: 'Mój Prąd (zakończony)',
    opis: 'PROGRAM ZAKOŃCZONY. Mój Prąd 6.0 zakończył nabór wniosków we wrześniu 2025 roku po wyczerpaniu budżetu. NFOŚiGW oficjalnie potwierdziło w marcu 2026, że edycja 7.0 nie zostanie uruchomiona i program nie będzie kontynuowany. W edycji 6.0 dofinansowanie wynosiło: do 7000 PLN na fotowoltaikę (z magazynem energii lub ciepła), do 6000 PLN na samą fotowoltaikę, do 16 000 PLN na magazyn energii elektrycznej (min. 2 kWh), do 5000 PLN na magazyn ciepła (min. 20 dm3). Łącznie do 28 000 PLN, max 50% kosztów. Program miał charakter refundacyjny. Dla osób planujących fotowoltaikę dostępne są alternatywy: program Czyste Powietrze (jeśli wymiana źródła ciepła + PV) lub ulga termomodernizacyjna w PIT (30% kosztów fotowoltaiki, max 53 000 PLN odliczenia).',
    kategoria: 'EKOLOGIA',
    kwota: 'do 28 000 PLN łącznie (ostatnia edycja 6.0, 2025)',
    kwotaMin: 0, kwotaMax: 28000,
    czestotliwosc: 'jednorazowo (ostatnia edycja 2025)',
    wymagania: {},
    wykluczenia: [
      { opis: 'PROGRAM ZAKOŃCZONY. Nabór 6.0 zamknięty wrzesień 2025. NFOŚiGW potwierdziło brak edycji 7.0.', sprawdz: 'program_aktywny' },
    ],
    wniosek: {
      kanal: ['ONLINE'],
      dokumenty: [
        'Dowód osobisty',
        'Faktura za zakup i montaż instalacji PV',
        'Zaświadczenie OSD o przyłączeniu mikroinstalacji do sieci',
        'Numer konta bankowego',
      ],
      kroki: [
        'UWAGA: Program zakończony. Nabór 6.0 zamknięty we wrześniu 2025, edycja 7.0 odwołana przez NFOŚiGW',
        'Alternatywy: program Czyste Powietrze (fotowoltaika przy wymianie źródła ciepła) lub ulga termomodernizacyjna w PIT',
        'Ulga termomodernizacyjna: 30% kosztów PV odliczysz od podatku, max 53 000 PLN łącznie z innymi pracami',
      ],
      terminRealizacji: 'Program zakończony, brak nowych naborów',
      pulapki: [
        'Program Mój Prąd 6.0 zakończony wrzesień 2025. Edycja 7.0 oficjalnie odwołana przez NFOŚiGW (marzec 2026)',
        'Ulga termomodernizacyjna w PIT może zastąpić część korzyści: 30% kosztów PV, max 53 000 PLN odliczenia',
        'Program Czyste Powietrze: PV może być elementem szerszej termomodernizacji budynku jednorodzinnego',
      ],
      odwolanie: 'Nie dotyczy (program zakończony)',
    },
    zrodloUrl: 'https://mojprad.gov.pl',
    zrodloNazwa: 'NFOŚiGW, Program Mój Prąd (zakończony)', dataWeryfikacji: '2026-05-23', dataWaznosci: '2025-09-30',
  },
  {
    id: 'moje-cieplo', nazwa: 'Moje Ciepło',
    opis: 'Moje Ciepło to program dotacji na pompy ciepła w NOWYCH budynkach jednorodzinnych (pozwolenie na budowę wydane po 01.01.2021). Dofinansowanie: pompa powietrzna (powietrze/woda lub powietrze/powietrze) do 7000 PLN (30% kosztów), pompa gruntowa do 21 000 PLN (30% kosztów). Posiadacze Karty Dużej Rodziny mogą uzyskać do 45% kosztów. Pompa ciepła musi być głównym i jedynym źródłem ciepła w budynku. Budynek musi spełniać podwyższony standard energetyczny (wskaźnik EP nie wyższy niż 55 kWh/(m2·rok) zgodnie z aktualnymi warunkami technicznymi). Wniosek online na mojecieplo.gov.pl. Nabór do 31.12.2026 lub wyczerpania budżetu (600 mln PLN). Częsty błąd: zakup pompy do istniejącego budynku,ten program dotyczy TYLKO nowych budynków; do starych jest program Czyste Powietrze. Praktyczna rada: pompa gruntowa ma wyższe dofinansowanie i niższe koszty eksploatacji, ale wyższy koszt instalacji,policz TCO na 15 lat.',
    kategoria: 'EKOLOGIA',
    kwota: 'do 7000 PLN (pompa powietrzna), do 21 000 PLN (pompa gruntowa)',
    kwotaMin: 0, kwotaMax: 21000,
    czestotliwosc: 'jednorazowo',
    wymagania: { wlasnosc: ['dom'] },
    wykluczenia: [
      { opis: 'Dotyczy wyłącznie nowych budynków jednorodzinnych (pozwolenie na budowę po 01.01.2021)', sprawdz: 'data_budowy' },
      { opis: 'Budynek musi spełniać podwyższony standard energetyczny', sprawdz: 'standard_energetyczny' },
    ],
    wniosek: {
      kanal: ['ONLINE'],
      dokumenty: [
        'Dowód osobisty',
        'Charakterystyka energetyczna budynku lub świadectwo',
        'Faktura za zakup i montaż pompy ciepła',
        'Karta Dużej Rodziny (jeśli dotyczy, podwyższony poziom dofinansowania)',
        'Akt własności lub odpis z księgi wieczystej',
      ],
      kroki: [
        'Upewnij się, że budynek jednorodzinny ma pozwolenie na budowę wydane po 01.01.2021',
        'Zainstaluj pompę ciepła (powietrzną lub gruntową) jako główne źródło ciepła',
        'Złóż wniosek elektronicznie przez Generator Wniosków na mojecieplo.gov.pl',
        'Dołącz fakturę, charakterystykę energetyczną budynku, akt własności',
        'Oczekuj na weryfikację i wypłatę dotacji (do 30% lub 45% kosztów z Kartą Dużej Rodziny)',
      ],
      terminRealizacji: '90 dni od złożenia kompletnego wniosku, nabór do 31.12.2026 lub wyczerpania środków',
      pulapki: [
        'Pompa powietrze/powietrze lub powietrze/woda: do 7000 PLN; pompa gruntowa: do 21 000 PLN',
        'Standardowe dofinansowanie: do 30% kosztów kwalifikowanych; z Kartą Dużej Rodziny: do 45%',
        'Dotyczy WYŁĄCZNIE nowych budynków (pozwolenie na budowę po 01.01.2021)',
        'Pompa ciepła musi być głównym i jedynym źródłem ciepła w budynku',
        'Budżet programu: 600 mln PLN. Po wyczerpaniu nabór zostanie zamknięty',
      ],
      odwolanie: 'Wniosek o ponowne rozpatrzenie do NFOŚiGW w ciągu 14 dni',
    },
    zrodloUrl: 'https://mojecieplo.gov.pl',
    zrodloNazwa: 'NFOŚiGW, Program Moje Ciepło', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'cieple-mieszkanie', nazwa: 'Ciepłe Mieszkanie',
    opis: 'Ciepłe Mieszkanie to program dofinansowania wymiany źródeł ciepła i termomodernizacji w budynkach wielorodzinnych (blokach, kamienicach). Skierowany do właścicieli lokali mieszkalnych w budynkach wielorodzinnych. Trzy poziomy: podstawowy,dochód roczny do 135 000 PLN, do 30% kosztów (max 16 500 PLN); podwyższony,dochód do 1894 PLN/os. (wieloosobowe) lub 2651 PLN (jednoosobowe), do 60% (max 27 500 PLN); najwyższy,dochód do 1090 PLN/os. lub 1526 PLN (jednoosobowe), do 90% (max 41 000 PLN). Wspólnoty mieszkaniowe mogą uzyskać do 375 000 PLN na cały budynek (z pompą ciepła). Program realizowany przez gminy,nie każda gmina przystąpiła, więc najpierw sprawdź w swoim urzędzie. Koszty kwalifikowane do 31.12.2025. Częsty błąd: założenie, że program działa wszędzie,to gmina decyduje o przystąpieniu i składa wniosek do WFOŚiGW. Praktyczna rada: jeśli Twoja gmina nie przystąpiła, napisz do wójta/burmistrza z prośbą o przystąpienie do programu.',
    kategoria: 'EKOLOGIA',
    kwota: 'do 16 500 PLN (podstawowy), do 27 500 PLN (podwyższony), do 41 000 PLN (najwyższy)',
    kwotaMin: 0, kwotaMax: 41000,
    czestotliwosc: 'jednorazowo',
    wymagania: { wlasnosc: ['mieszkanie'] },
    wykluczenia: [
      { opis: 'Dotyczy wyłącznie lokali w budynkach wielorodzinnych', sprawdz: 'typ_budynku' },
      { opis: 'Koszty kwalifikowane do 31.12.2025, wypłaty do 31.12.2026', sprawdz: 'termin_programu' },
    ],
    wniosek: {
      kanal: ['URZAD_GMINY'],
      dokumenty: [
        'Dowód osobisty',
        'Akt własności lokalu mieszkalnego',
        'PIT za ostatni rok podatkowy',
        'Zaświadczenie o dochodach (poziom podwyższony/najwyższy)',
        'Kosztorys planowanych prac termomodernizacyjnych',
      ],
      kroki: [
        'Sprawdź, czy Twoja gmina przystąpiła do programu Ciepłe Mieszkanie',
        'Określ poziom dofinansowania: podstawowy (dochód roczny do 135 000 PLN, do 30%), podwyższony (dochód do 1894 PLN/os. wieloosobowe lub 2651 PLN jednoosobowe, do 60%), najwyższy (dochód do 1090 PLN/os. lub 1526 PLN jednoosobowe, do 90%)',
        'Złóż wniosek w urzędzie gminy wraz z wymaganymi dokumentami',
        'Po akceptacji zrealizuj wymianę źródła ciepła i/lub termomodernizację lokalu',
        'Złóż rozliczenie z fakturami i protokołem odbioru',
      ],
      terminRealizacji: '30-60 dni na rozpatrzenie wniosku przez gminę',
      pulapki: [
        'Program realizowany przez gminy. Nie każda gmina przystąpiła do programu',
        'Mieszkańcy gmin o najwyższym zanieczyszczeniu powietrza mogą uzyskać dodatkowe 5% dofinansowania',
        'Wspólnoty mieszkaniowe mogą uzyskać do 375 000 PLN na budynek (z pompą ciepła)',
        'Koszty kwalifikowane tylko do 31.12.2025. Po tym terminie nowe wydatki nie będą refundowane',
        'Progi dochodowe: podstawowy, do 135 000 PLN rocznie; podwyższony, do 1894 PLN/os.; najwyższy, do 1090 PLN/os.',
      ],
      odwolanie: 'Odwołanie do gminy lub WFOŚiGW',
    },
    zrodloUrl: 'https://czystepowietrze.gov.pl/inne-programy/cieple-mieszkanie',
    zrodloNazwa: 'NFOŚiGW, Program Ciepłe Mieszkanie', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'stop-smog', nazwa: 'Stop Smog',
    opis: 'PROGRAM ZAKOŃCZONY z końcem 2024 roku. Stop Smog był programem 100% dofinansowania termomodernizacji budynków jednorodzinnych dla osób ubogich energetycznie w gminach objętych uchwałą antysmogową. Dofinansowanie do 53 000 PLN na budynek, pokrywające pełne koszty wymiany pieca, ocieplenia i wymiany okien. Gmina finansowała 30% ze środków własnych, 70% z budżetu państwa. Warunki: dochód do 2342 PLN netto/os. (jednoosobowe) lub 1873 PLN/os. (wieloosobowe), majątek do 53 000 PLN (bez wartości budynku), co najmniej 50% udziału we własności budynku. Mieszkaniec nie ponosił żadnych kosztów. Obowiązek utrzymania efektów termomodernizacji przez 10 lat. Niewykorzystane środki (ok. 150 mln PLN) przekierowano na termomodernizację budynków wielorodzinnych. Dla osób w podobnej sytuacji materialnej dostępny jest program Czyste Powietrze na poziomie najwyższym (do 135 000 PLN, do 100% kosztów).',
    kategoria: 'EKOLOGIA',
    kwota: 'do 53 000 PLN na budynek (100% kosztów)',
    kwotaMin: 0, kwotaMax: 53000,
    czestotliwosc: 'jednorazowo',
    wymagania: { wlasnosc: ['dom'], dochodMax: 2342 },
    wykluczenia: [
      { opis: 'PROGRAM ZAKOŃCZONY. Nabór wniosków zamknięty z końcem 2024 roku. Niewykorzystane środki (ok. 150 mln PLN) przeznaczone na termomodernizację budynków wielorodzinnych.', sprawdz: 'program_aktywny' },
      { opis: 'Dotyczy wyłącznie gmin objętych uchwałą antysmogową, które podpisały porozumienie z NFOŚiGW', sprawdz: 'gmina_stop_smog' },
      { opis: 'Mieszkaniec musi posiadać co najmniej połowę udziału we własności budynku', sprawdz: 'udzial_wlasnosci' },
    ],
    wniosek: {
      kanal: ['URZAD_GMINY'],
      dokumenty: [
        'Dowód osobisty',
        'Akt własności budynku jednorodzinnego',
        'Zaświadczenie o dochodach (dochód do 175% minimalnej emerytury na osobę dla jednoosobowych, lub 125% dla wieloosobowych)',
        'Oświadczenie o majątku nieprzekraczającym 53 000 PLN (z wyłączeniem wartości budynku)',
      ],
      kroki: [
        'UWAGA: Program zakończony z końcem 2024 roku. Poniższe kroki dotyczą archiwalnej procedury',
        'Sprawdź, czy gmina przystąpiła do programu Stop Smog i podpisała porozumienie z NFOŚiGW',
        'Złóż wniosek w urzędzie gminy z dokumentami dochodowymi i majątkowymi',
        'Gmina organizuje i finansuje termomodernizację, mieszkaniec nie ponosi kosztów',
        'Po realizacji: budynek musi utrzymać efekt ekologiczny przez 10 lat',
      ],
      terminRealizacji: 'Program zakończony, brak nowych naborów',
      pulapki: [
        'Program zamknięty z końcem 2024. Nowe wnioski nie są przyjmowane',
        'Progi dochodowe: do 2342 PLN netto/os. (jednoosobowe) lub do 1873 PLN netto/os. (wieloosobowe)',
        'Majątek wnioskodawcy nie mógł przekraczać 53 000 PLN (bez wartości budynku)',
        'Gmina finansowała 30% kosztów ze środków własnych, 70% z budżetu państwa',
        'Obowiązek utrzymania efektów termomodernizacji przez 10 lat po realizacji',
      ],
      odwolanie: 'Nie dotyczy (program zakończony)',
    },
    zrodloUrl: 'https://www.gov.pl/web/klimat/stop-smog-20--nowe-lepsze-zasady-od-31-marca',
    zrodloNazwa: 'Ministerstwo Klimatu i Środowiska, Program Stop Smog', dataWeryfikacji: '2026-07-06', dataWaznosci: '2026-12-31',
  },
  {
    id: 'dodatek-oslonowy', nazwa: 'Dodatek osłonowy',
    opis: 'PROGRAM ZAKOŃCZONY. Ostatnia edycja w 2024 roku. Dodatek osłonowy był jednorazowym świadczeniem pieniężnym wprowadzonym w odpowiedzi na kryzys energetyczny 2022-2023, mającym złagodzić wzrost cen energii i żywności. Kwoty w ostatniej edycji: 1 osoba 228,80 PLN, 2-3 osoby 343,20 PLN, 4-5 osób 486,20 PLN, 6+ osób 657,80 PLN. Przy ogrzewaniu węglem stawki podwyższone: 1 osoba 286 PLN, 2-3 osoby 429 PLN, 4-5 osób 607,75 PLN, 6+ osób 822,25 PLN. Progi dochodowe: 2500 PLN netto/os. (jednoosobowe), 1700 PLN/os. (wieloosobowe). Rząd nie przedłużył programu na 2025/2026. Osoby w trudnej sytuacji energetycznej mogą rozważyć: bon energetyczny, dodatek mieszkaniowy, zasiłek celowy na opał, lub program Czyste Powietrze (wymiana starego pieca na tańsze źródło ciepła).',
    kategoria: 'EKOLOGIA',
    kwota: '228,80-822,25 PLN (ostatnia edycja 2024)',
    kwotaMin: 228, kwotaMax: 822,
    czestotliwosc: 'jednorazowo (rocznie, ostatnia edycja 2024)',
    wymagania: { dochodMax: 2500 },
    wykluczenia: [
      { opis: 'PROGRAM ZAKOŃCZONY. Ostatnia edycja w 2024 roku, rząd nie przedłużył na 2025/2026', sprawdz: 'program_aktywny' },
      { opis: 'Program miał charakter przejściowy (odpowiedź na kryzys energetyczny 2022-2023)', sprawdz: 'status_programu' },
    ],
    wniosek: {
      kanal: ['MOPS', 'URZAD_GMINY'],
      dokumenty: [
        'Dowód osobisty',
        'Zaświadczenie o dochodach lub PIT',
        'Numer konta bankowego',
      ],
      kroki: [
        'UWAGA: Program zakończony. Ostatnie wnioski przyjmowano do 30.04.2024, wypłaty do 30.06.2024',
        'Złożenie wniosku w MOPS lub urzędzie gminy właściwym dla miejsca zamieszkania',
        'Kwoty zależały od liczby osób w gospodarstwie: 1 os. 228,80 PLN, 2-3 os. 343,20 PLN, 4-5 os. 486,20 PLN, 6+ os. 657,80 PLN',
        'Przy ogrzewaniu węglem stawki podwyższone: 1 os. 286 PLN, 2-3 os. 429 PLN, 4-5 os. 607,75 PLN, 6+ os. 822,25 PLN',
      ],
      terminRealizacji: 'Program zakończony, brak nowych naborów',
      pulapki: [
        'Program zakończony z końcem 2024, nowe wnioski nie są przyjmowane',
        'Progi dochodowe w ostatniej edycji: do 2500 PLN netto/os. (jednoosobowe) lub 1700 PLN/os. (wieloosobowe)',
        'Kwota minimalna wypłaty wynosiła 20 PLN. Poniżej tej kwoty świadczenie nie przysługiwało',
        'Dodatek nie podlegał opodatkowaniu, nie wykazywany w PIT',
      ],
      odwolanie: 'Nie dotyczy (program zakończony)',
    },
    zrodloUrl: 'https://www.gov.pl/web/klimat/dodatek-oslonowy',
    zrodloNazwa: 'Ministerstwo Klimatu i Środowiska (program zakończony)', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
];
