import { Benefit } from '../types';

export const INNE: Benefit[] = [
  {
    id: 'refundacja-okularow-nfz', nazwa: 'Refundacja okularów i soczewek z NFZ', kategoria: 'ZDROWIE',
    kwota: '50-700 PLN na okulary, do 600 PLN na soczewki kontaktowe',
    kwotaMin: 50, kwotaMax: 700,
    czestotliwosc: 'co 2 lata (dorośli), co rok (dzieci)',
    wymagania: {},
    wykluczenia: [],
    wniosek: {
      kanal: ['NFZ'],
      dokumenty: [
        'Zlecenie na zaopatrzenie w wyroby medyczne (wystawione przez okulistę lub optometrystę od 2026)',
        'Dowód osobisty lub legitymacja szkolna',
        'Karta ubezpieczenia zdrowotnego (opcjonalnie)',
      ],
      kroki: [
        'Umów wizytę u okulisty lub optometrysty (od 2026 optometrysta też może wystawić zlecenie)',
        'Specjalista wystawi e-zlecenie na zaopatrzenie w wyroby medyczne w systemie NFZ',
        'System NFZ automatycznie zweryfikuje zlecenie i nada numer identyfikacyjny',
        'Udaj się do salonu optycznego, który realizuje zlecenia NFZ',
        'Przy zakupie okaż e-zlecenie (numer), salon odliczy refundację od ceny',
      ],
      terminRealizacji: 'Zlecenie od ręki, realizacja w salonie natychmiast',
      pulapki: [
        'Wady do +-6,00 D: refundacja do 25 PLN za szkło (50 PLN za parę)',
        'Wady powyżej +-6,25 D: refundacja do 350 PLN za szkło (700 PLN za parę)',
        'Soczewki kontaktowe twarde/hybrydowe: do 600 PLN za sztukę (10% wkład własny)',
        'Refundacja dotyczy TYLKO soczewek korekcyjnych, oprawki, powłoki, filtry za własne pieniądze',
        'Dorośli: co 2 lata. Dzieci: co rok (lub częściej przy zmianach wady)',
        'Od 2026: zlecenie może wystawić nie tylko okulista, ale też optometrysta',
        'Pracownicy przy komputerze: DODATKOWE dofinansowanie od pracodawcy (śr. 450 PLN)',
      ],
      odwolanie: 'Reklamacja do oddziału NFZ',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/wyroby-medyczne/',
    zrodloNazwa: 'NFZ', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'karta-ekuz', nazwa: 'Europejska Karta Ubezpieczenia Zdrowotnego (EKUZ)', kategoria: 'ZDROWIE',
    kwota: 'bezpłatne leczenie w krajach UE/EFTA (na zasadach danego kraju)',
    kwotaMin: 0, kwotaMax: 0,
    czestotliwosc: 'ważna 3-20 lat (zależy od statusu ubezpieczenia)',
    wymagania: {},
    wykluczenia: [
      { opis: 'Brak ubezpieczenia zdrowotnego w Polsce (NFZ)', sprawdz: 'ubezpieczenie_nfz' },
    ],
    wniosek: {
      kanal: ['NFZ', 'ONLINE'], formularz: 'Wniosek o wydanie EKUZ',
      dokumenty: [
        'Dowód osobisty lub paszport',
        'Potwierdzenie ubezpieczenia zdrowotnego (ZUS weryfikuje automatycznie)',
      ],
      kroki: [
        'Złóż wniosek online przez Internetowe Konto Pacjenta (IKP) na pacjent.gov.pl lub w aplikacji mojeIKP',
        'Lub udaj się osobiście do oddziału/delegatury NFZ, karta wydawana od ręki',
        'Lub wyślij wniosek pocztą do NFZ',
        'Od 2026: wniosek o pobyt czasowy TYLKO elektronicznie przez IKP/mojeIKP',
        'Karta przyjdzie pocztą w ciągu 5-10 dni roboczych (online) lub od ręki (osobiście)',
      ],
      terminRealizacji: 'Osobiście: od ręki. Online: 5-10 dni roboczych',
      pulapki: [
        'BEZPŁATNA, nigdy nie płać za EKUZ',
        'Ważność zależy od statusu: pracujący 3 lata, emeryci 20 lat, dzieci do 18 r.ż., studenci 12 mies.',
        'Karta ważna RAZEM z dowodem osobistym, trzeba okazać oba',
        'Obejmuje NIEZBĘDNE leczenie w krajach UE/EFTA na zasadach TEGO kraju',
        'NIE zastępuje ubezpieczenia podróżnego, nie pokrywa transportu do Polski, planowanych zabiegów',
        'Od 2026: wniosek na pobyt czasowy TYLKO przez IKP (koniec papierowych wniosków)',
        'Działa w 30 krajach: UE + Islandia, Liechtenstein, Norwegia, Szwajcaria + UK',
      ],
      odwolanie: 'Reklamacja do oddziału NFZ',
    },
    zrodloUrl: 'https://pacjent.gov.pl/ekuz',
    zrodloNazwa: 'NFZ / Ministerstwo Zdrowia', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'ulga-na-leki', nazwa: 'Zwrot podatku za leki (ulga rehabilitacyjna na leki)', kategoria: 'PODATKI',
    kwota: 'odliczenie nadwyżki wydatków ponad 100 PLN/mies. od dochodu',
    kwotaMin: 0, kwotaMax: 0,
    czestotliwosc: 'rocznie (w rozliczeniu PIT)',
    wymagania: { niepelnosprawnosc: ['lekki', 'umiarkowany', 'znaczny'] },
    wykluczenia: [
      { opis: 'Tylko osoby z orzeczeniem o niepełnosprawności lub decyzją o rencie z niezdolności', sprawdz: 'orzeczenie_niepelnosprawnosc' },
    ],
    wniosek: {
      kanal: ['URZAD_SKARBOWY', 'ONLINE'], formularz: 'PIT-36 lub PIT-37 + PIT/O',
      dokumenty: [
        'Orzeczenie o niepełnosprawności (dowolny stopień) lub decyzja o rencie',
        'Faktury/rachunki/paragony za leki (z datą, kwotą, nazwą leku)',
        'Zaświadczenie lekarskie o konieczności stałego/długotrwałego stosowania leków',
        'PIT-36 lub PIT-37 + załącznik PIT/O',
      ],
      kroki: [
        'Zbieraj faktury/rachunki za leki przez cały rok (z wyraźnymi datami i kwotami)',
        'Uzyskaj zaświadczenie lekarskie potwierdzające stałe/długotrwałe stosowanie leków',
        'W każdym miesiącu policz wydatki na leki, odliczasz tylko nadwyżkę ponad 100 PLN',
        'Wypełnij PIT/O w ramach zeznania rocznego PIT-36 lub PIT-37',
        'Złóż zeznanie do 30 kwietnia za poprzedni rok',
      ],
      terminRealizacji: 'Zwrot podatku: 45 dni od złożenia PIT elektronicznie, 3 miesiące papierowo',
      pulapki: [
        'Odliczasz TYLKO nadwyżkę ponad 100 PLN w DANYM miesiącu, nie sumuj miesięcy',
        'Przykład: wydatki na leki w styczniu 250 PLN = odliczasz 150 PLN od dochodu',
        'Leki muszą być zalecone przez lekarza jako stałe/długotrwałe, nie tylko doraźne',
        'Odliczenie od DOCHODU, nie od podatku, realna korzyść to 12% lub 32% kwoty',
        'Może odliczyć osoba niepełnosprawna LUB podatnik utrzymujący osobę niepełnosprawną',
        'Leki nie muszą być związane z niepełnosprawnością, mogą być na dowolne schorzenie',
        'Zachowaj dokumenty 5 lat, US może zażądać ich do kontroli',
      ],
      odwolanie: 'Korekta zeznania PIT w ciągu 5 lat od terminu złożenia',
    },
    zrodloUrl: 'https://www.pit.pl/ulga-rehabilitacyjna/',
    zrodloNazwa: 'Ministerstwo Finansów', dataWeryfikacji: '2026-05-10', dataWaznosci: '2027-04-30',
  },
  {
    id: 'bon-turystyczny-regionalny', nazwa: 'Bon turystyczny (regionalny)', kategoria: 'POMOC_SPOLECZNA',
    kwota: 'do 500 PLN dopłaty do noclegu (zależnie od województwa)',
    kwotaMin: 0, kwotaMax: 500,
    czestotliwosc: 'jednorazowo (turami)',
    wymagania: {},
    wykluczenia: [
      { opis: 'Ogólnopolski bon turystyczny 800 PLN zakończył się 30.09.2022, obecnie tylko regionalne', sprawdz: 'bon_turystyczny_ogolnopolski' },
    ],
    wniosek: {
      kanal: ['ONLINE'],
      dokumenty: [
        'Dowód osobisty',
        'Potwierdzenie rezerwacji noclegu w danym regionie',
      ],
      kroki: [
        'Sprawdź, czy Twoje województwo uruchomiło bon turystyczny (2025-2026: Podlaskie, Warmińsko-Mazurskie)',
        'Zarejestruj się na platformie bonu danego województwa',
        'Zarezerwuj minimum 2 noclegi w wybranym obiekcie w regionie',
        'Wygeneruj bon online (pula ograniczona, bony rozchodzą się w minutach)',
        'Okaż bon przy zameldowaniu, dopłata do 500 PLN zostanie odliczona',
      ],
      terminRealizacji: 'Bon generowany natychmiastowo, pula ograniczona',
      pulapki: [
        'Ogólnopolski bon turystyczny (800 PLN na dziecko) ZAKOŃCZYŁ SIĘ 30.09.2022',
        'Obecnie działają TYLKO regionalne bony: Podlaski Bon Turystyczny, Bon Warmia Mazury 2026',
        'Pule bonów wyczerpują się w MINUTY, trzeba być gotowym w dniu startu',
        'Wymagane min. 2 noclegi w obiekcie na terenie danego województwa',
        'Dopłata do 500 PLN (zależy od programu regionalnego)',
        'Nie każde województwo ma taki program, sprawdź aktualne informacje',
        'Rząd rozważa nowy ogólnopolski bon, ale nie ma jeszcze decyzji',
      ],
      odwolanie: 'Nie dotyczy, program dobrowolny',
    },
    zrodloUrl: 'https://www.gov.pl/web/sport/bonturystyczny',
    zrodloNazwa: 'Ministerstwo Sportu', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
];
