import { Benefit } from '../types';

export const KRUS: Benefit[] = [
  {
    id: 'emerytura-rolnicza', nazwa: 'Emerytura rolnicza KRUS', kategoria: 'SENIOR',
    kwota: '1978,49-2243,60 PLN brutto (od marca 2026, zależnie od stażu)',
    kwotaMin: 1978, kwotaMax: 2243,
    czestotliwosc: 'miesięcznie',
    wymagania: { rolnik: true, emeryt: true },
    wykluczenia: [],
    wniosek: {
      kanal: ['KRUS'], formularz: 'KRUS SR-20',
      dokumenty: [
        'Dowód osobisty',
        'Dokumenty potwierdzające okresy ubezpieczenia w KRUS (min. 25 lat)',
        'Zaświadczenie o opłaceniu składek',
        'Akt własności lub dzierżawy gospodarstwa',
        'Numer konta bankowego',
      ],
      kroki: [
        'Upewnij się, że masz min. 25 lat ubezpieczenia w KRUS i osiągnąłeś wiek emerytalny (K: 60, M: 65)',
        'Wypełnij formularz KRUS SR-20 (wniosek o emeryturę rolniczą)',
        'Złóż wniosek w oddziale KRUS właściwym dla Twojego miejsca zamieszkania',
        'Dołącz dokumenty potwierdzające staż ubezpieczeniowy',
        'KRUS wyda decyzję w ciągu 30 dni',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'Wiek emerytalny: kobiety 60 lat, mężczyźni 65 lat',
        'Wymagany staż: minimum 25 lat ubezpieczenia emerytalno-rentowego w KRUS',
        'Emerytura podstawowa od marca 2026: 1780,64 PLN',
        'Najniższa emerytura od marca 2026: 1978,49 PLN brutto',
        'Po 25 latach ubezpieczenia: ok. 2101 PLN brutto, po 30 latach: ok. 2190 PLN',
        'Składa się z części składkowej (1% emerytury podstawowej za każdy rok) i uzupełniającej (do 95%)',
        'Waloryzacja co roku 1 marca, w 2026 wskaźnik 5,3%',
      ],
      odwolanie: 'Odwołanie do Sądu Okręgowego, Wydział Pracy i Ubezpieczeń Społecznych w ciągu 30 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/krus/waloryzacja-emerytur-i-rent-rolniczych-od-1-marca-2026-r',
    zrodloNazwa: 'KRUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2027-02-28',
  },
  {
    id: 'renta-rolnicza', nazwa: 'Renta rolnicza z tytułu niezdolności do pracy', kategoria: 'SENIOR',
    kwota: '1978,49 PLN brutto (od marca 2026, całkowita niezdolność)',
    kwotaMin: 1978, kwotaMax: 1978,
    czestotliwosc: 'miesięcznie',
    wymagania: { rolnik: true },
    wykluczenia: [
      { opis: 'Brak orzeczenia lekarza orzecznika KRUS o niezdolności do pracy w gospodarstwie', sprawdz: 'orzeczenie_krus' },
    ],
    wniosek: {
      kanal: ['KRUS'], formularz: 'KRUS SR-20',
      dokumenty: [
        'Dowód osobisty',
        'Dokumenty potwierdzające okresy ubezpieczenia w KRUS',
        'Dokumentacja medyczna potwierdzająca stan zdrowia',
        'Zaświadczenie lekarskie o stanie zdrowia (druk KRUS N-14)',
        'Numer konta bankowego',
      ],
      kroki: [
        'Zgłoś się do lekarza orzecznika KRUS z dokumentacją medyczną',
        'Lekarz orzecznik stwierdzi trwałą lub okresową całkowitą niezdolność do pracy w gospodarstwie',
        'Wypełnij wniosek KRUS SR-20 o rentę rolniczą',
        'Złóż wniosek w oddziale KRUS z kompletem dokumentów',
        'KRUS wyda decyzję w ciągu 30 dni',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'Wymagany staż ubezpieczeniowy zależy od wieku w momencie niezdolności',
        'Renta składa się z części składkowej (1% na rok) i uzupełniającej (do 95% emerytury podstawowej)',
        'Renta z tytułu częściowej niezdolności = 75% renty z tytułu całkowitej niezdolności',
        'Renta może być okresowa (na czas określony) lub stała',
        'Od marca 2026: renta minimalna wynosi 1978,49 PLN brutto',
        'Waloryzacja co roku 1 marca, wskaźnik 5,3% na 2026',
      ],
      odwolanie: 'Odwołanie do Sądu Okręgowego, Wydział Pracy i Ubezpieczeń Społecznych w ciągu 30 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/krus/waloryzacja-emerytur-i-rent-rolniczych-od-1-marca-2026-r',
    zrodloNazwa: 'KRUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2027-02-28',
  },
  {
    id: 'zasilek-macierzynski-krus', nazwa: 'Zasiłek macierzyński KRUS', kategoria: 'RODZINA',
    kwota: '1000 PLN miesięcznie', kwotaMin: 1000, kwotaMax: 1000,
    czestotliwosc: 'miesięcznie (przez 52-71 tygodni)',
    wymagania: { rolnik: true, ciaza: true },
    wykluczenia: [],
    wniosek: {
      kanal: ['KRUS'], formularz: 'SR-24A',
      dokumenty: [
        'Wniosek SR-24A',
        'Akt urodzenia dziecka lub zaświadczenie lekarskie',
        'Dokument potwierdzający przysposobienie lub przyjęcie dziecka na wychowanie (jeśli dotyczy)',
        'Dowód osobisty',
      ],
      kroki: [
        'Upewnij się, że jesteś objęty/a ubezpieczeniem emerytalno-rentowym w KRUS w chwili porodu',
        'Po urodzeniu dziecka wypełnij wniosek SR-24A',
        'Złóż wniosek w oddziale KRUS w ciągu 3 miesięcy od porodu lub przyjęcia dziecka',
        'Można złożyć elektronicznie przez ePUAP',
        'KRUS wyda decyzję i rozpocznie wypłaty',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'Kwota stała: 1000 PLN/mies., niezależna od dochodów czy wysokości składek',
        '52 tygodnie na 1 dziecko, do 71 tygodni przy porodach mnogich',
        'Od 2025: możliwość wydłużenia przy wcześniakach lub hospitalizacji dziecka',
        'Przysługuje matce, ojcu lub osobie, która przysposobiła/przyjęła dziecko na wychowanie',
        'MUSISZ być ubezpieczony w KRUS w chwili powstania prawa do zasiłku',
        'Wniosek w ciągu 3 miesięcy od porodu, po tym terminie tracisz miesiące wstecz',
      ],
      odwolanie: 'Odwołanie do Sądu Rejonowego, Wydział Pracy w ciągu 30 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/krus/zasilek-macierzynski',
    zrodloNazwa: 'KRUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'zasilek-chorobowy-krus', nazwa: 'Zasiłek chorobowy KRUS', kategoria: 'ZDROWIE',
    kwota: '25 PLN dziennie', kwotaMin: 25, kwotaMax: 25,
    czestotliwosc: 'dziennie (od 31. dnia choroby, max 180 dni + 360 dni przedłużenia)',
    wymagania: { rolnik: true },
    wykluczenia: [
      { opis: 'Nieprzerwane ubezpieczenie wypadkowe/chorobowe/macierzyńskie w KRUS przez min. 1 rok', sprawdz: 'staz_krus_1rok' },
    ],
    wniosek: {
      kanal: ['KRUS'],
      dokumenty: [
        'Zaświadczenie lekarskie o niezdolności do pracy (ZUS ZLA lub e-ZLA)',
        'Dowód osobisty',
        'Potwierdzenie opłacenia składek KRUS',
      ],
      kroki: [
        'Uzyskaj zaświadczenie lekarskie o niezdolności do pracy (e-ZLA)',
        'Lekarz wysyła e-ZLA elektronicznie do KRUS',
        'Zasiłek przysługuje od 31. dnia niezdolności do pracy',
        'KRUS wypłaca zasiłek automatycznie po upływie 30 dni choroby',
        'Jeśli choroba trwa dłużej niż 180 dni, możesz wnioskować o przedłużenie o 360 dni',
      ],
      terminRealizacji: 'Wypłata po upływie okresu wyczekiwania (30 dni)',
      pulapki: [
        '25 PLN/dzień od 2025 roku (wzrost o 5 PLN z 20 PLN)',
        'Zasiłek przysługuje dopiero od 31. dnia choroby, pierwsze 30 dni bez zasiłku',
        'Maksymalnie 180 dni, z możliwością przedłużenia o kolejne 360 dni (jeśli rokuje wyzdrowienie)',
        'Wymagany 1 rok ciągłego ubezpieczenia w KRUS (wyjątek: wypadek przy pracy rolniczej)',
        'Przy wypadku przy pracy rolniczej, zasiłek od 1. dnia bez okresu wyczekiwania',
        'Przysługuje też domownikom ubezpieczonym w KRUS',
      ],
      odwolanie: 'Odwołanie do Sądu Rejonowego, Wydział Pracy w ciągu 30 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/krus/zasilek-chorobowy',
    zrodloNazwa: 'KRUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'odszkodowanie-krus', nazwa: 'Jednorazowe odszkodowanie KRUS (wypadek przy pracy rolniczej)', kategoria: 'ZDROWIE',
    kwota: '1431 PLN za 1% uszczerbku na zdrowiu (max 143 100 PLN przy śmierci)',
    kwotaMin: 1431, kwotaMax: 143100,
    czestotliwosc: 'jednorazowo',
    wymagania: { rolnik: true },
    wykluczenia: [
      { opis: 'Wypadek musi być uznany za wypadek przy pracy rolniczej przez KRUS', sprawdz: 'wypadek_rolniczy' },
    ],
    wniosek: {
      kanal: ['KRUS'],
      dokumenty: [
        'Zgłoszenie wypadku przy pracy rolniczej (w ciągu 6 miesięcy od wypadku)',
        'Dokumentacja medyczna',
        'Protokół powypadkowy sporządzony przez KRUS',
        'Orzeczenie lekarza orzecznika KRUS o procentowym uszczerbku na zdrowiu',
        'Dowód osobisty',
      ],
      kroki: [
        'Zgłoś wypadek do KRUS jak najszybciej (max 6 miesięcy od zdarzenia)',
        'KRUS przeprowadzi dochodzenie i sporządzi protokół powypadkowy',
        'Lekarz orzecznik KRUS zbada Cię i oceni procentowy uszczerbek na zdrowiu',
        'KRUS wyda decyzję o przyznaniu odszkodowania',
        'Wypłata jednorazowa na konto',
      ],
      terminRealizacji: 'Decyzja w ciągu 30 dni od zakończenia leczenia i orzeczenia',
      pulapki: [
        '1431 PLN za każdy 1% uszczerbku na zdrowiu (od 2025)',
        '28 620 PLN dodatkowo przy niezdolności do samodzielnej egzystencji',
        '143 100 PLN z tytułu śmiertelnego wypadku (dla małżonka/dzieci)',
        '71 550 PLN z tytułu śmierci (dla innych członków rodziny)',
        'Wypadek przy pracy rolniczej = nagłe zdarzenie wywołane przyczyną zewnętrzną podczas pracy w gospodarstwie',
        'ZGŁOŚ wypadek do 6 miesięcy, po tym terminie roszczenie wygasa',
        'Obejmuje też drogę do/z pracy rolniczej',
      ],
      odwolanie: 'Odwołanie do Sądu Rejonowego, Wydział Pracy w ciągu 30 dni od decyzji',
    },
    zrodloUrl: 'https://www.gov.pl/web/krus/jednorazowe-odszkodowanie-za-wypadek-przy-pracy-rolniczej',
    zrodloNazwa: 'KRUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
];
