import { Benefit } from '../types';

export const KRUS: Benefit[] = [
  {
    id: 'emerytura-rolnicza', nazwa: 'Emerytura rolnicza KRUS',
    opis: 'Emerytura rolnicza z KRUS dla rolników z minimum 25 latami ubezpieczenia emerytalno-rentowego. Wiek emerytalny: kobiety 60, mężczyźni 65. Składa się z części składkowej (1% emerytury podstawowej za każdy rok) i uzupełniającej (do 95%). Kwota od marca 2026: min. 1978,49 PLN brutto, po 25 latach ok. 2101 PLN, po 30 latach ok. 2190 PLN. Emerytura podstawowa: 1780,64 PLN. Waloryzacja co roku 1 marca (2026: 5,3%). Wniosek w oddziale KRUS formularzem SR-20.',
    kategoria: 'SENIOR',
    kwota: '1978,49-2243,60 PLN brutto (od marca 2026, zależnie od stażu)',
    kwotaMin: 1978, kwotaMax: 2243,
    czestotliwosc: 'miesięcznie',
    wymagania: { rolnik: true, emeryt: true },
    wykluczenia: [],
    wniosek: {
      kanal: ['KRUS'], formularz: 'KRUS SR-20',
      dokumenty: [
        'Dowód osobisty',
        'Dokumenty potwierdzające okresy ubezpieczenia w KRUS (min. 25 lat)',
        'Zaświadczenie o opłaceniu składek',
        'Akt własności lub dzierżawy gospodarstwa',
        'Numer konta bankowego',
      ],
      kroki: [
        'Upewnij się, że masz min. 25 lat ubezpieczenia w KRUS i osiągnąłeś wiek emerytalny (K: 60, M: 65)',
        'Wypełnij formularz KRUS SR-20 (wniosek o emeryturę rolniczą)',
        'Złóż wniosek w oddziale KRUS właściwym dla Twojego miejsca zamieszkania',
        'Dołącz dokumenty potwierdzające staż ubezpieczeniowy',
        'KRUS wyda decyzję w ciągu 30 dni',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'Wiek emerytalny: kobiety 60 lat, mężczyźni 65 lat',
        'Wymagany staż: minimum 25 lat ubezpieczenia emerytalno-rentowego w KRUS',
        'Emerytura podstawowa od marca 2026: 1780,64 PLN',
        'Najniższa emerytura od marca 2026: 1978,49 PLN brutto',
        'Po 25 latach ubezpieczenia: ok. 2101 PLN brutto, po 30 latach: ok. 2190 PLN',
        'Składa się z części składkowej (1% emerytury podstawowej za każdy rok) i uzupełniającej (do 95%)',
        'Waloryzacja co roku 1 marca, w 2026 wskaźnik 5,3%',
      ],
      odwolanie: 'Odwołanie do Sądu Okręgowego, Wydział Pracy i Ubezpieczeń Społecznych w ciągu 30 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/krus/waloryzacja-emerytur-i-rent-rolniczych-od-1-marca-2026-r',
    zrodloNazwa: 'KRUS', dataWeryfikacji: '2026-05-23', dataWaznosci: '2027-02-28',
  },
  {
    id: 'renta-rolnicza', nazwa: 'Renta rolnicza z tytułu niezdolności do pracy',
    opis: 'Renta rolnicza z KRUS dla rolników niezdolnych do pracy w gospodarstwie, orzeczona przez lekarza orzecznika KRUS. Wymagany staż ubezpieczeniowy zależy od wieku. Składa się z części składkowej i uzupełniającej. Renta minimalna od marca 2026: 1978,49 PLN brutto. Renta z tytułu częściowej niezdolności = 75% renty całkowitej. Może być okresowa lub stała. Waloryzacja 1 marca. Wniosek w oddziale KRUS.',
    kategoria: 'SENIOR',
    kwota: '1978,49 PLN brutto (od marca 2026, całkowita niezdolność)',
    kwotaMin: 1978, kwotaMax: 1978,
    czestotliwosc: 'miesięcznie',
    wymagania: { rolnik: true },
    wykluczenia: [
      { opis: 'Brak orzeczenia lekarza orzecznika KRUS o niezdolności do pracy w gospodarstwie', sprawdz: 'orzeczenie_krus' },
    ],
    wniosek: {
      kanal: ['KRUS'], formularz: 'KRUS SR-20',
      dokumenty: [
        'Dowód osobisty',
        'Dokumenty potwierdzające okresy ubezpieczenia w KRUS',
        'Dokumentacja medyczna potwierdzająca stan zdrowia',
        'Zaświadczenie lekarskie o stanie zdrowia (druk KRUS N-14)',
        'Numer konta bankowego',
      ],
      kroki: [
        'Zgłoś się do lekarza orzecznika KRUS z dokumentacją medyczną',
        'Lekarz orzecznik stwierdzi trwałą lub okresową całkowitą niezdolność do pracy w gospodarstwie',
        'Wypełnij wniosek KRUS SR-20 o rentę rolniczą',
        'Złóż wniosek w oddziale KRUS z kompletem dokumentów',
        'KRUS wyda decyzję w ciągu 30 dni',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'Wymagany staż ubezpieczeniowy zależy od wieku w momencie niezdolności',
        'Renta składa się z części składkowej (1% na rok) i uzupełniającej (do 95% emerytury podstawowej)',
        'Renta z tytułu częściowej niezdolności = 75% renty z tytułu całkowitej niezdolności',
        'Renta może być okresowa (na czas określony) lub stała',
        'Od marca 2026: renta minimalna wynosi 1978,49 PLN brutto',
        'Waloryzacja co roku 1 marca, wskaźnik 5,3% na 2026',
      ],
      odwolanie: 'Odwołanie do Sądu Okręgowego, Wydział Pracy i Ubezpieczeń Społecznych w ciągu 30 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/krus/waloryzacja-emerytur-i-rent-rolniczych-od-1-marca-2026-r',
    zrodloNazwa: 'KRUS', dataWeryfikacji: '2026-05-23', dataWaznosci: '2027-02-28',
  },
  {
    id: 'zasilek-macierzynski-krus', nazwa: 'Zasiłek macierzyński KRUS',
    opis: 'Zasiłek macierzyński KRUS: 1000 PLN/mies. przez 52 tygodnie (1 dziecko) do 71 tygodni (porody mnogie). Kwota stała, niezależna od dochodów. Przysługuje matce, ojcu lub osobie przysposobiającej dziecko. Warunek: ubezpieczenie w KRUS w chwili porodu. Wniosek SR-24A w ciągu 3 mies. od porodu (po terminie tracisz miesiące wstecz). Można złożyć elektronicznie przez ePUAP. Od 2025 możliwość wydłużenia przy wcześniakach.',
    kategoria: 'RODZINA',
    kwota: '1000 PLN miesięcznie', kwotaMin: 1000, kwotaMax: 1000,
    czestotliwosc: 'miesięcznie (przez 52-71 tygodni)',
    wymagania: { rolnik: true, ciaza: true },
    wykluczenia: [],
    wniosek: {
      kanal: ['KRUS'], formularz: 'SR-24A',
      dokumenty: [
        'Wniosek SR-24A',
        'Akt urodzenia dziecka lub zaświadczenie lekarskie',
        'Dokument potwierdzający przysposobienie lub przyjęcie dziecka na wychowanie (jeśli dotyczy)',
        'Dowód osobisty',
      ],
      kroki: [
        'Upewnij się, że jesteś objęty/a ubezpieczeniem emerytalno-rentowym w KRUS w chwili porodu',
        'Po urodzeniu dziecka wypełnij wniosek SR-24A',
        'Złóż wniosek w oddziale KRUS w ciągu 3 miesięcy od porodu lub przyjęcia dziecka',
        'Można złożyć elektronicznie przez ePUAP',
        'KRUS wyda decyzję i rozpocznie wypłaty',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'Kwota stała: 1000 PLN/mies., niezależna od dochodów czy wysokości składek',
        '52 tygodnie na 1 dziecko, do 71 tygodni przy porodach mnogich',
        'Od 2025: możliwość wydłużenia przy wcześniakach lub hospitalizacji dziecka',
        'Przysługuje matce, ojcu lub osobie, która przysposobiła/przyjęła dziecko na wychowanie',
        'MUSISZ być ubezpieczony w KRUS w chwili powstania prawa do zasiłku',
        'Wniosek w ciągu 3 miesięcy od porodu, po tym terminie tracisz miesiące wstecz',
      ],
      odwolanie: 'Odwołanie do Sądu Rejonowego, Wydział Pracy w ciągu 30 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/krus/zasilek-macierzynski',
    zrodloNazwa: 'KRUS', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'zasilek-chorobowy-krus', nazwa: 'Zasiłek chorobowy KRUS',
    opis: 'Zasiłek chorobowy KRUS: 25 PLN/dzień (od 2025), ale dopiero od 31. dnia niezdolności do pracy (pierwsze 30 dni bez zasiłku). Max 180 dni z możliwością przedłużenia o 360 dni jeśli rokuje wyzdrowienie. Wymagany 1 rok ciągłego ubezpieczenia (wyjątek: wypadek przy pracy rolniczej, wtedy od 1. dnia bez karencji). Przysługuje też domownikom ubezpieczonym w KRUS. Lekarz wysyła e-ZLA elektronicznie do KRUS.',
    kategoria: 'ZDROWIE',
    kwota: '25 PLN dziennie', kwotaMin: 25, kwotaMax: 25,
    czestotliwosc: 'dziennie (od 31. dnia choroby, max 180 dni + 360 dni przedłużenia)',
    wymagania: { rolnik: true },
    wykluczenia: [
      { opis: 'Nieprzerwane ubezpieczenie wypadkowe/chorobowe/macierzyńskie w KRUS przez min. 1 rok', sprawdz: 'staz_krus_1rok' },
    ],
    wniosek: {
      kanal: ['KRUS'],
      dokumenty: [
        'Zaświadczenie lekarskie o niezdolności do pracy (ZUS ZLA lub e-ZLA)',
        'Dowód osobisty',
        'Potwierdzenie opłacenia składek KRUS',
      ],
      kroki: [
        'Uzyskaj zaświadczenie lekarskie o niezdolności do pracy (e-ZLA)',
        'Lekarz wysyła e-ZLA elektronicznie do KRUS',
        'Zasiłek przysługuje od 31. dnia niezdolności do pracy',
        'KRUS wypłaca zasiłek automatycznie po upływie 30 dni choroby',
        'Jeśli choroba trwa dłużej niż 180 dni, możesz wnioskować o przedłużenie o 360 dni',
      ],
      terminRealizacji: 'Wypłata po upływie okresu wyczekiwania (30 dni)',
      pulapki: [
        '25 PLN/dzień od 2025 roku (wzrost o 5 PLN z 20 PLN)',
        'Zasiłek przysługuje dopiero od 31. dnia choroby, pierwsze 30 dni bez zasiłku',
        'Maksymalnie 180 dni, z możliwością przedłużenia o kolejne 360 dni (jeśli rokuje wyzdrowienie)',
        'Wymagany 1 rok ciągłego ubezpieczenia w KRUS (wyjątek: wypadek przy pracy rolniczej)',
        'Przy wypadku przy pracy rolniczej, zasiłek od 1. dnia bez okresu wyczekiwania',
        'Przysługuje też domownikom ubezpieczonym w KRUS',
      ],
      odwolanie: 'Odwołanie do Sądu Rejonowego, Wydział Pracy w ciągu 30 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/krus/zasilek-chorobowy',
    zrodloNazwa: 'KRUS', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'odszkodowanie-krus', nazwa: 'Jednorazowe odszkodowanie KRUS (wypadek przy pracy rolniczej)',
    opis: 'Jednorazowe odszkodowanie za wypadek przy pracy rolniczej: 1431 PLN za każdy 1% uszczerbku na zdrowiu. Dodatkowe 28 620 PLN przy niezdolności do samodzielnej egzystencji. Przy śmierci: 143 100 PLN dla małżonka/dzieci, 71 550 PLN dla innych członków rodziny. Wypadek musi być zgłoszony do KRUS w ciągu 6 miesięcy. KRUS sporządzi protokół, lekarz orzecznik oceni uszczerbek. Obejmuje też drogę do/z pracy rolniczej. Nagłe zdarzenie wywołane przyczyną zewnętrzną podczas pracy w gospodarstwie.',
    kategoria: 'ZDROWIE',
    kwota: '1431 PLN za 1% uszczerbku na zdrowiu (max 143 100 PLN przy śmierci)',
    kwotaMin: 1431, kwotaMax: 143100,
    czestotliwosc: 'jednorazowo',
    wymagania: { rolnik: true },
    wykluczenia: [
      { opis: 'Wypadek musi być uznany za wypadek przy pracy rolniczej przez KRUS', sprawdz: 'wypadek_rolniczy' },
    ],
    wniosek: {
      kanal: ['KRUS'],
      dokumenty: [
        'Zgłoszenie wypadku przy pracy rolniczej (w ciągu 6 miesięcy od wypadku)',
        'Dokumentacja medyczna',
        'Protokół powypadkowy sporządzony przez KRUS',
        'Orzeczenie lekarza orzecznika KRUS o procentowym uszczerbku na zdrowiu',
        'Dowód osobisty',
      ],
      kroki: [
        'Zgłoś wypadek do KRUS jak najszybciej (max 6 miesięcy od zdarzenia)',
        'KRUS przeprowadzi dochodzenie i sporządzi protokół powypadkowy',
        'Lekarz orzecznik KRUS zbada Cię i oceni procentowy uszczerbek na zdrowiu',
        'KRUS wyda decyzję o przyznaniu odszkodowania',
        'Wypłata jednorazowa na konto',
      ],
      terminRealizacji: 'Decyzja w ciągu 30 dni od zakończenia leczenia i orzeczenia',
      pulapki: [
        '1431 PLN za każdy 1% uszczerbku na zdrowiu (od 2025)',
        '28 620 PLN dodatkowo przy niezdolności do samodzielnej egzystencji',
        '143 100 PLN z tytułu śmiertelnego wypadku (dla małżonka/dzieci)',
        '71 550 PLN z tytułu śmierci (dla innych członków rodziny)',
        'Wypadek przy pracy rolniczej = nagłe zdarzenie wywołane przyczyną zewnętrzną podczas pracy w gospodarstwie',
        'ZGŁOŚ wypadek do 6 miesięcy, po tym terminie roszczenie wygasa',
        'Obejmuje też drogę do/z pracy rolniczej',
      ],
      odwolanie: 'Odwołanie do Sądu Rejonowego, Wydział Pracy w ciągu 30 dni od decyzji',
    },
    zrodloUrl: 'https://www.gov.pl/web/krus/jednorazowe-odszkodowanie-za-wypadek-przy-pracy-rolniczej',
    zrodloNazwa: 'KRUS', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'zasilek-opiekunczy-krus', nazwa: 'Zasiłek opiekuńczy KRUS',
    opis: 'Zasiłek opiekuńczy z KRUS przysługuje rolnikowi lub domownikowi ubezpieczonemu w KRUS, który musi osobiście sprawować opiekę nad dzieckiem do 14 lat (lub starszym niepełnosprawnym) z powodu choroby, zamknięcia żłobka/szkoły lub porodu małżonki. Stawka: 1/30 emerytury podstawowej za każdy dzień opieki (od marca 2026: 1780,64 PLN / 30 = 59,35 PLN/dzień). Maksymalny okres: 60 dni w roku na dziecko do 14 lat, 14 dni na dorosłego członka rodziny. Warunek: minimum 1 rok ciągłego ubezpieczenia wypadkowego, chorobowego i macierzyńskiego w KRUS. Przy wypadku lub nagłej chorobie karencja nie obowiązuje. Wniosek KRUS SR-24 złożyć do 7 dni od powstania prawa do zasiłku.',
    kategoria: 'ZDROWIE',
    kwota: '59,35 PLN dziennie (1/30 emerytury podstawowej od marca 2026)', kwotaMin: 59, kwotaMax: 59,
    czestotliwosc: 'dziennie (max 60 dni/rok na dziecko do 14 lat, 14 dni na dorosłego)',
    wymagania: { rolnik: true },
    wykluczenia: [
      { opis: 'Wymagane min. 1 rok ciągłego ubezpieczenia KRUS (wyjątek: wypadek lub nagła choroba)', sprawdz: 'staz_krus_1rok' },
    ],
    wniosek: {
      kanal: ['KRUS'], formularz: 'KRUS SR-24',
      dokumenty: [
        'Wniosek o zasiłek opiekuńczy (formularz KRUS SR-24)',
        'Zaświadczenie lekarskie o chorobie dziecka lub podopiecznego',
        'Zaświadczenie o zamknięciu żłobka/szkoły/przedszkola (jeśli dotyczy)',
        'Akt urodzenia dziecka',
        'Dowód osobisty',
      ],
      kroki: [
        'Złóż wniosek do KRUS w ciągu 7 dni od dnia powstania prawa do zasiłku',
        'Dołącz zaświadczenie lekarskie potwierdzające konieczność sprawowania opieki',
        'KRUS obliczy zasiłek: 1/30 emerytury podstawowej (59,35 PLN/dzień od marca 2026) za każdy dzień opieki',
        'Decyzja i wypłata w ciągu 30 dni',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        '59,35 PLN/dzień (1/30 z 1780,64 PLN emerytury podstawowej od marca 2026)',
        'Max 60 dni/rok na dzieci do 14 lat, 14 dni na dorosłego chorego członka rodziny',
        'Wniosek MUSISZ złożyć do 7 dni od daty opieki, inaczej tracisz część zasiłku',
        'Wymagany 1 rok ciągłego ubezpieczenia KRUS (przy wypadku brak karencji)',
        'Zasiłek przysługuje tylko jednemu rodzicowi za ten sam dzień',
        'Domownicy ubezpieczeni w KRUS mają takie same prawa jak rolnicy',
      ],
      odwolanie: 'Odwołanie do Sądu Rejonowego, Wydział Pracy i Ubezpieczeń Społecznych w ciągu 30 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/krus/zasilki-z-tytulu-urodzenia-i-opieki-nad-dzieckiem',
    zrodloNazwa: 'KRUS', dataWeryfikacji: '2026-07-06', dataWaznosci: '2026-12-31',
  },
  {
    id: 'dodatek-pielegnacyjny-krus', nazwa: 'Dodatek pielęgnacyjny KRUS',
    opis: 'Dodatek pielęgnacyjny z KRUS przysługuje emerytom i rencistom rolniczym, którzy: (a) ukończyli 75 lat - przyznawany automatycznie z mocy prawa, lub (b) zostali uznani przez lekarza orzecznika KRUS za całkowicie niezdolnych do pracy i samodzielnej egzystencji. Kwota od marca 2026: 366,68 PLN brutto miesięcznie (waloryzacja 5,3%). Waloryzacja co roku 1 marca. Przyznawany automatycznie osobom 75+ pobierającym emeryturę lub rentę KRUS - nie trzeba składać wniosku. Nie można łączyć z zasiłkiem pielęgnacyjnym z urzędu gminy (wyższy jest korzystniejszy: 366,68 PLN vs. 215,84 PLN). Nie podlega opodatkowaniu PIT.',
    kategoria: 'SENIOR',
    kwota: '366,68 PLN miesięcznie (od marca 2026)', kwotaMin: 367, kwotaMax: 367,
    czestotliwosc: 'miesięcznie',
    wymagania: { rolnik: true, emeryt: true, wiekMin: 75 },
    wykluczenia: [
      { opis: 'Nie łączy się z zasiłkiem pielęgnacyjnym z gminy (trzeba wybrać jedno)', sprawdz: 'zasilek_pielegnacyjny_gmina' },
    ],
    wniosek: {
      kanal: ['KRUS'],
      dokumenty: [
        'Brak potrzeby składania wniosku dla osób 75+ pobierających emeryturę/rentę KRUS',
        'Dokumentacja medyczna (jeśli wniosek dotyczy niezdolności do samodzielnej egzystencji poniżej 75 r.ż.)',
      ],
      kroki: [
        'Dla osób 75+: dodatek przyznawany automatycznie z mocy prawa, nie trzeba nic robić',
        'Jeśli masz poniżej 75 lat i jesteś niezdolny do samodzielnej egzystencji: złóż wniosek w oddziale KRUS',
        'Lekarz orzecznik KRUS oceni stan zdrowia i wyda orzeczenie',
        'KRUS przyzna dodatek i wypłaci go razem z emeryturą/rentą',
      ],
      terminRealizacji: '30 dni od złożenia wniosku (lub automatycznie z chwilą ukończenia 75 lat)',
      pulapki: [
        'Od marca 2026: 366,68 PLN/mies. (wyższy niż zasiłek pielęgnacyjny z gminy: 215,84 PLN)',
        'Dla osób 75+ przyznawany AUTOMATYCZNIE, nie trzeba wniosku',
        'NIE łączy się z zasiłkiem pielęgnacyjnym z urzędu gminy, wybierz korzystniejszy (KRUS jest wyższy)',
        'Waloryzacja co roku 1 marca (wskaźnik 5,3% w 2026)',
        'Przysługuje też poniżej 75 lat jeśli lekarz KRUS stwierdzi niezdolność do samodzielnej egzystencji',
      ],
      odwolanie: 'Odwołanie do Sądu Okręgowego, Wydział Pracy i Ubezpieczeń Społecznych',
    },
    zrodloUrl: 'https://www.agrofakt.pl/dodatek-pielegnacyjny-krus-2026-nowa-kwota-po-waloryzacji-zasady-i-wniosek-krok-po-kroku/',
    zrodloNazwa: 'KRUS', dataWeryfikacji: '2026-05-23', dataWaznosci: '2027-02-28',
  },
  {
    id: 'zwrot-akcyzy-paliwa-rolniczego', nazwa: 'Zwrot podatku akcyzowego od paliwa rolniczego',
    opis: 'Zwrot akcyzy za olej napędowy używany do produkcji rolnej. Stawka 2026: 1,48 PLN za litr. Limit zwrotu: 162,80 PLN/ha użytków rolnych rocznie + 5,92 PLN na sztukę świń (średniorocznie) + 59,20 PLN na dużą jednostkę przeliczeniową (DJP) bydła, owiec, kóz i koni. Dwa nabory rocznie: 1 lutego - 2 marca 2026 (wypłata kwiecień) oraz 1 sierpnia - 31 sierpnia 2026 (wypłata październik). Wniosek składa się w urzędzie gminy właściwym dla miejsca zamieszkania. Wymagane faktury VAT dokumentujące zakup oleju napędowego. Przykład: rolnik z 50 ha dostanie max 8140 PLN zwrotu rocznie za paliwo.',
    kategoria: 'PRACA',
    kwota: '1,48 PLN/litr ONW, limit 162,80 PLN/ha rocznie (+ bonus za zwierzęta)', kwotaMin: 0, kwotaMax: 0,
    czestotliwosc: 'dwa razy w roku (kwiecień i październik)',
    wymagania: { rolnik: true },
    wykluczenia: [],
    wniosek: {
      kanal: ['URZAD_GMINY'],
      dokumenty: [
        'Wniosek o zwrot podatku akcyzowego (druk dostępny w urzędzie gminy)',
        'Oryginalne faktury VAT za zakup oleju napędowego (z okresu od 1 sierpnia do 31 stycznia lub od 1 lutego do 31 lipca)',
        'Zaświadczenie z ARiMR o średniej rocznej liczbie zwierząt (dla produkcji zwierzęcej)',
        'Oświadczenie o posiadanej powierzchni użytków rolnych (z ewidencji gruntów)',
      ],
      kroki: [
        'Zbieraj faktury VAT za zakup oleju napędowego (ON) przez cały rok',
        'W terminie naboru (1 lutego - 2 marca lub 1 sierpnia - 31 sierpnia) złóż wniosek w urzędzie gminy',
        'Dołącz oryginalne faktury VAT za paliwo',
        'Przy produkcji zwierzęcej: dołącz zaświadczenie z ARiMR o liczbie zwierząt (możesz wygenerować samodzielnie z IRZplus)',
        'Urząd gminy wyda decyzję, wypłata do 30 kwietnia (1. nabór) lub do 31 października (2. nabór)',
      ],
      terminRealizacji: 'Wypłata do 30 kwietnia (1. nabór) lub do 31 października (2. nabór)',
      pulapki: [
        'Stawka 2026: 1,48 PLN/litr (wzrost z poprzednich lat)',
        'Limit roczny: 162,80 PLN/ha + 5,92 PLN/świnia + 59,20 PLN/DJP bydła',
        'ZBIERAJ faktury VAT przez cały rok, bez nich nie dostaniesz zwrotu',
        'Dwa nabory rocznie: luty-marzec i sierpień, nie przegap terminów',
        'Przy produkcji zwierzęcej zaświadczenie z ARiMR możesz wygenerować sam z IRZplus',
        'Wniosek składasz w URZĘDZIE GMINY, nie w ARiMR ani w urzędzie skarbowym',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni od decyzji',
    },
    zrodloUrl: 'https://www.gov.pl/web/rolnictwo/zwrot-podatku-akcyzowego',
    zrodloNazwa: 'Ministerstwo Rolnictwa', dataWeryfikacji: '2026-07-06', dataWaznosci: '2026-12-31',
  },
  {
    id: 'premia-dla-mlodego-rolnika', nazwa: 'Premia dla młodego rolnika (ARiMR)',
    opis: 'Premia dla młodego rolnika to dotacja ARiMR w ramach Planu Strategicznego WPR 2023-2027. Kwota: 200 000 PLN dla upraw roślinnych lub 300 000 PLN przy produkcji zwierzęcej (nowość od 2026). Wypłacana w 2 transzach: 70% (140 000 PLN) po podpisaniu umowy, 30% (60 000 PLN) po realizacji biznesplanu. Warunki: wiek 18-40 lat (nieukończone 41 lat), prowadzenie działalności rolniczej nie wcześniej niż 24 miesiące przed wnioskiem, kwalifikacje rolnicze lub zobowiązanie do uzupełnienia w 36 mies. Zobowiązanie: min. 60% przychodów z rolnictwa przez 5 lat. Nabór 2026: czerwiec - lipiec (może być ostatni w tej perspektywie finansowej). Powierzchnia gospodarstwa: min. 1 ha, max 300 ha, wartość ekonomiczna min. 15 000 EUR.',
    kategoria: 'PRACA',
    kwota: '200 000 PLN (uprawy) lub 300 000 PLN (z produkcją zwierzęcą)', kwotaMin: 200000, kwotaMax: 300000,
    czestotliwosc: 'jednorazowo (w 2 transzach)',
    wymagania: { rolnik: true, wiekMin: 18, wiekMax: 40 },
    wykluczenia: [
      { opis: 'Przekroczony wiek 40 lat w dniu złożenia wniosku', sprawdz: 'wiek_max_40' },
      { opis: 'Prowadzenie działalności rolniczej wcześniej niż 24 miesiące przed wnioskiem', sprawdz: 'data_dzialalnosci' },
    ],
    wniosek: {
      kanal: ['ARiMR', 'ONLINE'], formularz: 'eWniosekPlus (ARiMR)',
      dokumenty: [
        'Dowód osobisty lub paszport',
        'Dokumenty potwierdzające posiadanie lub dzierżawę gruntów rolnych',
        'Biznesplan na 5 lat (formularz ARiMR)',
        'Dokumenty potwierdzające kwalifikacje rolnicze lub zobowiązanie do ich uzupełnienia',
        'Oświadczenie o prowadzeniu działalności rolniczej',
        'Numer konta bankowego',
      ],
      kroki: [
        'Zarejestruj się w systemie eWniosekPlus (agencja.arimr.gov.pl)',
        'Wypełnij wniosek w terminie naboru (czerwiec - lipiec 2026)',
        'Przygotuj biznesplan na 5 lat z planem inwestycji i przychodów',
        'Złóż wniosek elektronicznie z kompletem dokumentów',
        'ARiMR oceni wniosek i przyśle decyzję (punktacja: wiek, wykształcenie, kierunek produkcji)',
        'Po podpisaniu umowy: I transza 70% (140 000 PLN lub 210 000 PLN)',
        'Po realizacji biznesplanu: II transza 30%',
      ],
      terminRealizacji: 'Kilka miesięcy od zamknięcia naboru, wypłata I transzy po podpisaniu umowy',
      pulapki: [
        'WIEK: nieukończone 41 lat w dniu złożenia wniosku (nie data urodzin, a dzień złożenia)',
        '300 000 PLN: TYLKO przy produkcji zwierzęcej (nowość w naborze 2026)',
        'Nabór 2026 (czerwiec-lipiec) może być OSTATNIM w tej perspektywie finansowej, nie przegap',
        'Biznesplan musi być realistyczny, ARiMR weryfikuje wykonalność',
        'Zobowiązanie: 60% przychodów z rolnictwa przez min. 5 lat od podpisania umowy',
        'Kwalifikacje rolnicze: wykształcenie rolnicze LUB staż w rolnictwie, można uzupełnić w 36 mies.',
        'Nie dotyczy rolników już prowadzących działalność rolniczą od ponad 24 miesięcy',
      ],
      odwolanie: 'Odwołanie do Dyrektora Oddziału Regionalnego ARiMR, następnie do sądu administracyjnego',
    },
    zrodloUrl: 'https://www.gov.pl/web/arimr',
    zrodloNazwa: 'ARiMR', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-07-31',
  },
  {
    id: 'doplaty-bezposrednie-arimr', nazwa: 'Dopłaty bezpośrednie ARiMR (płatności obszarowe)',
    opis: 'Dopłaty bezpośrednie z budżetu UE i krajowego dla aktywnych rolników za utrzymanie gruntów rolnych. Szacunkowe stawki 2026 (ostateczne kwoty jesienią): podstawowe wsparcie dochodów: ~494,54 PLN/ha, płatność redystrybucyjna (pierwsze 30 ha): ~171,41 PLN/ha, małe gospodarstwa (do 5 ha): ~960,57 PLN/ha, dopłata dla młodych rolników: ~253,76 PLN/ha. Ekoschematy (dodatkowe): od 479 do 2387 PLN/ha (np. za międzyplony, przekształcenie na użytki zielone). Dopłaty do zwierząt: bydło ~325 PLN/sztukę, krowy ~416 PLN/sztukę, owce ~111 PLN/sztukę. Wnioski przez eWniosekPlus. Termin 2026: do 1 czerwca (wydłużony z powodu suszy). Warunek: "aktywny rolnik" - przy dopłatach powyżej 1125 EUR w 2025 r. wymagane wykazanie kosztów/przychodów.',
    kategoria: 'PRACA',
    kwota: 'ok. 494-960 PLN/ha podstawowych + ekoschematy do 2387 PLN/ha', kwotaMin: 0, kwotaMax: 0,
    czestotliwosc: 'rocznie (wypłata listopad-grudzień)',
    wymagania: { rolnik: true },
    wykluczenia: [
      { opis: 'Rolnik musi spełniać wymogi "aktywnego rolnika" (aktywność zawodowa)', sprawdz: 'aktywny_rolnik' },
    ],
    wniosek: {
      kanal: ['ARiMR', 'ONLINE'], formularz: 'eWniosekPlus (agencja.arimr.gov.pl)',
      dokumenty: [
        'Wniosek o dopłaty bezpośrednie przez system eWniosekPlus',
        'Dane o powierzchni użytków rolnych (system ARiMR)',
        'Oświadczenia dot. ekoschematów (jeśli wnioskujesz o dodatkowe płatności)',
        'Przy zwierzętach: dane z bazy IRZplus',
      ],
      kroki: [
        'Zaloguj się do eWniosekPlus na stronie agencja.arimr.gov.pl',
        'Sprawdź i zaktualizuj dane o działkach rolnych (granice, powierzchnie)',
        'Zaznacz ekoschematy, o które wnioskujesz (opcjonalnie, ale zwiększają dopłatę)',
        'Złóż wniosek do 1 czerwca 2026 (termin wydłużony z powodu suszy)',
        'Dopłaty wypłacane od listopada/grudnia 2026',
      ],
      terminRealizacji: 'Wypłata od listopada/grudnia 2026',
      pulapki: [
        'Termin 2026: do 1 czerwca (wydłużony z powodu suszy, normalnie 15 maja)',
        'Stawki szacunkowe, ostateczne kwoty znane dopiero jesienią',
        'Od 2026: wymóg "aktywnego rolnika" dla większych dopłat, sprawdź czy Cię dotyczy',
        'GAEC 7 (nowe przepisy 2026): wymogi dotyczące różnorodności upraw - sprawdź czy spełniasz',
        'Ekoschematy zwiększają dopłatę o 479-2387 PLN/ha, warto oznaczyć',
        'Płatność redystrybucyjna: dodatkowe 171 PLN/ha dla PIERWSZYCH 30 ha (korzystne dla małych)',
      ],
      odwolanie: 'Odwołanie do Dyrektora Oddziału Regionalnego ARiMR, następnie do sądu administracyjnego',
    },
    zrodloUrl: 'https://www.gov.pl/web/arimr',
    zrodloNazwa: 'ARiMR', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-06-01',
  },
  {
    id: 'doplaty-do-ubezpieczen-upraw', nazwa: 'Dofinansowanie ubezpieczenia upraw i zwierząt (65%)',
    opis: 'Państwo dopłaca do 65% składki ubezpieczenia upraw rolnych i zwierząt gospodarskich. Warunek: ubezpieczenie musi obejmować co najmniej 50% powierzchni upraw. Dotyczy: zbóż, rzepaku, kukurydzy, buraków cukrowych, warzyw, owoców, tytoniu, roślin strączkowych i innych upraw, a także bydła, koni, owiec, kóz, świń, drobiu. Firmy z akredytacją: PZU SA, Concordia, Pocztowe TUW, InterRisk, ERGO Hestia. Rolnik płaci tylko 35% składki, resztę dopłaca budżet państwa. Opcja: zamiast płacić gotówką, możesz potrącić składkę z dopłat bezpośrednich ARiMR (na wniosek). Minimalne sumy gwarancyjne ustalane co roku przez ministerstwo rolnictwa.',
    kategoria: 'PRACA',
    kwota: 'do 65% dopłaty do składki ubezpieczeniowej (płacisz tylko 35%)', kwotaMin: 0, kwotaMax: 0,
    czestotliwosc: 'rocznie (przy zawarciu polisy)',
    wymagania: { rolnik: true },
    wykluczenia: [],
    wniosek: {
      kanal: ['ONLINE', 'ARiMR'],
      dokumenty: [
        'Brak wniosku do ARiMR, umowę zawierasz bezpośrednio z ubezpieczycielem',
        'Dowód osobisty i numer NIP/PESEL',
        'Numer identyfikacyjny ARiMR i dane o gospodarstwie',
        'Informacja o powierzchni i rodzaju upraw',
      ],
      kroki: [
        'Skontaktuj się z jedną z firm: PZU SA, Concordia, Pocztowe TUW, InterRisk, ERGO Hestia',
        'Zawrzyj umowę ubezpieczenia obejmującą min. 50% powierzchni upraw',
        'Zapłać tylko 35% składki (65% dopłaca budżet państwa bezpośrednio do ubezpieczyciela)',
        'Opcja alternatywna: złóż wniosek w ARiMR o potrącenie składki z dopłat bezpośrednich',
        'Firma ubezpieczeniowa przekaże składkę do ARiMR i rozliczy dopłatę państwową',
      ],
      terminRealizacji: 'Ubezpieczenie aktywne od dnia zawarcia polisy',
      pulapki: [
        'Dopłata 65% tylko jeśli ubezpieczysz min. 50% powierzchni upraw',
        'Firmy akredytowane (2026): PZU SA, Concordia, Pocztowe TUW, InterRisk, ERGO Hestia',
        'Możesz potrącić składkę z dopłat bezpośrednich - złóż wniosek w ARiMR do składania wniosków o dopłaty',
        'Limit dla tytoniu/warzyw/owoców: do 25% sumy ubezpieczenia; pozostałe uprawy: do 15%',
        'Stawki i zakresy ustalane przez ministry co roku, sprawdź aktualny wykaz upraw',
      ],
      odwolanie: 'Spory z ubezpieczycielem: Rzecznik Finansowy lub sąd cywilny',
    },
    zrodloUrl: 'https://www.gov.pl/web/rolnictwo/ubezpieczenie-upraw-rolnych-i-zwierzat-gospodarskich-w-2026-r-z-doplata-skladki-z-budzetu-panstwa',
    zrodloNazwa: 'Ministerstwo Rolnictwa', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
];
