import { Benefit } from '../types';

export const MIESZKANIE: Benefit[] = [
  {
    id: 'dodatek-mieszkaniowy', nazwa: 'Dodatek mieszkaniowy',
    opis: 'Dodatek mieszkaniowy to comiesięczna dopłata do czynszu i opłat za mieszkanie, przyznawana na 6 miesięcy. Skierowany do osób o niskich dochodach, niezależnie od formy własności lokalu (właściciele, najemcy, członkowie spółdzielni). Kryterium dochodowe: dochód na osobę nie może przekraczać 40% przeciętnego wynagrodzenia dla gospodarstwa jednoosobowego (ok. 2538 PLN) lub 30% dla wieloosobowego. Powierzchnia mieszkania musi mieścić się w normatywach: 35 m2 dla 1 osoby, 40 m2 dla 2 osób, 45 m2 dla 3 osób, itd. (dopuszczalne przekroczenie o 30%, lub 50% jeśli udział pokoju z kuchnią przekracza 60% powierzchni). Kwota dodatku pokrywa różnicę między wydatkami na mieszkanie a 15-20% dochodu gospodarstwa. Częsty błąd: nieskładanie wniosku po 6 miesiącach, dodatek trzeba odnawiać co pół roku. Praktyczna rada: wniosek można złożyć w urzędzie gminy lub MOPS, zarządca budynku musi potwierdzić wysokość czynszu.',
    kategoria: 'MIESZKANIE',
    kwota: 'pokrycie części czynszu (zależne od gminy)', czestotliwosc: 'miesięcznie (6 miesięcy)',
    wymagania: { dochodMax: 2538 },
    wykluczenia: [{ opis: 'Powierzchnia mieszkania przekracza normatywy (35-80 m2 zależne od liczby osób)', sprawdz: 'powierzchnia_normatyw' }],
    wniosek: {
      kanal: ['URZAD_GMINY', 'MOPS'],
      dokumenty: ['Zaświadczenie o dochodach za 3 miesiące', 'Dokument potwierdzający tytuł prawny do lokalu', 'Deklaracja o wysokości dochodów'],
      kroki: [
        'Pobierz formularz wniosku z urzędu gminy lub MOPS',
        'Poproś zarządcę budynku o potwierdzenie wysokości czynszu',
        'Wypełnij deklarację o dochodach za ostatnie 3 miesiące',
        'Złóż wniosek w urzędzie gminy',
      ],
      terminRealizacji: '30 dni od złożenia wniosku',
      pulapki: ['Dochód na osobę: max 40% (1-osob.) lub 30% (wieloosob.) przeciętnego wynagrodzenia', 'Przysługuje na 6 miesięcy, potem trzeba złożyć ponownie'],
      odwolanie: 'Odwołanie do SKO w ciągu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/dodatek-mieszkaniowy',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'mieszkanie-na-start', nazwa: 'Mieszkanie na Start (kredyt #naStart)',
    opis: 'Mieszkanie na Start (kredyt #naStart) to rządowy program dopłat do rat kredytu hipotecznego na pierwsze mieszkanie lub dom. Dopłata obniża ratę kredytu przez 10 lat. Skierowany do osób do 45. roku życia, które nie posiadają i nie posiadały innego mieszkania ani domu. Warunki: kredyt musi być udzielony przez bank uczestniczący w programie, a cena za m2 mieszkania nie może przekraczać limitów cenowych ustalanych dla każdej lokalizacji. Częsty błąd: założenie, że program jest zawsze dostępny, rząd może go zawieszać lub modyfikować warunki, dlatego przed planowaniem zakupu mieszkania trzeba sprawdzić aktualny status programu na gov.pl. Praktyczna rada: porównaj oferty kilku banków uczestniczących w programie, bo prowizje i marże mogą się znacząco różnić. Program nie obejmuje zakupu działki ani budowy domu systemem gospodarczym.',
    kategoria: 'MIESZKANIE',
    kwota: 'dopłata do kredytu (obniżenie raty)', czestotliwosc: 'miesięcznie (10 lat)',
    wymagania: { wiekMax: 45 },
    wykluczenia: [{ opis: 'Posiadanie innego mieszkania lub domu', sprawdz: 'inne_mieszkanie' }],
    wniosek: {
      kanal: ['BANK'],
      dokumenty: ['Wniosek kredytowy w banku uczestniczącym w programie', 'Dowód osobisty', 'Zaświadczenie o dochodach'],
      kroki: [
        'Sprawdź czy program jest aktualnie aktywny (zależy od decyzji rządu)',
        'Znajdź bank uczestniczący w programie',
        'Złóż wniosek o kredyt z dopłatą',
        'Bank weryfikuje spełnienie warunków programu',
      ],
      terminRealizacji: 'Jak standardowy kredyt hipoteczny (1-3 miesiące)',
      pulapki: ['Program może być zawieszony, sprawdź aktualny status', 'Limity cenowe na m2 zależne od lokalizacji'],
      odwolanie: 'Reklamacja w banku',
    },
    zrodloUrl: 'https://www.gov.pl/web/rozwoj-technologia/mieszkanie-na-start',
    zrodloNazwa: 'Ministerstwo Rozwoju', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'dodatek-energetyczny', nazwa: 'Dodatek energetyczny',
    opis: 'Dodatek energetyczny to comiesięczna dopłata do kosztów energii elektrycznej dla tzw. odbiorców wrażliwych. Kwota wynosi ok. 15-44 PLN miesięcznie, zależnie od liczby osób w gospodarstwie domowym (1 osoba, 2-4 osoby, 5+ osób). Warunek kluczowy: musisz NAJPIERW mieć przyznany dodatek mieszkaniowy. Bez niego nie dostaniesz dodatku energetycznego. Wymagana jest też umowa kompleksowa lub umowa sprzedaży energii z dostawcą prądu na swoje nazwisko. Częsty błąd: składanie wniosku o dodatek energetyczny bez wcześniejszego uzyskania dodatku mieszkaniowego. Praktyczna rada: kwota jest niewielka, ale warto ją łączyć z innymi świadczeniami (dodatek mieszkaniowy, zasiłek celowy na opał). Wniosek składasz w urzędzie gminy.',
    kategoria: 'MIESZKANIE',
    kwota: 'ok. 15-44 PLN miesięcznie', kwotaMin: 15, kwotaMax: 44,
    czestotliwosc: 'miesięcznie',
    wymagania: { dochodMax: 2538 },
    wykluczenia: [{ opis: 'Wymaga posiadania umowy z dostawcą energii', sprawdz: 'umowa_energia' }],
    wniosek: {
      kanal: ['URZAD_GMINY'],
      dokumenty: ['Kopia umowy z dostawcą energii', 'Decyzja o przyznaniu dodatku mieszkaniowego'],
      kroki: ['Musisz najpierw otrzymać dodatek mieszkaniowy', 'Złóż wniosek o dodatek energetyczny w urzędzie gminy', 'Dołącz kopię umowy z dostawcą prądu'],
      terminRealizacji: '30 dni',
      pulapki: ['Wymaga NAJPIERW uzyskania dodatku mieszkaniowego', 'Kwota jest niska ale łączy się z innymi świadczeniami'],
      odwolanie: 'Odwołanie do SKO',
    },
    zrodloUrl: 'https://www.gov.pl/web/energia/dodatek-energetyczny',
    zrodloNazwa: 'Ministerstwo Energii', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'fundusz-wsparcia-kredytobiorcow', nazwa: 'Fundusz Wsparcia Kredytobiorców (FWK)',
    opis: 'FWK to pomoc dla osób, które nie są w stanie spłacać rat kredytu mieszkaniowego. Do 3000 PLN miesięcznie przez max 40 miesięcy (łącznie do 120 000 PLN), wypłacane bezpośrednio do banku (kredytobiorca nie dostaje gotówki). Wsparcie jest bezzwrotne przez 2 lata od ostatniej wypłaty, potem spłacane w 200 nieoprocentowanych ratach przez ok. 16 lat. Jeśli spłacisz 134 z 200 rat bez opóźnienia -- reszta umorzona. Warunki: bezrobocie LUB rata kredytu > 40% dochodu LUB dochód netto po spłacie kredytu < 2525 PLN (1-os.) / 2057,50 PLN/osobę (wieloosobowe). Wniosek przez bank, który udzielił kredytu. Dotyczy kredytów na mieszkanie lub dom na własne potrzeby.',
    kategoria: 'MIESZKANIE',
    kwota: 'do 3000 PLN/mies. przez max 40 miesięcy (łącznie do 120 000 PLN)', kwotaMin: 0, kwotaMax: 3000,
    czestotliwosc: 'miesięcznie (max 40 mies.)',
    wymagania: {},
    wykluczenia: [
      { opis: 'Dotyczy tylko kredytów mieszkaniowych (mieszkanie lub dom na własne potrzeby)', sprawdz: 'kredyt_mieszkaniowy' },
    ],
    wniosek: {
      kanal: ['BANK', 'BGK'],
      dokumenty: [
        'Wniosek o wsparcie z FWK (dostępny w banku kredytodawcy)',
        'Umowa kredytu hipotecznego',
        'Zaświadczenie o bezrobociu lub zaświadczenie o dochodach',
        'Zaświadczenie potwierdzające wysokość raty kredytu',
        'Dowód osobisty',
      ],
      kroki: [
        'Udaj się do banku, który udzielił Ci kredytu hipotecznego',
        'Poproś o formularz wniosku o wsparcie z Funduszu Wsparcia Kredytobiorców',
        'Wykaż spełnienie jednego z warunków: bezrobocie LUB rata > 40% dochodu LUB niski dochód po racie',
        'Bank przekaże wniosek do BGK (Bank Gospodarstwa Krajowego)',
        'Po pozytywnej decyzji: do 3000 PLN/mies. trafia bezpośrednio do banku jako spłata raty',
        'Po 2 latach od ostatniej wypłaty: spłata w 200 nieoprocentowanych ratach (ok. 16 lat)',
      ],
      terminRealizacji: 'Decyzja BGK w ciągu kilku tygodni',
      pulapki: [
        'Do 3000 PLN/mies., max 40 miesięcy, kwota ustalana indywidualnie',
        'NIE gotówka -- pieniądze trafiają bezpośrednio do banku na spłatę kredytu',
        'Spłata: 200 rat po 2 latach od ostatniej wypłaty, nieoprocentowane',
        'Jeśli spłacisz 134 z 200 rat na czas -- reszta UMORZONA (ok. 33% kwoty)',
        'Warunek: kredyt musi być na mieszkanie/dom na własne potrzeby (nie inwestycyjny)',
        'Kryterium dochodowe 2025: dochód netto po racie < 2525 PLN (1 os.) lub 2057,50 PLN/os. (więcej os.)',
      ],
      odwolanie: 'Odwołanie do BGK w ciągu 14 dni od decyzji odmownej',
    },
    zrodloUrl: 'https://www.bgk.pl/produkty/fundusz-wsparcia-kredytobiorcow/',
    zrodloNazwa: 'BGK (Bank Gospodarstwa Krajowego)', dataWeryfikacji: '2026-05-14', dataWaznosci: '2026-12-31',
  },
];
