import { Benefit } from '../types';

export const MIESZKANIE: Benefit[] = [
  {
    id: 'dodatek-mieszkaniowy', nazwa: 'Dodatek mieszkaniowy',
    opis: 'Dodatek mieszkaniowy to comiesięczna dopłata do czynszu i opłat za mieszkanie, przyznawana na 6 miesięcy. Skierowany do osób o niskich dochodach, niezależnie od formy własności lokalu (właściciele, najemcy, członkowie spółdzielni). Kryterium dochodowe: dochód na osobę nie może przekraczać 40% przeciętnego wynagrodzenia dla gospodarstwa jednoosobowego (ok. 2538 PLN) lub 30% dla wieloosobowego. Powierzchnia mieszkania musi mieścić się w normatywach: 35 m2 dla 1 osoby, 40 m2 dla 2 osób, 45 m2 dla 3 osób, itd. (dopuszczalne przekroczenie o 30%, lub 50% jeśli udział pokoju z kuchnią przekracza 60% powierzchni). Kwota dodatku pokrywa różnicę między wydatkami na mieszkanie a 15-20% dochodu gospodarstwa. Częsty błąd: nieskładanie wniosku po 6 miesiącach -- dodatek trzeba odnawiać co pół roku. Praktyczna rada: wniosek można złożyć w urzędzie gminy lub MOPS, zarządca budynku musi potwierdzić wysokość czynszu.',
    kategoria: 'MIESZKANIE',
    kwota: 'pokrycie części czynszu (zależne od gminy)', czestotliwosc: 'miesięcznie (6 miesięcy)',
    wymagania: { dochodMax: 2538 },
    wykluczenia: [{ opis: 'Powierzchnia mieszkania przekracza normatywy (35-80 m2 zależne od liczby osób)', sprawdz: 'powierzchnia_normatyw' }],
    wniosek: {
      kanal: ['URZAD_GMINY', 'MOPS'],
      dokumenty: ['Zaświadczenie o dochodach za 3 miesiące', 'Dokument potwierdzający tytuł prawny do lokalu', 'Deklaracja o wysokości dochodów'],
      kroki: [
        'Pobierz formularz wniosku z urzędu gminy lub MOPS',
        'Poproś zarządcę budynku o potwierdzenie wysokości czynszu',
        'Wypełnij deklarację o dochodach za ostatnie 3 miesiące',
        'Złóż wniosek w urzędzie gminy',
      ],
      terminRealizacji: '30 dni od złożenia wniosku',
      pulapki: ['Dochód na osobę: max 40% (1-osob.) lub 30% (wieloosob.) przeciętnego wynagrodzenia', 'Przysługuje na 6 miesięcy, potem trzeba złożyć ponownie'],
      odwolanie: 'Odwołanie do SKO w ciągu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/dodatek-mieszkaniowy',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'mieszkanie-na-start', nazwa: 'Mieszkanie na Start (kredyt #naStart)',
    opis: 'Mieszkanie na Start (kredyt #naStart) to rządowy program dopłat do rat kredytu hipotecznego na pierwsze mieszkanie lub dom. Dopłata obniża ratę kredytu przez 10 lat. Skierowany do osób do 45. roku życia, które nie posiadają i nie posiadały innego mieszkania ani domu. Warunki: kredyt musi być udzielony przez bank uczestniczący w programie, a cena za m2 mieszkania nie może przekraczać limitów cenowych ustalanych dla każdej lokalizacji. Częsty błąd: założenie, że program jest zawsze dostępny -- rząd może go zawieszać lub modyfikować warunki, dlatego przed planowaniem zakupu mieszkania trzeba sprawdzić aktualny status programu na gov.pl. Praktyczna rada: porównaj oferty kilku banków uczestniczących w programie, bo prowizje i marże mogą się znacząco różnić. Program nie obejmuje zakupu działki ani budowy domu systemem gospodarczym.',
    kategoria: 'MIESZKANIE',
    kwota: 'dopłata do kredytu (obniżenie raty)', czestotliwosc: 'miesięcznie (10 lat)',
    wymagania: { wiekMax: 45 },
    wykluczenia: [{ opis: 'Posiadanie innego mieszkania lub domu', sprawdz: 'inne_mieszkanie' }],
    wniosek: {
      kanal: ['BANK'],
      dokumenty: ['Wniosek kredytowy w banku uczestniczącym w programie', 'Dowód osobisty', 'Zaświadczenie o dochodach'],
      kroki: [
        'Sprawdź czy program jest aktualnie aktywny (zależy od decyzji rządu)',
        'Znajdź bank uczestniczący w programie',
        'Złóż wniosek o kredyt z dopłatą',
        'Bank weryfikuje spełnienie warunków programu',
      ],
      terminRealizacji: 'Jak standardowy kredyt hipoteczny (1-3 miesiące)',
      pulapki: ['Program może być zawieszony, sprawdź aktualny status', 'Limity cenowe na m2 zależne od lokalizacji'],
      odwolanie: 'Reklamacja w banku',
    },
    zrodloUrl: 'https://www.gov.pl/web/rozwoj-technologia/mieszkanie-na-start',
    zrodloNazwa: 'Ministerstwo Rozwoju', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'dodatek-energetyczny', nazwa: 'Dodatek energetyczny',
    opis: 'Dodatek energetyczny to comiesięczna dopłata do kosztów energii elektrycznej dla tzw. odbiorców wrażliwych. Kwota wynosi ok. 15-44 PLN miesięcznie, zależnie od liczby osób w gospodarstwie domowym (1 osoba, 2-4 osoby, 5+ osób). Warunek kluczowy: musisz NAJPIERW mieć przyznany dodatek mieszkaniowy -- bez niego nie dostaniesz dodatku energetycznego. Wymagana jest też umowa kompleksowa lub umowa sprzedaży energii z dostawcą prądu na swoje nazwisko. Częsty błąd: składanie wniosku o dodatek energetyczny bez wcześniejszego uzyskania dodatku mieszkaniowego. Praktyczna rada: kwota jest niewielka, ale warto ją łączyć z innymi świadczeniami (dodatek mieszkaniowy, zasiłek celowy na opał). Wniosek składasz w urzędzie gminy.',
    kategoria: 'MIESZKANIE',
    kwota: 'ok. 15-44 PLN miesięcznie', kwotaMin: 15, kwotaMax: 44,
    czestotliwosc: 'miesięcznie',
    wymagania: { dochodMax: 2538 },
    wykluczenia: [{ opis: 'Wymaga posiadania umowy z dostawcą energii', sprawdz: 'umowa_energia' }],
    wniosek: {
      kanal: ['URZAD_GMINY'],
      dokumenty: ['Kopia umowy z dostawcą energii', 'Decyzja o przyznaniu dodatku mieszkaniowego'],
      kroki: ['Musisz najpierw otrzymać dodatek mieszkaniowy', 'Złóż wniosek o dodatek energetyczny w urzędzie gminy', 'Dołącz kopię umowy z dostawcą prądu'],
      terminRealizacji: '30 dni',
      pulapki: ['Wymaga NAJPIERW uzyskania dodatku mieszkaniowego', 'Kwota jest niska ale łączy się z innymi świadczeniami'],
      odwolanie: 'Odwołanie do SKO',
    },
    zrodloUrl: 'https://www.gov.pl/web/energia/dodatek-energetyczny',
    zrodloNazwa: 'Ministerstwo Energii', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
];
