import { Benefit } from '../types';

export const NIEPELNOSPRAWNOSC: Benefit[] = [
  {
    id: 'swiadczenie-wspierajace', nazwa: 'Swiadczenie wspierajace', kategoria: 'NIEPELNOSPRAWNOSC',
    kwota: '752-4134 PLN miesiecznie', kwotaMin: 752, kwotaMax: 4134,
    czestotliwosc: 'miesiecznie',
    wymagania: { niepelnosprawnosc: ['umiarkowany', 'znaczny'] },
    wykluczenia: [],
    wniosek: {
      kanal: ['PUE_ZUS', 'EMPATIA', 'BANK'], formularz: 'SWP (wniosek o swiadczenie wspierajace)',
      dokumenty: ['Decyzja WZON o poziomie potrzeby wsparcia (min. 70 pkt)', 'Dowod osobisty', 'Numer konta bankowego'],
      kroki: [
        'Krok 1: Zloz wniosek PPW-1 do WZON o ustalenie poziomu potrzeby wsparcia',
        'Krok 2: Wypelnij kwestionariusz PPW-K (samoocena w 32 obszarach zycia)',
        'Krok 3: Czekaj na decyzje WZON (do 3 miesiecy)',
        'Krok 4: Jesli uzyskasz min. 70 pkt -- zloz wniosek SWP przez PUE ZUS',
        'Krok 5: Wpisz numer decyzji WZON we wniosku',
      ],
      terminRealizacji: 'WZON: do 3 miesiecy. ZUS: 30 dni od wniosku SWP',
      pulapki: [
        'Od stycznia 2026 prog obnizono z 87 do 70 pkt -- jesli wczesniej odmowiono, mozesz probowac ponownie',
        'Kwota zalezy od punktacji: 70-74 pkt = 752 PLN, 95-100 pkt = 4134 PLN',
        'Wniosek SWP skladasz TYLKO elektronicznie (PUE ZUS, Empatia lub bank)',
      ],
      odwolanie: 'Odwolanie od decyzji WZON do Sadu Pracy w ciagu 30 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/swiadczenie-wspierajace',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'dodatek-pielegnacyjny', nazwa: 'Dodatek pielegnacyjny', kategoria: 'NIEPELNOSPRAWNOSC',
    kwota: '348,22 PLN miesiecznie', kwotaMin: 348, kwotaMax: 348,
    czestotliwosc: 'miesiecznie',
    wymagania: { wiekMin: 75 },
    wykluczenia: [],
    wniosek: {
      kanal: ['PUE_ZUS'],
      dokumenty: ['Brak -- przyznawany automatycznie po ukonczeniu 75 lat'],
      kroki: ['Dla osob 75+ ZUS przyznaje automatycznie -- nie musisz skladac wniosku', 'Dla osob ponizej 75 lat z orzeczeniem o niezdolnosci do samodzielnej egzystencji -- zloz wniosek w ZUS'],
      terminRealizacji: 'Automatycznie od miesiaca ukonczenia 75 lat',
      pulapki: ['75+: automatyczne. Ponizej 75: wymaga orzeczenia lekarskiego ZUS', 'Nie laczy sie ze swiadczeniem pielegnacyjnym'],
      odwolanie: 'Odwolanie do Sadu Pracy',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/dodatek-pielegnacyjny',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'dofinansowanie-pfron', nazwa: 'Dofinansowanie PFRON', kategoria: 'NIEPELNOSPRAWNOSC',
    kwota: 'do kilku tysiecy PLN (zalezne od rodzaju wsparcia)', czestotliwosc: 'jednorazowo lub rocznie',
    wymagania: { niepelnosprawnosc: ['lekki', 'umiarkowany', 'znaczny'] },
    wykluczenia: [],
    wniosek: {
      kanal: ['MOPS'],
      dokumenty: ['Orzeczenie o niepelnosprawnosci', 'Faktura lub kosztorys (dla sprzetu/adaptacji)', 'Dowod osobisty'],
      kroki: [
        'Skontaktuj sie z PCPR lub MOPS w swoim powiecie',
        'Zapytaj o dostepne programy PFRON (sprzet, likwidacja barier, turnus, samochod)',
        'Zloz wniosek z kompletem dokumentow',
        'Dofinansowanie pokrywa czesc kosztow (zwykle 50-80%)',
      ],
      terminRealizacji: '30-60 dni',
      pulapki: ['Kazdy powiat ma wlasny budzet -- srodki moga sie skonczyc w trakcie roku', 'Warto skladac na poczatku roku kalendarzowego'],
      odwolanie: 'Odwolanie do Starosty',
    },
    zrodloUrl: 'https://www.pfron.org.pl/',
    zrodloNazwa: 'PFRON', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'turnusy-rehabilitacyjne', nazwa: 'Turnusy rehabilitacyjne', kategoria: 'NIEPELNOSPRAWNOSC',
    kwota: 'dofinansowanie do 1449 PLN', kwotaMin: 906, kwotaMax: 1449,
    czestotliwosc: 'rocznie',
    wymagania: { niepelnosprawnosc: ['lekki', 'umiarkowany', 'znaczny'] },
    wykluczenia: [],
    wniosek: {
      kanal: ['MOPS'],
      dokumenty: ['Orzeczenie o niepelnosprawnosci', 'Wniosek lekarza o skierowanie na turnus', 'Dowod osobisty'],
      kroki: [
        'Uzyskaj wniosek lekarza o skierowanie na turnus rehabilitacyjny',
        'Zloz wniosek w PCPR o dofinansowanie turnusu',
        'Wybierz osrodek z rejestru osrodkow prowadzacych turnusy',
        'PCPR pokryje czesc kosztow (kwota zalezy od stopnia niepelnosprawnosci)',
      ],
      terminRealizacji: '30 dni od zlozenia wniosku',
      pulapki: ['Turnus trwa min. 14 dni', 'Osrodek musi byc wpisany do rejestru', 'Skladaj wczesnie -- budzet sie konczy'],
      odwolanie: 'Odwolanie do Starosty',
    },
    zrodloUrl: 'https://www.pfron.org.pl/',
    zrodloNazwa: 'PFRON', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
];
