import { Benefit } from '../types';

export const NIEPELNOSPRAWNOSC: Benefit[] = [
  {
    id: 'swiadczenie-wspierajace', nazwa: 'Świadczenie wspierające', kategoria: 'NIEPELNOSPRAWNOSC',
    kwota: '752-4134 PLN miesięcznie', kwotaMin: 752, kwotaMax: 4134,
    czestotliwosc: 'miesięcznie',
    wymagania: { niepelnosprawnosc: ['umiarkowany', 'znaczny'] },
    wykluczenia: [],
    wniosek: {
      kanal: ['PUE_ZUS', 'EMPATIA', 'BANK'], formularz: 'SWP (wniosek o świadczenie wspierające)',
      dokumenty: ['Decyzja WZON o poziomie potrzeby wsparcia (min. 70 pkt)', 'Dowód osobisty', 'Numer konta bankowego'],
      kroki: [
        'Krok 1: Złóż wniosek PPW-1 do WZON o ustalenie poziomu potrzeby wsparcia',
        'Krok 2: Wypełnij kwestionariusz PPW-K (samoocena w 32 obszarach życia)',
        'Krok 3: Czekaj na decyzję WZON (do 3 miesięcy)',
        'Krok 4: Jeśli uzyskasz min. 70 pkt, złóż wniosek SWP przez PUE ZUS',
        'Krok 5: Wpisz numer decyzji WZON we wniosku',
      ],
      terminRealizacji: 'WZON: do 3 miesięcy. ZUS: 30 dni od wniosku SWP',
      pulapki: [
        'Od stycznia 2026 próg obniżono z 87 do 70 pkt, jeśli wcześniej odmówiono, możesz próbować ponownie',
        'Kwota zależy od punktacji: 70-74 pkt = 752 PLN, 95-100 pkt = 4134 PLN',
        'Wniosek SWP składasz TYLKO elektronicznie (PUE ZUS, Empatia lub bank)',
      ],
      odwolanie: 'Odwołanie od decyzji WZON do Sądu Pracy w ciągu 30 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/swiadczenie-wspierajace',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'dodatek-pielegnacyjny', nazwa: 'Dodatek pielęgnacyjny', kategoria: 'NIEPELNOSPRAWNOSC',
    kwota: '348,22 PLN miesięcznie', kwotaMin: 348, kwotaMax: 348,
    czestotliwosc: 'miesięcznie',
    wymagania: { wiekMin: 75 },
    wykluczenia: [],
    wniosek: {
      kanal: ['PUE_ZUS'],
      dokumenty: ['Brak, przyznawany automatycznie po ukończeniu 75 lat'],
      kroki: ['Dla osób 75+ ZUS przyznaje automatycznie, nie musisz składać wniosku', 'Dla osób poniżej 75 lat z orzeczeniem o niezdolności do samodzielnej egzystencji, złóż wniosek w ZUS'],
      terminRealizacji: 'Automatycznie od miesiąca ukończenia 75 lat',
      pulapki: ['75+: automatyczne. Poniżej 75: wymaga orzeczenia lekarskiego ZUS', 'Nie łączy się ze świadczeniem pielęgnacyjnym'],
      odwolanie: 'Odwołanie do Sądu Pracy',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/dodatek-pielegnacyjny',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'dofinansowanie-pfron', nazwa: 'Dofinansowanie PFRON', kategoria: 'NIEPELNOSPRAWNOSC',
    kwota: 'do kilku tysięcy PLN (zależne od rodzaju wsparcia)', czestotliwosc: 'jednorazowo lub rocznie',
    wymagania: { niepelnosprawnosc: ['lekki', 'umiarkowany', 'znaczny'] },
    wykluczenia: [],
    wniosek: {
      kanal: ['MOPS'],
      dokumenty: ['Orzeczenie o niepełnosprawności', 'Faktura lub kosztorys (dla sprzętu/adaptacji)', 'Dowód osobisty'],
      kroki: [
        'Skontaktuj się z PCPR lub MOPS w swoim powiecie',
        'Zapytaj o dostępne programy PFRON (sprzęt, likwidacja barier, turnus, samochód)',
        'Złóż wniosek z kompletem dokumentów',
        'Dofinansowanie pokrywa część kosztów (zwykle 50-80%)',
      ],
      terminRealizacji: '30-60 dni',
      pulapki: ['Każdy powiat ma własny budżet, środki mogą się skończyć w trakcie roku', 'Warto składać na początku roku kalendarzowego'],
      odwolanie: 'Odwołanie do Starosty',
    },
    zrodloUrl: 'https://www.pfron.org.pl/',
    zrodloNazwa: 'PFRON', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'turnusy-rehabilitacyjne', nazwa: 'Turnusy rehabilitacyjne', kategoria: 'NIEPELNOSPRAWNOSC',
    kwota: 'dofinansowanie do 1449 PLN', kwotaMin: 906, kwotaMax: 1449,
    czestotliwosc: 'rocznie',
    wymagania: { niepelnosprawnosc: ['lekki', 'umiarkowany', 'znaczny'] },
    wykluczenia: [],
    wniosek: {
      kanal: ['MOPS'],
      dokumenty: ['Orzeczenie o niepełnosprawności', 'Wniosek lekarza o skierowanie na turnus', 'Dowód osobisty'],
      kroki: [
        'Uzyskaj wniosek lekarza o skierowanie na turnus rehabilitacyjny',
        'Złóż wniosek w PCPR o dofinansowanie turnusu',
        'Wybierz ośrodek z rejestru ośrodków prowadzących turnusy',
        'PCPR pokryje część kosztów (kwota zależy od stopnia niepełnosprawności)',
      ],
      terminRealizacji: '30 dni od złożenia wniosku',
      pulapki: ['Turnus trwa min. 14 dni', 'Ośrodek musi być wpisany do rejestru', 'Składaj wcześnie, budżet się kończy'],
      odwolanie: 'Odwołanie do Starosty',
    },
    zrodloUrl: 'https://www.pfron.org.pl/',
    zrodloNazwa: 'PFRON', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
];
