import { Benefit } from '../types';

export const NIEPELNOSPRAWNOSC: Benefit[] = [
  {
    id: 'swiadczenie-wspierajace', nazwa: 'Świadczenie wspierające',
    opis: 'Świadczenie wspierające to comiesięczne świadczenie pieniężne wypłacane bezpośrednio osobie z niepełnosprawnością (nie opiekunowi). Kwota zależy od punktacji WZON i jest powiązana z rentą socjalną (1978,49 PLN od marca 2026, waloryzacja 5,3%). Po waloryzacji marzec 2026: 70-74 pkt = 792 PLN, 75-79 pkt = 1188 PLN, 80-84 pkt = 1583 PLN, 85-89 pkt = 1979 PLN, 90-94 pkt = 2769 PLN, 95-100 pkt = 4353 PLN miesięcznie. Procedura dwuetapowa: najpierw składasz wniosek PPW-1 do Wojewódzkiego Zespołu ds. Orzekania o Niepełnosprawności (WZON) o ustalenie poziomu potrzeby wsparcia, wypełniasz kwestionariusz samooceny PPW-K (32 obszary życia), a po uzyskaniu min. 70 pkt składasz wniosek SWP elektronicznie przez PUE ZUS, portal Empatia lub bank. Od stycznia 2026 próg obniżono z 87 do 70 pkt, jeśli wcześniej odmówiono Ci świadczenia, warto złożyć ponowny wniosek. Częsty błąd: próba złożenia wniosku SWP papierowo: przyjmowane są WYŁĄCZNIE wnioski elektroniczne. Świadczenie nie zależy od dochodu. Można je łączyć z rentą, emeryturą i innymi świadczeniami.',
    kategoria: 'NIEPELNOSPRAWNOSC',
    kwota: '792-4353 PLN miesięcznie (po waloryzacji marzec 2026)', kwotaMin: 792, kwotaMax: 4353,
    czestotliwosc: 'miesięcznie',
    wymagania: { niepelnosprawnosc: ['umiarkowany', 'znaczny'] },
    wykluczenia: [],
    wniosek: {
      kanal: ['PUE_ZUS', 'EMPATIA', 'BANK'], formularz: 'SWP (wniosek o świadczenie wspierające)',
      dokumenty: ['Decyzja WZON o poziomie potrzeby wsparcia (min. 70 pkt)', 'Dowód osobisty', 'Numer konta bankowego'],
      kroki: [
        'Krok 1: Złóż wniosek PPW-1 do WZON o ustalenie poziomu potrzeby wsparcia',
        'Krok 2: Wypełnij kwestionariusz PPW-K (samoocena w 32 obszarach życia)',
        'Krok 3: Czekaj na decyzję WZON (do 3 miesięcy)',
        'Krok 4: Jeśli uzyskasz min. 70 pkt, złóż wniosek SWP przez PUE ZUS',
        'Krok 5: Wpisz numer decyzji WZON we wniosku',
      ],
      terminRealizacji: 'WZON: do 3 miesięcy. ZUS: 30 dni od wniosku SWP',
      pulapki: [
        'Od stycznia 2026 próg obniżono z 87 do 70 pkt, jeśli wcześniej odmówiono, możesz próbować ponownie',
        'Kwota zależy od punktacji (po waloryzacji marzec 2026): 70-74 pkt = 792 PLN, 95-100 pkt = 4353 PLN',
        'Wniosek SWP składasz TYLKO elektronicznie (PUE ZUS, Empatia lub bank)',
      ],
      odwolanie: 'Odwołanie od decyzji WZON do Sądu Pracy w ciągu 30 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/swiadczenie-wspierajace',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'dodatek-pielegnacyjny', nazwa: 'Dodatek pielęgnacyjny',
    opis: 'Dodatek pielęgnacyjny wynosi 366,68 PLN miesięcznie (od 1 marca 2026, po waloryzacji 5,3%) i jest wypłacany przez ZUS. Dla osób, które ukończyły 75 lat, przyznawany jest automatycznie, nie trzeba składać wniosku, ZUS dolicza go do emerytury lub renty. Osoby poniżej 75 lat mogą go otrzymać, jeśli lekarz orzecznik ZUS stwierdzi całkowitą niezdolność do pracy oraz niezdolność do samodzielnej egzystencji. Częsty błąd: mylenie dodatku pielęgnacyjnego (z ZUS, 366,68 PLN) z zasiłkiem pielęgnacyjnym (z gminy, 215,84 PLN). To dwa różne świadczenia i nie można ich pobierać jednocześnie. Jeśli masz prawo do obu, musisz wybrać jedno. Praktyczna rada: dla osób 75+ dodatek pielęgnacyjny z ZUS jest korzystniejszy (wyższa kwota). Dodatek nie zależy od dochodu. Waloryzowany co roku 1 marca razem z emeryturami.',
    kategoria: 'NIEPELNOSPRAWNOSC',
    kwota: '366,68 PLN miesięcznie (od marca 2026)', kwotaMin: 367, kwotaMax: 367,
    czestotliwosc: 'miesięcznie',
    wymagania: { wiekMin: 75 },
    wykluczenia: [],
    wniosek: {
      kanal: ['PUE_ZUS'],
      dokumenty: ['Brak, przyznawany automatycznie po ukończeniu 75 lat'],
      kroki: ['Dla osób 75+ ZUS przyznaje automatycznie, nie musisz składać wniosku', 'Dla osób poniżej 75 lat z orzeczeniem o niezdolności do samodzielnej egzystencji, złóż wniosek w ZUS'],
      terminRealizacji: 'Automatycznie od miesiąca ukończenia 75 lat',
      pulapki: ['75+: automatyczne. Poniżej 75: wymaga orzeczenia lekarskiego ZUS', 'Nie łączy się ze świadczeniem pielęgnacyjnym'],
      odwolanie: 'Odwołanie do Sądu Pracy',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/dodatek-pielegnacyjny',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'dofinansowanie-pfron', nazwa: 'Dofinansowanie PFRON',
    opis: 'Dofinansowanie PFRON obejmuje szereg programów wsparcia dla osób z niepełnosprawnością, realizowanych przez Powiatowe Centra Pomocy Rodzinie (PCPR) i MOPS. Dostępne formy: likwidacja barier architektonicznych (podjazdy, windy, adaptacja łazienki, do 95% kosztów), sprzęt rehabilitacyjny i ortopedyczny (wózki, protezy, aparaty słuchowe, do 80% kosztów), dofinansowanie samochodu (zakup lub przystosowanie, do kilkunastu tys. PLN), sprzęt komputerowy (dla osób z dysfunkcją wzroku, słuchu, do 3500 PLN). Wymagane orzeczenie o niepełnosprawności (dowolny stopień). Częsty błąd: składanie wniosku pod koniec roku, gdy budżet powiatu na PFRON jest już wyczerpany. Praktyczna rada: złóż wniosek w styczniu-marcu, gdy pula środków jest największa. Każdy powiat ma własny budżet i priorytety, więc kwoty i dostępność różnią się w zależności od miejsca zamieszkania. Warto zapytać w PCPR o aktualnie dostępne programy.',
    kategoria: 'NIEPELNOSPRAWNOSC',
    kwota: 'do kilku tysięcy PLN (zależne od rodzaju wsparcia)', czestotliwosc: 'jednorazowo lub rocznie',
    wymagania: { niepelnosprawnosc: ['lekki', 'umiarkowany', 'znaczny'] },
    wykluczenia: [],
    wniosek: {
      kanal: ['MOPS'],
      dokumenty: ['Orzeczenie o niepełnosprawności', 'Faktura lub kosztorys (dla sprzętu/adaptacji)', 'Dowód osobisty'],
      kroki: [
        'Skontaktuj się z PCPR lub MOPS w swoim powiecie',
        'Zapytaj o dostępne programy PFRON (sprzęt, likwidacja barier, turnus, samochód)',
        'Złóż wniosek z kompletem dokumentów',
        'Dofinansowanie pokrywa część kosztów (zwykle 50-80%)',
      ],
      terminRealizacji: '30-60 dni',
      pulapki: ['Każdy powiat ma własny budżet, środki mogą się skończyć w trakcie roku', 'Warto składać na początku roku kalendarzowego'],
      odwolanie: 'Odwołanie do Starosty',
    },
    zrodloUrl: 'https://www.pfron.org.pl/',
    zrodloNazwa: 'PFRON', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'pfron-aktywny-samorzad', nazwa: 'PFRON Aktywny Samorząd 2026',
    opis: 'Program PFRON Aktywny Samorząd to roczny program finansujący zakup sprzętu i usług wspierających aktywność zawodową i społeczną osób z niepełnosprawnością. Realizowany przez powiaty (PCPR). Budżet 2026: 306,1 mln PLN. Moduł I (likwidacja barier transportowych i dostępu): dofinansowanie zakupu samochodu (do 27 000 PLN przy znacznym stopniu), jego przystosowania, wózka elektrycznego (do 10 000 PLN lub więcej przy znacznym stopniu kończyn górnych), protezy po amputacji (do 9000-35 000 PLN zależnie od rodzaju), aparatu słuchowego (do 3500 PLN). Dofinansowanie sprzętu komputerowego i elektronicznego (do 10 000 PLN dla osób z dysfunkcją wzroku, narządu ruchu lub słuchu). Moduł II (studia): dofinansowanie opłat za naukę w szkole wyższej, kurs lub szkołę policealną (do 4000 PLN rocznie, do 8000 PLN przy znacznym stopniu). Wymagane: orzeczenie o niepełnosprawności (min. umiarkowany stopień dla większości modułów, lekki dopuszczony przy barierach transportowych). BRAK kryterium dochodowego dla większości elementów, ale może być wymagany wkład własny 15-25%. Nabór wniosków: zwykle marzec-sierpień każdego roku. Każdy powiat ma własne ogłoszenie o naborze w systemie SOW (online) lub w PCPR.',
    kategoria: 'NIEPELNOSPRAWNOSC',
    kwota: 'do 10 000-35 000 PLN (zależnie od rodzaju wsparcia)',
    kwotaMin: 0, kwotaMax: 35000,
    czestotliwosc: 'rocznie (nabór marzec-sierpień)',
    wymagania: { niepelnosprawnosc: ['umiarkowany', 'znaczny'] },
    wykluczenia: [],
    wniosek: {
      kanal: ['PFRON', 'ONLINE'],
      dokumenty: [
        'Orzeczenie o niepełnosprawności lub równoważne',
        'Faktura pro-forma lub kosztorys na planowany zakup/usługę',
        'Dowód osobisty',
        'Zaświadczenie o zatrudnieniu lub nauce (Moduł II: studiowanie)',
        'Dokumentacja medyczna uzasadniająca rodzaj wsparcia (np. amputacja, dysfunkcja wzroku)',
      ],
      kroki: [
        'Śledź ogłoszenia o naborze w swoim PCPR lub systemie SOW (sow.pfron.org.pl)',
        'Sprawdź, czy Twoja niepełnosprawność kwalifikuje się do danego obszaru wsparcia',
        'Złóż wniosek w systemie SOW (online) lub w PCPR (papierowo) w terminie naboru',
        'PCPR oceni wniosek i przyzna dofinansowanie do wysokości dostępnej puli',
        'Po otrzymaniu decyzji zakup sprzęt/usługę i dostarcz fakturę, PCPR wypłaci dofinansowanie',
      ],
      terminRealizacji: '30-60 dni od złożenia wniosku',
      pulapki: [
        'Nabór wniosków zwykle marzec-sierpień, po tym terminie pula może być wyczerpana',
        'Każdy powiat ma własną pulę środków i własne ogłoszenie o naborze, sprawdź w swoim PCPR',
        'Może być wymagany wkład własny 15-25% kosztów (poza Modułem II)',
        'Dofinansowanie udzielane raz w danym roku i obszarze, nie dwa razy na to samo',
        'Wniosek można złożyć w systemie SOW online: sow.pfron.org.pl',
        'Budżet programu na 2026: 306,1 mln PLN, po wyczerpaniu nabór zamykany',
      ],
      odwolanie: 'Odwołanie do Starosty w ciągu 14 dni od decyzji PCPR',
    },
    zrodloUrl: 'https://www.pfron.org.pl/aktualnosci/szczegoly-aktualnosci/news/aktywny-samorzad-2026/',
    zrodloNazwa: 'PFRON', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'turnusy-rehabilitacyjne', nazwa: 'Turnusy rehabilitacyjne',
    opis: 'Turnusy rehabilitacyjne to 14-dniowe pobyty w ośrodkach rehabilitacyjnych, dofinansowane przez PFRON za pośrednictwem PCPR. Dofinansowanie od 30.03.2026 (po waloryzacji) zależy od stopnia niepełnosprawności: znaczny: do 2207 PLN, umiarkowany: do 1987 PLN, lekki: do 1840 PLN. Osoby ze znaczną niepełnosprawnością mogą uzyskać dodatkowe dofinansowanie na opiekuna. Wymagane: orzeczenie o niepełnosprawności i wniosek lekarza o skierowanie na turnus. Ośrodek musi być wpisany do rejestru ośrodków prowadzących turnusy rehabilitacyjne (sprawdź na empatia.mpips.gov.pl). Częsty błąd: wybór ośrodka spoza rejestru,PCPR nie zwróci kosztów. Praktyczna rada: złóż wniosek na początku roku (styczeń-marzec), bo pula środków jest ograniczona i kończy się zwykle do połowy roku. Turnus można odbyć 1 raz w roku. Dofinansowanie pokrywa część kosztów, resztę (zwykle 30-50%) pokrywasz samodzielnie.',
    kategoria: 'NIEPELNOSPRAWNOSC',
    kwota: 'dofinansowanie 1840-2207 PLN (od 30.03.2026)', kwotaMin: 1840, kwotaMax: 2207,
    czestotliwosc: 'rocznie',
    wymagania: { niepelnosprawnosc: ['lekki', 'umiarkowany', 'znaczny'] },
    wykluczenia: [],
    wniosek: {
      kanal: ['MOPS'],
      dokumenty: ['Orzeczenie o niepełnosprawności', 'Wniosek lekarza o skierowanie na turnus', 'Dowód osobisty'],
      kroki: [
        'Uzyskaj wniosek lekarza o skierowanie na turnus rehabilitacyjny',
        'Złóż wniosek w PCPR o dofinansowanie turnusu',
        'Wybierz ośrodek z rejestru ośrodków prowadzących turnusy',
        'PCPR pokryje część kosztów (kwota zależy od stopnia niepełnosprawności)',
      ],
      terminRealizacji: '30 dni od złożenia wniosku',
      pulapki: ['Turnus trwa min. 14 dni', 'Ośrodek musi być wpisany do rejestru', 'Składaj wcześnie, budżet się kończy'],
      odwolanie: 'Odwołanie do Starosty',
    },
    zrodloUrl: 'https://www.pfron.org.pl/',
    zrodloNazwa: 'PFRON', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'asystent-osobisty', nazwa: 'Asystent osobisty osoby z niepełnosprawnością (AOON)',
    opis: 'Asystent osobisty osoby z niepełnosprawnością (AOON) to bezpłatna usługa, w ramach której wykwalifikowany asystent pomaga osobie z niepełnosprawnością w codziennym funkcjonowaniu i aktywnym uczestnictwie w życiu społecznym. Program finansowany jest z Funduszu Solidarnościowego i realizowany przez gminy oraz powiaty (budżet edycji 2026 to ok. 1,1 mld PLN). Usługa nie polega na wypłacie pieniędzy, ale na zapewnieniu konkretnej pomocy: wyjście z domu, dojazd na rehabilitację, do lekarza, urzędu, pracy lub na zajęcia, pomoc w zakupach, w załatwianiu spraw urzędowych, w czynnościach dnia codziennego i w nawiązywaniu kontaktów społecznych. Kto się kwalifikuje: dzieci do 16 roku życia z orzeczeniem o niepełnosprawności (ze wskazaniami konieczności stałej opieki) oraz osoby pełnoletnie z orzeczeniem o znacznym lub umiarkowanym stopniu niepełnosprawności (lub orzeczeniem równoważnym). Brak kryterium dochodowego. Liczba godzin wsparcia zależy od stopnia niepełnosprawności i potrzeb (zwykle do kilkuset godzin rocznie). Uczestnik może sam wskazać osobę, która ma być jego asystentem (poza najbliższą rodziną). Wniosek (Karta zgłoszenia) składa się w ośrodku pomocy społecznej (OPS/MOPS) lub w urzędzie gminy/powiatu, który przystąpił do programu w danym roku. Uwaga: nie każda gmina co roku realizuje program, a nabory są ograniczone czasowo i pulą miejsc.',
    kategoria: 'NIEPELNOSPRAWNOSC',
    kwota: 'usługa bezpłatna (do kilkuset godzin wsparcia rocznie)',
    kwotaMin: 0, kwotaMax: 0,
    czestotliwosc: 'rocznie (edycja programu)',
    wymagania: { niepelnosprawnosc: ['umiarkowany', 'znaczny'] },
    wykluczenia: [
      { opis: 'Gmina/powiat nie przystąpił w danym roku do programu AOON lub wyczerpał pulę miejsc', sprawdz: 'gmina_realizuje_aoon' },
    ],
    wniosek: {
      kanal: ['MOPS', 'URZAD_GMINY'], formularz: 'Karta zgłoszenia do programu AOON',
      dokumenty: [
        'Karta zgłoszenia do programu',
        'Orzeczenie o niepełnosprawności (znaczny/umiarkowany stopień lub orzeczenie dla dziecka do 16 lat)',
        'Ewentualne wskazanie osoby asystenta (poza najbliższą rodziną)',
        'Klauzula informacyjna RODO',
      ],
      kroki: [
        'Sprawdź w swoim OPS/MOPS lub urzędzie gminy, czy program AOON jest realizowany w tym roku',
        'Pobierz i wypełnij Kartę zgłoszenia do programu',
        'Dołącz orzeczenie o niepełnosprawności',
        'Możesz wskazać konkretną osobę na asystenta (nie może to być najbliższy członek rodziny)',
        'Po zakwalifikowaniu ustalany jest zakres i liczba godzin wsparcia',
      ],
      terminRealizacji: 'Zależnie od naboru w gminie (zwykle nabór na początku roku)',
      pulapki: [
        'To usługa, nie wypłata pieniędzy, asystent realnie pomaga w codziennych czynnościach',
        'Nie każda gmina realizuje program co roku, sprawdź lokalnie',
        'Asystentem nie może być najbliższy członek rodziny uczestnika',
        'Można łączyć z opieką wytchnieniową, ale nie w tych samych godzinach',
      ],
      odwolanie: 'Brak trybu odwoławczego, usługa zależna od puli miejsc, można zgłosić się w kolejnej edycji',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/asystent-osobisty-osoby-z-niepelnosprawnoscia',
    zrodloNazwa: 'Ministerstwo Rodziny, Pracy i Polityki Społecznej', dataWeryfikacji: '2026-06-03', dataWaznosci: '2026-12-31',
  },
];
