import { Benefit } from '../types';

export const PODATKI: Benefit[] = [
  {
    id: 'ulga-termomodernizacyjna', nazwa: 'Ulga termomodernizacyjna',
    opis: 'Odliczenie od dochodu wydatków na termomodernizację budynku jednorodzinnego, do 53 000 PLN na podatnika (nie na budynek). Obejmuje: ocieplenie ścian, wymianę okien i drzwi, montaż pompy ciepła, paneli fotowoltaicznych, kolektorów słonecznych, wymianę pieca, instalację rekuperacji. TYLKO domy jednorodzinne. Mieszkania w bloku nie kwalifikują się, nawet jeśli masz udział w częściach wspólnych. Limit 53 000 PLN dotyczy podatnika, więc małżonkowie mogą odliczyć łącznie 106 000 PLN. Inwestycja musi być zakończona w ciągu 3 lat od końca roku, w którym poniesiono pierwszy wydatek. Jeśli nie zdążysz, musisz doliczyć odliczone kwoty z powrotem do dochodu. Faktury muszą być wystawione na właściciela budynku. Odliczenie od dochodu, nie od podatku, realna oszczędność to 12-32% wydanej kwoty w zależności od progu podatkowego. Można łączyć z dotacją Czyste Powietrze, ale nie wolno odliczyć tej samej kwoty dwa razy, odliczasz tylko część nieobjętą dotacją.',
    kategoria: 'PODATKI',
    kwota: 'do 53 000 PLN odliczenia', kwotaMax: 53000, czestotliwosc: 'jednorazowo (rozłożenie na 6 lat)',
    wymagania: { wlasnosc: ['dom_jednorodzinny'] },
    wykluczenia: [{ opis: 'Dotyczy TYLKO domów jednorodzinnych, mieszkania w bloku NIE kwalifikują się', sprawdz: 'dom_jednorodzinny' }],
    wniosek: {
      kanal: ['URZAD_SKARBOWY'], formularz: 'PIT/O',
      dokumenty: ['Faktury za materiały i usługi termomodernizacyjne', 'Audyt energetyczny (opcjonalnie)'],
      kroki: [
        'Zbieraj faktury za prace termomodernizacyjne (ocieplenie, wymiana okien, panele fotowoltaiczne, pompa ciepła)',
        'Przy rozliczeniu PIT wypełnij załącznik PIT/O',
        'Wpisz kwotę wydatków (max 53 000 PLN)',
        'Inwestycję musisz zakończyć w ciągu 3 lat od końca roku pierwszego wydatku',
      ],
      terminRealizacji: 'Zwrot przy rozliczeniu PIT',
      pulapki: ['TYLKO domy jednorodzinne, mieszkania w bloku nie kwalifikują się', 'Limit 53 000 PLN na podatnika, nie na budynek', 'Faktura musi być na właściciela domu'],
      odwolanie: 'Korekta PIT',
    },
    zrodloUrl: 'https://www.podatki.gov.pl/pit/ulgi-odliczenia-i-zwolnienia/ulga-termomodernizacyjna/',
    zrodloNazwa: 'Ministerstwo Finansów', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'ulga-rehabilitacyjna', nazwa: 'Ulga rehabilitacyjna',
    opis: 'Odliczenie od dochodu wydatków związanych z rehabilitacją i ułatwieniem wykonywania czynności życiowych osobom z niepełnosprawnością. Przysługuje osobom z orzeczeniem o niepełnosprawności (lekki, umiarkowany lub znaczny stopień) ORAZ osobom utrzymującym takie osoby (np. rodzic dziecka z orzeczeniem, jeśli dochód osoby niepełnosprawnej nie przekroczył 19 061,28 PLN rocznie). Wydatki limitowane: leki przepisane przez lekarza specjalistę, odliczasz nadwyżkę ponad 100 PLN miesięcznie (musisz udowodnić zakup fakturami). Wydatki nielimitowane (odliczasz pełną kwotę): adaptacja mieszkania, sprzęt rehabilitacyjny, przejazdy na zabiegi, turnusy rehabilitacyjne, opłacenie przewodnika (stopień znaczny lub niewidomi), utrzymanie psa asystującego (ryczałt 2820 PLN rocznie bez konieczności dokumentowania). Samochód: osoby z niepełnosprawnością ruchową lub ze znacznym stopniem mogą odliczyć do 2280 PLN rocznie za używanie samochodu na dojazdy na zabiegi. Wydatki muszą być udokumentowane, wyjątkiem jest pies asystujący i opłacenie przewodnika, gdzie wystarczy oświadczenie.',
    kategoria: 'PODATKI',
    kwota: 'odliczenie rzeczywistych wydatków', czestotliwosc: 'rocznie',
    wymagania: { niepelnosprawnosc: ['lekki', 'umiarkowany', 'znaczny'] },
    wykluczenia: [],
    wniosek: {
      kanal: ['URZAD_SKARBOWY'], formularz: 'PIT/O',
      dokumenty: ['Orzeczenie o niepełnosprawności', 'Faktury/rachunki za wydatki rehabilitacyjne'],
      kroki: [
        'Zbieraj dokumenty wydatków: leki (pow. 100 PLN/mies.), sprzęt, transport, turnusy',
        'Przy rozliczeniu PIT wypełnij PIT/O w części dotyczącej ulgi rehabilitacyjnej',
        'Odlicz wydatki od dochodu',
      ],
      terminRealizacji: 'Zwrot przy rozliczeniu PIT',
      pulapki: ['Leki: odliczasz nadwyżkę powyżej 100 PLN miesięcznie', 'Utrzymanie psa asystującego: ryczałt 2820 PLN bez dokumentowania'],
      odwolanie: 'Korekta PIT',
    },
    zrodloUrl: 'https://www.podatki.gov.pl/pit/ulgi-odliczenia-i-zwolnienia/ulga-rehabilitacyjna/',
    zrodloNazwa: 'Ministerstwo Finansów', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'ulga-internetowa', nazwa: 'Ulga na internet',
    opis: 'Odliczenie od dochodu wydatków na internet (stacjonarny lub mobilny) do 760 PLN rocznie. Dotyczy internetu w dowolnej formie: kablowy, światłowodowy, mobilny (LTE/5G), satelitarny. Nie ma wymagań co do prędkości. Faktura musi być wystawiona na podatnika. Można odliczyć wyłącznie w 2 kolejnych następujących po sobie latach podatkowych. Jeśli odliczyłeś w 2024 i 2025, ulga jest wyczerpana na zawsze. Jeśli nigdy nie korzystałeś, możesz zacząć w dowolnym roku. Odliczenie od dochodu (nie od podatku), więc realna oszczędność to ok. 12-32% kwoty w zależności od progu podatkowego. Częsty błąd: ludzie myślą, że mogą odliczać co roku. Nie, maksymalnie 2 kolejne lata i koniec. Nie można też przerwać i wrócić: jeśli odliczyłeś w 2024, musisz kontynuować w 2025 albo tracisz drugi rok.',
    kategoria: 'PODATKI',
    kwota: 'do 760 PLN odliczenia rocznie', kwotaMax: 760, czestotliwosc: 'rocznie (przez 2 lata)',
    wymagania: {},
    wykluczenia: [{ opis: 'Można skorzystać TYLKO w 2 kolejnych latach, jeśli już korzystałeś, ulga jest wyczerpana', sprawdz: 'ulga_internet_lata' }],
    wniosek: {
      kanal: ['URZAD_SKARBOWY'], formularz: 'PIT/O',
      dokumenty: ['Faktury za usługę internetową'],
      kroki: ['Zbieraj faktury za internet przez cały rok', 'Przy rozliczeniu PIT odlicz w PIT/O (max 760 PLN)'],
      terminRealizacji: 'Zwrot przy rozliczeniu PIT',
      pulapki: ['TYLKO 2 kolejne lata podatkowe, potem ulga przepada na zawsze', 'Nie musiałeś używać internetu wcześniej, liczy się pierwszy rok odliczenia'],
      odwolanie: 'Korekta PIT',
    },
    zrodloUrl: 'https://www.podatki.gov.pl/pit/ulgi-odliczenia-i-zwolnienia/ulga-na-internet/',
    zrodloNazwa: 'Ministerstwo Finansów', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'ulga-ikze', nazwa: 'Ulga na IKZE',
    opis: 'Odliczenie od dochodu wpłat na Indywidualne Konto Zabezpieczenia Emerytalnego (IKZE). Limit wpłat w 2026 roku to 9 388,80 PLN (dla osób na umowie o pracę/zleceniu) lub 14 083,20 PLN (dla prowadzących działalność gospodarczą). IKZE można założyć w banku, domu maklerskim, TFI lub towarzystwie ubezpieczeniowym. Odliczenie od dochodu, realna oszczędność to 12-32% wpłaconej kwoty w zależności od progu podatkowego. Przy wypłacie po ukończeniu 65 lat i wpłacaniu przez min. 5 lat, pobierany jest zryczałtowany podatek 10% od całej kwoty. Wcześniejsza wypłata (przed 65 r.ż.) oznacza doliczenie wypłaconej kwoty do dochodu i opodatkowanie według skali, tracisz całą korzyść podatkową. IKZE to nie to samo co IKE. IKE nie daje odliczenia rocznego, ale za to wypłata jest całkowicie wolna od podatku. Można mieć oba jednocześnie. Nie można przenosić środków między IKE a IKZE. Limit zmienia się co roku (jest powiązany z przeciętnym wynagrodzeniem), więc trzeba sprawdzać aktualny.',
    kategoria: 'PODATKI',
    kwota: 'do 9 388,80 PLN odliczenia rocznie (2026)', kwotaMax: 9388, czestotliwosc: 'rocznie',
    wymagania: {},
    wykluczenia: [],
    wniosek: {
      kanal: ['URZAD_SKARBOWY'], formularz: 'PIT/O',
      dokumenty: ['Potwierdzenie wpłat na IKZE z instytucji finansowej'],
      kroki: ['Załóż IKZE w banku, TFI lub u brokera', 'Wpłacaj do limitu rocznego', 'Przy rozliczeniu PIT odlicz w PIT/O'],
      terminRealizacji: 'Zwrot przy rozliczeniu PIT',
      pulapki: ['Limit wpłat zmienia się co roku, sprawdź aktualny', 'Wypłata z IKZE przed 65 r.ż. = podatek 10%'],
      odwolanie: 'Korekta PIT',
    },
    zrodloUrl: 'https://www.podatki.gov.pl/pit/ulgi-odliczenia-i-zwolnienia/',
    zrodloNazwa: 'Ministerstwo Finansów', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'wspolne-rozliczenie', nazwa: 'Wspólne rozliczenie małżonków',
    opis: 'Wspólne rozliczenie podatkowe małżonków pozwala obliczyć podatek od połowy łącznego dochodu obojga małżonków, a następnie pomnożyć go razy dwa. Największa korzyść występuje, gdy jeden małżonek zarabia dużo, a drugi mało lub wcale, pozwala to "ściągnąć" dochód lepiej zarabiającego poniżej progu 120 000 PLN (drugi próg podatkowy 32%). Przykład: mąż zarabia 200 000 PLN, żona 0 PLN. Bez wspólnego rozliczenia mąż płaci 32% od nadwyżki ponad 120 000 PLN. Wspólnie: podstawa to 100 000 PLN na osobę, więc oboje w pierwszym progu (12%). Oszczędność: ok. 16 000 PLN. Warunki: małżeństwo musi trwać przez cały rok podatkowy, obowiązuje wspólność majątkowa. Nie można korzystać, jeśli którykolwiek małżonek rozlicza się ryczałtem od przychodów ewidencjonowanych (z wyjątkiem najmu prywatnego od 2023 r.) lub kartą podatkową. Można złożyć wspólne rozliczenie nawet po śmierci małżonka (jeśli zmarł w trakcie roku podatkowego). Wdowiec/wdowa po śmierci małżonka w roku podatkowym też może rozliczyć się wspólnie za ten rok.',
    kategoria: 'PODATKI',
    kwota: 'oszczędność zależy od różnicy dochodów', czestotliwosc: 'rocznie',
    wymagania: { stanCywilny: ['malzenstwo'] },
    wykluczenia: [{ opis: 'Nie można jeśli którykolwiek małżonek rozlicza się ryczałtem lub kartą podatkową', sprawdz: 'ryczalt_karta' }],
    wniosek: {
      kanal: ['URZAD_SKARBOWY'], formularz: 'PIT-37 lub PIT-36 (wspólne)',
      dokumenty: ['PIT roczny obu małżonków'],
      kroki: ['Przy rozliczeniu PIT zaznacz opcję wspólnego rozliczenia', 'System obliczy podatek od połowy łącznego dochodu x2', 'Korzystne gdy jeden małżonek zarabia dużo więcej niż drugi'],
      terminRealizacji: 'Natychmiast przy rozliczeniu',
      pulapki: ['Oboje musicie mieć wspólność majątkową', 'Nie działa jeśli ktoś rozlicza się ryczałtem'],
      odwolanie: 'Korekta PIT',
    },
    zrodloUrl: 'https://www.podatki.gov.pl/pit/',
    zrodloNazwa: 'Ministerstwo Finansów', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'ulga-dla-mlodych', nazwa: 'Ulga dla młodych (PIT-0)',
    opis: 'Zwolnienie z podatku dochodowego PIT dla osób do 26. roku życia: przychody do 85 528 PLN rocznie są całkowicie wolne od podatku. Dotyczy wyłącznie przychodów z: umowy o pracę, umowy zlecenia, praktyk absolwenckich i stażu uczniowskiego. NIE dotyczy: umów o dzieło, działalności gospodarczej, kontraktów B2B, przychodów z najmu, ze sprzedaży nieruchomości, z praw autorskich (poza tymi w ramach stosunku pracy). Ulga działa automatycznie, pracodawca nie pobiera zaliczek na PIT. Jeśli pracodawca mimo to pobrał zaliczkę (np. nie wiedział o uldze), odzyskasz ją przy rozliczeniu rocznym. Ulga kończy się w dniu 26. urodzin, nie z końcem roku, przychody uzyskane po urodzinach są już opodatkowane. Jeśli zarabiasz więcej niż 85 528 PLN rocznie, nadwyżka jest opodatkowana na zasadach ogólnych (12%, potem 32%). Ulga nie zwalnia ze składek ZUS, składki zdrowotna i społeczne są pobierane normalnie. Częsty błąd: studenci na umowie o dzieło myślą, że mają PIT-0. Nie mają, umowa o dzieło nie kwalifikuje się.',
    kategoria: 'PODATKI',
    kwota: 'zwolnienie z PIT do 85 528 PLN rocznie', kwotaMax: 85528, czestotliwosc: 'rocznie',
    wymagania: { wiekMax: 26 },
    wykluczenia: [{ opis: 'Dotyczy tylko przychodów z umowy o pracę, zlecenia i praktyk', sprawdz: 'rodzaj_umowy_mlody' }],
    wniosek: {
      kanal: ['URZAD_SKARBOWY'],
      dokumenty: ['Brak dodatkowych, ulga stosowana automatycznie'],
      kroki: ['Ulga działa automatycznie, pracodawca nie pobiera zaliczki na PIT', 'Jeśli pracodawca pobrał zaliczkę, odzyskasz ją przy rozliczeniu rocznym'],
      terminRealizacji: 'Automatycznie',
      pulapki: ['Nie dotyczy działalności gospodarczej', 'Nie dotyczy umów o dzieło', 'Po 26 urodzinach, ulga kończy się w dniu urodzin'],
      odwolanie: 'Nie dotyczy',
    },
    zrodloUrl: 'https://www.podatki.gov.pl/pit/ulgi-odliczenia-i-zwolnienia/ulga-dla-mlodych/',
    zrodloNazwa: 'Ministerstwo Finansów', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'opp-1-5-procent', nazwa: '1,5% podatku na OPP',
    opis: 'Możliwość przekazania 1,5% zapłaconego podatku dochodowego na wybraną Organizację Pożytku Publicznego (OPP). To NIE jest darowizna i NIE kosztuje podatnika ani złotówki. To część podatku, którą i tak płacisz, ale możesz zdecydować, dokąd trafi. Jeśli nie wskażesz OPP, ta kwota zostaje w budżecie państwa. Wystarczy wpisać numer KRS organizacji w odpowiedniej rubryce PIT-u rocznego. Listę organizacji ze statusem OPP znajdziesz na stronie niw.gov.pl. Możesz też wskazać cel szczegółowy (np. konkretne dziecko w fundacji). Kwota przekazywana jest proporcjonalna do zapłaconego podatku, jeśli Twój podatek wyniósł 10 000 PLN, OPP dostanie 150 PLN. Jeśli korzystasz z ulgi dla młodych i Twój podatek wynosi 0 PLN, nie masz czego przekazać. Korzystanie z Twój e-PIT (automatycznego rozliczenia PIT przez urząd) zachowuje wybór OPP z poprzedniego roku. Jeśli chcesz zmienić organizację, musisz to zrobić aktywnie.',
    kategoria: 'PODATKI',
    kwota: '1,5% zapłaconego podatku', czestotliwosc: 'rocznie',
    wymagania: {},
    wykluczenia: [],
    wniosek: {
      kanal: ['URZAD_SKARBOWY'], formularz: 'PIT roczny (rubryka OPP)',
      dokumenty: ['Numer KRS wybranej organizacji pożytku publicznego'],
      kroki: ['Przy rozliczeniu PIT wpisz numer KRS wybranej OPP', 'Urząd Skarbowy przekaże 1,5% Twojego podatku na tę organizację'],
      terminRealizacji: 'Automatycznie po rozliczeniu PIT',
      pulapki: ['To nie jest darowizna, to podatek który i tak płacisz, tylko kierujesz go na OPP', 'Jeśli nie wpiszesz KRS, pieniądze idą do budżetu ogólnego'],
      odwolanie: 'Korekta PIT',
    },
    zrodloUrl: 'https://www.podatki.gov.pl/pit/1-5-procent/',
    zrodloNazwa: 'Ministerstwo Finansów', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'ip-box', nazwa: 'IP Box (5% podatku od własności intelektualnej)',
    opis: 'Preferencyjna stawka 5% podatku dochodowego od dochodów uzyskanych z kwalifikowanych praw własności intelektualnej (IP). Zamiast standardowych 12%/32% (skala) lub 19% (liniowy), płacisz tylko 5%. Kwalifikowane IP to m.in.: patenty, prawa ochronne na wzory użytkowe, autorskie prawa majątkowe do programów komputerowych, prawa z rejestracji topografii układów scalonych, prawa z rejestracji produktów leczniczych. Najczęściej korzystają programiści na B2B, prawo autorskie do kodu kwalifikuje się jako IP. Warunki: musisz prowadzić działalność gospodarczą, musisz prowadzić prace badawczo-rozwojowe (B+R) związane z wytworzeniem lub ulepszeniem IP, musisz prowadzić odrębną ewidencję przychodów i kosztów dla każdego kwalifikowanego IP od początku roku (nie można zacząć w trakcie roku wstecz). Dochód z IP oblicza się według wzoru nexus, uwzględnia proporcję kosztów B+R poniesionych bezpośrednio przez podatnika do kosztów ogółem. Jeśli 100% pracy wykonujesz sam (bez podwykonawców), nexus wynosi 1.0 i cały dochód kwalifikuje się. Bez właściwej ewidencji urząd skarbowy zakwestionuje ulgę przy kontroli. IP Box można łączyć z ulgą B+R, ale nie do tego samego dochodu.',
    kategoria: 'PODATKI',
    kwota: 'stawka 5% zamiast 12/19/32%', czestotliwosc: 'rocznie',
    wymagania: { prowadzDzialalnosc: true },
    wykluczenia: [{ opis: 'Wymaga prowadzenia ewidencji IP i prac B+R', sprawdz: 'ewidencja_ip' }],
    wniosek: {
      kanal: ['URZAD_SKARBOWY'], formularz: 'PIT/IP (załącznik do PIT-36 lub PIT-36L)',
      dokumenty: ['Ewidencja prac badawczo-rozwojowych', 'Dokumentacja kwalifikowanego IP'],
      kroki: [
        'Prowadź odrębną ewidencję przychodów i kosztów związanych z IP',
        'Przy rozliczeniu PIT wypełnij załącznik PIT/IP',
        'Zastosuj stawkę 5% do dochodu z kwalifikowanego IP',
      ],
      terminRealizacji: 'Przy rozliczeniu rocznym PIT',
      pulapki: ['Wymaga prowadzenia szczegółowej ewidencji, bez niej US może zakwestionować', 'Dotyczy patentów, praw autorskich do programów komputerowych, wzorów użytkowych'],
      odwolanie: 'Odwołanie od decyzji US',
    },
    zrodloUrl: 'https://www.podatki.gov.pl/pit/ulgi-odliczenia-i-zwolnienia/ip-box/',
    zrodloNazwa: 'Ministerstwo Finansów', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
];
