import { Benefit } from '../types';

export const PODATKI: Benefit[] = [
  {
    id: 'ulga-termomodernizacyjna', nazwa: 'Ulga termomodernizacyjna', kategoria: 'PODATKI',
    kwota: 'do 53 000 PLN odliczenia', kwotaMax: 53000, czestotliwosc: 'jednorazowo (rozłożenie na 6 lat)',
    wymagania: { wlasnosc: ['dom_jednorodzinny'] },
    wykluczenia: [{ opis: 'Dotyczy TYLKO domów jednorodzinnych, mieszkania w bloku NIE kwalifikują się', sprawdz: 'dom_jednorodzinny' }],
    wniosek: {
      kanal: ['URZAD_SKARBOWY'], formularz: 'PIT/O',
      dokumenty: ['Faktury za materiały i usługi termomodernizacyjne', 'Audyt energetyczny (opcjonalnie)'],
      kroki: [
        'Zbieraj faktury za prace termomodernizacyjne (ocieplenie, wymiana okien, panele fotowoltaiczne, pompa ciepła)',
        'Przy rozliczeniu PIT wypełnij załącznik PIT/O',
        'Wpisz kwotę wydatków (max 53 000 PLN)',
        'Inwestycję musisz zakończyć w ciągu 3 lat od końca roku pierwszego wydatku',
      ],
      terminRealizacji: 'Zwrot przy rozliczeniu PIT',
      pulapki: ['TYLKO domy jednorodzinne, mieszkania w bloku nie kwalifikują się', 'Limit 53 000 PLN na podatnika, nie na budynek', 'Faktura musi być na właściciela domu'],
      odwolanie: 'Korekta PIT',
    },
    zrodloUrl: 'https://www.podatki.gov.pl/pit/ulgi-odliczenia-i-zwolnienia/ulga-termomodernizacyjna/',
    zrodloNazwa: 'Ministerstwo Finansów', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'ulga-rehabilitacyjna', nazwa: 'Ulga rehabilitacyjna', kategoria: 'PODATKI',
    kwota: 'odliczenie rzeczywistych wydatków', czestotliwosc: 'rocznie',
    wymagania: { niepelnosprawnosc: ['lekki', 'umiarkowany', 'znaczny'] },
    wykluczenia: [],
    wniosek: {
      kanal: ['URZAD_SKARBOWY'], formularz: 'PIT/O',
      dokumenty: ['Orzeczenie o niepełnosprawności', 'Faktury/rachunki za wydatki rehabilitacyjne'],
      kroki: [
        'Zbieraj dokumenty wydatków: leki (pow. 100 PLN/mies.), sprzęt, transport, turnusy',
        'Przy rozliczeniu PIT wypełnij PIT/O w części dotyczącej ulgi rehabilitacyjnej',
        'Odlicz wydatki od dochodu',
      ],
      terminRealizacji: 'Zwrot przy rozliczeniu PIT',
      pulapki: ['Leki: odliczasz nadwyżkę powyżej 100 PLN miesięcznie', 'Utrzymanie psa asystującego: ryczałt 2820 PLN bez dokumentowania'],
      odwolanie: 'Korekta PIT',
    },
    zrodloUrl: 'https://www.podatki.gov.pl/pit/ulgi-odliczenia-i-zwolnienia/ulga-rehabilitacyjna/',
    zrodloNazwa: 'Ministerstwo Finansów', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'ulga-internetowa', nazwa: 'Ulga na internet', kategoria: 'PODATKI',
    kwota: 'do 760 PLN odliczenia rocznie', kwotaMax: 760, czestotliwosc: 'rocznie (przez 2 lata)',
    wymagania: {},
    wykluczenia: [{ opis: 'Można skorzystać TYLKO w 2 kolejnych latach, jeśli już korzystałeś, ulga jest wyczerpana', sprawdz: 'ulga_internet_lata' }],
    wniosek: {
      kanal: ['URZAD_SKARBOWY'], formularz: 'PIT/O',
      dokumenty: ['Faktury za usługę internetową'],
      kroki: ['Zbieraj faktury za internet przez cały rok', 'Przy rozliczeniu PIT odlicz w PIT/O (max 760 PLN)'],
      terminRealizacji: 'Zwrot przy rozliczeniu PIT',
      pulapki: ['TYLKO 2 kolejne lata podatkowe, potem ulga przepada na zawsze', 'Nie musiałeś używać internetu wcześniej, liczy się pierwszy rok odliczenia'],
      odwolanie: 'Korekta PIT',
    },
    zrodloUrl: 'https://www.podatki.gov.pl/pit/ulgi-odliczenia-i-zwolnienia/ulga-na-internet/',
    zrodloNazwa: 'Ministerstwo Finansów', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'ulga-ikze', nazwa: 'Ulga na IKZE', kategoria: 'PODATKI',
    kwota: 'do 9 388,80 PLN odliczenia rocznie (2026)', kwotaMax: 9388, czestotliwosc: 'rocznie',
    wymagania: {},
    wykluczenia: [],
    wniosek: {
      kanal: ['URZAD_SKARBOWY'], formularz: 'PIT/O',
      dokumenty: ['Potwierdzenie wpłat na IKZE z instytucji finansowej'],
      kroki: ['Załóż IKZE w banku, TFI lub u brokera', 'Wpłacaj do limitu rocznego', 'Przy rozliczeniu PIT odlicz w PIT/O'],
      terminRealizacji: 'Zwrot przy rozliczeniu PIT',
      pulapki: ['Limit wpłat zmienia się co roku, sprawdź aktualny', 'Wypłata z IKZE przed 65 r.ż. = podatek 10%'],
      odwolanie: 'Korekta PIT',
    },
    zrodloUrl: 'https://www.podatki.gov.pl/pit/ulgi-odliczenia-i-zwolnienia/',
    zrodloNazwa: 'Ministerstwo Finansów', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'wspolne-rozliczenie', nazwa: 'Wspólne rozliczenie małżonków', kategoria: 'PODATKI',
    kwota: 'oszczędność zależy od różnicy dochodów', czestotliwosc: 'rocznie',
    wymagania: { stanCywilny: ['malzenstwo'] },
    wykluczenia: [{ opis: 'Nie można jeśli którykolwiek małżonek rozlicza się ryczałtem lub kartą podatkową', sprawdz: 'ryczalt_karta' }],
    wniosek: {
      kanal: ['URZAD_SKARBOWY'], formularz: 'PIT-37 lub PIT-36 (wspólne)',
      dokumenty: ['PIT roczny obu małżonków'],
      kroki: ['Przy rozliczeniu PIT zaznacz opcję wspólnego rozliczenia', 'System obliczy podatek od połowy łącznego dochodu x2', 'Korzystne gdy jeden małżonek zarabia dużo więcej niż drugi'],
      terminRealizacji: 'Natychmiast przy rozliczeniu',
      pulapki: ['Oboje musicie mieć wspólność majątkową', 'Nie działa jeśli ktoś rozlicza się ryczałtem'],
      odwolanie: 'Korekta PIT',
    },
    zrodloUrl: 'https://www.podatki.gov.pl/pit/',
    zrodloNazwa: 'Ministerstwo Finansów', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'ulga-dla-mlodych', nazwa: 'Ulga dla młodych (PIT-0)', kategoria: 'PODATKI',
    kwota: 'zwolnienie z PIT do 85 528 PLN rocznie', kwotaMax: 85528, czestotliwosc: 'rocznie',
    wymagania: { wiekMax: 26 },
    wykluczenia: [{ opis: 'Dotyczy tylko przychodów z umowy o pracę, zlecenia i praktyk', sprawdz: 'rodzaj_umowy_mlody' }],
    wniosek: {
      kanal: ['URZAD_SKARBOWY'],
      dokumenty: ['Brak dodatkowych, ulga stosowana automatycznie'],
      kroki: ['Ulga działa automatycznie, pracodawca nie pobiera zaliczki na PIT', 'Jeśli pracodawca pobrał zaliczkę, odzyskasz ją przy rozliczeniu rocznym'],
      terminRealizacji: 'Automatycznie',
      pulapki: ['Nie dotyczy działalności gospodarczej', 'Nie dotyczy umów o dzieło', 'Po 26 urodzinach, ulga kończy się w dniu urodzin'],
      odwolanie: 'Nie dotyczy',
    },
    zrodloUrl: 'https://www.podatki.gov.pl/pit/ulgi-odliczenia-i-zwolnienia/ulga-dla-mlodych/',
    zrodloNazwa: 'Ministerstwo Finansów', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'opp-1-5-procent', nazwa: '1,5% podatku na OPP', kategoria: 'PODATKI',
    kwota: '1,5% zapłaconego podatku', czestotliwosc: 'rocznie',
    wymagania: {},
    wykluczenia: [],
    wniosek: {
      kanal: ['URZAD_SKARBOWY'], formularz: 'PIT roczny (rubryka OPP)',
      dokumenty: ['Numer KRS wybranej organizacji pożytku publicznego'],
      kroki: ['Przy rozliczeniu PIT wpisz numer KRS wybranej OPP', 'Urząd Skarbowy przekaże 1,5% Twojego podatku na tę organizację'],
      terminRealizacji: 'Automatycznie po rozliczeniu PIT',
      pulapki: ['To nie jest darowizna, to podatek który i tak płacisz, tylko kierujesz go na OPP', 'Jeśli nie wpiszesz KRS, pieniądze idą do budżetu ogólnego'],
      odwolanie: 'Korekta PIT',
    },
    zrodloUrl: 'https://www.podatki.gov.pl/pit/1-5-procent/',
    zrodloNazwa: 'Ministerstwo Finansów', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'ip-box', nazwa: 'IP Box (5% podatku od własności intelektualnej)', kategoria: 'PODATKI',
    kwota: 'stawka 5% zamiast 12/19/32%', czestotliwosc: 'rocznie',
    wymagania: { prowadzDzialalnosc: true },
    wykluczenia: [{ opis: 'Wymaga prowadzenia ewidencji IP i prac B+R', sprawdz: 'ewidencja_ip' }],
    wniosek: {
      kanal: ['URZAD_SKARBOWY'], formularz: 'PIT/IP (załącznik do PIT-36 lub PIT-36L)',
      dokumenty: ['Ewidencja prac badawczo-rozwojowych', 'Dokumentacja kwalifikowanego IP'],
      kroki: [
        'Prowadź odrębną ewidencję przychodów i kosztów związanych z IP',
        'Przy rozliczeniu PIT wypełnij załącznik PIT/IP',
        'Zastosuj stawkę 5% do dochodu z kwalifikowanego IP',
      ],
      terminRealizacji: 'Przy rozliczeniu rocznym PIT',
      pulapki: ['Wymaga prowadzenia szczegółowej ewidencji, bez niej US może zakwestionować', 'Dotyczy patentów, praw autorskich do programów komputerowych, wzorów użytkowych'],
      odwolanie: 'Odwołanie od decyzji US',
    },
    zrodloUrl: 'https://www.podatki.gov.pl/pit/ulgi-odliczenia-i-zwolnienia/ip-box/',
    zrodloNazwa: 'Ministerstwo Finansów', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
];
