import { Benefit } from '../types';

export const POMOC_SPOLECZNA: Benefit[] = [
  {
    id: 'karta-duzej-rodziny', nazwa: 'Karta Dużej Rodziny', kategoria: 'POMOC_SPOLECZNA',
    kwota: 'zniżki 37-49% na kolej, darmowy wstęp do Parków Narodowych, rabaty w sieciach handlowych',
    kwotaMin: 0, kwotaMax: 0,
    czestotliwosc: 'ciągłe (dożywotnia dla rodziców)',
    wymagania: { dzieci: { min: 3 } },
    wykluczenia: [],
    wniosek: {
      kanal: ['URZAD_GMINY', 'EMPATIA', 'ONLINE'], formularz: 'Wniosek o przyznanie KDR',
      dokumenty: [
        'Dowody osobiste rodziców',
        'Akty urodzenia dzieci',
        'PESEL wszystkich członków rodziny',
        'Oświadczenie o władzy rodzicielskiej (dla rodziców)',
        'Zaświadczenie ze szkoły/uczelni (dla dzieci 18-25 lat)',
      ],
      kroki: [
        'Złóż wniosek w urzędzie gminy lub elektronicznie przez portal Empatia (empatia.mpips.gov.pl)',
        'Wypełnij formularz dla każdego członka rodziny',
        'Dołącz wymagane dokumenty',
        'Karta zostanie wydana w ciągu 30 dni -- bezpłatnie',
        'Możesz wybrać kartę tradycyjną (plastikową) lub elektroniczną w aplikacji mObywatel',
      ],
      terminRealizacji: 'Do 30 dni od złożenia wniosku',
      pulapki: [
        'DOŻYWOTNIA dla rodziców -- nawet jeśli dzieci są już dorosłe',
        'Dla dzieci: ważna do 18 r.ż. lub do 25 r.ż. jeśli uczą się',
        'Dzieci z niepełnosprawnością -- karta bezterminowa',
        '37% zniżki na bilety kolejowe jednorazowe, 49% na miesięczne',
        'Darmowy wstęp do 23 Parków Narodowych',
        'Zniżki w: Kaufland, Lidl, Spar, Deichmann, CCC i setkach innych',
        'Od 2026: osoby bezrobotne z KDR mają prawo do zasiłku przez 365 dni (zamiast 180)',
        'Od 2026: pierwszeństwo w skierowaniu na szkolenia i kursy PUP',
        'Karta BEZPŁATNA -- nie trzeba nic płacić',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/karta-duzej-rodziny-ogolne',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'zasilek-staly-mops', nazwa: 'Zasiłek stały (MOPS)', kategoria: 'POMOC_SPOLECZNA',
    kwota: '100-1229 PLN miesięcznie', kwotaMin: 100, kwotaMax: 1229,
    czestotliwosc: 'miesięcznie',
    wymagania: { niepelnosprawnosc: ['umiarkowany', 'znaczny'] },
    wykluczenia: [
      { opis: 'Dochód przekracza 130% kryterium dochodowego (1313 PLN dla osoby samotnej, 1069,90 PLN/os. w rodzinie)', sprawdz: 'dochod_mops' },
    ],
    wniosek: {
      kanal: ['MOPS'],
      dokumenty: [
        'Dowód osobisty',
        'Orzeczenie o niepełnosprawności (znaczny lub umiarkowany stopień) lub decyzja o rencie',
        'Zaświadczenie o dochodach z ostatnich 3 miesięcy',
        'Dowody opłat za mieszkanie (czynsz, media)',
        'Inne dokumenty dotyczące sytuacji życiowej',
      ],
      kroki: [
        'Udaj się do MOPS/GOPS w swojej gminie',
        'Złóż wniosek o zasiłek stały',
        'Pracownik socjalny przeprowadzi wywiad środowiskowy w Twoim domu (14 dni)',
        'MOPS obliczy zasiłek: kryterium dochodowe x 130% minus Twój dochód',
        'Decyzja w ciągu 30 dni od wywiadu',
      ],
      terminRealizacji: '30 dni od przeprowadzenia wywiadu środowiskowego',
      pulapki: [
        'Kryterium dochodowe 2025/2026: 1010 PLN (osoba samotna), 823 PLN (osoba w rodzinie)',
        'Zasiłek = 130% kryterium minus dochód. Dla osoby samotnej: max 1313 - dochód',
        'Minimum 100 PLN, maximum 1229 PLN',
        'Przysługuje osobom niezdolnym do pracy z powodu niepełnosprawności lub wieku',
        'Osoba samotna bez dochodu z orzeczeniem znacznym otrzyma 1229 PLN',
        'Można łączyć z zasiłkiem pielęgnacyjnym (215,84 PLN)',
        'Wywiad środowiskowy jest OBOWIĄZKOWY -- pracownik odwiedzi Cię w domu',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/zasilek-staly',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'zasilek-okresowy-mops', nazwa: 'Zasiłek okresowy (MOPS)', kategoria: 'POMOC_SPOLECZNA',
    kwota: 'min. 20 PLN -- max zależny od różnicy kryterium i dochodu',
    kwotaMin: 20, kwotaMax: 1010,
    czestotliwosc: 'miesięcznie (na czas określony)',
    wymagania: {},
    wykluczenia: [
      { opis: 'Dochód przekracza kryterium dochodowe (1010 PLN samotna, 823 PLN/os. w rodzinie)', sprawdz: 'dochod_mops' },
    ],
    wniosek: {
      kanal: ['MOPS'],
      dokumenty: [
        'Dowód osobisty',
        'Zaświadczenie o dochodach z ostatnich 3 miesięcy',
        'Dokumenty potwierdzające sytuację (np. zaświadczenie lekarskie, wypowiedzenie z pracy)',
        'Dowody opłat za mieszkanie',
      ],
      kroki: [
        'Udaj się do MOPS/GOPS w swojej gminie',
        'Złóż wniosek o zasiłek okresowy, podaj przyczynę (choroba, bezrobocie, niepełnosprawność)',
        'Pracownik socjalny przeprowadzi wywiad środowiskowy',
        'MOPS wyda decyzję o przyznaniu zasiłku na czas określony',
        'Zasiłek wypłacany co miesiąc do czasu poprawy sytuacji',
      ],
      terminRealizacji: '30 dni od przeprowadzenia wywiadu środowiskowego',
      pulapki: [
        'Przyznawany z powodu: długotrwałej choroby, niepełnosprawności, bezrobocia, wielodzietności',
        'Kwota = kryterium dochodowe minus dochód, ale nie mniej niż 50% tej różnicy',
        'Minimum 20 PLN miesięcznie',
        'Przyznawany na czas określony -- trzeba odnawiać',
        'Kryterium dochodowe: 1010 PLN (osoba samotna), 823 PLN (na osobę w rodzinie)',
        'Wymaga wywiadu środowiskowego',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/zasilek-okresowy',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'zasilek-celowy-mops', nazwa: 'Zasiłek celowy (MOPS)', kategoria: 'POMOC_SPOLECZNA',
    kwota: 'kwota ustalana indywidualnie (zwykle 100-1000 PLN)',
    kwotaMin: 100, kwotaMax: 1000,
    czestotliwosc: 'jednorazowo lub doraźnie',
    wymagania: {},
    wykluczenia: [
      { opis: 'Dochód przekracza kryterium dochodowe (1010 PLN samotna, 823 PLN/os. w rodzinie)', sprawdz: 'dochod_mops' },
    ],
    wniosek: {
      kanal: ['MOPS'],
      dokumenty: [
        'Dowód osobisty',
        'Zaświadczenie o dochodach',
        'Dokumenty uzasadniające cel zasiłku (rachunki, faktury, zaświadczenia)',
      ],
      kroki: [
        'Udaj się do MOPS/GOPS i opisz swoją sytuację',
        'Wskaż konkretny cel: żywność, leki, opał, odzież, remont, pogrzeb',
        'Pracownik socjalny przeprowadzi wywiad środowiskowy',
        'MOPS wyda decyzję o przyznaniu zasiłku na wskazany cel',
        'Otrzymasz środki lub MOPS opłaci rachunek bezpośrednio',
      ],
      terminRealizacji: '30 dni od przeprowadzenia wywiadu, w nagłych wypadkach -- ekspresowo',
      pulapki: [
        'Zasiłek NA KONKRETNY CEL: żywność, leki, opał, odzież, remont, pogrzeb, przedmioty użytku domowego',
        'Kryterium dochodowe: 1010 PLN (samotna), 823 PLN/os. (rodzina)',
        'W szczególnych przypadkach (klęska żywiołowa, pożar) -- zasiłek celowy specjalny BEZ kryterium dochodowego',
        'Kwota ustalana indywidualnie -- zależy od sytuacji i budżetu MOPS',
        'Można przyznać wielokrotnie w roku, ale nie jest to gwarantowane',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/zasilki-celowe',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'zasilek-celowy-specjalny', nazwa: 'Specjalny zasiłek celowy (MOPS)', kategoria: 'POMOC_SPOLECZNA',
    kwota: 'do wysokości kryterium dochodowego (do 1010 PLN osoba samotna, do 823 PLN/os. w rodzinie)',
    kwotaMax: 1010,
    czestotliwosc: 'jednorazowo (w szczególnie uzasadnionych przypadkach)',
    wymagania: {},
    wykluczenia: [],
    wniosek: {
      kanal: ['MOPS'],
      dokumenty: [
        'Dowód osobisty',
        'Zaświadczenie o dochodach',
        'Dokumenty potwierdzające szczególną sytuację (np. zaświadczenie lekarskie, protokół zdarzenia losowego, rachunki)',
      ],
      kroki: [
        'Zgłoś się do MOPS/GOPS w gminie zamieszkania',
        'Złóż wniosek o specjalny zasiłek celowy, opisując szczególne okoliczności',
        'Pracownik socjalny przeprowadzi wywiad środowiskowy w ciągu 14 dni',
        'MOPS oceni, czy sytuacja kwalifikuje się jako szczególnie uzasadniona i wyda decyzję',
      ],
      terminRealizacji: '30 dni od przeprowadzenia wywiadu środowiskowego',
      pulapki: [
        'Przysługuje osobom z dochodem POWYŻEJ kryterium dochodowego -- w odróżnieniu od zwykłego zasiłku celowego',
        'Decyzja jest uznaniowa -- MOPS ocenia indywidualnie każdy przypadek',
        'Nie podlega zwrotowi (w odróżnieniu od zasiłku celowego przyznanego pod warunkiem zwrotu)',
        'Kwota nie może przekroczyć kryterium dochodowego osoby samotnej (1010 PLN) lub na osobę w rodzinie (823 PLN)',
        'Nie trzeba spełniać kryterium dochodowego -- to świadczenie dla osób w wyjątkowej sytuacji życiowej',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni od doręczenia decyzji',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/zasilki-celowe',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'schronienie-posilek-ubranie', nazwa: 'Schronienie, posiłek, ubranie (MOPS)', kategoria: 'POMOC_SPOLECZNA',
    kwota: 'bezpłatne (świadczenie niepieniężne)',
    kwotaMin: 0, kwotaMax: 0,
    czestotliwosc: 'doraźnie lub ciągłe',
    wymagania: {},
    wykluczenia: [],
    wniosek: {
      kanal: ['MOPS'],
      dokumenty: [
        'Dowód osobisty (jeśli posiadasz)',
        'W nagłych przypadkach -- można bez dokumentów',
      ],
      kroki: [
        'Zgłoś się do MOPS/GOPS lub bezpośrednio do noclegowni/schroniska',
        'Schronienie: noclegownia, ogrzewalnia, schronisko nie wymagają wywiadu środowiskowego ani decyzji administracyjnej',
        'Posiłek: MOPS przydziela gorący posiłek decyzją administracyjną',
        'Ubranie: MOPS zapewnia bieliznę, odzież i obuwie stosowne do pory roku',
        'W nagłych wypadkach -- pomoc natychmiastowa bez formalności',
      ],
      terminRealizacji: 'Natychmiast w nagłych wypadkach, do 30 dni w trybie standardowym',
      pulapki: [
        'To OBOWIĄZKOWE zadanie gminy -- nie może odmówić osobie potrzebującej',
        'Schronienie w noclegowni/ogrzewalni -- BEZ wywiadu środowiskowego i BEZ decyzji administracyjnej',
        'Koszty schronienia w noclegowni/ogrzewalni NIE podlegają zwrotowi',
        'Schronisko (wyższy standard) -- wymaga decyzji, koszty mogą być zwrotne',
        'Posiłek dla dzieci w szkole -- realizowany w ramach programu Posiłek w Szkole i w Domu',
        'Brak kryterium dochodowego dla noclegowni i ogrzewalni',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni (jeśli wydano decyzję)',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/pomoc-spoleczna',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'posilek-w-szkole-i-w-domu', nazwa: 'Program Posiłek w Szkole i w Domu', kategoria: 'POMOC_SPOLECZNA',
    kwota: 'bezpłatne posiłki (wartość ok. 200-400 PLN/mies.)',
    kwotaMin: 0, kwotaMax: 0,
    czestotliwosc: 'codziennie w dni szkolne',
    wymagania: { dzieci: { min: 1, wiekMax: 18 } },
    wykluczenia: [
      { opis: 'Dochód przekracza 200% kryterium dochodowego (1646 PLN/os. w rodzinie)', sprawdz: 'dochod_posilek' },
    ],
    wniosek: {
      kanal: ['MOPS'],
      dokumenty: [
        'Dowód osobisty rodzica/opiekuna',
        'Zaświadczenie o dochodach rodziny',
        'Zaświadczenie ze szkoły dziecka',
        'PESEL dziecka',
      ],
      kroki: [
        'Złóż wniosek o pomoc w formie posiłku w MOPS/GOPS',
        'Pracownik socjalny przeprowadzi wywiad środowiskowy',
        'MOPS wyda decyzję o przyznaniu bezpłatnych posiłków',
        'Szkoła zostanie poinformowana -- dziecko otrzyma posiłki w stołówce',
        'Dotyczy też dorosłych (seniorzy, osoby bezdomne) -- bezpłatne posiłki',
      ],
      terminRealizacji: '30 dni od złożenia wniosku',
      pulapki: [
        'Program rządowy na lata 2024-2028 -- budżet: 1,1 mld PLN rocznie',
        'Bezpłatne posiłki jeśli dochód do 200% kryterium (1646 PLN/os. w rodzinie)',
        'Dochód 200-250% kryterium (1646-2057,50 PLN) -- posiłki z 50% odpłatnością',
        'Dotyczy: dzieci w przedszkolach i szkołach, seniorów, osób dorosłych w trudnej sytuacji',
        'Osoby samotne: kryterium 2020 PLN (200% z 1010 PLN)',
        'Program obejmuje też dofinansowanie stołówek szkolnych (do 80 000 PLN na szkołę)',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/posilek-w-szkole-i-w-domu',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-10', dataWaznosci: '2028-12-31',
  },
  {
    id: 'stypendium-sportowe-gminne', nazwa: 'Stypendium sportowe gminne', kategoria: 'POMOC_SPOLECZNA',
    kwota: '200-400 PLN miesięcznie (zależnie od gminy i osiągnięć)',
    kwotaMin: 200, kwotaMax: 400,
    czestotliwosc: 'miesięcznie (zwykle 10 miesięcy)',
    wymagania: { wiekMax: 21 },
    wykluczenia: [],
    wniosek: {
      kanal: ['URZAD_GMINY'],
      dokumenty: [
        'Wniosek o stypendium sportowe (formularz gminy)',
        'Potwierdzenie zameldowania na terenie gminy',
        'Dokumenty potwierdzające osiągnięcia sportowe (dyplomy, wyniki zawodów)',
        'Zaświadczenie z klubu sportowego',
        'Zgoda rodzica (dla nieletnich)',
      ],
      kroki: [
        'Sprawdź uchwałę swojej rady gminy o zasadach przyznawania stypendiów sportowych',
        'Przygotuj dokumentację potwierdzającą wyniki sportowe (medale, rankingi)',
        'Złóż wniosek w urzędzie gminy -- zwykle do 30 stycznia na dany rok',
        'Komisja oceni osiągnięcia i przyzna stypendium',
        'Wypłata co miesiąc przez okres ustalony w uchwale (zwykle 10 miesięcy)',
      ],
      terminRealizacji: 'Zależy od gminy -- zwykle 30-60 dni od terminu naboru',
      pulapki: [
        'Każda gmina ma WŁASNE zasady -- kwoty i kryteria różnią się radykalnie',
        'Zwykle wymóg zameldowania na terenie gminy',
        'Wiek do 21 lat (niektóre gminy mają inny limit)',
        'Trzeba wykazać osiągnięcia: medale na zawodach, powołanie do kadry, rankingi',
        'Termin naboru wniosków -- zwykle styczeń, ale sprawdź w swojej gminie',
        'Stypendium może być opodatkowane (zwolnienie do 3800 PLN rocznie)',
      ],
      odwolanie: 'Zależy od gminy -- zazwyczaj brak trybu odwoławczego (uznaniowe)',
    },
    zrodloUrl: 'https://www.gov.pl/web/sport/stypendia-son-dsw',
    zrodloNazwa: 'Ministerstwo Sportu', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
];
