import { Benefit } from '../types';

export const RODZINA: Benefit[] = [
  {
    id: '800-plus', nazwa: 'Świadczenie wychowawcze 800+', kategoria: 'RODZINA',
    kwota: '800 PLN miesięcznie na dziecko', kwotaMin: 800, kwotaMax: 800,
    czestotliwosc: 'miesięcznie',
    wymagania: { dzieci: { min: 1, wiekMax: 18 } },
    wykluczenia: [],
    wniosek: {
      kanal: ['PUE_ZUS', 'BANK', 'EMPATIA'], formularz: 'SW-1',
      dokumenty: ['PESEL dziecka', 'Numer konta bankowego'],
      kroki: [
        'Zaloguj się na PUE ZUS, bankowość elektroniczną lub portal Empatia',
        'Wypełnij wniosek SW-1 (świadczenie wychowawcze)',
        'Podaj PESEL dziecka/dzieci i numer konta',
        'Wyślij wniosek elektronicznie',
        'ZUS wyda decyzję w ciągu 30 dni -- pieniądze przyjdą na konto',
      ],
      terminRealizacji: '30 dni od złożenia wniosku',
      pulapki: [
        'Wniosek na nowy okres świadczeniowy składa się od 1 lutego',
        'Brak progu dochodowego -- przysługuje wszystkim',
        'Jeśli złożysz po terminie, możesz stracić wypłatę za wcześniejsze miesiące',
      ],
      odwolanie: 'Odwołanie do Prezesa ZUS w ciągu 14 dni od decyzji',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/800plus',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'becikowe', nazwa: 'Becikowe (jednorazowa zapomoga)', kategoria: 'RODZINA',
    kwota: '1000 PLN jednorazowo', kwotaMin: 1000, kwotaMax: 1000,
    czestotliwosc: 'jednorazowo',
    wymagania: { dzieci: { min: 1, wiekMax: 1 }, dochodMax: 1922 },
    wykluczenia: [{ opis: 'Dochód przekracza 1922 PLN netto na osobę w rodzinie', sprawdz: 'dochod_na_osobe' }],
    wniosek: {
      kanal: ['URZAD_GMINY', 'MOPS'], formularz: 'SR-2',
      dokumenty: [
        'Akt urodzenia dziecka',
        'Zaświadczenie lekarskie o opiece medycznej od 10 tygodnia ciąży',
        'Zaświadczenie o dochodach lub PIT za poprzedni rok',
        'Dowód osobisty',
      ],
      kroki: [
        'Przygotuj zaświadczenie lekarskie potwierdzające opiekę od 10 tygodnia ciąży',
        'Udaj się do MOPS lub urzędu gminy z kompletem dokumentów',
        'Wypełnij formularz SR-2',
        'Złóż wniosek w ciągu 12 miesięcy od urodzenia dziecka',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'Próg dochodowy: 1922 PLN netto na osobę -- wiele rodzin jest tuż nad progiem',
        'MUSISZ mieć zaświadczenie o opiece medycznej od 10 tygodnia ciąży',
        'Wniosek trzeba złożyć w ciągu 12 miesięcy od narodzin',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/becikowe',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'kosiniakowe', nazwa: 'Świadczenie rodzicielskie (kosiniakowe)', kategoria: 'RODZINA',
    kwota: '1000 PLN miesięcznie przez 12 miesięcy', kwotaMin: 1000, kwotaMax: 1000,
    czestotliwosc: 'miesięcznie (12 mies.)',
    wymagania: { ciaza: true, zatrudnienie: ['bezrobotny', 'student', 'umowa_cywilnoprawna', 'rolnik'] },
    wykluczenia: [
      { opis: 'Osoby otrzymujące zasiłek macierzyński', sprawdz: 'zasilek_macierzynski' },
      { opis: 'Osoby otrzymujące zasiłek dla bezrobotnych', sprawdz: 'zasilek_bezrobotnych' },
    ],
    wniosek: {
      kanal: ['URZAD_GMINY', 'MOPS'], formularz: 'SR-7',
      dokumenty: ['Akt urodzenia dziecka', 'Dowód osobisty', 'Oświadczenie o braku zasiłku macierzyńskiego'],
      kroki: [
        'Po urodzeniu dziecka przygotuj akt urodzenia',
        'Udaj się do MOPS lub urzędu gminy',
        'Wypełnij wniosek SR-7',
        'Złóż wniosek w ciągu 3 miesięcy od porodu (potem tracisz miesiące wstecz)',
      ],
      terminRealizacji: '30 dni od złożenia wniosku',
      pulapki: [
        'Nie przysługuje osobom na umowie o pracę (one dostają zasiłek macierzyński z ZUS)',
        'Złóż w ciągu 3 miesięcy od porodu -- potem tracisz wypłatę za wcześniejsze miesiące',
        'Brak progu dochodowego',
      ],
      odwolanie: 'Odwołanie do SKO w ciągu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/swiadczenie-rodzicielskie',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'ulga-prorodzinna', nazwa: 'Ulga prorodzinna (na dzieci)', kategoria: 'RODZINA',
    kwota: '1112-2700 PLN rocznie na dziecko', kwotaMin: 1112, kwotaMax: 2700,
    czestotliwosc: 'rocznie (odliczenie w PIT)',
    wymagania: { dzieci: { min: 1, wiekMax: 25 } },
    wykluczenia: [
      { opis: 'Na 1 dziecko: dochód rodzica nie może przekroczyć 112 000 PLN (lub 56 000 PLN dla samotnych)', sprawdz: 'dochod_prorodzinna' },
    ],
    wniosek: {
      kanal: ['URZAD_SKARBOWY'], formularz: 'PIT/O (załącznik do PIT-37 lub PIT-36)',
      dokumenty: ['Akt urodzenia dziecka (do wglądu)', 'PIT roczny'],
      kroki: [
        'Przy rozliczeniu rocznym PIT wypełnij załącznik PIT/O',
        'Wpisz dane dzieci i liczbę miesięcy opieki',
        'Kwoty: 1112,04 PLN (1-2 dziecko), 2000,04 PLN (3 dziecko), 2700 PLN (4+ dziecko)',
        'Odliczenie automatycznie zmniejszy podatek do zapłaty',
      ],
      terminRealizacji: 'Zwrot przy rozliczeniu PIT (45-90 dni)',
      pulapki: [
        'Na 1 dziecko obowiązuje próg dochodowy (112 000 PLN brutto rocznie)',
        'Na 2+ dzieci NIE MA progu dochodowego',
        'Dzieci 18-25 lat: ulga tylko jeśli się uczą i nie zarobiły więcej niż 21 371 PLN rocznie',
      ],
      odwolanie: 'Korekta zeznania PIT',
    },
    zrodloUrl: 'https://www.podatki.gov.pl/pit/ulgi-odliczenia-i-zwolnienia/ulga-na-dzieci/',
    zrodloNazwa: 'Ministerstwo Finansów', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'dobry-start', nazwa: 'Dobry Start (300+)', kategoria: 'RODZINA',
    kwota: '300 PLN jednorazowo na dziecko', kwotaMin: 300, kwotaMax: 300,
    czestotliwosc: 'rocznie (przed rokiem szkolnym)',
    wymagania: { dzieci: { min: 1, wiekMax: 20 } },
    wykluczenia: [{ opis: 'Dziecko musi się uczyć (szkoła podstawowa, średnia, zawodowa)', sprawdz: 'nauka_dziecka' }],
    wniosek: {
      kanal: ['PUE_ZUS', 'BANK', 'EMPATIA'],
      dokumenty: ['PESEL dziecka', 'Numer konta bankowego'],
      kroki: [
        'Wnioski składasz od 1 lipca każdego roku',
        'Zaloguj się na PUE ZUS lub bankowość elektroniczną',
        'Wypełnij wniosek o świadczenie Dobry Start',
        'Podaj PESEL uczącego się dziecka',
      ],
      terminRealizacji: 'Wypłata w ciągu 30 dni (jeśli złożysz w lipcu -- wypłata we wrześniu)',
      pulapki: [
        'Składaj od 1 lipca -- wcześniej system nie przyjmuje',
        'Dziecko musi uczestniczyć w roku szkolnym (nie dotyczy przedszkolaków)',
        'Brak progu dochodowego',
      ],
      odwolanie: 'Odwołanie do Prezesa ZUS w ciągu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/dobry-start',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'renta-rodzinna', nazwa: 'Renta rodzinna', kategoria: 'RODZINA',
    kwota: '85-95% emerytury zmarłego', czestotliwosc: 'miesięcznie',
    wymagania: {},
    wykluczenia: [],
    wniosek: {
      kanal: ['PUE_ZUS'], formularz: 'ERR (wniosek o rentę rodzinną)',
      dokumenty: [
        'Akt zgonu współmałżonka',
        'Akt małżeństwa',
        'Zaświadczenie o zatrudnieniu zmarłego lub decyzja emerytalna',
        'Dowód osobisty wnioskodawcy',
      ],
      kroki: [
        'Przygotuj akt zgonu i dokumenty potwierdzające staż pracy zmarłego',
        'Wypełnij formularz ERR na PUE ZUS lub w oddziale ZUS',
        'Dołącz wszystkie wymagane dokumenty',
        'ZUS wyda decyzję w ciągu 30 dni',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'Wielu wdowców/wdów nie wie że im przysługuje -- warto sprawdzić',
        'Można wybrać korzystniejszą rentę: własną lub rodzinną',
        'Przysługuje też dzieciom zmarłego (do 25 roku życia jeśli się uczą)',
      ],
      odwolanie: 'Odwołanie do Sądu Pracy w ciągu 30 dni od decyzji ZUS',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/renty/renta-rodzinna',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
];
