import { Benefit } from '../types';

export const RODZINA: Benefit[] = [
  {
    id: '800-plus', nazwa: 'Swiadczenie wychowawcze 800+', kategoria: 'RODZINA',
    kwota: '800 PLN miesiecznie na dziecko', kwotaMin: 800, kwotaMax: 800,
    czestotliwosc: 'miesiecznie',
    wymagania: { dzieci: { min: 1, wiekMax: 18 } },
    wykluczenia: [],
    wniosek: {
      kanal: ['PUE_ZUS', 'BANK', 'EMPATIA'], formularz: 'SW-1',
      dokumenty: ['PESEL dziecka', 'Numer konta bankowego'],
      kroki: [
        'Zaloguj sie na PUE ZUS, bankowosc elektroniczna lub portal Empatia',
        'Wypelnij wniosek SW-1 (swiadczenie wychowawcze)',
        'Podaj PESEL dziecka/dzieci i numer konta',
        'Wyslij wniosek elektronicznie',
        'ZUS wyda decyzje w ciagu 30 dni -- pieniadze przyjda na konto',
      ],
      terminRealizacji: '30 dni od zlozenia wniosku',
      pulapki: [
        'Wniosek na nowy okres swiadczeniowy sklada sie od 1 lutego',
        'Brak progu dochodowego -- przysluguje wszystkim',
        'Jesli zlozysz po terminie, mozesz stracic wyplate za wczesniejsze miesiace',
      ],
      odwolanie: 'Odwolanie do Prezesa ZUS w ciagu 14 dni od decyzji',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/800plus',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'becikowe', nazwa: 'Becikowe (jednorazowa zapomoga)', kategoria: 'RODZINA',
    kwota: '1000 PLN jednorazowo', kwotaMin: 1000, kwotaMax: 1000,
    czestotliwosc: 'jednorazowo',
    wymagania: { dzieci: { min: 1, wiekMax: 1 }, dochodMax: 1922 },
    wykluczenia: [{ opis: 'Dochod przekracza 1922 PLN netto na osobe w rodzinie', sprawdz: 'dochod_na_osobe' }],
    wniosek: {
      kanal: ['URZAD_GMINY', 'MOPS'], formularz: 'SR-2',
      dokumenty: [
        'Akt urodzenia dziecka',
        'Zaswiadczenie lekarskie o opiece medycznej od 10 tygodnia ciazy',
        'Zaswiadczenie o dochodach lub PIT za poprzedni rok',
        'Dowod osobisty',
      ],
      kroki: [
        'Przygotuj zaswiadczenie lekarskie potwierdzajace opieke od 10 tygodnia ciazy',
        'Udaj sie do MOPS lub urzedu gminy z kompletem dokumentow',
        'Wypelnij formularz SR-2',
        'Zloz wniosek w ciagu 12 miesiecy od urodzenia dziecka',
      ],
      terminRealizacji: '30 dni od zlozenia kompletnego wniosku',
      pulapki: [
        'Prog dochodowy: 1922 PLN netto na osobe -- wiele rodzin jest tuz nad progiem',
        'MUSISZ miec zaswiadczenie o opiece medycznej od 10 tygodnia ciazy',
        'Wniosek trzeba zlozyc w ciagu 12 miesiecy od narodzin',
      ],
      odwolanie: 'Odwolanie do Samorzadowego Kolegium Odwolawczego w ciagu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/becikowe',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'kosiniakowe', nazwa: 'Swiadczenie rodzicielskie (kosiniakowe)', kategoria: 'RODZINA',
    kwota: '1000 PLN miesiecznie przez 12 miesiecy', kwotaMin: 1000, kwotaMax: 1000,
    czestotliwosc: 'miesiecznie (12 mies.)',
    wymagania: { ciaza: true, zatrudnienie: ['bezrobotny', 'student', 'umowa_cywilnoprawna', 'rolnik'] },
    wykluczenia: [
      { opis: 'Osoby otrzymujace zasilek macierzynski', sprawdz: 'zasilek_macierzynski' },
      { opis: 'Osoby otrzymujace zasilek dla bezrobotnych', sprawdz: 'zasilek_bezrobotnych' },
    ],
    wniosek: {
      kanal: ['URZAD_GMINY', 'MOPS'], formularz: 'SR-7',
      dokumenty: ['Akt urodzenia dziecka', 'Dowod osobisty', 'Oswiadczenie o braku zasilku macierzynskiego'],
      kroki: [
        'Po urodzeniu dziecka przygotuj akt urodzenia',
        'Udaj sie do MOPS lub urzedu gminy',
        'Wypelnij wniosek SR-7',
        'Zloz wniosek w ciagu 3 miesiecy od porodu (potem tracisz miesiace wstecz)',
      ],
      terminRealizacji: '30 dni od zlozenia wniosku',
      pulapki: [
        'Nie przysluguje osobom na umowie o prace (one dostaja zasilek macierzynski z ZUS)',
        'Zloz w ciagu 3 miesiecy od porodu -- potem tracisz wyplate za wczesniejsze miesiace',
        'Brak progu dochodowego',
      ],
      odwolanie: 'Odwolanie do SKO w ciagu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/swiadczenie-rodzicielskie',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'ulga-prorodzinna', nazwa: 'Ulga prorodzinna (na dzieci)', kategoria: 'RODZINA',
    kwota: '1112-2700 PLN rocznie na dziecko', kwotaMin: 1112, kwotaMax: 2700,
    czestotliwosc: 'rocznie (odliczenie w PIT)',
    wymagania: { dzieci: { min: 1, wiekMax: 25 } },
    wykluczenia: [
      { opis: 'Na 1 dziecko: dochod rodzica nie moze przekroczyc 112 000 PLN (lub 56 000 PLN dla samotnych)', sprawdz: 'dochod_prorodzinna' },
    ],
    wniosek: {
      kanal: ['URZAD_SKARBOWY'], formularz: 'PIT/O (zalacznik do PIT-37 lub PIT-36)',
      dokumenty: ['Akt urodzenia dziecka (do wgladu)', 'PIT roczny'],
      kroki: [
        'Przy rozliczeniu rocznym PIT wypelnij zalacznik PIT/O',
        'Wpisz dane dzieci i liczbe miesiecy opieki',
        'Kwoty: 1112,04 PLN (1-2 dziecko), 2000,04 PLN (3 dziecko), 2700 PLN (4+ dziecko)',
        'Odliczenie automatycznie zmniejszy podatek do zaplaty',
      ],
      terminRealizacji: 'Zwrot przy rozliczeniu PIT (45-90 dni)',
      pulapki: [
        'Na 1 dziecko obowiazuje prog dochodowy (112 000 PLN brutto rocznie)',
        'Na 2+ dzieci NIE MA progu dochodowego',
        'Dzieci 18-25 lat: ulga tylko jesli sie ucza i nie zarobily wiecej niz 21 371 PLN rocznie',
      ],
      odwolanie: 'Korekta zeznania PIT',
    },
    zrodloUrl: 'https://www.podatki.gov.pl/pit/ulgi-odliczenia-i-zwolnienia/ulga-na-dzieci/',
    zrodloNazwa: 'Ministerstwo Finansow', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'dobry-start', nazwa: 'Dobry Start (300+)', kategoria: 'RODZINA',
    kwota: '300 PLN jednorazowo na dziecko', kwotaMin: 300, kwotaMax: 300,
    czestotliwosc: 'rocznie (przed rokiem szkolnym)',
    wymagania: { dzieci: { min: 1, wiekMax: 20 } },
    wykluczenia: [{ opis: 'Dziecko musi sie uczyc (szkola podstawowa, srednia, zawodowa)', sprawdz: 'nauka_dziecka' }],
    wniosek: {
      kanal: ['PUE_ZUS', 'BANK', 'EMPATIA'],
      dokumenty: ['PESEL dziecka', 'Numer konta bankowego'],
      kroki: [
        'Wnioski skladasz od 1 lipca kazdego roku',
        'Zaloguj sie na PUE ZUS lub bankowosc elektroniczna',
        'Wypelnij wniosek o swiadczenie Dobry Start',
        'Podaj PESEL uczacego sie dziecka',
      ],
      terminRealizacji: 'Wyplata w ciagu 30 dni (jesli zlozysz w lipcu -- wyplata we wrzesniu)',
      pulapki: [
        'Skladaj od 1 lipca -- wczesniej system nie przyjmuje',
        'Dziecko musi uczestniczyc w roku szkolnym (nie dotyczy przedszkolakow)',
        'Brak progu dochodowego',
      ],
      odwolanie: 'Odwolanie do Prezesa ZUS w ciagu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/dobry-start',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'renta-rodzinna', nazwa: 'Renta rodzinna', kategoria: 'RODZINA',
    kwota: '85-95% emerytury zmarlego', czestotliwosc: 'miesiecznie',
    wymagania: {},
    wykluczenia: [],
    wniosek: {
      kanal: ['PUE_ZUS'], formularz: 'ERR (wniosek o rente rodzinna)',
      dokumenty: [
        'Akt zgonu wspolmalzonka',
        'Akt malzenstwa',
        'Zaswiadczenie o zatrudnieniu zmarlego lub decyzja emerytalna',
        'Dowod osobisty wnioskodawcy',
      ],
      kroki: [
        'Przygotuj akt zgonu i dokumenty potwierdzajace staz pracy zmarlego',
        'Wypelnij formularz ERR na PUE ZUS lub w oddziale ZUS',
        'Dolacz wszystkie wymagane dokumenty',
        'ZUS wyda decyzje w ciagu 30 dni',
      ],
      terminRealizacji: '30 dni od zlozenia kompletnego wniosku',
      pulapki: [
        'Wielu wdowcow/wdow nie wie ze im przysluguje -- warto sprawdzic',
        'Mozna wybrac korzystniejsza rente: wlasna lub rodzinna',
        'Przysluguje tez dzieciom zmarlego (do 25 roku zycia jesli sie ucza)',
      ],
      odwolanie: 'Odwolanie do Sadu Pracy w ciagu 30 dni od decyzji ZUS',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/renty/renta-rodzinna',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
];
