import { Benefit } from '../types';

export const RODZINA: Benefit[] = [
  {
    id: '800-plus', nazwa: 'Świadczenie wychowawcze 800+',
    opis: 'Świadczenie 800 PLN miesięcznie na każde dziecko do ukończenia 18 roku życia, niezależnie od dochodu rodziny. Przysługuje obywatelom polskim oraz cudzoziemcom legalnie przebywającym w Polsce. Nie trzeba być zatrudnionym, świadczenie dostaje każdy rodzic, opiekun prawny lub opiekun faktyczny dziecka. Wniosek składa się wyłącznie elektronicznie: przez PUE ZUS, bankowość elektroniczną lub portal Empatia. Wypłata następuje co miesiąc na wskazane konto bankowe. Nowy okres świadczeniowy zaczyna się 1 czerwca, a wnioski na nowy okres przyjmowane są od 1 lutego. Jeśli złożysz wniosek po 30 kwietnia, stracisz wypłatę za wcześniejsze miesiące (nie ma wyrównania wstecz). Świadczenie nie jest wliczane do dochodu przy ustalaniu prawa do innych świadczeń. Nie podlega opodatkowaniu PIT. W przypadku rodziców żyjących w rozłączeniu świadczenie przysługuje temu, kto faktycznie sprawuje opiekę nad dzieckiem. Przy opiece naprzemiennej kwota jest dzielona po połowie (400 PLN na każdego rodzica).',
    kategoria: 'RODZINA',
    kwota: '800 PLN miesięcznie na dziecko', kwotaMin: 800, kwotaMax: 800,
    czestotliwosc: 'miesięcznie',
    wymagania: { dzieci: { min: 1, wiekMax: 18 } },
    wykluczenia: [],
    wniosek: {
      kanal: ['PUE_ZUS', 'BANK', 'EMPATIA'], formularz: 'SW-1',
      dokumenty: ['PESEL dziecka', 'Numer konta bankowego'],
      kroki: [
        'Zaloguj się na PUE ZUS, bankowość elektroniczną lub portal Empatia',
        'Wypełnij wniosek SW-1 (świadczenie wychowawcze)',
        'Podaj PESEL dziecka/dzieci i numer konta',
        'Wyślij wniosek elektronicznie',
        'ZUS wyda decyzję w ciągu 30 dni, pieniądze przyjdą na konto',
      ],
      terminRealizacji: '30 dni od złożenia wniosku',
      pulapki: [
        'Wniosek na nowy okres świadczeniowy składa się od 1 lutego',
        'Brak progu dochodowego, przysługuje wszystkim',
        'Jeśli złożysz po terminie, możesz stracić wypłatę za wcześniejsze miesiące',
      ],
      odwolanie: 'Odwołanie do Prezesa ZUS w ciągu 14 dni od decyzji',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/800plus',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'becikowe', nazwa: 'Becikowe (jednorazowa zapomoga)',
    opis: 'Jednorazowa zapomoga w wysokości 1000 PLN z tytułu urodzenia się żywego dziecka. Przysługuje matce, ojcu, opiekunowi prawnemu lub opiekunowi faktycznemu dziecka, pod warunkiem że dochód na osobę w rodzinie nie przekracza 1922 PLN netto miesięcznie. Kluczowy wymóg: matka dziecka musi pozostawać pod opieką medyczną nie później niż od 10 tygodnia ciąży do dnia porodu, konieczne jest zaświadczenie lekarskie lub od położnej potwierdzające ten fakt. Bez tego zaświadczenia wniosek zostanie odrzucony, nawet jeśli spełniasz kryterium dochodowe. Wniosek składa się w MOPS lub urzędzie gminy w ciągu 12 miesięcy od urodzenia dziecka. Po tym terminie prawo do becikowego przepada bezpowrotnie. Dochód liczony jest na podstawie roku bazowego (najczęściej rok kalendarzowy poprzedzający okres zasiłkowy), z uwzględnieniem zmian z ostatnich miesięcy (utrata/uzyskanie dochodu). Wiele rodzin z dochodem niewiele powyżej progu nie zdaje sobie sprawy, że utrata pracy lub inne zmiany mogą obniżyć dochód poniżej progu i otworzyć prawo do becikowego. Becikowe nie podlega opodatkowaniu.',
    kategoria: 'RODZINA',
    kwota: '1000 PLN jednorazowo', kwotaMin: 1000, kwotaMax: 1000,
    czestotliwosc: 'jednorazowo',
    wymagania: { dzieci: { min: 1, wiekMax: 1 }, dochodMax: 1922 },
    wykluczenia: [{ opis: 'Dochód przekracza 1922 PLN netto na osobę w rodzinie', sprawdz: 'dochod_na_osobe' }],
    wniosek: {
      kanal: ['URZAD_GMINY', 'MOPS'], formularz: 'SR-2',
      dokumenty: [
        'Akt urodzenia dziecka',
        'Zaświadczenie lekarskie o opiece medycznej od 10 tygodnia ciąży',
        'Zaświadczenie o dochodach lub PIT za poprzedni rok',
        'Dowód osobisty',
      ],
      kroki: [
        'Przygotuj zaświadczenie lekarskie potwierdzające opiekę od 10 tygodnia ciąży',
        'Udaj się do MOPS lub urzędu gminy z kompletem dokumentów',
        'Wypełnij formularz SR-2',
        'Złóż wniosek w ciągu 12 miesięcy od urodzenia dziecka',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'Próg dochodowy: 1922 PLN netto na osobę, wiele rodzin jest tuż nad progiem',
        'MUSISZ mieć zaświadczenie o opiece medycznej od 10 tygodnia ciąży',
        'Wniosek trzeba złożyć w ciągu 12 miesięcy od narodzin',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/becikowe',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'kosiniakowe', nazwa: 'Świadczenie rodzicielskie (kosiniakowe)',
    opis: 'Świadczenie rodzicielskie, potocznie zwane kosiniakowym, wynosi 1000 PLN miesięcznie i jest wypłacane przez 52 tygodnie (12 miesięcy) od urodzenia dziecka. Przy bliźniakach okres wydłuża się do 65 tygodni, przy trojaczkach do 67, przy czworaczkach do 69, a przy pięcioraczkach i więcej do 71 tygodni. Świadczenie jest skierowane do osób, które nie mają prawa do zasiłku macierzyńskiego z ZUS, czyli do bezrobotnych, studentów, osób na umowach cywilnoprawnych (zlecenie, dzieło) i rolników. Osoby zatrudnione na umowie o pracę dostają zasiłek macierzyński z ZUS i nie mogą pobierać kosiniakowego. Nie obowiązuje żaden próg dochodowy. Wniosek składa się w MOPS lub urzędzie gminy na formularzu SR-7. Kluczowy termin: wniosek trzeba złożyć w ciągu 3 miesięcy od porodu, aby otrzymać wypłatę od dnia narodzin. Po tym terminie wypłata przysługuje dopiero od miesiąca złożenia wniosku, tracisz pieniądze za wcześniejsze miesiące. Kosiniakowe nie przysługuje osobom pobierającym zasiłek dla bezrobotnych. Świadczenie nie podlega opodatkowaniu PIT. Ojciec dziecka również może złożyć wniosek, jeśli matka nie pobiera tego świadczenia.',
    kategoria: 'RODZINA',
    kwota: '1000 PLN miesięcznie przez 12 miesięcy', kwotaMin: 1000, kwotaMax: 1000,
    czestotliwosc: 'miesięcznie (12 mies.)',
    wymagania: { ciaza: true, zatrudnienie: ['bezrobotny', 'student', 'umowa_cywilnoprawna', 'rolnik'] },
    wykluczenia: [
      { opis: 'Osoby otrzymujące zasiłek macierzyński', sprawdz: 'zasilek_macierzynski' },
      { opis: 'Osoby otrzymujące zasiłek dla bezrobotnych', sprawdz: 'zasilek_bezrobotnych' },
    ],
    wniosek: {
      kanal: ['URZAD_GMINY', 'MOPS'], formularz: 'SR-7',
      dokumenty: ['Akt urodzenia dziecka', 'Dowód osobisty', 'Oświadczenie o braku zasiłku macierzyńskiego'],
      kroki: [
        'Po urodzeniu dziecka przygotuj akt urodzenia',
        'Udaj się do MOPS lub urzędu gminy',
        'Wypełnij wniosek SR-7',
        'Złóż wniosek w ciągu 3 miesięcy od porodu (potem tracisz miesiące wstecz)',
      ],
      terminRealizacji: '30 dni od złożenia wniosku',
      pulapki: [
        'Nie przysługuje osobom na umowie o pracę (one dostają zasiłek macierzyński z ZUS)',
        'Złóż w ciągu 3 miesięcy od porodu, potem tracisz wypłatę za wcześniejsze miesiące',
        'Brak progu dochodowego',
      ],
      odwolanie: 'Odwołanie do SKO w ciągu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/swiadczenie-rodzicielskie',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'ulga-prorodzinna', nazwa: 'Ulga prorodzinna (na dzieci)',
    opis: 'Ulga podatkowa odliczana od podatku PIT przy rozliczeniu rocznym. Przysługuje rodzicom, opiekunom prawnym i rodzicom zastępczym dzieci do 18 roku życia, a w przypadku dzieci uczących się, do 25 roku życia (pod warunkiem że dziecko nie zarobiło więcej niż 21 371 PLN rocznie). Kwoty roczne na dziecko: 1112,04 PLN za pierwsze i drugie dziecko, 2000,04 PLN za trzecie dziecko, 2700 PLN za czwarte i każde kolejne. Przy jednym dziecku obowiązuje próg dochodowy: 112 000 PLN brutto rocznie dla małżeństw rozliczających się wspólnie lub 56 000 PLN dla osób samotnie wychowujących dziecko. Przy dwójce i więcej dzieci NIE MA żadnego progu dochodowego. Częsty błąd: rodzice jednego dziecka z dochodem powyżej progu tracą prawo do ulgi, ale nie wiedzą że próg dotyczy tylko rodzin z jednym dzieckiem. Ulgę odlicza się w załączniku PIT/O do zeznania PIT-37 lub PIT-36. Jeśli podatek jest zbyt niski, aby odliczyć pełną ulgę, można otrzymać różnicę jako zwrot z urzędu skarbowego (do wysokości zapłaconych składek ZUS i zdrowotnych). Ulga jest dzielona między rodziców proporcjonalnie lub w całości przez jednego z nich, wymaga to zgodnego oświadczenia. W przypadku rozwodu ulgę rozlicza rodzic sprawujący faktyczną opiekę nad dzieckiem.',
    kategoria: 'RODZINA',
    kwota: '1112-2700 PLN rocznie na dziecko', kwotaMin: 1112, kwotaMax: 2700,
    czestotliwosc: 'rocznie (odliczenie w PIT)',
    wymagania: { dzieci: { min: 1, wiekMax: 25 } },
    wykluczenia: [
      { opis: 'Na 1 dziecko: dochód rodzica nie może przekroczyć 112 000 PLN (lub 56 000 PLN dla samotnych)', sprawdz: 'dochod_prorodzinna' },
    ],
    wniosek: {
      kanal: ['URZAD_SKARBOWY'], formularz: 'PIT/O (załącznik do PIT-37 lub PIT-36)',
      dokumenty: ['Akt urodzenia dziecka (do wglądu)', 'PIT roczny'],
      kroki: [
        'Przy rozliczeniu rocznym PIT wypełnij załącznik PIT/O',
        'Wpisz dane dzieci i liczbę miesięcy opieki',
        'Kwoty: 1112,04 PLN (1-2 dziecko), 2000,04 PLN (3 dziecko), 2700 PLN (4+ dziecko)',
        'Odliczenie automatycznie zmniejszy podatek do zapłaty',
      ],
      terminRealizacji: 'Zwrot przy rozliczeniu PIT (45-90 dni)',
      pulapki: [
        'Na 1 dziecko obowiązuje próg dochodowy (112 000 PLN brutto rocznie)',
        'Na 2+ dzieci NIE MA progu dochodowego',
        'Dzieci 18-25 lat: ulga tylko jeśli się uczą i nie zarobiły więcej niż 21 371 PLN rocznie',
      ],
      odwolanie: 'Korekta zeznania PIT',
    },
    zrodloUrl: 'https://www.podatki.gov.pl/pit/ulgi-odliczenia-i-zwolnienia/ulga-na-dzieci/',
    zrodloNazwa: 'Ministerstwo Finansów', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'dobry-start', nazwa: 'Dobry Start (300+)',
    opis: 'Jednorazowe świadczenie 300 PLN na każde uczące się dziecko, wypłacane raz w roku przed rozpoczęciem roku szkolnego. Ma na celu pokrycie kosztów wyprawki szkolnej. Przysługuje niezależnie od dochodu rodziny. Obejmuje dzieci uczęszczające do szkoły podstawowej, ponadpodstawowej (liceum, technikum, szkoła branżowa), do ukończenia 20 roku życia, a w przypadku dzieci z niepełnosprawnością do 24 roku życia. Nie obejmuje przedszkolaków ani studentów. Wniosek składa się wyłącznie elektronicznie: przez PUE ZUS, bankowość elektroniczną lub portal Empatia. Wnioski przyjmowane są od 1 lipca do 30 listopada każdego roku. Jeśli złożysz wniosek w lipcu lub sierpniu, wypłata nastąpi nie później niż do 30 września. Przy późniejszym złożeniu, w ciągu 2 miesięcy od daty wniosku. Świadczenie przysługuje na każde dziecko osobno, więc rodzina z trójką dzieci w szkole otrzyma 900 PLN. Nie podlega opodatkowaniu PIT i nie jest wliczane do dochodu przy ustalaniu prawa do innych świadczeń.',
    kategoria: 'RODZINA',
    kwota: '300 PLN jednorazowo na dziecko', kwotaMin: 300, kwotaMax: 300,
    czestotliwosc: 'rocznie (przed rokiem szkolnym)',
    wymagania: { dzieci: { min: 1, wiekMax: 20 } },
    wykluczenia: [{ opis: 'Dziecko musi się uczyć (szkoła podstawowa, średnia, zawodowa)', sprawdz: 'nauka_dziecka' }],
    wniosek: {
      kanal: ['PUE_ZUS', 'BANK', 'EMPATIA'],
      dokumenty: ['PESEL dziecka', 'Numer konta bankowego'],
      kroki: [
        'Wnioski składasz od 1 lipca każdego roku',
        'Zaloguj się na PUE ZUS lub bankowość elektroniczną',
        'Wypełnij wniosek o świadczenie Dobry Start',
        'Podaj PESEL uczącego się dziecka',
      ],
      terminRealizacji: 'Wypłata w ciągu 30 dni (jeśli złożysz w lipcu, wypłata we wrześniu)',
      pulapki: [
        'Składaj od 1 lipca, wcześniej system nie przyjmuje',
        'Dziecko musi uczestniczyć w roku szkolnym (nie dotyczy przedszkolaków)',
        'Brak progu dochodowego',
      ],
      odwolanie: 'Odwołanie do Prezesa ZUS w ciągu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/dobry-start',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'aktywnie-w-zlobku', nazwa: 'Aktywnie w żłobku (Aktywny Rodzic)',
    opis: 'Dofinansowanie do 1500 PLN miesięcznie na pokrycie kosztów opieki w żłobku, klubie dziecięcym, u dziennego opiekuna lub niani, dla dzieci od 12 do 35 miesiąca życia (1-3 lata). Świadczenie z programu Aktywny Rodzic (weszło w życie 15 października 2024 r., zastąpiło Rodzinny Kapitał Opiekuńczy). BRAK kryterium dochodowego. Pieniądze trafiają bezpośrednio do placówki/opiekuna i pomniejszają miesięczną opłatę rodzica. Jeśli koszt opieki jest niższy niż 1500 PLN, przekazywana jest kwota równa kosztowi, nie wyższa. Możliwe jest skorzystanie z dofinansowania zarówno dla żłobka publicznego, jak i prywatnego. Opiekun dzienny i niania też mogą być dofinansowani, ale niania musi być zgłoszona do ZUS przez rodzica na umowie uaktywniającej. Wniosek wyłącznie elektronicznie przez ZUS (PUE ZUS, bankowość elektroniczną lub portal Empatia). Uwaga: nie można jednocześnie pobierać Aktywnie w żłobku i Aktywnie w domu (wzajemnie się wykluczają). Można łączyć ze świadczeniem 800+. Świadczenie nie wlicza się do dochodu i nie jest opodatkowane.',
    kategoria: 'RODZINA',
    kwota: 'do 1500 PLN miesięcznie na opiekę', kwotaMin: 0, kwotaMax: 1500,
    czestotliwosc: 'miesięcznie',
    wymagania: { dzieci: { min: 1, wiekMax: 3 } },
    wykluczenia: [
      { opis: 'Wyklucza się z Aktywnie w domu (można pobierać tylko jedno)', sprawdz: 'aktywnie_w_domu' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS', 'BANK', 'EMPATIA'],
      dokumenty: [
        'PESEL dziecka',
        'Dane placówki/opiekuna (NIP lub PESEL niani)',
        'Numer konta bankowego placówki lub opiekuna',
        'Umowa uaktywniająca z nianią (jeśli dotyczy)',
      ],
      kroki: [
        'Zaloguj się na PUE ZUS, bankowość elektroniczną lub portal Empatia',
        'Wybierz wniosek o świadczenie Aktywnie w żłobku (program Aktywny Rodzic)',
        'Podaj dane dziecka (PESEL) i dane placówki/opiekuna',
        'Dofinansowanie trafia bezpośrednio do placówki i pomniejsza Twoją miesięczną opłatę',
        'ZUS wyda decyzję w ciągu 30 dni',
      ],
      terminRealizacji: '30 dni od złożenia wniosku',
      pulapki: [
        'Dofinansowanie do 1500 PLN/mies, nie może przekraczać faktycznego kosztu opieki',
        'Obejmuje żłobek publiczny i prywatny, klub dziecięcy, dziennego opiekuna, nianię',
        'Niania musi być zgłoszona do ZUS na umowie uaktywniającej',
        'Wyklucza się z Aktywnie w domu, można pobierać tylko jedno naraz',
        'Brak progu dochodowego, dostępne dla wszystkich',
        'Dziecko musi mieć ukończone 12 miesięcy, max 35 miesięcy',
      ],
      odwolanie: 'Odwołanie do Prezesa ZUS w ciągu 14 dni od decyzji',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/aktywny-rodzic',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-12', dataWaznosci: '2026-12-31',
  },
  {
    id: 'aktywnie-w-domu', nazwa: 'Aktywnie w domu (Aktywny Rodzic)',
    opis: 'Świadczenie 500 PLN miesięcznie dla rodzin z dziećmi od 12 do 35 miesiąca życia (1-3 lata), które nie korzystają z żłobka, klubu dziecięcego, dziennego opiekuna ani niani. Część programu Aktywny Rodzic (od 15 października 2024 r.). BRAK kryterium dochodowego. Przeznaczone dla rodzin wychowujących dziecko w domu - wystarczy że dziecko jest w odpowiednim wieku i rodzic nie pobiera dofinansowania Aktywnie w żłobku. Wniosek wyłącznie elektronicznie przez ZUS (PUE ZUS, bankowość elektroniczną lub portal Empatia). Pieniądze trafiają na konto rodzica co miesiąc. Uwaga: jeśli w trakcie pobierania świadczenia zapiszesz dziecko do żłobka i złożysz wniosek Aktywnie w żłobku, Aktywnie w domu automatycznie wygasa. Nie wlicza się do dochodu, nie jest opodatkowane. Można łączyć z 800+, becikowym i innymi świadczeniami.',
    kategoria: 'RODZINA',
    kwota: '500 PLN miesięcznie', kwotaMin: 500, kwotaMax: 500,
    czestotliwosc: 'miesięcznie',
    wymagania: { dzieci: { min: 1, wiekMax: 3 } },
    wykluczenia: [
      { opis: 'Wyklucza się z Aktywnie w żłobku (można pobierać tylko jedno)', sprawdz: 'aktywnie_w_zlobku' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS', 'BANK', 'EMPATIA'],
      dokumenty: [
        'PESEL dziecka',
        'Numer konta bankowego rodzica',
      ],
      kroki: [
        'Zaloguj się na PUE ZUS, bankowość elektroniczną lub portal Empatia',
        'Wybierz wniosek o świadczenie Aktywnie w domu (program Aktywny Rodzic)',
        'Podaj PESEL dziecka i numer konta',
        'ZUS wyda decyzję w ciągu 30 dni, 500 PLN co miesiąc na konto',
      ],
      terminRealizacji: '30 dni od złożenia wniosku',
      pulapki: [
        '500 PLN/mies dla dzieci 12-35 miesięcy nieučęszczających do żłobka/opiekuna',
        'Automatycznie wygasa gdy złożysz wniosek Aktywnie w żłobku',
        'Brak progu dochodowego, każda rodzina ma prawo',
        'Tylko elektronicznie: ZUS, bankowość lub Empatia',
      ],
      odwolanie: 'Odwołanie do Prezesa ZUS w ciągu 14 dni od decyzji',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/aktywny-rodzic',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-12', dataWaznosci: '2026-12-31',
  },
  {
    id: 'aktywni-rodzice-w-pracy', nazwa: 'Aktywni Rodzice w Pracy (Aktywny Rodzic)',
    opis: 'Świadczenie do 1500 PLN miesięcznie na pokrycie kosztów opieki nad dzieckiem od 12 do 35 miesiąca życia, przeznaczone dla rodziców aktywnych zawodowo, którzy nie korzystają z żłobka ani opiekuna dziennego (dziecko przebywa z nianią lub w innej nieformalnej opiece). Część programu Aktywny Rodzic (od 15 października 2024 r.). Warunek: przynajmniej jeden rodzic musi być zatrudniony (umowa o pracę, umowa zlecenie, samozatrudnienie) lub prowadzić działalność pozarolniczą. BRAK kryterium dochodowego. Pieniądze wypłacane rodzicowi na konto, nie bezpośrednio do opiekuna. Różnica od "Aktywnie w żłobku": tam pieniądze trafiają do placówki, tu trafiają do rodziny. Wniosek wyłącznie elektronicznie przez ZUS. Jeśli aktywność zawodowa rodzica ustanie, świadczenie wygasa od następnego miesiąca. Nie wlicza się do dochodu, nie jest opodatkowane.',
    kategoria: 'RODZINA',
    kwota: 'do 1500 PLN miesięcznie', kwotaMin: 0, kwotaMax: 1500,
    czestotliwosc: 'miesięcznie',
    wymagania: { dzieci: { min: 1, wiekMax: 3 }, zatrudnienie: ['pracownik', 'samozatrudniony', 'umowa_cywilnoprawna'] },
    wykluczenia: [
      { opis: 'Rodzic musi być aktywny zawodowo (praca, zlecenie lub działalność)', sprawdz: 'aktywnosc_zawodowa' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS', 'BANK', 'EMPATIA'],
      dokumenty: [
        'PESEL dziecka',
        'Zaświadczenie o zatrudnieniu lub wydruk z CEIDG',
        'Numer konta bankowego rodzica',
      ],
      kroki: [
        'Upewnij się, że jesteś zatrudniony (umowa, zlecenie lub własna działalność)',
        'Zaloguj się na PUE ZUS, bankowość elektroniczną lub portal Empatia',
        'Wybierz wniosek Aktywni Rodzice w Pracy (program Aktywny Rodzic)',
        'Podaj dane dziecka i potwierdzenie aktywności zawodowej',
        'ZUS wyda decyzję w ciągu 30 dni, pieniądze na konto co miesiąc',
      ],
      terminRealizacji: '30 dni od złożenia wniosku',
      pulapki: [
        'Wymaga aktywności zawodowej: umowa o pracę, zlecenie lub własna firma',
        'Świadczenie wygasa gdy ustanie aktywność zawodowa',
        'Dla dzieci 12-35 miesięcy, które nie chodzą do żłobka',
        'Pieniądze trafiają do rodziców (nie do opiekuna), na dowolną opiekę',
        'Brak progu dochodowego',
      ],
      odwolanie: 'Odwołanie do Prezesa ZUS w ciągu 14 dni od decyzji',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/aktywny-rodzic',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-12', dataWaznosci: '2026-12-31',
  },
  {
    id: 'renta-rodzinna', nazwa: 'Renta rodzinna',
    opis: 'Renta rodzinna to comiesięczne świadczenie z ZUS wypłacane członkom rodziny po śmierci osoby, która miała prawo do emerytury lub renty (lub spełniała warunki do ich uzyskania). Przysługuje: wdowie/wdowcowi (jeśli ukończyła/ukończył 50 lat lub jest niezdolna/niezdolny do pracy, albo wychowuje dziecko do 16 lat lub uczące się do 18 lat), dzieciom zmarłego (do 16 roku życia, lub do 25 roku życia jeśli się uczą), rodzicom zmarłego (jeśli byli na jego utrzymaniu). Wysokość: dla jednej uprawnionej osoby: 85% świadczenia zmarłego, dla dwóch osób: 90%, dla trzech i więcej: 95%. Renta jest dzielona równo między wszystkich uprawnionych. Minimalna renta rodzinna wynosi 1780,96 PLN brutto (od marca 2025). Częsty błąd: wiele wdów/wdowców nie wie, że mogą wybrać korzystniejszą opcję: własną emeryturę albo rentę rodzinną po zmarłym małżonku. Warto porównać obie kwoty przed podjęciem decyzji. Wniosek składa się na formularzu ERR w ZUS. Prawo do renty rodzinnej nie wygasa z upływem czasu, można złożyć wniosek nawet kilka lat po śmierci bliskiego, ale świadczenie będzie wypłacane najwcześniej od miesiąca złożenia wniosku (bez wyrównania za lata wstecz). Renta rodzinna podlega opodatkowaniu PIT.',
    kategoria: 'RODZINA',
    kwota: '85-95% emerytury zmarłego', czestotliwosc: 'miesięcznie',
    wymagania: { statusWdowiec: true },
    wykluczenia: [],
    wniosek: {
      kanal: ['PUE_ZUS'], formularz: 'ERR (wniosek o rentę rodzinną)',
      dokumenty: [
        'Akt zgonu współmałżonka',
        'Akt małżeństwa',
        'Zaświadczenie o zatrudnieniu zmarłego lub decyzja emerytalna',
        'Dowód osobisty wnioskodawcy',
      ],
      kroki: [
        'Przygotuj akt zgonu i dokumenty potwierdzające staż pracy zmarłego',
        'Wypełnij formularz ERR na PUE ZUS lub w oddziale ZUS',
        'Dołącz wszystkie wymagane dokumenty',
        'ZUS wyda decyzję w ciągu 30 dni',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'Wielu wdowców/wdów nie wie że im przysługuje, warto sprawdzić',
        'Można wybrać korzystniejszą rentę: własną lub rodzinną',
        'Przysługuje też dzieciom zmarłego (do 25 roku życia jeśli się uczą)',
      ],
      odwolanie: 'Odwołanie do Sądu Pracy w ciągu 30 dni od decyzji ZUS',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/renty/renta-rodzinna',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'fundusz-alimentacyjny', nazwa: 'Fundusz alimentacyjny',
    opis: 'Fundusz alimentacyjny to świadczenie państwa wypłacane dzieciom, gdy rodzic zobowiązany do płacenia alimentów ich nie płaci, a egzekucja komornicza jest bezskuteczna. Maksymalna kwota: 1000 PLN miesięcznie na dziecko (do wysokości zasądzonych alimentów). Kryterium dochodowe: 1209 PLN netto na osobę w rodzinie (od 1 października 2026 r. wzrośnie do 1665 PLN). Obowiązuje zasada "złotówka za złotówkę": przekroczenie progu nie pozbawia świadczenia całkowicie - kwota jest pomniejszana o nadwyżkę dochodu. Warunek: zasądzone lub ugodzone alimenty PLUS bezskuteczna egzekucja komornicza. Przysługuje dzieciom do 18 lat lub do 25 lat jeśli się uczą. Wniosek elektronicznie od 1 lipca (Empatia, PUE ZUS, bankowość) lub w MOPS od 1 sierpnia. Fundusz dochodzi zwrotu świadczeń od dłużnika alimentacyjnego.',
    kategoria: 'RODZINA',
    kwota: 'do 1000 PLN miesięcznie na dziecko (do kwoty zasądzonych alimentów)', kwotaMin: 0, kwotaMax: 1000,
    czestotliwosc: 'miesięcznie',
    wymagania: { dzieci: { min: 1 }, dochodMax: 1209 },
    wykluczenia: [
      { opis: 'Egzekucja komornicza alimentów nie jest bezskuteczna (komornik ściąga alimenty)', sprawdz: 'bezskutecznosc_egzekucji' },
      { opis: 'Dochód na osobę w rodzinie przekracza 1209 PLN (od X 2026 r.: 1665 PLN)', sprawdz: 'dochod_alimenty' },
    ],
    wniosek: {
      kanal: ['MOPS', 'EMPATIA', 'PUE_ZUS', 'BANK'],
      dokumenty: [
        'Wyrok sądu lub ugoda sądowa zasądzająca alimenty',
        'Zaświadczenie komornika o bezskuteczności egzekucji alimentów',
        'Dokumenty potwierdzające dochody rodziny (PIT, zaświadczenie o zarobkach)',
        'Akt urodzenia dziecka',
        'Zaświadczenie ze szkoły lub uczelni (dla dzieci 18-25 lat)',
        'Dowód osobisty wnioskodawcy',
      ],
      kroki: [
        'Upewnij się, że masz wyrok sądowy lub ugodę zasądzającą alimenty',
        'Zgłoś się do komornika i uzyskaj zaświadczenie o bezskuteczności egzekucji',
        'Od 1 lipca złóż wniosek elektronicznie przez portal Empatia, PUE ZUS lub bankowość elektroniczną',
        'Alternatywnie: od 1 sierpnia złóż wniosek w MOPS lub GOPS właściwym dla miejsca zamieszkania',
        'MOPS wyda decyzję i wypłaci świadczenie na konto',
        'UWAGA: fundusz ściga dłużnika alimentacyjnego o zwrot wypłaconych kwot',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'Kryterium dochodowe: 1209 PLN/osobę (od 1 X 2026 r.: 1665 PLN/osobę)',
        '"Złotówka za złotówkę": przekroczenie progu nie zeruje świadczenia, tylko je pomniejsza',
        'Max 1000 PLN/dziecko, ale tylko do kwoty zasądzonych alimentów (jeśli alimenty to 600 PLN, dostaniesz 600 PLN)',
        'MUSISZ mieć zaświadczenie komornika o bezskuteczności egzekucji - bez tego wniosek zostanie odrzucony',
        'Fundusz dochodzi zwrotu wypłaconych świadczeń od dłużnika alimentacyjnego',
        'Nowy okres świadczeniowy zaczyna się 1 października, wnioski od 1 lipca (elektronicznie) lub 1 sierpnia (MOPS)',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni od decyzji',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/swiadczenia-z-funduszu-alimentacyjnego---wzor-wniosku-i-zalacznikow-do-stosowania-na-nowy-okres-20212022',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-14', dataWaznosci: '2026-09-30',
  },
];
