import { Benefit } from '../types';

export const SENIOR: Benefit[] = [
  {
    id: 'opieka-75-plus', nazwa: 'Program Opieka 75+',
    opis: 'Program Opieka 75+ zapewnia bezpłatne lub częściowo odpłatne usługi opiekuńcze w domu dla seniorów w gminach do 60 000 mieszkańców. Opiekun przychodzi do domu i pomaga w codziennych czynnościach: zakupy, gotowanie, sprzątanie, higiena osobista, pomoc w kontaktach z lekarzem. Koszt godziny usługi ustalany przez gminę (ok. 30-50 PLN/h), ale przy dochodzie do 250% kryterium dochodowego (2525 PLN) usługi są bezpłatne. Powyżej tego progu odpłatność ustalana wg uchwały gminy. Procedura: wniosek w GOPS/MOPS, wywiad środowiskowy w domu, decyzja administracyjna o zakresie i odpłatności usług. Częsty błąd: mieszkańcy dużych miast (powyżej 60 000 mieszkańców) szukają tego programu. Duże miasta mają odrębne programy usług opiekuńczych, o które trzeba pytać w miejskim MOPS. Praktyczna rada: nie każda gmina przystąpiła do programu, zadzwoń do GOPS i zapytaj wprost.',
    kategoria: 'SENIOR',
    kwota: 'bezpłatne lub częściowo odpłatne usługi opiekuńcze (koszt godziny ustala gmina, ok. 30-50 PLN/h)',
    kwotaMin: 0, kwotaMax: 0,
    czestotliwosc: 'ciągłe (usługi opiekuńcze w domu)',
    wymagania: { wiekMin: 75 },
    wykluczenia: [
      { opis: 'Gminy powyżej 60 000 mieszkańców nie uczestniczą w programie', sprawdz: 'wielkosc_gminy' },
    ],
    wniosek: {
      kanal: ['MOPS'],
      dokumenty: [
        'Dowód osobisty',
        'Zaświadczenie o dochodach (dochód do 250% kryterium = 2525 PLN, bezpłatnie)',
        'Zaświadczenie lekarskie o stanie zdrowia (opcjonalnie)',
      ],
      kroki: [
        'Skontaktuj się z GOPS/MOPS w swojej gminie i zapytaj czy gmina przystąpiła do programu Opieka 75+',
        'Złóż wniosek o usługi opiekuńcze w GOPS/MOPS',
        'Pracownik socjalny przeprowadzi wywiad środowiskowy w Twoim domu',
        'GOPS wyda decyzję administracyjną o przyznaniu usług i ewentualnej odpłatności',
        'Opiekun zacznie wizyty domowe wg ustalonego harmonogramu',
      ],
      terminRealizacji: 'Decyzja w ciągu 30 dni od wywiadu środowiskowego',
      pulapki: [
        'Program dotyczy TYLKO gmin do 60 000 mieszkańców, duże miasta mają odrębne programy',
        'Dochód do 250% kryterium (2525 PLN) = bezpłatne usługi. Powyżej, odpłatność wg uchwały gminy',
        'Gmina musi sama przystąpić do programu, nie wszystkie to zrobiły',
        'Usługi obejmują: pomoc w codziennych czynnościach, higienę, zakupy, przygotowanie posiłków',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni od decyzji',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/program-opieka-75-na-rok-2026',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'korpus-wsparcia-seniorow', nazwa: 'Korpus Wsparcia Seniorów (Teleopieka)',
    opis: 'Korpus Wsparcia Seniorów to program zapewniający osobom 60+ bezpłatną opaskę bezpieczeństwa z przyciskiem SOS, czujnikiem upadków i lokalizacją GPS, połączoną 24/7 z centrum interwencyjnym (Moduł II: Teleopieka). Wystarczy nacisnąć przycisk lub opaska wykryje upadek, a operator skontaktuje się głosowo i wezwie pomoc. Moduł I to usługi sąsiedzkie: zorganizowana pomoc sąsiadów w codziennych sprawach. BRAK kryterium dochodowego, każdy senior 60+ może skorzystać. Dla seniora program jest bezpłatny, gmina pokrywa koszty z dofinansowaniem do 80% z budżetu państwa. Częsty błąd: założenie, że program działa w każdej gminie, gmina musi sama przystąpić, nie wszystkie to zrobiły. Praktyczna rada: zadzwoń do MOPS/GOPS i zapytaj, czy gmina przystąpiła. Jeśli nie, zgłoś zapotrzebowanie, im więcej seniorów pyta, tym większa szansa, że gmina przystąpi w następnym naborze.',
    kategoria: 'SENIOR',
    kwota: 'bezpłatna opaska bezpieczeństwa + dostęp do centrum interwencyjnego 24/7',
    kwotaMin: 0, kwotaMax: 0,
    czestotliwosc: 'ciągłe (cały rok)',
    wymagania: { wiekMin: 60 },
    wykluczenia: [],
    wniosek: {
      kanal: ['MOPS'],
      dokumenty: [
        'Dowód osobisty',
        'Brak kryterium dochodowego, nie trzeba zaświadczeń o dochodach',
      ],
      kroki: [
        'Sprawdź, czy Twoja gmina przystąpiła do programu Korpus Wsparcia Seniorów',
        'Skontaktuj się z MOPS/GOPS w swojej gminie',
        'Złóż wniosek o udział w Module I (usługi sąsiedzkie) lub Module II (teleopieka)',
        'Moduł II: otrzymasz opaskę bezpieczeństwa z przyciskiem SOS i czujnikiem upadków',
        'Opaska łączy Cię 24/7 z centrum interwencyjnym, wystarczy nacisnąć przycisk',
      ],
      terminRealizacji: 'Zależnie od gminy, zwykle kilka tygodni od złożenia wniosku',
      pulapki: [
        'BRAK kryterium dochodowego, każdy senior 60+ może skorzystać',
        'Moduł I: usługi sąsiedzkie (pomoc sąsiadów w codziennych czynnościach)',
        'Moduł II: teleopieka, opaska z GPS, czujnik upadków, przycisk SOS, kontakt głosowy z operatorem',
        'Gmina dostaje do 80% dofinansowania kosztów, dla seniora bezpłatne',
        'Nie każda gmina przystępuje, sprawdź w swoim MOPS',
      ],
      odwolanie: 'Program dobrowolny, decyzja gminy',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/program-korpus-wsparcia-seniorow-na-rok-2026',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'karta-seniora', nazwa: 'Ogólnopolska Karta Seniora',
    opis: 'Ogólnopolska Karta Seniora to karta zniżkowa dla osób 60+ dająca rabaty 5-30% w ponad 5000 punktach w Polsce: apteki, sanatoria, rehabilitacja, optycy, kina, teatry, restauracje, fryzjerzy, sklepy. Prowadzona przez Stowarzyszenie MANKO. W gminach zrzeszonych w programie Gmina Przyjazna Seniorom (360+ gmin) karta jest BEZPŁATNA. Poza programem gminnym karta kosztuje 35 PLN/1 rok lub 50 PLN/2 lata. Karta zawiera imię, nazwisko i zdjęcie. Okazujesz ją przy płatności w punktach partnerskich (lista na kartaseniora.pl). Częsty błąd: mylenie z lokalnymi kartami seniora, wiele miast (Warszawa, Kraków, Wrocław) ma WŁASNE karty z innymi zniżkami. Można mieć obie jednocześnie. Praktyczna rada: sprawdź najpierw, czy Twoja gmina jest w programie (bezpłatna karta), a potem porównaj z lokalną kartą seniora, najczęściej warto mieć obie.',
    kategoria: 'SENIOR',
    kwota: 'zniżki 5-30% w ponad 5000 punktach w Polsce',
    kwotaMin: 0, kwotaMax: 0,
    czestotliwosc: 'ciągłe (ważna 1-2 lata)',
    wymagania: { wiekMin: 60 },
    wykluczenia: [],
    wniosek: {
      kanal: ['ONLINE', 'URZAD_GMINY'],
      dokumenty: [
        'Dowód osobisty (potwierdzenie wieku 60+)',
        'Zdjęcie (do karty)',
      ],
      kroki: [
        'Sprawdź, czy Twoja gmina uczestniczy w Programie Gmina Przyjazna Seniorom (bezpłatna karta)',
        'Jeśli tak, złóż wniosek w urzędzie gminy lub online na stronie programu',
        'Jeśli nie, wykup członkostwo w Stowarzyszeniu MANKO: 35 PLN/1 rok lub 50 PLN/2 lata',
        'Otrzymasz kartę z imieniem, nazwiskiem i zdjęciem',
        'Okazuj kartę w punktach partnerskich (lista na kartaseniora.pl)',
      ],
      terminRealizacji: 'Do 14 dni roboczych',
      pulapki: [
        'W gminach zrzeszonych (360+ gmin), karta BEZPŁATNA',
        'Poza programem gminnym, opłata 35 PLN/rok lub 50 PLN/2 lata',
        'Zniżki: apteki, sanatoria, rehabilitacja, optycy, kina, teatry, restauracje, fryzjerzy',
        'Nie jest to karta urzędowa, to program Stowarzyszenia MANKO',
        'Każde miasto może mieć też WŁASNĄ Kartę Seniora z lokalnymi zniżkami',
      ],
      odwolanie: 'Nie dotyczy, program dobrowolny',
    },
    zrodloUrl: 'https://glosseniora.pl/ogolnopolska-karta-seniora/',
    zrodloNazwa: 'Stowarzyszenie MANKO', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'zasilek-pielegnacyjny', nazwa: 'Zasiłek pielęgnacyjny',
    opis: 'Zasiłek pielęgnacyjny wynosi 215,84 PLN miesięcznie i jest wypłacany przez gminę (nie ZUS). Przysługuje: osobom 75+ z mocy prawa, dzieciom z orzeczeniem o niepełnosprawności, dorosłym z orzeczeniem o znacznym stopniu niepełnosprawności, oraz dorosłym z orzeczeniem o umiarkowanym stopniu, jeśli niepełnosprawność powstała przed 21. rokiem życia. BRAK kryterium dochodowego. Wniosek na formularzu SR-5 w urzędzie gminy, MOPS lub elektronicznie przez portal Empatia. Częsty błąd: pobieranie jednocześnie zasiłku pielęgnacyjnego (215,84 PLN z gminy) i dodatku pielęgnacyjnego (348,22 PLN z ZUS). To NIEDOZWOLONE, musisz wybrać jedno świadczenie. Dla osób 75+ korzystniejszy jest dodatek pielęgnacyjny z ZUS (wyższa kwota, automatycznie). Waloryzacja co 3 lata, najbliższa w 2027. Praktyczna rada: jeśli masz 75+ i dostajesz emeryturę z ZUS, sprawdź czy nie masz automatycznie dodatku pielęgnacyjnego, wtedy zasiłek pielęgnacyjny Ci nie przysługuje.',
    kategoria: 'SENIOR',
    kwota: '215,84 PLN miesięcznie', kwotaMin: 215.84, kwotaMax: 215.84,
    czestotliwosc: 'miesięcznie',
    wymagania: { wiekMin: 75 },
    wykluczenia: [
      { opis: 'Nie przysługuje osobom pobierającym dodatek pielęgnacyjny z ZUS', sprawdz: 'dodatek_pielegnacyjny' },
      { opis: 'Nie przysługuje osobom umieszczonym w instytucji zapewniającej całodobową opiekę', sprawdz: 'instytucja_opieki' },
    ],
    wniosek: {
      kanal: ['URZAD_GMINY', 'MOPS', 'EMPATIA'], formularz: 'SR-5',
      dokumenty: [
        'Dowód osobisty',
        'Orzeczenie o niepełnosprawności (dla osób poniżej 75 lat)',
        'Dla osób 75+, wystarczy dowód osobisty (przyznawany z mocy prawa)',
      ],
      kroki: [
        'Dla osób 75+: zasiłek przysługuje z mocy prawa, złóż wniosek SR-5 w urzędzie gminy lub przez Empatię',
        'Dla osób poniżej 75 lat: uzyskaj orzeczenie o niepełnosprawności',
        'Wypełnij formularz SR-5',
        'Złóż wniosek w urzędzie gminy, MOPS lub elektronicznie przez portal Empatia',
        'Decyzja w ciągu 30 dni',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'BRAK kryterium dochodowego, przysługuje niezależnie od zarobków',
        'Nie łączy się z dodatkiem pielęgnacyjnym z ZUS, musisz wybrać jedno',
        'Dla osób 75+ przyznawany z mocy prawa, ale TRZEBA złożyć wniosek',
        'Waloryzacja co 3 lata, najbliższa w 2027 roku',
        'Przysługuje też dzieciom z orzeczeniem i dorosłym z niepełnosprawnością od przed 21 r.ż.',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/zasilek-pielegnacyjny',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-10', dataWaznosci: '2027-10-31',
  },
  {
    id: 'swiadczenie-pielegnacyjne', nazwa: 'Świadczenie pielęgnacyjne (nowe zasady 2024+)',
    opis: 'Świadczenie pielęgnacyjne wynosi 3386 PLN miesięcznie (2026) i przysługuje rodzicowi/opiekunowi dziecka z niepełnosprawnością. Od 2024 obowiązują NOWE zasady: opiekun MOŻE pracować zarobkowo bez limitu dochodów, ale świadczenie przysługuje TYLKO do 18. roku życia dziecka. Na drugie i kolejne dziecko z niepełnosprawnością kwota rośnie o 100% (6772 PLN na dwoje dzieci). BRAK kryterium dochodowego. Osoby, które korzystały ze świadczenia na STARYCH zasadach (sprzed 2024), mogą na nich pozostać. Na starych zasadach opiekun NIE może pracować, ale świadczenie nie ma limitu wiekowego dziecka. Wybór między starymi a nowymi zasadami jest kluczowy i zależy od indywidualnej sytuacji. Waloryzacja co roku 1 stycznia. Wniosek SR-5Z w urzędzie gminy, MOPS lub przez Empatię. Częsty błąd: automatyczne przejście na nowe zasady bez kalkulacji, jeśli dziecko ma np. 16 lat i opiekun nie pracuje, nowe zasady dadzą świadczenie tylko na 2 lata. Praktyczna rada: przed zmianą zasad skonsultuj się z prawnikiem lub pracownikiem MOPS.',
    kategoria: 'SENIOR',
    kwota: '3386 PLN miesięcznie (2026)', kwotaMin: 3386, kwotaMax: 6772,
    czestotliwosc: 'miesięcznie',
    wymagania: { dzieci: { min: 1 } },
    wykluczenia: [
      { opis: 'Na nowych zasadach: tylko na dziecko do 18 roku życia z niepełnosprawnością', sprawdz: 'wiek_dziecka_niepelnosprawnego' },
    ],
    wniosek: {
      kanal: ['URZAD_GMINY', 'MOPS', 'EMPATIA'], formularz: 'SR-5Z',
      dokumenty: [
        'Orzeczenie o niepełnosprawności dziecka (znaczny stopień lub wskazanie stałej/długotrwałej opieki)',
        'Dowód osobisty rodzica/opiekuna',
        'Akt urodzenia dziecka',
        'Numer konta bankowego',
      ],
      kroki: [
        'Uzyskaj orzeczenie o niepełnosprawności dziecka z zespołu orzekającego',
        'Wypełnij wniosek SR-5Z o świadczenie pielęgnacyjne',
        'Złóż wniosek w urzędzie gminy, MOPS lub elektronicznie przez Empatię',
        'Decyzja w ciągu 30 dni',
        'Świadczenie wypłacane co miesiąc na konto',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'NOWE zasady od 2024: opiekun MOŻE pracować bez limitu zarobków',
        'Nowe zasady: świadczenie przysługuje TYLKO do 18 r.ż. dziecka',
        'Na drugie i kolejne dziecko z niepełnosprawnością, +100% (czyli 6772 PLN na dwoje dzieci)',
        'Stare zasady (sprzed 2024): opiekun NIE może pracować, ale świadczenie bez limitu wieku dziecka',
        'Osoby na starych zasadach mogą na nich pozostać, nie muszą przechodzić na nowe',
        'Rolnicy od 2024 nie muszą rezygnować z gospodarstwa',
        'BRAK kryterium dochodowego',
        'Waloryzacja co roku 1 stycznia',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/swiadczenie-pielegnacyjne',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'dzienny-dom-pomocy', nazwa: 'Dzienny Dom Pomocy / Senior+',
    opis: 'Dzienny Dom Pomocy (dawniej Senior+, od 2026 program Aktywni Seniorzy 2026-2030) to placówka dziennego pobytu dla osób 60+, otwarta w dni robocze min. 8 godzin dziennie. Oferuje: ciepłe posiłki, zajęcia edukacyjne i kulturalne, rehabilitację, terapię zajęciową, kontakty społeczne. Wartość usług ok. 1000-2000 PLN/mies., a odpłatność ustalana przez gminę zależnie od dochodu (często bezpłatne dla osób o niskich dochodach). Procedura: wniosek w MOPS/GOPS, wywiad środowiskowy, decyzja o skierowaniu. Częsty błąd: szukanie Dziennego Domu Senior+ pod starą nazwą. Od 2026 program zmienił nazwę na Aktywni Seniorzy. Nie każda gmina ma taką placówkę. Praktyczna rada: jeśli w Twojej gminie nie ma Dziennego Domu Pomocy, sprawdź gminy sąsiednie lub zapytaj w MOPS o Kluby Seniora (prostsza forma, min. 2 dni w tygodniu po 4 godziny).',
    kategoria: 'SENIOR',
    kwota: 'bezpłatne lub częściowo odpłatne usługi dzienne (wartość ok. 1000-2000 PLN/mies.)',
    kwotaMin: 0, kwotaMax: 0,
    czestotliwosc: 'ciągłe (dni robocze, min. 8h dziennie)',
    wymagania: { wiekMin: 60 },
    wykluczenia: [],
    wniosek: {
      kanal: ['MOPS'],
      dokumenty: [
        'Dowód osobisty',
        'Zaświadczenie o dochodach',
        'Zaświadczenie lekarskie o braku przeciwwskazań',
      ],
      kroki: [
        'Znajdź Dzienny Dom Pomocy / Dzienny Dom Senior+ w swojej gminie',
        'Złóż wniosek w MOPS/GOPS o skierowanie',
        'Pracownik socjalny przeprowadzi wywiad środowiskowy',
        'MOPS wyda decyzję o skierowaniu i ewentualnej odpłatności',
        'Korzystaj z pobytu dziennego: posiłki, zajęcia aktywizujące, rehabilitacja, kontakty społeczne',
      ],
      terminRealizacji: 'Decyzja w ciągu 30 dni',
      pulapki: [
        'Program Senior+ formalnie zakończył się 31.12.2025, od 2026 program Aktywni Seniorzy 2026-2030',
        'Odpłatność ustalana przez gminę, zależna od dochodu',
        'Oferta: posiłki, zajęcia edukacyjne, kulturalne, rehabilitacja, terapia zajęciowa',
        'Nie każda gmina ma taki dom, sprawdź lokalnie',
        'Dostępne min. 8h dziennie, poniedziałek-piątek',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni od decyzji',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/program-senior',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'refundacja-okulary-nfz', nazwa: 'Refundacja okularów i soczewek z NFZ',
    opis: 'Refundacja okularów z NFZ pokrywa część kosztu szkieł korekcyjnych (NIE oprawek). Limity: wada do +-6 dioptrii: 50 PLN za parę szkieł (25 PLN/szkło); wada powyżej +-6,25 D: do 200 PLN za parę; wada powyżej +-10 D,do 700 PLN za parę. Soczewki kontaktowe: do 600 PLN, ale tylko przy określonych schorzeniach (stożek rogówki, afakia, duża anizometropia). Zlecenie wystawia okulista z kontraktem NFZ (od 2026 także optometrysta). Zlecenie jest elektroniczne (eZWM), automatycznie weryfikowane. Realizujesz je u optyka mającego umowę z NFZ, dopłata odliczana od razu przy zakupie. Dorośli: raz na 2 lata, dzieci: co rok (lub częściej przy zmianie wady). Częsty błąd: oczekiwanie refundacji oprawek lub powłok (antyrefleks, fotochrom), te elementy płacisz z własnej kieszeni. Praktyczna rada: pracownicy przy komputerze mogą uzyskać DODATKOWE dofinansowanie od pracodawcy (średnio 450 PLN) na mocy Kodeksu pracy, poproś o to w dziale kadr.',
    kategoria: 'SENIOR',
    kwota: '50-700 PLN na szkła okularowe, do 600 PLN na soczewki kontaktowe',
    kwotaMin: 50, kwotaMax: 700,
    czestotliwosc: 'raz na 2 lata (dorośli)',
    wymagania: {},
    wykluczenia: [
      { opis: 'Zlecenie musi być wystawione przez okulistę z kontraktem NFZ', sprawdz: 'okulista_nfz' },
      { opis: 'Refundacja nie obejmuje oprawek ani dodatkowych powłok na szkłach', sprawdz: 'zakres_refundacji' },
    ],
    wniosek: {
      kanal: ['NFZ', 'POZ'],
      dokumenty: [
        'Zlecenie na wyrób medyczny od okulisty z kontraktem NFZ',
        'Dowód osobisty lub legitymacja emeryta/rencisty',
        'Karta ubezpieczenia zdrowotnego',
      ],
      kroki: [
        'Umów się na wizytę u okulisty mającego kontrakt z NFZ',
        'Okulista wystawi zlecenie na wyrób medyczny (szkła korekcyjne lub soczewki)',
        'Zlecenie jest automatycznie weryfikowane w systemie eZWM',
        'Udaj się do optyka realizującego zlecenia NFZ',
        'Optyk zrealizuje zlecenie, dopłata NFZ zostanie odliczona od ceny szkieł',
      ],
      terminRealizacji: 'Realizacja od ręki u optyka (po uzyskaniu zlecenia)',
      pulapki: [
        'Limity refundacji szkieł dla dorosłych: 50 PLN (wada do +/-6 dptr), 200 PLN (+/-6,25 do +/-10 dptr), 700 PLN (powyżej +/-10 dptr)',
        'Refundacja dotyczy TYLKO szkieł, oprawki i powłoki (antyrefleks, fotochrom) na własny koszt',
        'Dorosłym przysługuje raz na 2 lata, dzieciom częściej, jeśli zmieni się wada',
        'Soczewki kontaktowe do 600 PLN, ale tylko przy określonych schorzeniach (np. stożek rogówki, afakia)',
        'Nie każdy okulista ma kontrakt NFZ, sprawdź przed wizytą',
      ],
      odwolanie: 'Reklamacja do Oddziału Wojewódzkiego NFZ',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/wyroby-medyczne/',
    zrodloNazwa: 'Narodowy Fundusz Zdrowia', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
];
