import { Benefit } from '../types';

export const SENIOR: Benefit[] = [
  {
    id: 'opieka-75-plus', nazwa: 'Program Opieka 75+',
    opis: 'Program Opieka 75+ zapewnia bezpłatne lub częściowo odpłatne usługi opiekuńcze w domu dla seniorów w gminach do 60 000 mieszkańców. Opiekun przychodzi do domu i pomaga w codziennych czynnościach: zakupy, gotowanie, sprzątanie, higiena osobista, pomoc w kontaktach z lekarzem. Koszt godziny usługi ustalany przez gminę (ok. 30-50 PLN/h), ale przy dochodzie do 250% kryterium dochodowego (2525 PLN) usługi są bezpłatne. Powyżej tego progu odpłatność ustalana wg uchwały gminy. Procedura: wniosek w GOPS/MOPS, wywiad środowiskowy w domu, decyzja administracyjna o zakresie i odpłatności usług. Częsty błąd: mieszkańcy dużych miast (powyżej 60 000 mieszkańców) szukają tego programu. Duże miasta mają odrębne programy usług opiekuńczych, o które trzeba pytać w miejskim MOPS. Praktyczna rada: nie każda gmina przystąpiła do programu, zadzwoń do GOPS i zapytaj wprost.',
    kategoria: 'SENIOR',
    kwota: 'bezpłatne lub częściowo odpłatne usługi opiekuńcze (koszt godziny ustala gmina, ok. 30-50 PLN/h)',
    kwotaMin: 0, kwotaMax: 0,
    czestotliwosc: 'ciągłe (usługi opiekuńcze w domu)',
    wymagania: { wiekMin: 75 },
    wykluczenia: [
      { opis: 'Gminy powyżej 60 000 mieszkańców nie uczestniczą w programie', sprawdz: 'wielkosc_gminy' },
    ],
    wniosek: {
      kanal: ['MOPS'],
      dokumenty: [
        'Dowód osobisty',
        'Zaświadczenie o dochodach (dochód do 250% kryterium = 2525 PLN, bezpłatnie)',
        'Zaświadczenie lekarskie o stanie zdrowia (opcjonalnie)',
      ],
      kroki: [
        'Skontaktuj się z GOPS/MOPS w swojej gminie i zapytaj czy gmina przystąpiła do programu Opieka 75+',
        'Złóż wniosek o usługi opiekuńcze w GOPS/MOPS',
        'Pracownik socjalny przeprowadzi wywiad środowiskowy w Twoim domu',
        'GOPS wyda decyzję administracyjną o przyznaniu usług i ewentualnej odpłatności',
        'Opiekun zacznie wizyty domowe wg ustalonego harmonogramu',
      ],
      terminRealizacji: 'Decyzja w ciągu 30 dni od wywiadu środowiskowego',
      pulapki: [
        'Program dotyczy TYLKO gmin do 60 000 mieszkańców, duże miasta mają odrębne programy',
        'Dochód do 250% kryterium (2525 PLN) = bezpłatne usługi. Powyżej, odpłatność wg uchwały gminy',
        'Gmina musi sama przystąpić do programu, nie wszystkie to zrobiły',
        'Usługi obejmują: pomoc w codziennych czynnościach, higienę, zakupy, przygotowanie posiłków',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni od decyzji',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/program-opieka-75-na-rok-2026',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'korpus-wsparcia-seniorow', nazwa: 'Korpus Wsparcia Seniorów (Teleopieka)',
    opis: 'Korpus Wsparcia Seniorów to program zapewniający osobom 60+ bezpłatną opaskę bezpieczeństwa z przyciskiem SOS, czujnikiem upadków i lokalizacją GPS, połączoną 24/7 z centrum interwencyjnym (Moduł II: Teleopieka). Wystarczy nacisnąć przycisk lub opaska wykryje upadek, a operator skontaktuje się głosowo i wezwie pomoc. Moduł I to usługi sąsiedzkie: zorganizowana pomoc sąsiadów w codziennych sprawach. BRAK kryterium dochodowego, każdy senior 60+ może skorzystać. Dla seniora program jest bezpłatny, gmina pokrywa koszty z dofinansowaniem do 80% z budżetu państwa. Częsty błąd: założenie, że program działa w każdej gminie, gmina musi sama przystąpić, nie wszystkie to zrobiły. Praktyczna rada: zadzwoń do MOPS/GOPS i zapytaj, czy gmina przystąpiła. Jeśli nie, zgłoś zapotrzebowanie, im więcej seniorów pyta, tym większa szansa, że gmina przystąpi w następnym naborze.',
    kategoria: 'SENIOR',
    kwota: 'bezpłatna opaska bezpieczeństwa + dostęp do centrum interwencyjnego 24/7',
    kwotaMin: 0, kwotaMax: 0,
    czestotliwosc: 'ciągłe (cały rok)',
    wymagania: { wiekMin: 60 },
    wykluczenia: [],
    wniosek: {
      kanal: ['MOPS'],
      dokumenty: [
        'Dowód osobisty',
        'Brak kryterium dochodowego, nie trzeba zaświadczeń o dochodach',
      ],
      kroki: [
        'Sprawdź, czy Twoja gmina przystąpiła do programu Korpus Wsparcia Seniorów',
        'Skontaktuj się z MOPS/GOPS w swojej gminie',
        'Złóż wniosek o udział w Module I (usługi sąsiedzkie) lub Module II (teleopieka)',
        'Moduł II: otrzymasz opaskę bezpieczeństwa z przyciskiem SOS i czujnikiem upadków',
        'Opaska łączy Cię 24/7 z centrum interwencyjnym, wystarczy nacisnąć przycisk',
      ],
      terminRealizacji: 'Zależnie od gminy, zwykle kilka tygodni od złożenia wniosku',
      pulapki: [
        'BRAK kryterium dochodowego, każdy senior 60+ może skorzystać',
        'Moduł I: usługi sąsiedzkie (pomoc sąsiadów w codziennych czynnościach)',
        'Moduł II: teleopieka, opaska z GPS, czujnik upadków, przycisk SOS, kontakt głosowy z operatorem',
        'Gmina dostaje do 80% dofinansowania kosztów, dla seniora bezpłatne',
        'Nie każda gmina przystępuje, sprawdź w swoim MOPS',
      ],
      odwolanie: 'Program dobrowolny, decyzja gminy',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/program-korpus-wsparcia-seniorow-na-rok-2026',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'karta-seniora', nazwa: 'Ogólnopolska Karta Seniora',
    opis: 'Ogólnopolska Karta Seniora to karta zniżkowa dla osób 60+ dająca rabaty 5-30% w ponad 5000 punktach w Polsce: apteki, sanatoria, rehabilitacja, optycy, kina, teatry, restauracje, fryzjerzy, sklepy. Prowadzona przez Stowarzyszenie MANKO. W gminach zrzeszonych w programie Gmina Przyjazna Seniorom (360+ gmin) karta jest BEZPŁATNA. Poza programem gminnym karta kosztuje 35 PLN/1 rok lub 50 PLN/2 lata. Karta zawiera imię, nazwisko i zdjęcie. Okazujesz ją przy płatności w punktach partnerskich (lista na kartaseniora.pl). Częsty błąd: mylenie z lokalnymi kartami seniora, wiele miast (Warszawa, Kraków, Wrocław) ma WŁASNE karty z innymi zniżkami. Można mieć obie jednocześnie. Praktyczna rada: sprawdź najpierw, czy Twoja gmina jest w programie (bezpłatna karta), a potem porównaj z lokalną kartą seniora, najczęściej warto mieć obie.',
    kategoria: 'SENIOR',
    kwota: 'zniżki 5-30% w ponad 5000 punktach w Polsce',
    kwotaMin: 0, kwotaMax: 0,
    czestotliwosc: 'ciągłe (ważna 1-2 lata)',
    wymagania: { wiekMin: 60 },
    wykluczenia: [],
    wniosek: {
      kanal: ['ONLINE', 'URZAD_GMINY'],
      dokumenty: [
        'Dowód osobisty (potwierdzenie wieku 60+)',
        'Zdjęcie (do karty)',
      ],
      kroki: [
        'Sprawdź, czy Twoja gmina uczestniczy w Programie Gmina Przyjazna Seniorom (bezpłatna karta)',
        'Jeśli tak, złóż wniosek w urzędzie gminy lub online na stronie programu',
        'Jeśli nie, wykup członkostwo w Stowarzyszeniu MANKO: 35 PLN/1 rok lub 50 PLN/2 lata',
        'Otrzymasz kartę z imieniem, nazwiskiem i zdjęciem',
        'Okazuj kartę w punktach partnerskich (lista na kartaseniora.pl)',
      ],
      terminRealizacji: 'Do 14 dni roboczych',
      pulapki: [
        'W gminach zrzeszonych (360+ gmin), karta BEZPŁATNA',
        'Poza programem gminnym, opłata 35 PLN/rok lub 50 PLN/2 lata',
        'Zniżki: apteki, sanatoria, rehabilitacja, optycy, kina, teatry, restauracje, fryzjerzy',
        'Nie jest to karta urzędowa, to program Stowarzyszenia MANKO',
        'Każde miasto może mieć też WŁASNĄ Kartę Seniora z lokalnymi zniżkami',
      ],
      odwolanie: 'Nie dotyczy, program dobrowolny',
    },
    zrodloUrl: 'https://glosseniora.pl/ogolnopolska-karta-seniora/',
    zrodloNazwa: 'Stowarzyszenie MANKO', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'zasilek-pielegnacyjny', nazwa: 'Zasiłek pielęgnacyjny',
    opis: 'Zasiłek pielęgnacyjny wynosi 215,84 PLN miesięcznie i jest wypłacany przez gminę (nie ZUS). Przysługuje: osobom 75+ z mocy prawa, dzieciom z orzeczeniem o niepełnosprawności, dorosłym z orzeczeniem o znacznym stopniu niepełnosprawności, oraz dorosłym z orzeczeniem o umiarkowanym stopniu, jeśli niepełnosprawność powstała przed 21. rokiem życia. BRAK kryterium dochodowego. Wniosek na formularzu SR-5 w urzędzie gminy, MOPS lub elektronicznie przez portal Empatia. Częsty błąd: pobieranie jednocześnie zasiłku pielęgnacyjnego (215,84 PLN z gminy) i dodatku pielęgnacyjnego (366,68 PLN z ZUS po waloryzacji marzec 2026). To NIEDOZWOLONE, musisz wybrać jedno świadczenie. Dla osób 75+ korzystniejszy jest dodatek pielęgnacyjny z ZUS (wyższa kwota, automatycznie). Waloryzacja co 3 lata, najbliższa w 2027. Praktyczna rada: jeśli masz 75+ i dostajesz emeryturę z ZUS, sprawdź czy nie masz automatycznie dodatku pielęgnacyjnego, wtedy zasiłek pielęgnacyjny Ci nie przysługuje.',
    kategoria: 'SENIOR',
    kwota: '215,84 PLN miesięcznie', kwotaMin: 215.84, kwotaMax: 215.84,
    czestotliwosc: 'miesięcznie',
    wymagania: { wiekMin: 75 },
    wykluczenia: [
      { opis: 'Nie przysługuje osobom pobierającym dodatek pielęgnacyjny z ZUS', sprawdz: 'dodatek_pielegnacyjny' },
      { opis: 'Nie przysługuje osobom umieszczonym w instytucji zapewniającej całodobową opiekę', sprawdz: 'instytucja_opieki' },
    ],
    wniosek: {
      kanal: ['URZAD_GMINY', 'MOPS', 'EMPATIA'], formularz: 'SR-5',
      dokumenty: [
        'Dowód osobisty',
        'Orzeczenie o niepełnosprawności (dla osób poniżej 75 lat)',
        'Dla osób 75+, wystarczy dowód osobisty (przyznawany z mocy prawa)',
      ],
      kroki: [
        'Dla osób 75+: zasiłek przysługuje z mocy prawa, złóż wniosek SR-5 w urzędzie gminy lub przez Empatię',
        'Dla osób poniżej 75 lat: uzyskaj orzeczenie o niepełnosprawności',
        'Wypełnij formularz SR-5',
        'Złóż wniosek w urzędzie gminy, MOPS lub elektronicznie przez portal Empatia',
        'Decyzja w ciągu 30 dni',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'BRAK kryterium dochodowego, przysługuje niezależnie od zarobków',
        'Nie łączy się z dodatkiem pielęgnacyjnym z ZUS, musisz wybrać jedno',
        'Dla osób 75+ przyznawany z mocy prawa, ale TRZEBA złożyć wniosek',
        'Waloryzacja co 3 lata, najbliższa w 2027 roku',
        'Przysługuje też dzieciom z orzeczeniem i dorosłym z niepełnosprawnością od przed 21 r.ż.',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/zasilek-pielegnacyjny',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-23', dataWaznosci: '2027-10-31',
  },
  {
    id: 'swiadczenie-pielegnacyjne', nazwa: 'Świadczenie pielęgnacyjne (nowe zasady 2024+)',
    opis: 'Świadczenie pielęgnacyjne wynosi 3386 PLN miesięcznie (2026) i przysługuje rodzicowi/opiekunowi dziecka z niepełnosprawnością. Od 2024 obowiązują NOWE zasady: opiekun MOŻE pracować zarobkowo bez limitu dochodów, ale świadczenie przysługuje TYLKO do 18. roku życia dziecka. Na drugie i kolejne dziecko z niepełnosprawnością kwota rośnie o 100% (6772 PLN na dwoje dzieci). BRAK kryterium dochodowego. Osoby, które korzystały ze świadczenia na STARYCH zasadach (sprzed 2024), mogą na nich pozostać. Na starych zasadach opiekun NIE może pracować, ale świadczenie nie ma limitu wiekowego dziecka. Wybór między starymi a nowymi zasadami jest kluczowy i zależy od indywidualnej sytuacji. Waloryzacja co roku 1 stycznia. Wniosek SR-5Z w urzędzie gminy, MOPS lub przez Empatię. Częsty błąd: automatyczne przejście na nowe zasady bez kalkulacji, jeśli dziecko ma np. 16 lat i opiekun nie pracuje, nowe zasady dadzą świadczenie tylko na 2 lata. Praktyczna rada: przed zmianą zasad skonsultuj się z prawnikiem lub pracownikiem MOPS.',
    kategoria: 'SENIOR',
    kwota: '3386 PLN miesięcznie (2026)', kwotaMin: 3386, kwotaMax: 6772,
    czestotliwosc: 'miesięcznie',
    wymagania: { dzieci: { min: 1 } },
    wykluczenia: [
      { opis: 'Na nowych zasadach: tylko na dziecko do 18 roku życia z niepełnosprawnością', sprawdz: 'wiek_dziecka_niepelnosprawnego' },
    ],
    wniosek: {
      kanal: ['URZAD_GMINY', 'MOPS', 'EMPATIA'], formularz: 'SR-5Z',
      dokumenty: [
        'Orzeczenie o niepełnosprawności dziecka (znaczny stopień lub wskazanie stałej/długotrwałej opieki)',
        'Dowód osobisty rodzica/opiekuna',
        'Akt urodzenia dziecka',
        'Numer konta bankowego',
      ],
      kroki: [
        'Uzyskaj orzeczenie o niepełnosprawności dziecka z zespołu orzekającego',
        'Wypełnij wniosek SR-5Z o świadczenie pielęgnacyjne',
        'Złóż wniosek w urzędzie gminy, MOPS lub elektronicznie przez Empatię',
        'Decyzja w ciągu 30 dni',
        'Świadczenie wypłacane co miesiąc na konto',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'NOWE zasady od 2024: opiekun MOŻE pracować bez limitu zarobków',
        'Nowe zasady: świadczenie przysługuje TYLKO do 18 r.ż. dziecka',
        'Na drugie i kolejne dziecko z niepełnosprawnością, +100% (czyli 6772 PLN na dwoje dzieci)',
        'Stare zasady (sprzed 2024): opiekun NIE może pracować, ale świadczenie bez limitu wieku dziecka',
        'Osoby na starych zasadach mogą na nich pozostać, nie muszą przechodzić na nowe',
        'Rolnicy od 2024 nie muszą rezygnować z gospodarstwa',
        'BRAK kryterium dochodowego',
        'Waloryzacja co roku 1 stycznia',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/swiadczenie-wspierajace-i-swiadczenie-pielegnacyjne---informacje',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-25', dataWaznosci: '2026-12-31',
  },
  {
    id: 'dzienny-dom-pomocy', nazwa: 'Dzienny Dom Pomocy / Senior+',
    opis: 'Dzienny Dom Pomocy (dawniej Senior+, od 2026 program Aktywni Seniorzy 2026-2030) to placówka dziennego pobytu dla osób 60+, otwarta w dni robocze min. 8 godzin dziennie. Oferuje: ciepłe posiłki, zajęcia edukacyjne i kulturalne, rehabilitację, terapię zajęciową, kontakty społeczne. Wartość usług ok. 1000-2000 PLN/mies., a odpłatność ustalana przez gminę zależnie od dochodu (często bezpłatne dla osób o niskich dochodach). Procedura: wniosek w MOPS/GOPS, wywiad środowiskowy, decyzja o skierowaniu. Częsty błąd: szukanie Dziennego Domu Senior+ pod starą nazwą. Od 2026 program zmienił nazwę na Aktywni Seniorzy. Nie każda gmina ma taką placówkę. Praktyczna rada: jeśli w Twojej gminie nie ma Dziennego Domu Pomocy, sprawdź gminy sąsiednie lub zapytaj w MOPS o Kluby Seniora (prostsza forma, min. 2 dni w tygodniu po 4 godziny).',
    kategoria: 'SENIOR',
    kwota: 'bezpłatne lub częściowo odpłatne usługi dzienne (wartość ok. 1000-2000 PLN/mies.)',
    kwotaMin: 0, kwotaMax: 0,
    czestotliwosc: 'ciągłe (dni robocze, min. 8h dziennie)',
    wymagania: { wiekMin: 60 },
    wykluczenia: [],
    wniosek: {
      kanal: ['MOPS'],
      dokumenty: [
        'Dowód osobisty',
        'Zaświadczenie o dochodach',
        'Zaświadczenie lekarskie o braku przeciwwskazań',
      ],
      kroki: [
        'Znajdź Dzienny Dom Pomocy / Dzienny Dom Senior+ w swojej gminie',
        'Złóż wniosek w MOPS/GOPS o skierowanie',
        'Pracownik socjalny przeprowadzi wywiad środowiskowy',
        'MOPS wyda decyzję o skierowaniu i ewentualnej odpłatności',
        'Korzystaj z pobytu dziennego: posiłki, zajęcia aktywizujące, rehabilitacja, kontakty społeczne',
      ],
      terminRealizacji: 'Decyzja w ciągu 30 dni',
      pulapki: [
        'Program Senior+ formalnie zakończył się 31.12.2025, od 2026 program Aktywni Seniorzy 2026-2030',
        'Odpłatność ustalana przez gminę, zależna od dochodu',
        'Oferta: posiłki, zajęcia edukacyjne, kulturalne, rehabilitacja, terapia zajęciowa',
        'Nie każda gmina ma taki dom, sprawdź lokalnie',
        'Dostępne min. 8h dziennie, poniedziałek-piątek',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni od decyzji',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/program-wieloletni-senior-na-lata-2021-2025',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-07-06', dataWaznosci: '2026-12-31',
  },
  {
    id: 'leki-senior-65plus', nazwa: 'Bezpłatne leki dla seniorów 65+',
    opis: 'Program bezpłatnych leków dla osób, które ukończyły 65 rok życia. Od 1 września 2023 r. program rozszerzono z grupy 75+ na 65+. Lista bezpłatnych leków obejmuje ponad 2000 preparatów na choroby przewlekłe: nadciśnienie, cukrzyca, niewydolność serca, osteoporoza, choroba Alzheimera, depresja, astma, POCHP i inne. Aktualna lista publikowana jest co 2 miesiące przez Ministerstwo Zdrowia (obwieszczenie refundacyjne). Warunki: ubezpieczenie w NFZ oraz wiek 65+. Leki może przepisać lekarz POZ, lekarz specjalista z kontraktem NFZ, lekarz AOS, a od 2024 r. pielęgniarka POZ i pielęgniarka AOS (w zakresie swoich uprawnień). Na recepcie musi pojawić się litera "S" lub "Senior 65+" - pytaj o to wprost. Bezpłatny lek można zastąpić odpłatnym odpowiednikiem (np. zamiennik innej firmy), ale wymagana jest zgoda pacjenta. Nie wszystkie leki na daną chorobę są w wykazie bezpłatnym: aptekarz lub lekarz może sprawdzić aktualny wykaz w systemie. Częste nieporozumienie: program nie dotyczy suplementów diety, środków spożywczych specjalnego przeznaczenia ani wyrobów medycznych (np. glukometrów). Praktyczna rada: przed każdą wizytą zapytaj lekarza czy przepisywany lek jest na liście bezpłatnych leków dla seniorów. Lista zmienia się co 2 miesiące.',
    kategoria: 'SENIOR',
    kwota: 'bezpłatne leki (oszczędność nawet kilkuset PLN miesięcznie)',
    kwotaMin: 0, kwotaMax: 0,
    czestotliwosc: 'ciągłe (przy każdej recepcie)',
    wymagania: { wiekMin: 65 },
    wykluczenia: [],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: [
        'Dowód osobisty (potwierdzenie wieku 65+)',
        'Karta ubezpieczenia zdrowotnego lub numer PESEL',
      ],
      kroki: [
        'Nie ma formalnego wniosku, wystarczy zgłosić się do lekarza',
        'Przy wizycie u lekarza POZ lub specjalisty powiedz, że masz 65+ i chcesz leki bezpłatne',
        'Lekarz sprawdzi, czy przepisywany lek jest na liście bezpłatnych leków dla seniorów',
        'Na recepcie pojawi się oznaczenie bezpłatności (litera "S" lub "Senior 65+")',
        'W aptece zapłacisz 0 PLN za leki z tej listy',
      ],
      terminRealizacji: 'Natychmiast przy wystawieniu recepty',
      pulapki: [
        'Lista leków bezpłatnych zmienia się co 2 miesiące, zawsze pytaj lekarza',
        'Nie obejmuje suplementów diety, środków spożywczych ani wyrobów medycznych',
        'Program dla ubezpieczonych w NFZ, wymagany wiek 65+',
        'Lekarz musi oznaczyć receptę, zapytaj o to wprost',
        'Ponad 2000 preparatów: nadciśnienie, cukrzyca, serce, osteoporoza, Alzheimer, astma i inne',
        'Możliwość zamiany na płatny odpowiednik innej firmy, ale to Twój wybór',
      ],
      odwolanie: 'Reklamacja do oddziału NFZ lub Rzecznika Praw Pacjenta',
    },
    zrodloUrl: 'https://www.gov.pl/web/zdrowie/',
    zrodloNazwa: 'Ministerstwo Zdrowia', dataWeryfikacji: '2026-05-27', dataWaznosci: '2026-12-31',
  },
  {
    id: 'bon-senioralny', nazwa: 'Bon senioralny (domowe usługi opiekuńcze)',
    opis: 'Bon senioralny to nowe świadczenie od 2026 roku zapewniające domowe usługi opiekuńcze dla seniorów 75+ w trudnej sytuacji. Kwota: do 2150 PLN miesięcznie dla osób 85+ z orzeczeniem i samotnych, niższe kwoty dla pozostałych grup 75+. Kryterium dochodowe: miesięczny dochód brutto nie może przekraczać 3410 PLN (podlega corocznej waloryzacji). Wymóg: orzeczenie o niepełnosprawności lub zaświadczenie lekarskie, zamieszkiwanie samotnie lub wyłącznie z innymi seniorami. Świadczenie nie jest wypłacane gotówką - gmina organizuje opiekuna, który przychodzi do domu. Usługi: opieka domowa, rehabilitacja, wsparcie pielęgniarskie, fizjoterapia, asystent osoby starszej. Pilot: III kwartał 2026 r. (woj. mazowieckie, wielkopolskie, dolnośląskie, pomorskie). Pełne wdrożenie w Polsce: I kwartał 2027. Bon senioralny zastępuje dotychczasowe programy: Opieka 75+, Asystent Osoby Starszej, Opieka Wytchnieniowa.',
    kategoria: 'SENIOR',
    kwota: 'do 2150 PLN/mies. w usługach opiekuńczych (zależnie od wieku i potrzeb)', kwotaMin: 0, kwotaMax: 2150,
    czestotliwosc: 'miesięcznie (usługi, nie gotówka)',
    wymagania: { wiekMin: 75, dochodMax: 3410 },
    wykluczenia: [
      { opis: 'Dochód przekracza 3410 PLN miesięcznie brutto', sprawdz: 'dochod_3410' },
      { opis: 'Brak orzeczenia o niepełnosprawności lub zaświadczenia lekarskiego', sprawdz: 'orzeczenie_niepelnosprawnosc' },
    ],
    wniosek: {
      kanal: ['MOPS'],
      dokumenty: [
        'Dowód osobisty (potwierdzenie wieku 75+)',
        'Orzeczenie o niepełnosprawności (stopień umiarkowany lub znaczny) LUB zaświadczenie lekarskie',
        'Zaświadczenie o dochodach (nie wyższe niż 3410 PLN/mies.)',
        'Oświadczenie o sytuacji życiowej (samotne zamieszkiwanie lub z innym seniorem)',
      ],
      kroki: [
        'Program jest na etapie pilotażu (woj. mazowieckie, wielkopolskie, dolnośląskie, pomorskie od Q3 2026)',
        'Pełne wdrożenie na terenie całego kraju planowane na I kwartał 2027',
        'Złóż wniosek w MOPS/GOPS właściwym dla miejsca zamieszkania',
        'Pracownik socjalny oceni potrzeby i zakres usług',
        'Gmina przydzieli opiekuna, który będzie przychodził do domu',
      ],
      terminRealizacji: 'Decyzja w ciągu 30 dni od złożenia wniosku (program pilotażowy)',
      pulapki: [
        'DO 2150 PLN/mies. dla seniorów 85+ z orzeczeniem, pozostali mogą otrzymać mniej',
        'Kryterium dochodowe: max 3410 PLN brutto/mies. (coroczna waloryzacja)',
        'NIE gotówka - gmina organizuje opiekuna (usługi opiekuńcze, nie przelew)',
        'Pilot od Q3 2026 tylko w 4 województwach, pełne wdrożenie od Q1 2027',
        'Wymóg: orzeczenie o niepełnosprawności LUB zaświadczenie lekarskie + zamieszkiwanie samotnie',
        'Program łączy dotychczasowe: Opieka 75+, Asystent Osoby Starszej, Opieka Wytchnieniowa',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni od decyzji',
    },
    zrodloUrl: 'https://www.infor.pl/twoje-pieniadze/swiadczenia/7516106,bon-senioralny-2026-nawet-2150-zl-na-opieke-nad-seniorem-dla-kogo-i-jak-zlozyc-wniosek.html',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-23', dataWaznosci: '2027-12-31',
  },
  {
    id: 'dodatek-kombatancki', nazwa: 'Dodatek kombatancki i świadczenia dla kombatantów',
    opis: 'Kombatanci oraz osoby represjonowane (więźniowie obozów, łagrów, osoby deportowane do pracy przymusowej) mają prawo do pakietu świadczeń wypłacanych przez ZUS na podstawie zaświadczenia Szefa Urzędu do Spraw Kombatantów i Osób Represjonowanych. Na pakiet składają się: dodatek kombatancki 366,68 PLN miesięcznie (od 1 marca 2026), dodatek kompensacyjny w wysokości 15% dodatku kombatanckiego, czyli 55,00 PLN miesięcznie, oraz ryczałt energetyczny 336,16 PLN miesięcznie (rekompensata kosztów energii, gazu i opału). Łącznie daje to ponad 750 PLN miesięcznie dodatkowo do emerytury lub renty. Świadczenia są waloryzowane co roku 1 marca razem z emeryturami. Dodatkowo kombatanci mają uprawnienia pozapieniężne: prawo do bezpłatnych leków na liście, pierwszeństwo w dostępie do świadczeń zdrowotnych i aptek, zniżki na przejazdy (ulga 51% na PKP i komunikację miejską) oraz pomoc pieniężną z Urzędu do Spraw Kombatantów w trudnej sytuacji. Aby otrzymać świadczenia, najpierw trzeba uzyskać status kombatanta lub osoby represjonowanej (decyzja Szefa UdSKiOR), a następnie złożyć wniosek do ZUS o przyznanie dodatków. Świadczenia są wolne od podatku dochodowego.',
    kategoria: 'SENIOR',
    kwota: 'dodatek kombatancki 366,68 PLN + kompensacyjny 55,00 PLN + ryczałt energetyczny 336,16 PLN miesięcznie (od marca 2026)',
    kwotaMin: 758, kwotaMax: 758,
    czestotliwosc: 'miesięcznie',
    wymagania: {},
    wykluczenia: [
      { opis: 'Brak statusu kombatanta lub osoby represjonowanej (decyzja Szefa Urzędu do Spraw Kombatantów)', sprawdz: 'status_kombatanta' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'Wniosek o przyznanie dodatku kombatanckiego (po uzyskaniu zaświadczenia UdSKiOR)',
      dokumenty: [
        'Zaświadczenie Szefa Urzędu do Spraw Kombatantów i Osób Represjonowanych o uprawnieniach',
        'Dokumenty potwierdzające działalność kombatancką lub represje',
        'Dowód osobisty',
      ],
      kroki: [
        'Złóż wniosek do Urzędu do Spraw Kombatantów i Osób Represjonowanych o przyznanie statusu',
        'Po otrzymaniu zaświadczenia o uprawnieniach złóż wniosek do ZUS',
        'ZUS dolicza dodatek kombatancki, kompensacyjny i ryczałt energetyczny do emerytury/renty',
        'Skorzystaj z uprawnień dodatkowych: zniżki na przejazdy, leki, pierwszeństwo w przychodniach',
      ],
      terminRealizacji: 'UdSKiOR: kilka miesięcy na decyzję o statusie. ZUS: 30 dni od wniosku o dodatki',
      pulapki: [
        'Najpierw status z UdSKiOR, dopiero potem dodatki z ZUS, to dwa etapy',
        'Ryczałt energetyczny (336,16 PLN) to często pomijany, znaczący składnik pakietu',
        'Świadczenia wolne od podatku, doliczane do emerytury/renty',
        'Uprawnienia obejmują też zniżki transportowe i dostęp do leków oraz świadczeń zdrowotnych',
      ],
      odwolanie: 'Odwołanie od decyzji UdSKiOR do sądu administracyjnego, od decyzji ZUS do Sądu Pracy',
    },
    zrodloUrl: 'https://www.gov.pl/web/krus/dodatek-kombatancki',
    zrodloNazwa: 'KRUS / Urząd do Spraw Kombatantów i Osób Represjonowanych', dataWeryfikacji: '2026-07-06', dataWaznosci: '2026-12-31',
  },
  {
    id: 'swiadczenie-dzialacze-opozycji', nazwa: 'Świadczenie dla działaczy opozycji antykomunistycznej',
    opis: 'Comiesięczne świadczenie pieniężne dla działaczy opozycji antykomunistycznej oraz osób represjonowanych z powodów politycznych w okresie PRL (1956-1989). Od 1 marca 2026 wynosi 1978,49 PLN brutto miesięcznie (kwota powiązana z najniższą emeryturą, waloryzowana co roku). Świadczenie przysługuje osobom, którym Szef Urzędu do Spraw Kombatantów i Osób Represjonowanych potwierdził status działacza opozycji antykomunistycznej lub osoby represjonowanej z powodów politycznych. W odróżnieniu od wcześniejszych przepisów, od 2023 r. świadczenie przyznawane jest bez kryterium dochodowego, każda uprawniona osoba otrzymuje pełną kwotę niezależnie od innych dochodów czy emerytury. Świadczenie jest wolne od podatku dochodowego i nie wlicza się do dochodu przy ustalaniu prawa do innych świadczeń. Przyznawane wyłącznie na wniosek złożony do Urzędu do Spraw Kombatantów. Status działacza opozycji potwierdza wcześniej Instytut Pamięci Narodowej (IPN) lub odpowiednia weryfikacja UdSKiOR. Oprócz świadczenia comiesięcznego działacze opozycji mają prawo do pomocy pieniężnej jednorazowej lub okresowej w trudnej sytuacji materialnej oraz do uprawnień analogicznych do kombatanckich.',
    kategoria: 'SENIOR',
    kwota: '1978,49 PLN brutto miesięcznie (od marca 2026, bez kryterium dochodowego)',
    kwotaMin: 1978, kwotaMax: 1978,
    czestotliwosc: 'miesięcznie',
    wymagania: {},
    wykluczenia: [
      { opis: 'Brak potwierdzonego statusu działacza opozycji antykomunistycznej lub osoby represjonowanej z powodów politycznych', sprawdz: 'status_dzialacza_opozycji' },
    ],
    wniosek: {
      kanal: ['ONLINE'],
      formularz: 'Wniosek o świadczenie pieniężne do Szefa UdSKiOR',
      dokumenty: [
        'Wniosek o przyznanie statusu i świadczenia do Urzędu do Spraw Kombatantów',
        'Dokumenty potwierdzające działalność opozycyjną lub represje (np. materiały IPN)',
        'Dowód osobisty',
      ],
      kroki: [
        'Złóż wniosek o potwierdzenie statusu działacza opozycji do Urzędu do Spraw Kombatantów',
        'Dołącz dokumenty potwierdzające działalność lub represje (pomocne materiały z IPN)',
        'Po potwierdzeniu statusu Urząd przyznaje świadczenie pieniężne',
        'Świadczenie wypłacane co miesiąc, bez kryterium dochodowego',
      ],
      terminRealizacji: 'Kilka miesięcy (postępowanie o potwierdzenie statusu)',
      pulapki: [
        'Od 2023 r. brak kryterium dochodowego, pełna kwota niezależnie od emerytury',
        'Świadczenie wolne od podatku i nie wlicza się do dochodu',
        'Wymaga potwierdzenia statusu, samo uczestnictwo w opozycji nie wystarcza bez dokumentów',
        'Przysługuje też pomoc jednorazowa lub okresowa w trudnej sytuacji materialnej',
      ],
      odwolanie: 'Odwołanie od decyzji Szefa UdSKiOR do Wojewódzkiego Sądu Administracyjnego',
    },
    zrodloUrl: 'https://www.kombatanci.gov.pl/index.php/pl/uprawnienia/sprawy-zdrowotne-i-socjalne/dzialacze-opozycji-i-osoby-represjonowane/319-swiadczenie-pieniezne-dla-dzialaczy-opozycji-antykomunistycznej-osob-represjonowanych-z-powodow-politycznych',
    zrodloNazwa: 'Urząd do Spraw Kombatantów i Osób Represjonowanych', dataWeryfikacji: '2026-07-06', dataWaznosci: '2026-12-31',
  },
];
