import { Benefit } from '../types';

export const SENIOR: Benefit[] = [
  {
    id: 'opieka-75-plus', nazwa: 'Program Opieka 75+', kategoria: 'SENIOR',
    kwota: 'bezpłatne lub częściowo odpłatne usługi opiekuńcze (koszt godziny ustala gmina, ok. 30-50 PLN/h)',
    kwotaMin: 0, kwotaMax: 0,
    czestotliwosc: 'ciągłe (usługi opiekuńcze w domu)',
    wymagania: { wiekMin: 75 },
    wykluczenia: [
      { opis: 'Gminy powyżej 60 000 mieszkańców nie uczestniczą w programie', sprawdz: 'wielkosc_gminy' },
    ],
    wniosek: {
      kanal: ['MOPS'],
      dokumenty: [
        'Dowód osobisty',
        'Zaświadczenie o dochodach (dochód do 250% kryterium = 2525 PLN -- bezpłatnie)',
        'Zaświadczenie lekarskie o stanie zdrowia (opcjonalnie)',
      ],
      kroki: [
        'Skontaktuj się z GOPS/MOPS w swojej gminie i zapytaj czy gmina przystąpiła do programu Opieka 75+',
        'Złóż wniosek o usługi opiekuńcze w GOPS/MOPS',
        'Pracownik socjalny przeprowadzi wywiad środowiskowy w Twoim domu',
        'GOPS wyda decyzję administracyjną o przyznaniu usług i ewentualnej odpłatności',
        'Opiekun zacznie wizyty domowe wg ustalonego harmonogramu',
      ],
      terminRealizacji: 'Decyzja w ciągu 30 dni od wywiadu środowiskowego',
      pulapki: [
        'Program dotyczy TYLKO gmin do 60 000 mieszkańców -- duże miasta mają odrębne programy',
        'Dochód do 250% kryterium (2525 PLN) = bezpłatne usługi. Powyżej -- odpłatność wg uchwały gminy',
        'Gmina musi sama przystąpić do programu -- nie wszystkie to zrobiły',
        'Usługi obejmują: pomoc w codziennych czynnościach, higienę, zakupy, przygotowanie posiłków',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni od decyzji',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/program-opieka-75-na-rok-2026',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'korpus-wsparcia-seniorow', nazwa: 'Korpus Wsparcia Seniorów (Teleopieka)', kategoria: 'SENIOR',
    kwota: 'bezpłatna opaska bezpieczeństwa + dostęp do centrum interwencyjnego 24/7',
    kwotaMin: 0, kwotaMax: 0,
    czestotliwosc: 'ciągłe (cały rok)',
    wymagania: { wiekMin: 60 },
    wykluczenia: [],
    wniosek: {
      kanal: ['MOPS'],
      dokumenty: [
        'Dowód osobisty',
        'Brak kryterium dochodowego -- nie trzeba zaświadczeń o dochodach',
      ],
      kroki: [
        'Sprawdź, czy Twoja gmina przystąpiła do programu Korpus Wsparcia Seniorów',
        'Skontaktuj się z MOPS/GOPS w swojej gminie',
        'Złóż wniosek o udział w Module I (usługi sąsiedzkie) lub Module II (teleopieka)',
        'Moduł II: otrzymasz opaskę bezpieczeństwa z przyciskiem SOS i czujnikiem upadków',
        'Opaska łączy Cię 24/7 z centrum interwencyjnym -- wystarczy nacisnąć przycisk',
      ],
      terminRealizacji: 'Zależnie od gminy -- zwykle kilka tygodni od złożenia wniosku',
      pulapki: [
        'BRAK kryterium dochodowego -- każdy senior 60+ może skorzystać',
        'Moduł I: usługi sąsiedzkie (pomoc sąsiadów w codziennych czynnościach)',
        'Moduł II: teleopieka -- opaska z GPS, czujnik upadków, przycisk SOS, kontakt głosowy z operatorem',
        'Gmina dostaje do 80% dofinansowania kosztów -- dla seniora bezpłatne',
        'Nie każda gmina przystępuje -- sprawdź w swoim MOPS',
      ],
      odwolanie: 'Program dobrowolny -- decyzja gminy',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/program-korpus-wsparcia-seniorow-na-rok-2026',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'karta-seniora', nazwa: 'Ogólnopolska Karta Seniora', kategoria: 'SENIOR',
    kwota: 'zniżki 5-30% w ponad 5000 punktach w Polsce',
    kwotaMin: 0, kwotaMax: 0,
    czestotliwosc: 'ciągłe (ważna 1-2 lata)',
    wymagania: { wiekMin: 60 },
    wykluczenia: [],
    wniosek: {
      kanal: ['ONLINE', 'URZAD_GMINY'],
      dokumenty: [
        'Dowód osobisty (potwierdzenie wieku 60+)',
        'Zdjęcie (do karty)',
      ],
      kroki: [
        'Sprawdź, czy Twoja gmina uczestniczy w Programie Gmina Przyjazna Seniorom (bezpłatna karta)',
        'Jeśli tak -- złóż wniosek w urzędzie gminy lub online na stronie programu',
        'Jeśli nie -- wykup członkostwo w Stowarzyszeniu MANKO: 35 PLN/1 rok lub 50 PLN/2 lata',
        'Otrzymasz kartę z imieniem, nazwiskiem i zdjęciem',
        'Okazuj kartę w punktach partnerskich (lista na kartaseniora.pl)',
      ],
      terminRealizacji: 'Do 14 dni roboczych',
      pulapki: [
        'W gminach zrzeszonych (360+ gmin) -- karta BEZPŁATNA',
        'Poza programem gminnym -- opłata 35 PLN/rok lub 50 PLN/2 lata',
        'Zniżki: apteki, sanatoria, rehabilitacja, optycy, kina, teatry, restauracje, fryzjerzy',
        'Nie jest to karta urzędowa -- to program Stowarzyszenia MANKO',
        'Każde miasto może mieć też WŁASNĄ Kartę Seniora z lokalnymi zniżkami',
      ],
      odwolanie: 'Nie dotyczy -- program dobrowolny',
    },
    zrodloUrl: 'https://glosseniora.pl/ogolnopolska-karta-seniora/',
    zrodloNazwa: 'Stowarzyszenie MANKO', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'zasilek-pielegnacyjny', nazwa: 'Zasiłek pielęgnacyjny', kategoria: 'SENIOR',
    kwota: '215,84 PLN miesięcznie', kwotaMin: 215.84, kwotaMax: 215.84,
    czestotliwosc: 'miesięcznie',
    wymagania: { wiekMin: 75 },
    wykluczenia: [
      { opis: 'Nie przysługuje osobom pobierającym dodatek pielęgnacyjny z ZUS', sprawdz: 'dodatek_pielegnacyjny' },
      { opis: 'Nie przysługuje osobom umieszczonym w instytucji zapewniającej całodobową opiekę', sprawdz: 'instytucja_opieki' },
    ],
    wniosek: {
      kanal: ['URZAD_GMINY', 'MOPS', 'EMPATIA'], formularz: 'SR-5',
      dokumenty: [
        'Dowód osobisty',
        'Orzeczenie o niepełnosprawności (dla osób poniżej 75 lat)',
        'Dla osób 75+ -- wystarczy dowód osobisty (przyznawany z mocy prawa)',
      ],
      kroki: [
        'Dla osób 75+: zasiłek przysługuje z mocy prawa -- złóż wniosek SR-5 w urzędzie gminy lub przez Empatię',
        'Dla osób poniżej 75 lat: uzyskaj orzeczenie o niepełnosprawności',
        'Wypełnij formularz SR-5',
        'Złóż wniosek w urzędzie gminy, MOPS lub elektronicznie przez portal Empatia',
        'Decyzja w ciągu 30 dni',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'BRAK kryterium dochodowego -- przysługuje niezależnie od zarobków',
        'Nie łączy się z dodatkiem pielęgnacyjnym z ZUS -- musisz wybrać jedno',
        'Dla osób 75+ przyznawany z mocy prawa, ale TRZEBA złożyć wniosek',
        'Waloryzacja co 3 lata -- najbliższa w 2027 roku',
        'Przysługuje też dzieciom z orzeczeniem i dorosłym z niepełnosprawnością od przed 21 r.ż.',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/zasilek-pielegnacyjny',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-10', dataWaznosci: '2027-10-31',
  },
  {
    id: 'swiadczenie-pielegnacyjne', nazwa: 'Świadczenie pielęgnacyjne (nowe zasady 2024+)', kategoria: 'SENIOR',
    kwota: '3386 PLN miesięcznie (2026)', kwotaMin: 3386, kwotaMax: 6772,
    czestotliwosc: 'miesięcznie',
    wymagania: { dzieci: { min: 1 } },
    wykluczenia: [
      { opis: 'Na nowych zasadach: tylko na dziecko do 18 roku życia z niepełnosprawnością', sprawdz: 'wiek_dziecka_niepelnosprawnego' },
    ],
    wniosek: {
      kanal: ['URZAD_GMINY', 'MOPS', 'EMPATIA'], formularz: 'SR-5Z',
      dokumenty: [
        'Orzeczenie o niepełnosprawności dziecka (znaczny stopień lub wskazanie stałej/długotrwałej opieki)',
        'Dowód osobisty rodzica/opiekuna',
        'Akt urodzenia dziecka',
        'Numer konta bankowego',
      ],
      kroki: [
        'Uzyskaj orzeczenie o niepełnosprawności dziecka z zespołu orzekającego',
        'Wypełnij wniosek SR-5Z o świadczenie pielęgnacyjne',
        'Złóż wniosek w urzędzie gminy, MOPS lub elektronicznie przez Empatię',
        'Decyzja w ciągu 30 dni',
        'Świadczenie wypłacane co miesiąc na konto',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'NOWE zasady od 2024: opiekun MOŻE pracować bez limitu zarobków',
        'Nowe zasady: świadczenie przysługuje TYLKO do 18 r.ż. dziecka',
        'Na drugie i kolejne dziecko z niepełnosprawnością -- +100% (czyli 6772 PLN na dwoje dzieci)',
        'Stare zasady (sprzed 2024): opiekun NIE może pracować, ale świadczenie bez limitu wieku dziecka',
        'Osoby na starych zasadach mogą na nich pozostać -- nie muszą przechodzić na nowe',
        'Rolnicy od 2024 nie muszą rezygnować z gospodarstwa',
        'BRAK kryterium dochodowego',
        'Waloryzacja co roku 1 stycznia',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/swiadczenie-pielegnacyjne',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'dzienny-dom-pomocy', nazwa: 'Dzienny Dom Pomocy / Senior+', kategoria: 'SENIOR',
    kwota: 'bezpłatne lub częściowo odpłatne usługi dzienne (wartość ok. 1000-2000 PLN/mies.)',
    kwotaMin: 0, kwotaMax: 0,
    czestotliwosc: 'ciągłe (dni robocze, min. 8h dziennie)',
    wymagania: { wiekMin: 60 },
    wykluczenia: [],
    wniosek: {
      kanal: ['MOPS'],
      dokumenty: [
        'Dowód osobisty',
        'Zaświadczenie o dochodach',
        'Zaświadczenie lekarskie o braku przeciwwskazań',
      ],
      kroki: [
        'Znajdź Dzienny Dom Pomocy / Dzienny Dom Senior+ w swojej gminie',
        'Złóż wniosek w MOPS/GOPS o skierowanie',
        'Pracownik socjalny przeprowadzi wywiad środowiskowy',
        'MOPS wyda decyzję o skierowaniu i ewentualnej odpłatności',
        'Korzystaj z pobytu dziennego: posiłki, zajęcia aktywizujące, rehabilitacja, kontakty społeczne',
      ],
      terminRealizacji: 'Decyzja w ciągu 30 dni',
      pulapki: [
        'Program Senior+ formalnie zakończył się 31.12.2025 -- od 2026 program Aktywni Seniorzy 2026-2030',
        'Odpłatność ustalana przez gminę -- zależna od dochodu',
        'Oferta: posiłki, zajęcia edukacyjne, kulturalne, rehabilitacja, terapia zajęciowa',
        'Nie każda gmina ma taki dom -- sprawdź lokalnie',
        'Dostępne min. 8h dziennie, poniedziałek-piątek',
      ],
      odwolanie: 'Odwołanie do Samorządowego Kolegium Odwoławczego w ciągu 14 dni od decyzji',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/program-senior',
    zrodloNazwa: 'Ministerstwo Rodziny', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'refundacja-okulary-nfz', nazwa: 'Refundacja okularow i soczewek z NFZ', kategoria: 'SENIOR',
    kwota: '50-700 PLN na szkla okularowe, do 600 PLN na soczewki kontaktowe',
    kwotaMin: 50, kwotaMax: 700,
    czestotliwosc: 'raz na 2 lata (dorosli)',
    wymagania: {},
    wykluczenia: [
      { opis: 'Zlecenie musi byc wystawione przez okulistę z kontraktem NFZ', sprawdz: 'okulista_nfz' },
      { opis: 'Refundacja nie obejmuje oprawek ani dodatkowych powlok na szklach', sprawdz: 'zakres_refundacji' },
    ],
    wniosek: {
      kanal: ['NFZ', 'POZ'],
      dokumenty: [
        'Zlecenie na wyrob medyczny od okulisty z kontraktem NFZ',
        'Dowod osobisty lub legitymacja emeryta/rencisty',
        'Karta ubezpieczenia zdrowotnego',
      ],
      kroki: [
        'Umow sie na wizyte u okulisty majacego kontrakt z NFZ',
        'Okulista wystawi zlecenie na wyrob medyczny (szkla korekcyjne lub soczewki)',
        'Zlecenie jest automatycznie weryfikowane w systemie eZWM',
        'Udaj sie do optyka realizujacego zlecenia NFZ',
        'Optyk zrealizuje zlecenie -- doplata NFZ zostanie odliczona od ceny szkiel',
      ],
      terminRealizacji: 'Realizacja od reki u optyka (po uzyskaniu zlecenia)',
      pulapki: [
        'Limity refundacji szkiel dla doroslych: 50 PLN (wada do +/-6 dptr), 200 PLN (+/-6,25 do +/-10 dptr), 700 PLN (powyzej +/-10 dptr)',
        'Refundacja dotyczy TYLKO szkiel -- oprawki i powloki (antyrefleks, fotochrom) na wlasny koszt',
        'Doroslym przysluguje raz na 2 lata -- dzieciom czesciej, jesli zmieni sie wada',
        'Soczewki kontaktowe do 600 PLN -- ale tylko przy okreslonych schorzeniach (np. stozek rogowki, afakia)',
        'Nie kazdy okulista ma kontrakt NFZ -- sprawdz przed wizyta',
      ],
      odwolanie: 'Reklamacja do Oddzialu Wojewodzkiego NFZ',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/wyroby-medyczne/',
    zrodloNazwa: 'Narodowy Fundusz Zdrowia', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
];
