import { Benefit } from '../types';

export const ZDROWIE: Benefit[] = [
  {
    id: 'moje-zdrowie', nazwa: 'Program Moje Zdrowie', kategoria: 'ZDROWIE',
    kwota: 'bezpłatne badania (wartość ok. 500 PLN)', kwotaMin: 500, kwotaMax: 500,
    czestotliwosc: 'co 3-5 lat',
    wymagania: { wiekMin: 20 },
    wykluczenia: [],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Dowód osobisty lub mObywatel', 'Karta ubezpieczenia zdrowotnego (opcjonalnie)'],
      kroki: [
        'Wejdź na pacjent.gov.pl lub aplikację Moje IKP',
        'Wypełnij ankietę zdrowotną online',
        'Umów wizytę w swoim ośrodku POZ (lekarz pierwszego kontaktu)',
        'Wykonaj badania: morfologia, glukoza, kreatynina, lipidogram, badanie moczu',
        'Odbierz wyniki i omów je z lekarzem',
      ],
      terminRealizacji: 'Wyniki w ciągu 7-14 dni',
      pulapki: [
        'Badanie dostępne raz na 5 lat (wiek 20-49) lub raz na 3 lata (wiek 50+)',
        'Trzeba najpierw wypełnić ankietę, bez niej POZ może odmówić',
        'Nie każdy POZ realizuje program, sprawdź listę na pacjent.gov.pl',
      ],
      odwolanie: 'Program dobrowolny, nie wymaga odwołania',
    },
    zrodloUrl: 'https://pacjent.gov.pl/program-moje-zdrowie',
    zrodloNazwa: 'Ministerstwo Zdrowia', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'mammografia', nazwa: 'Mammografia profilaktyczna', kategoria: 'ZDROWIE',
    kwota: 'bezpłatne badanie', czestotliwosc: 'co 2 lata',
    wymagania: { wiekMin: 45, wiekMax: 74, plec: 'K' },
    wykluczenia: [{ opis: 'Kobiety leczone z powodu raka piersi', sprawdz: 'leczenie_rak_piersi' }],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Dowód osobisty'],
      kroki: [
        'Znajdź placówkę realizującą program na nfz.gov.pl/dla-pacjenta/programy-profilaktyczne',
        'Zadzwoń i umów termin, nie potrzebujesz skierowania',
        'Przyjdź na badanie mammograficzne',
        'Wynik otrzymasz pocztowo lub w placówce w ciągu 2-3 tygodni',
      ],
      terminRealizacji: 'Wynik w 2-3 tygodnie',
      pulapki: ['Nie potrzebujesz skierowania od lekarza, możesz iść bezpośrednio', 'Badanie co 2 lata, nie częściej'],
      odwolanie: 'Nie dotyczy',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/programy-profilaktyczne/',
    zrodloNazwa: 'NFZ', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'cytologia', nazwa: 'Cytologia profilaktyczna', kategoria: 'ZDROWIE',
    kwota: 'bezpłatne badanie', czestotliwosc: 'co 3 lata',
    wymagania: { wiekMin: 25, wiekMax: 64, plec: 'K' },
    wykluczenia: [],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Dowód osobisty'],
      kroki: [
        'Znajdź gabinet ginekologiczny realizujący program na nfz.gov.pl',
        'Umów wizytę, nie potrzebujesz skierowania',
        'Wykonaj badanie cytologiczne',
        'Wynik otrzymasz w ciągu 2-4 tygodni',
      ],
      terminRealizacji: 'Wynik w 2-4 tygodnie',
      pulapki: ['Badanie co 3 lata, jeśli wykonałaś cytologię prywatnie, i tak możesz skorzystać z programu NFZ', 'Nie potrzebujesz skierowania'],
      odwolanie: 'Nie dotyczy',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/programy-profilaktyczne/',
    zrodloNazwa: 'NFZ', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'kolonoskopia', nazwa: 'Kolonoskopia profilaktyczna', kategoria: 'ZDROWIE',
    kwota: 'bezpłatne badanie', czestotliwosc: 'co 10 lat',
    wymagania: { wiekMin: 50, wiekMax: 65 },
    wykluczenia: [],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Dowód osobisty', 'Wyniki badań krwi (morfologia, koagulologia)'],
      kroki: [
        'Znajdź ośrodek realizujący program na nfz.gov.pl',
        'Zadzwoń i zapisz się, nie potrzebujesz skierowania',
        'Przygotuj się do badania (dieta 3 dni przed, środek czyszczący)',
        'Wykonaj kolonoskopię',
      ],
      terminRealizacji: 'Badanie w ciągu 1-3 miesięcy od zapisania',
      pulapki: [
        'Osoby 40-49 z wywiadem rodzinnym (rak jelita grubego u krewnego I stopnia) też się kwalifikują',
        'Wymaga przygotowania, dieta i oczyszczenie jelita',
      ],
      odwolanie: 'Nie dotyczy',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/programy-profilaktyczne/',
    zrodloNazwa: 'NFZ', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'prostata', nazwa: 'Badania prostaty (PSA)', kategoria: 'ZDROWIE',
    kwota: 'bezpłatne badanie', czestotliwosc: 'co rok',
    wymagania: { wiekMin: 50, plec: 'M' },
    wykluczenia: [],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Dowód osobisty'],
      kroki: [
        'Zgłoś się do lekarza POZ po skierowanie na badanie PSA',
        'Wykonaj badanie krwi w laboratorium',
        'Odbierz wyniki i omów z lekarzem',
      ],
      terminRealizacji: 'Wynik w 3-7 dni',
      pulapki: ['Mężczyźni 45+ z wywiadem rodzinnym powinni zacząć wcześniej', 'Badanie PSA to badanie krwi, nie wymaga specjalnego przygotowania'],
      odwolanie: 'Nie dotyczy',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/programy-profilaktyczne/',
    zrodloNazwa: 'NFZ', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'szczepienia-hpv', nazwa: 'Szczepienia przeciwko HPV', kategoria: 'ZDROWIE',
    kwota: 'bezpłatne szczepienie (wartość ok. 1500 PLN)', kwotaMin: 1500, kwotaMax: 1500,
    czestotliwosc: 'jednorazowo',
    wymagania: { wiekMin: 12, wiekMax: 13, plec: 'K' },
    wykluczenia: [],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Książeczka zdrowia dziecka', 'Zgoda rodzica/opiekuna'],
      kroki: [
        'Skontaktuj się z lekarzem POZ dziecka',
        'Lekarz zakwalifikuje dziecko do szczepienia',
        'Szczepienie w 2 dawkach w odstępie 6 miesięcy',
      ],
      terminRealizacji: 'Szczepienie dostępne od razu',
      pulapki: ['Program dotyczy dziewcząt, chłopcy nie są objęci programem bezpłatnym', 'Wymagane 2 dawki w odstępie 6 miesięcy'],
      odwolanie: 'Nie dotyczy',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/programy-profilaktyczne/',
    zrodloNazwa: 'NFZ', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'profilaktyka-krazenia', nazwa: 'Profilaktyka chorób układu krążenia', kategoria: 'ZDROWIE',
    kwota: 'bezpłatne badanie', czestotliwosc: 'co 5 lat',
    wymagania: { wiekMin: 35, wiekMax: 65 },
    wykluczenia: [{ opis: 'Osoby leczone z powodu chorób układu krążenia', sprawdz: 'leczenie_krazenie' }],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Dowód osobisty'],
      kroki: [
        'Zgłoś się do lekarza POZ i zapytaj o program CHUK',
        'Wypełnij ankietę oceny ryzyka sercowo-naczyniowego',
        'Wykonaj badania: ciśnienie, cholesterol, glukoza',
        'Lekarz omówi wyniki i zaleci dalsze postępowanie',
      ],
      terminRealizacji: 'Wyniki na miejscu lub w ciągu tygodnia',
      pulapki: ['Badanie co 5 lat, warto sprawdzić kiedy ostatnio korzystałeś'],
      odwolanie: 'Nie dotyczy',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/programy-profilaktyczne/',
    zrodloNazwa: 'NFZ', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'rak-pluc', nazwa: 'Wczesne wykrywanie raka płuc', kategoria: 'ZDROWIE',
    kwota: 'bezpłatna tomografia (wartość ok. 400 PLN)', kwotaMin: 400, kwotaMax: 400,
    czestotliwosc: 'co rok',
    wymagania: { wiekMin: 55, wiekMax: 74 },
    wykluczenia: [{ opis: 'Wymaga historii palenia (min. 20 paczkolat)', sprawdz: 'palenie_historia' }],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Dowód osobisty', 'Ankieta kwalifikacyjna (historia palenia)'],
      kroki: [
        'Znajdź ośrodek realizujący program na nfz.gov.pl',
        'Wypełnij ankietę kwalifikacyjną dotyczącą historii palenia',
        'Jeśli spełnisz kryteria, wykonaj niskodawkową tomografię komputerową klatki piersiowej',
      ],
      terminRealizacji: 'Wynik w 2-3 tygodnie',
      pulapki: ['Kryterium: min. 20 paczkolat palenia lub rzucenie palenia w ciągu ostatnich 15 lat'],
      odwolanie: 'Nie dotyczy',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/programy-profilaktyczne/',
    zrodloNazwa: 'NFZ', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
];
