import { Benefit } from '../types';

export const ZDROWIE: Benefit[] = [
  {
    id: 'moje-zdrowie', nazwa: 'Program Moje Zdrowie',
    opis: 'Program Moje Zdrowie to bezpłatny pakiet badań profilaktycznych finansowany przez NFZ, skierowany do wszystkich dorosłych ubezpieczonych od 20. roku życia. W ramach programu wykonuje się: morfologię krwi obwodowej, stężenie glukozy we krwi na czczo, stężenie kreatyniny, lipidogram (cholesterol całkowity, HDL, LDL, trójglicerydy), badanie ogólne moczu, a u osób 50+ dodatkowo badanie krwi utajonej w kale. Osoby w wieku 20-49 lat mogą skorzystać raz na 5 lat, osoby 50+ raz na 3 lata. Warunkiem jest wypełnienie ankiety zdrowotnej online na pacjent.gov.pl lub w aplikacji Moje IKP. Bez wypełnionej ankiety lekarz POZ nie rozpocznie procedury. Badania wykonuje się w ośrodku POZ, do którego jest się zapisanym. Nie każda przychodnia realizuje program, listę placówek można sprawdzić na pacjent.gov.pl. Częste nieporozumienie: program nie zastępuje standardowych badań zleconych przez lekarza w ramach leczenia. To dodatkowy pakiet profilaktyczny. Wyniki są dostępne w ciągu 7-14 dni i omawiane z lekarzem pierwszego kontaktu.',
    kategoria: 'ZDROWIE',
    kwota: 'bezpłatne badania (wartość ok. 500 PLN)', kwotaMin: 500, kwotaMax: 500,
    czestotliwosc: 'co 3-5 lat',
    wymagania: { wiekMin: 20 },
    wykluczenia: [],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Dowód osobisty lub mObywatel', 'Karta ubezpieczenia zdrowotnego (opcjonalnie)'],
      kroki: [
        'Wejdź na pacjent.gov.pl lub aplikację Moje IKP',
        'Wypełnij ankietę zdrowotną online',
        'Umów wizytę w swoim ośrodku POZ (lekarz pierwszego kontaktu)',
        'Wykonaj badania: morfologia, glukoza, kreatynina, lipidogram, badanie moczu',
        'Odbierz wyniki i omów je z lekarzem',
      ],
      terminRealizacji: 'Wyniki w ciągu 7-14 dni',
      pulapki: [
        'Badanie dostępne raz na 5 lat (wiek 20-49) lub raz na 3 lata (wiek 50+)',
        'Trzeba najpierw wypełnić ankietę, bez niej POZ może odmówić',
        'Nie każdy POZ realizuje program, sprawdź listę na pacjent.gov.pl',
      ],
      odwolanie: 'Program dobrowolny, nie wymaga odwołania',
    },
    zrodloUrl: 'https://pacjent.gov.pl/program-moje-zdrowie',
    zrodloNazwa: 'Ministerstwo Zdrowia', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'mammografia', nazwa: 'Mammografia profilaktyczna',
    opis: 'Mammografia profilaktyczna to bezpłatne badanie rentgenowskie piersi finansowane przez NFZ w ramach Programu Profilaktyki Raka Piersi. Skierowane jest do kobiet w wieku 45-74 lat. Badanie polega na wykonaniu zdjęcia RTG obu piersi (po dwa zdjęcia każdej piersi) i trwa około 15 minut. Można z niego skorzystać co 2 lata. Nie wymaga skierowania od lekarza, wystarczy zadzwonić do placówki realizującej program i umówić termin. Listę placówek można znaleźć na nfz.gov.pl/dla-pacjenta/programy-profilaktyczne lub zadzwonić na infolinię NFZ: 800 190 590. Wynik przychodzi pocztą lub jest do odbioru w placówce w ciągu 2-3 tygodni. Częsty błąd: kobiety leczone z powodu raka piersi nie kwalifikują się do programu profilaktycznego, one mają badania w ramach leczenia onkologicznego. Kolejne nieporozumienie: wykonanie mammografii prywatnie nie resetuje 2-letniego interwału w programie NFZ. Kobiety z grupy podwyższonego ryzyka (mutacja BRCA1/BRCA2, rak piersi w rodzinie) powinny skonsultować się z lekarzem w sprawie częstszych badań poza programem. Mammografia mobilna (mammobus) jest równoważna z badaniem stacjonarnym.',
    kategoria: 'ZDROWIE',
    kwota: 'bezpłatne badanie', czestotliwosc: 'co 2 lata',
    wymagania: { wiekMin: 45, wiekMax: 74, plec: 'K' },
    wykluczenia: [{ opis: 'Kobiety leczone z powodu raka piersi', sprawdz: 'leczenie_rak_piersi' }],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Dowód osobisty'],
      kroki: [
        'Znajdź placówkę realizującą program na nfz.gov.pl/dla-pacjenta/programy-profilaktyczne',
        'Zadzwoń i umów termin, nie potrzebujesz skierowania',
        'Przyjdź na badanie mammograficzne',
        'Wynik otrzymasz pocztowo lub w placówce w ciągu 2-3 tygodni',
      ],
      terminRealizacji: 'Wynik w 2-3 tygodnie',
      pulapki: ['Nie potrzebujesz skierowania od lekarza, możesz iść bezpośrednio', 'Badanie co 2 lata, nie częściej'],
      odwolanie: 'Nie dotyczy',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/programy-profilaktyczne/',
    zrodloNazwa: 'NFZ', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'cytologia', nazwa: 'Cytologia profilaktyczna',
    opis: 'Cytologia profilaktyczna to bezpłatne badanie przesiewowe w kierunku raka szyjki macicy, finansowane przez NFZ w ramach Programu Profilaktyki Raka Szyjki Macicy. Skierowane jest do kobiet w wieku 25-64 lat. Badanie polega na pobraniu przez ginekologa wymazu z szyjki macicy i kanału szyjki. Trwa kilka minut i jest bezbolesne (może być lekko nieprzyjemne). Można z niego skorzystać co 3 lata. Nie wymaga skierowania, wystarczy umówić się bezpośrednio w gabinecie ginekologicznym realizującym program. Ważne: nawet jeśli kobieta wykonała cytologię prywatnie, nadal może skorzystać z bezpłatnego programu NFZ (liczy się data ostatniej cytologii w ramach programu, nie prywatnej). Wynik jest dostępny w ciągu 2-4 tygodni. Jeśli wynik jest nieprawidłowy, pacjentka jest kierowana na dalszą diagnostykę: kolposkopię. Częste nieporozumienie: cytologia nie wykrywa HPV. To osobne badanie. Kobiety po histerektomii całkowitej (usunięciu macicy z szyjką) nie potrzebują cytologii, chyba że operacja była z powodu stanu przedrakowego. Przed badaniem nie należy stosować globulek dopochwowych ani współżyć przez 24-48 godzin.',
    kategoria: 'ZDROWIE',
    kwota: 'bezpłatne badanie', czestotliwosc: 'co 3 lata',
    wymagania: { wiekMin: 25, wiekMax: 64, plec: 'K' },
    wykluczenia: [],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Dowód osobisty'],
      kroki: [
        'Znajdź gabinet ginekologiczny realizujący program na nfz.gov.pl',
        'Umów wizytę, nie potrzebujesz skierowania',
        'Wykonaj badanie cytologiczne',
        'Wynik otrzymasz w ciągu 2-4 tygodni',
      ],
      terminRealizacji: 'Wynik w 2-4 tygodnie',
      pulapki: ['Badanie co 3 lata, jeśli wykonałaś cytologię prywatnie, i tak możesz skorzystać z programu NFZ', 'Nie potrzebujesz skierowania'],
      odwolanie: 'Nie dotyczy',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/programy-profilaktyczne/',
    zrodloNazwa: 'NFZ', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'kolonoskopia', nazwa: 'Kolonoskopia profilaktyczna',
    opis: 'Kolonoskopia profilaktyczna to bezpłatne badanie wziernikowe jelita grubego finansowane przez NFZ w ramach Programu Badań Przesiewowych Raka Jelita Grubego. Skierowane jest do osób w wieku 50-65 lat (obie płcie). Wyjątek: osoby w wieku 40-49 lat z wywiadem rodzinnym: jeśli krewny pierwszego stopnia (rodzic, rodzeństwo, dziecko) chorował na raka jelita grubego, kwalifikują się do programu 10 lat wcześniej. Badanie polega na wprowadzeniu giętkiego endoskopu przez odbytnicę i oglądaniu wnętrza jelita grubego. Trwa 20-40 minut. Podczas badania lekarz może usunąć polipy (zmniejsza to ryzyko raka nawet o 80%). Badanie wykonuje się co 10 lat, chyba że lekarz zaleci częstsze kontrole po usunięciu polipów. Nie wymaga skierowania. Wymaga przygotowania: 3 dni przed badaniem dieta lekkostrawna (bez błonnika, owoców, warzyw), dzień przed badaniem przyjęcie środka przeczyszczającego (np. Fortrans). Konieczne są wcześniejsze badania krwi (morfologia, koagulologia). Czas oczekiwania na termin to zazwyczaj 1-3 miesiące. Badanie można wykonać w znieczuleniu (sedacji), warto o to zapytać przy rejestracji. Po badaniu w sedacji nie wolno prowadzić samochodu przez 24 godziny.',
    kategoria: 'ZDROWIE',
    kwota: 'bezpłatne badanie', czestotliwosc: 'co 10 lat',
    wymagania: { wiekMin: 50, wiekMax: 65 },
    wykluczenia: [],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Dowód osobisty', 'Wyniki badań krwi (morfologia, koagulologia)'],
      kroki: [
        'Znajdź ośrodek realizujący program na nfz.gov.pl',
        'Zadzwoń i zapisz się, nie potrzebujesz skierowania',
        'Przygotuj się do badania (dieta 3 dni przed, środek czyszczący)',
        'Wykonaj kolonoskopię',
      ],
      terminRealizacji: 'Badanie w ciągu 1-3 miesięcy od zapisania',
      pulapki: [
        'Osoby 40-49 z wywiadem rodzinnym (rak jelita grubego u krewnego I stopnia) też się kwalifikują',
        'Wymaga przygotowania, dieta i oczyszczenie jelita',
      ],
      odwolanie: 'Nie dotyczy',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/programy-profilaktyczne/',
    zrodloNazwa: 'NFZ', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'prostata', nazwa: 'Badania prostaty (PSA)',
    opis: 'Badanie PSA (antygen swoisty dla prostaty) to bezpłatne badanie krwi finansowane przez NFZ, służące do wczesnego wykrywania raka prostaty. Skierowane jest do mężczyzn od 50. roku życia. Mężczyźni z wywiadem rodzinnym (rak prostaty u ojca lub brata) powinni zacząć badania od 45. roku życia. Badanie polega na pobraniu próbki krwi z żyły i oznaczeniu poziomu PSA. Nie wymaga specjalnego przygotowania, ale przez 48 godzin przed badaniem nie należy jeździć na rowerze, odbywać stosunków seksualnych ani poddawać się badaniu per rectum, mogą fałszywie podwyższyć wynik. Do badania potrzebne jest skierowanie od lekarza POZ. Wynik jest dostępny w ciągu 3-7 dni. Podwyższony PSA (powyżej 4 ng/ml) nie oznacza automatycznie raka, może wskazywać na łagodny przerost prostaty lub zapalenie. Lekarz ocenia wynik w kontekście wieku, wielkości prostaty i dynamiki zmian. Częste nieporozumienie: badanie PSA nie jest tym samym co badanie per rectum (badanie palcem przez odbytnicę). To dwa różne badania i oba są ważne w diagnostyce. Badanie można powtarzać co rok.',
    kategoria: 'ZDROWIE',
    kwota: 'bezpłatne badanie', czestotliwosc: 'co rok',
    wymagania: { wiekMin: 50, plec: 'M' },
    wykluczenia: [],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Dowód osobisty'],
      kroki: [
        'Zgłoś się do lekarza POZ po skierowanie na badanie PSA',
        'Wykonaj badanie krwi w laboratorium',
        'Odbierz wyniki i omów z lekarzem',
      ],
      terminRealizacji: 'Wynik w 3-7 dni',
      pulapki: ['Mężczyźni 45+ z wywiadem rodzinnym powinni zacząć wcześniej', 'Badanie PSA to badanie krwi, nie wymaga specjalnego przygotowania'],
      odwolanie: 'Nie dotyczy',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/programy-profilaktyczne/',
    zrodloNazwa: 'NFZ', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'szczepienia-hpv', nazwa: 'Szczepienia przeciwko HPV',
    opis: 'Bezpłatne szczepienie przeciwko wirusowi brodawczaka ludzkiego (HPV) finansowane przez NFZ w ramach Programu Szczepień Ochronnych. HPV jest główną przyczyną raka szyjki macicy, ale wywołuje też raka gardła, odbytu i prącia. Program obejmuje dziewczęta w wieku 12-13 lat (rocznikowo). Szczepienie składa się z 2 dawek podawanych w odstępie 6 miesięcy. Stosowana jest szczepionka 9-walentna (Gardasil 9), chroniąca przed 9 typami HPV, w tym typami 16 i 18 odpowiedzialnymi za ok. 70% przypadków raka szyjki macicy. Wartość rynkowa szczepienia to ok. 1500 PLN. Szczepienie wykonuje lekarz POZ, potrzebna jest zgoda rodzica lub opiekuna prawnego oraz książeczka zdrowia dziecka. Kwalifikacja odbywa się przez lekarza (badanie, wywiad). Częste nieporozumienie: program bezpłatny dotyczy dziewcząt, chłopcy nie są objęci refundacją (choć medycznie szczepienie jest dla nich też zalecane). Kolejny mit: szczepienie nie chroni przed HPV, jeśli do zakażenia już doszło, dlatego podaje się je przed rozpoczęciem aktywności seksualnej. Szczepienie nie zwalnia z regularnej cytologii w przyszłości, bo nie chroni przed wszystkimi typami HPV onkogennymi.',
    kategoria: 'ZDROWIE',
    kwota: 'bezpłatne szczepienie (wartość ok. 1500 PLN)', kwotaMin: 1500, kwotaMax: 1500,
    czestotliwosc: 'jednorazowo',
    wymagania: { wiekMin: 12, wiekMax: 13, plec: 'K' },
    wykluczenia: [],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Książeczka zdrowia dziecka', 'Zgoda rodzica/opiekuna'],
      kroki: [
        'Skontaktuj się z lekarzem POZ dziecka',
        'Lekarz zakwalifikuje dziecko do szczepienia',
        'Szczepienie w 2 dawkach w odstępie 6 miesięcy',
      ],
      terminRealizacji: 'Szczepienie dostępne od razu',
      pulapki: ['Program dotyczy dziewcząt, chłopcy nie są objęci programem bezpłatnym', 'Wymagane 2 dawki w odstępie 6 miesięcy'],
      odwolanie: 'Nie dotyczy',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/programy-profilaktyczne/',
    zrodloNazwa: 'NFZ', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'profilaktyka-krazenia', nazwa: 'Profilaktyka chorób układu krążenia',
    opis: 'Program Profilaktyki Chorób Układu Krążenia (CHUK) to bezpłatne badanie przesiewowe finansowane przez NFZ, skierowane do osób w wieku 35-65 lat obu płci. Celem jest wczesne wykrycie czynników ryzyka chorób sercowo-naczyniowych (zawał, udar). W ramach programu wykonuje się: pomiar ciśnienia tętniczego, pomiar masy ciała i wzrostu (BMI), oznaczenie cholesterolu całkowitego i glukozy we krwi na czczo, a lekarz ocenia ryzyko sercowo-naczyniowe za pomocą skali SCORE. Badanie dostępne jest co 5 lat. Wykonuje się je w gabinecie lekarza POZ, wystarczy zapytać o program CHUK przy rejestracji. Wykluczone są osoby już leczone z powodu chorób układu krążenia (nadciśnienie, choroba wieńcowa, po zawale lub udarze), one mają badania w ramach leczenia. Częste nieporozumienie: program CHUK to nie to samo co Program Moje Zdrowie. To dwa osobne programy i można skorzystać z obu. Wyniki są zazwyczaj dostępne na miejscu (ciśnienie, BMI) lub w ciągu tygodnia (wyniki laboratoryjne). Na podstawie wyniku SCORE lekarz może zalecić zmianę stylu życia, dietę lub skierować do kardiologa.',
    kategoria: 'ZDROWIE',
    kwota: 'bezpłatne badanie', czestotliwosc: 'co 5 lat',
    wymagania: { wiekMin: 35, wiekMax: 65 },
    wykluczenia: [{ opis: 'Osoby leczone z powodu chorób układu krążenia', sprawdz: 'leczenie_krazenie' }],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Dowód osobisty'],
      kroki: [
        'Zgłoś się do lekarza POZ i zapytaj o program CHUK',
        'Wypełnij ankietę oceny ryzyka sercowo-naczyniowego',
        'Wykonaj badania: ciśnienie, cholesterol, glukoza',
        'Lekarz omówi wyniki i zaleci dalsze postępowanie',
      ],
      terminRealizacji: 'Wyniki na miejscu lub w ciągu tygodnia',
      pulapki: ['Badanie co 5 lat, warto sprawdzić kiedy ostatnio korzystałeś'],
      odwolanie: 'Nie dotyczy',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/programy-profilaktyczne/',
    zrodloNazwa: 'NFZ', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'rak-pluc', nazwa: 'Wczesne wykrywanie raka płuc',
    opis: 'Program Wczesnego Wykrywania Raka Płuca to bezpłatne badanie przesiewowe finansowane przez NFZ, skierowane do osób w wieku 55-74 lat obu płci z historią palenia tytoniu. Kryterium kwalifikacji: minimum 20 paczkolat palenia (np. 1 paczka dziennie przez 20 lat lub 2 paczki dziennie przez 10 lat) LUB rzucenie palenia w ciągu ostatnich 15 lat przy spełnieniu kryterium paczkolat. Badanie polega na wykonaniu niskodawkowej tomografii komputerowej (LDCT) klatki piersiowej, trwa kilka minut, jest bezbolesne i nie wymaga podania kontrastu. Dawka promieniowania jest znacznie niższa niż przy standardowej tomografii. Badanie można powtarzać co rok. Nie wymaga skierowania, ale wymaga wypełnienia ankiety kwalifikacyjnej dotyczącej historii palenia. Listę ośrodków realizujących program można znaleźć na nfz.gov.pl. Czas oczekiwania na wynik to 2-3 tygodnie. Częste nieporozumienie: zwykłe RTG klatki piersiowej nie zastępuje LDCT w wykrywaniu raka płuc. RTG wykrywa guzy dopiero w zaawansowanym stadium. Program nie obejmuje osób, które nigdy nie paliły lub paliły mniej niż 20 paczkolat. Wartość rynkowa tomografii to ok. 400 PLN.',
    kategoria: 'ZDROWIE',
    kwota: 'bezpłatna tomografia (wartość ok. 400 PLN)', kwotaMin: 400, kwotaMax: 400,
    czestotliwosc: 'co rok',
    wymagania: { wiekMin: 55, wiekMax: 74 },
    wykluczenia: [{ opis: 'Wymaga historii palenia (min. 20 paczkolat)', sprawdz: 'palenie_historia' }],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Dowód osobisty', 'Ankieta kwalifikacyjna (historia palenia)'],
      kroki: [
        'Znajdź ośrodek realizujący program na nfz.gov.pl',
        'Wypełnij ankietę kwalifikacyjną dotyczącą historii palenia',
        'Jeśli spełnisz kryteria, wykonaj niskodawkową tomografię komputerową klatki piersiowej',
      ],
      terminRealizacji: 'Wynik w 2-3 tygodnie',
      pulapki: ['Kryterium: min. 20 paczkolat palenia lub rzucenie palenia w ciągu ostatnich 15 lat'],
      odwolanie: 'Nie dotyczy',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/programy-profilaktyczne/',
    zrodloNazwa: 'NFZ', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'prawo-do-dokumentacji-medycznej', nazwa: 'Prawo do bezpłatnej dokumentacji medycznej',
    opis: 'Każdy pacjent ma prawo do bezpłatnej pierwszej kopii swojej dokumentacji medycznej z dowolnej placówki. Obejmuje: historię choroby, karty leczenia, wyniki badań, opisy operacji, karty wypisowe, wyniki RTG i MRI. Pierwsza kopia każdego rodzaju dokumentu jest bezpłatna. Kolejne kopie tego samego dokumentu mogą być odpłatne (maksymalne stawki ustawowe). Placówka ma 30 dni na udostępnienie. Wniosek nie musi być uzasadniony ani pisemny - ustna prośba wystarczy, placówka nie może pytać "po co". Na podstawie RODO i ustawy o prawach pacjenta. Prawo do dokumentacji obejmuje też bliskich po śmierci pacjenta.',
    kategoria: 'ZDROWIE',
    kwota: 'bezpłatna pierwsza kopia każdego rodzaju dokumentu', kwotaMin: 0, kwotaMax: 0,
    czestotliwosc: 'jednorazowo (na żądanie)',
    wymagania: {},
    wykluczenia: [],
    wniosek: {
      kanal: ['NFZ', 'POZ'],
      dokumenty: [
        'Dowód tożsamości (do okazania przy odbiorze)',
        'Upoważnienie osoby trzeciej (jeśli odbiór w imieniu pacjenta)',
      ],
      kroki: [
        'Złóż wniosek w placówce, która przechowuje dokumentację (szpital, przychodnia, gabinet)',
        'Wniosek może być ustny, pisemny lub elektroniczny - forma dowolna',
        'NIE musisz uzasadniać, po co potrzebujesz dokumentacji',
        'Placówka ma 30 dni na udostępnienie (termin z RODO)',
        'Pierwsza kopia jest bezpłatna - nie płacisz nic',
        'Kolejne kopie tego samego dokumentu mogą być odpłatne (ustawowe maksymalne stawki)',
      ],
      terminRealizacji: 'Do 30 dni od złożenia wniosku (RODO)',
      pulapki: [
        'Pierwsza kopia każdego rodzaju dokumentu ZAWSZE bezpłatna (wyrok TSUE + RODO)',
        'Placówka NIE może pytać po co Ci dokumentacja',
        'Wniosek może być ustny - nie musisz pisać pisma',
        'Obejmuje: historię choroby, wyniki badań, karty wypisowe, opisy operacji, RTG, MRI',
        'Po śmierci pacjenta dokumentację mogą uzyskać bliscy (małżonek, dzieci, rodzice)',
        'Jeśli placówka odmawia lub żąda nieuzasadnionej opłaty: skarga do Rzecznika Praw Pacjenta (bezpłatna)',
      ],
      odwolanie: 'Skarga do Rzecznika Praw Pacjenta: tel. 800 190 590 (bezpłatna infolinia), rpp.gov.pl',
    },
    zrodloUrl: 'https://www.gov.pl/web/rpp/prawo-do-dokumentacji-medycznej',
    zrodloNazwa: 'Rzecznik Praw Pacjenta', dataWeryfikacji: '2026-05-23', dataWaznosci: '2027-12-31',
  },
  {
    id: 'fundusz-kompensacyjny-zdarzen-medycznych', nazwa: 'Odszkodowanie za błąd medyczny bez sądu (Fundusz Kompensacyjny)',
    opis: 'Od 1 lipca 2024 r. działa Fundusz Kompensacyjny Zdarzeń Medycznych przy Rzeczniku Praw Pacjenta - zastąpił zlikwidowane komisje wojewódzkie. Pozwala uzyskać odszkodowanie za błąd medyczny bez procesu sądowego, szybciej i taniej niż przez sąd. Maksymalne kwoty: 100 000 PLN za zakażenie, uszkodzenie ciała lub rozstrój zdrowia, 300 000 PLN za śmierć pacjenta (łącznie dla wszystkich uprawnionych). Decyzja w ciągu 4 miesięcy. Opłata za wniosek: 300 PLN (zwracana przy pozytywnej decyzji). Termin zgłoszenia: rok od dowiedzenia się o zdarzeniu, nie później niż 3 lata od zdarzenia. Dotyczy zdarzeń w podmiotach leczniczych. Nie wyklucza późniejszego procesu sądowego o wyższe odszkodowanie.',
    kategoria: 'ZDROWIE',
    kwota: 'do 100 000 PLN (uszkodzenie ciała/rozstrój zdrowia) lub do 300 000 PLN (śmierć)', kwotaMin: 0, kwotaMax: 100000,
    czestotliwosc: 'jednorazowo',
    wymagania: {},
    wykluczenia: [
      { opis: 'Termin: rok od dowiedzenia się o zdarzeniu, max 3 lata od zdarzenia', sprawdz: 'termin_blad_medyczny' },
    ],
    wniosek: {
      kanal: ['ONLINE'],
      dokumenty: [
        'Wniosek do Funduszu Kompensacyjnego (formularz na rpp.gov.pl)',
        'Dokumentacja medyczna potwierdzająca zdarzenie i jego skutki',
        'Opis zdarzenia medycznego (co się stało, kiedy, gdzie, jakie konsekwencje)',
        'Potwierdzenie opłaty 300 PLN (zwracana przy pozytywnej decyzji)',
        'Dowód osobisty lub upoważnienie dla pełnomocnika',
      ],
      kroki: [
        'Zbierz dokumentację medyczną dotyczącą zdarzenia (wypisy, wyniki badań, zaświadczenia)',
        'Złóż wniosek do Funduszu Kompensacyjnego Zdarzeń Medycznych na rpp.gov.pl',
        'Uiść opłatę 300 PLN (zwracana jeśli Fundusz uzna zdarzenie medyczne)',
        'Fundusz zbada sprawę i wyda decyzję w ciągu 4 miesięcy',
        'Przy pozytywnej decyzji: propozycja odszkodowania (możesz ją przyjąć lub odrzucić)',
        'Odrzucenie propozycji nie wyklucza procesu sądowego o wyższe odszkodowanie',
      ],
      terminRealizacji: '4 miesiące od złożenia kompletnego wniosku',
      pulapki: [
        'Od 1 VII 2024 r. to FUNDUSZ KOMPENSACYJNY przy RPP, NIE komisje wojewódzkie (te są zlikwidowane)',
        'Termin złożenia wniosku: rok od dowiedzenia się, max 3 lata od zdarzenia - po tym upływa',
        'Opłata 300 PLN: zwracana przy pozytywnej decyzji, zatrzymywana przy negatywnej',
        'Maksimum to 100 000 PLN za uszkodzenie ciała, 300 000 PLN za śmierć (łącznie dla rodziny)',
        'Możesz odrzucić propozycję funduszu i iść do sądu - decyzja funduszu nie zamyka tej drogi',
        'Dotyczy zdarzeń w podmiotach leczniczych (szpital, klinika) - nie dotyczy prywatnych gabinetów nieprowadzonych jako podmiot leczniczy',
      ],
      odwolanie: 'Odrzucenie propozycji Funduszu umożliwia drogę sądową. Skarga na działanie Funduszu: Rzecznik Praw Pacjenta rpp.gov.pl',
    },
    zrodloUrl: 'https://www.gov.pl/web/rpp/fundusz-kompensacyjny-zdarzen-medycznych',
    zrodloNazwa: 'Rzecznik Praw Pacjenta', dataWeryfikacji: '2026-05-23', dataWaznosci: '2027-12-31',
  },
];
