import { Benefit } from '../types';

export const ZDROWIE: Benefit[] = [
  {
    id: 'moje-zdrowie', nazwa: 'Program Moje Zdrowie', kategoria: 'ZDROWIE',
    kwota: 'bezplatne badania (wartosc ok. 500 PLN)', kwotaMin: 500, kwotaMax: 500,
    czestotliwosc: 'co 3-5 lat',
    wymagania: { wiekMin: 20 },
    wykluczenia: [],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Dowod osobisty lub mObywatel', 'Karta ubezpieczenia zdrowotnego (opcjonalnie)'],
      kroki: [
        'Wejdz na pacjent.gov.pl lub aplikacje Moje IKP',
        'Wypelnij ankiete zdrowotna online',
        'Umow wizyte w swoim osrodku POZ (lekarz pierwszego kontaktu)',
        'Wykonaj badania: morfologia, glukoza, kreatynina, lipidogram, badanie moczu',
        'Odbierz wyniki i omow je z lekarzem',
      ],
      terminRealizacji: 'Wyniki w ciagu 7-14 dni',
      pulapki: [
        'Badanie dostepne raz na 5 lat (wiek 20-49) lub raz na 3 lata (wiek 50+)',
        'Trzeba najpierw wypelnic ankiete -- bez niej POZ moze odmowic',
        'Nie kazdy POZ realizuje program -- sprawdz liste na pacjent.gov.pl',
      ],
      odwolanie: 'Program dobrowolny -- nie wymaga odwolania',
    },
    zrodloUrl: 'https://pacjent.gov.pl/program-moje-zdrowie',
    zrodloNazwa: 'Ministerstwo Zdrowia', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'mammografia', nazwa: 'Mammografia profilaktyczna', kategoria: 'ZDROWIE',
    kwota: 'bezplatne badanie', czestotliwosc: 'co 2 lata',
    wymagania: { wiekMin: 45, wiekMax: 74, plec: 'K' },
    wykluczenia: [{ opis: 'Kobiety leczone z powodu raka piersi', sprawdz: 'leczenie_rak_piersi' }],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Dowod osobisty'],
      kroki: [
        'Znajdz placowke realizujaca program na nfz.gov.pl/dla-pacjenta/programy-profilaktyczne',
        'Zadzwon i umow termin -- nie potrzebujesz skierowania',
        'Przyjdz na badanie mammograficzne',
        'Wynik otrzymasz pocztowo lub w placowce w ciagu 2-3 tygodni',
      ],
      terminRealizacji: 'Wynik w 2-3 tygodnie',
      pulapki: ['Nie potrzebujesz skierowania od lekarza -- mozesz isc bezposrednio', 'Badanie co 2 lata, nie czesciej'],
      odwolanie: 'Nie dotyczy',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/programy-profilaktyczne/',
    zrodloNazwa: 'NFZ', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'cytologia', nazwa: 'Cytologia profilaktyczna', kategoria: 'ZDROWIE',
    kwota: 'bezplatne badanie', czestotliwosc: 'co 3 lata',
    wymagania: { wiekMin: 25, wiekMax: 64, plec: 'K' },
    wykluczenia: [],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Dowod osobisty'],
      kroki: [
        'Znajdz gabinet ginekologiczny realizujacy program na nfz.gov.pl',
        'Umow wizyte -- nie potrzebujesz skierowania',
        'Wykonaj badanie cytologiczne',
        'Wynik otrzymasz w ciagu 2-4 tygodni',
      ],
      terminRealizacji: 'Wynik w 2-4 tygodnie',
      pulapki: ['Badanie co 3 lata -- jesli wykonalas cytologie prywatnie, i tak mozesz skorzystac z programu NFZ', 'Nie potrzebujesz skierowania'],
      odwolanie: 'Nie dotyczy',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/programy-profilaktyczne/',
    zrodloNazwa: 'NFZ', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'kolonoskopia', nazwa: 'Kolonoskopia profilaktyczna', kategoria: 'ZDROWIE',
    kwota: 'bezplatne badanie', czestotliwosc: 'co 10 lat',
    wymagania: { wiekMin: 50, wiekMax: 65 },
    wykluczenia: [],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Dowod osobisty', 'Wyniki badan krwi (morfologia, koagulologia)'],
      kroki: [
        'Znajdz osrodek realizujacy program na nfz.gov.pl',
        'Zadzwon i zapisz sie -- nie potrzebujesz skierowania',
        'Przygotuj sie do badania (dieta 3 dni przed, srodek czyszczacy)',
        'Wykonaj kolonoskopie',
      ],
      terminRealizacji: 'Badanie w ciagu 1-3 miesiecy od zapisania',
      pulapki: [
        'Osoby 40-49 z wywiadem rodzinnym (rak jelita grubego u krewnego I stopnia) tez sie kwalifikuja',
        'Wymaga przygotowania -- dieta i oczyszczenie jelita',
      ],
      odwolanie: 'Nie dotyczy',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/programy-profilaktyczne/',
    zrodloNazwa: 'NFZ', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'prostata', nazwa: 'Badania prostaty (PSA)', kategoria: 'ZDROWIE',
    kwota: 'bezplatne badanie', czestotliwosc: 'co rok',
    wymagania: { wiekMin: 50, plec: 'M' },
    wykluczenia: [],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Dowod osobisty'],
      kroki: [
        'Zglos sie do lekarza POZ po skierowanie na badanie PSA',
        'Wykonaj badanie krwi w laboratorium',
        'Odbierz wyniki i omow z lekarzem',
      ],
      terminRealizacji: 'Wynik w 3-7 dni',
      pulapki: ['Mezczyzni 45+ z wywiadem rodzinnym powinni zaczac wczesniej', 'Badanie PSA to badanie krwi -- nie wymaga specjalnego przygotowania'],
      odwolanie: 'Nie dotyczy',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/programy-profilaktyczne/',
    zrodloNazwa: 'NFZ', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'szczepienia-hpv', nazwa: 'Szczepienia przeciwko HPV', kategoria: 'ZDROWIE',
    kwota: 'bezplatne szczepienie (wartosc ok. 1500 PLN)', kwotaMin: 1500, kwotaMax: 1500,
    czestotliwosc: 'jednorazowo',
    wymagania: { wiekMin: 12, wiekMax: 13, plec: 'K' },
    wykluczenia: [],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Ksiazeczka zdrowia dziecka', 'Zgoda rodzica/opiekuna'],
      kroki: [
        'Skontaktuj sie z lekarzem POZ dziecka',
        'Lekarz zakwalifikuje dziecko do szczepienia',
        'Szczepienie w 2 dawkach w odstepie 6 miesiecy',
      ],
      terminRealizacji: 'Szczepienie dostepne od razu',
      pulapki: ['Program dotyczy dziewczat -- chlopcy nie sa objeci programem bezplatnym', 'Wymagane 2 dawki w odstepie 6 miesiecy'],
      odwolanie: 'Nie dotyczy',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/programy-profilaktyczne/',
    zrodloNazwa: 'NFZ', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'profilaktyka-krazenia', nazwa: 'Profilaktyka chorob ukladu krazenia', kategoria: 'ZDROWIE',
    kwota: 'bezplatne badanie', czestotliwosc: 'co 5 lat',
    wymagania: { wiekMin: 35, wiekMax: 65 },
    wykluczenia: [{ opis: 'Osoby leczone z powodu chorob ukladu krazenia', sprawdz: 'leczenie_krazenie' }],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Dowod osobisty'],
      kroki: [
        'Zglos sie do lekarza POZ i zapytaj o program CHUK',
        'Wypelnij ankiete oceny ryzyka sercowo-naczyniowego',
        'Wykonaj badania: cisnienie, cholesterol, glukoza',
        'Lekarz omowi wyniki i zaleci dalsze postepowanie',
      ],
      terminRealizacji: 'Wyniki na miejscu lub w ciagu tygodnia',
      pulapki: ['Badanie co 5 lat -- warto sprawdzic kiedy ostatnio korzystales'],
      odwolanie: 'Nie dotyczy',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/programy-profilaktyczne/',
    zrodloNazwa: 'NFZ', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
  {
    id: 'rak-pluc', nazwa: 'Wczesne wykrywanie raka pluc', kategoria: 'ZDROWIE',
    kwota: 'bezplatna tomografia (wartosc ok. 400 PLN)', kwotaMin: 400, kwotaMax: 400,
    czestotliwosc: 'co rok',
    wymagania: { wiekMin: 55, wiekMax: 74 },
    wykluczenia: [{ opis: 'Wymaga historii palenia (min. 20 paczkolat)', sprawdz: 'palenie_historia' }],
    wniosek: {
      kanal: ['POZ'],
      dokumenty: ['Dowod osobisty', 'Ankieta kwalifikacyjna (historia palenia)'],
      kroki: [
        'Znajdz osrodek realizujacy program na nfz.gov.pl',
        'Wypelnij ankiete kwalifikacyjna dotyczaca historii palenia',
        'Jesli spelnisz kryteria -- wykonaj niskodawkowa tomografie komputerowa klatki piersiowej',
      ],
      terminRealizacji: 'Wynik w 2-3 tygodnie',
      pulapki: ['Kryterium: min. 20 paczkolat palenia lub rzucenie palenia w ciagu ostatnich 15 lat'],
      odwolanie: 'Nie dotyczy',
    },
    zrodloUrl: 'https://www.nfz.gov.pl/dla-pacjenta/programy-profilaktyczne/',
    zrodloNazwa: 'NFZ', dataWeryfikacji: '2026-05-09', dataWaznosci: '2026-12-31',
  },
];
