import { Benefit } from '../types';

export const ZUS: Benefit[] = [
  {
    id: 'zasilek-chorobowy', nazwa: 'Zasiłek chorobowy (L4)', kategoria: 'ZUS',
    kwota: '80% wynagrodzenia (100% w ciąży, wypadek przy pracy lub badania dawców)',
    czestotliwosc: 'dziennie (max 182 dni, 270 dni w ciąży/gruźlica)',
    wymagania: {
      zatrudnienie: ['umowa_o_prace', 'umowa_zlecenie', 'dzialalnosc'],
    },
    wykluczenia: [
      { opis: 'Brak ubezpieczenia chorobowego (np. umowa o dzieło)', sprawdz: 'ubezpieczenie_chorobowe' },
      { opis: 'Niezdolność do pracy powstała w pierwszych 30 dniach ubezpieczenia (pracownik) lub 90 dniach (dobrowolne)', sprawdz: 'okres_wyczekiwania' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS Z-3 (pracownik) / ZUS Z-3a (zleceniobiorca) / ZUS Z-3b (działalność)',
      dokumenty: [
        'Zwolnienie lekarskie e-ZLA (wystawiane elektronicznie przez lekarza)',
        'Zaświadczenie płatnika składek ZUS Z-3/Z-3a/Z-3b',
        'Dowód osobisty',
      ],
      kroki: [
        'Lekarz wystawia e-ZLA, trafia automatycznie do ZUS i pracodawcy',
        'Pracodawca wypełnia ZUS Z-3 i przekazuje do ZUS (jeśli zasiłek wypłaca ZUS)',
        'Pierwsze 33 dni choroby w roku (14 dni dla osób 50+) płaci pracodawca jako wynagrodzenie chorobowe',
        'Od 34. dnia (15. dnia dla 50+) zasiłek chorobowy wypłaca ZUS',
        'Osoby prowadzące działalność składają wniosek ZUS Z-3b na PUE ZUS',
      ],
      terminRealizacji: '30 dni od złożenia kompletnej dokumentacji',
      pulapki: [
        'Pierwsze 33 dni to wynagrodzenie chorobowe od pracodawcy, nie zasiłek ZUS',
        'Okres wyczekiwania: 30 dni ciągłego ubezpieczenia (pracownik) lub 90 dni (dobrowolne)',
        'Maksymalnie 182 dni zasiłku (270 dni przy ciąży lub gruźlicy)',
        'Kontrola ZUS może skutkować utratą zasiłku. Nie wykonuj pracy zarobkowej na L4',
      ],
      odwolanie: 'Sprzeciw do Komisji Lekarskiej ZUS w ciągu 14 dni, potem odwołanie do Sądu Pracy',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/zasilki/zasilek-chorobowy',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'zasilek-macierzynski', nazwa: 'Zasiłek macierzyński', kategoria: 'ZUS',
    kwota: '81,5% wynagrodzenia (wniosek do 21 dni po porodzie) lub 100%/70% (bez wcześniejszego wniosku)',
    czestotliwosc: 'miesięcznie (20-37 tygodni urlop macierzyński + do 32-34 tygodni urlop rodzicielski)',
    wymagania: {
      ciaza: true,
      zatrudnienie: ['umowa_o_prace', 'umowa_zlecenie', 'dzialalnosc'],
    },
    wykluczenia: [
      { opis: 'Brak ubezpieczenia chorobowego w dniu porodu', sprawdz: 'ubezpieczenie_chorobowe_porod' },
      { opis: 'Osoby bez tytułu do ubezpieczenia mogą ubiegać się o kosiniakowe zamiast zasiłku macierzyńskiego', sprawdz: 'brak_ubezpieczenia' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS Z-3 / ZUS Z-3a / ZUS Z-3b + wniosek do pracodawcy',
      dokumenty: [
        'Akt urodzenia dziecka lub zaświadczenie lekarskie o przewidywanej dacie porodu',
        'Wniosek o urlop macierzyński i rodzicielski (do pracodawcy)',
        'Zaświadczenie płatnika składek ZUS Z-3',
      ],
      kroki: [
        'Złóż wniosek o urlop macierzyński u pracodawcy',
        'W ciągu 21 dni po porodzie złóż wniosek o zasiłek za cały okres (macierzyński + rodzicielski) -- stawka 81,5%',
        'Jeśli nie złożysz w 21 dni: 100% za urlop macierzyński, potem 70% za rodzicielski',
        'Pracodawca przekazuje ZUS Z-3 do ZUS',
        'ZUS wypłaca zasiłek co miesiąc',
      ],
      terminRealizacji: '30 dni od złożenia wniosku',
      pulapki: [
        'Termin 21 dni po porodzie jest kluczowy -- decyduje o stawce 81,5% vs 100%/70%',
        'Ojciec może przejąć część urlopu rodzicielskiego (9 tygodni zarezerwowane wyłącznie dla drugiego rodzica)',
        'Na działalności: podstawa zasiłku zależy od opłacanych składek przez min. 12 miesięcy',
        'Zasiłek macierzyński nie może być niższy niż 1000 PLN miesięcznie (dopełnienie do kosiniakowego)',
      ],
      odwolanie: 'Odwołanie do Sądu Pracy w ciągu 30 dni od decyzji ZUS',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/zasilki/zasilek-macierzynski',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'zasilek-opiekunczy', nazwa: 'Zasiłek opiekuńczy', kategoria: 'ZUS',
    kwota: '80% wynagrodzenia',
    czestotliwosc: 'dziennie (max 60 dni/rok -- dziecko do 14 lat; 14 dni/rok -- inny członek rodziny)',
    wymagania: {
      zatrudnienie: ['umowa_o_prace', 'umowa_zlecenie', 'dzialalnosc'],
    },
    wykluczenia: [
      { opis: 'Brak ubezpieczenia chorobowego', sprawdz: 'ubezpieczenie_chorobowe' },
      { opis: 'Inny członek rodziny może zapewnić opiekę (nie dotyczy opieki nad chorym dzieckiem do lat 2)', sprawdz: 'inny_opiekun' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS Z-15A (dziecko) / ZUS Z-15B (inny członek rodziny)',
      dokumenty: [
        'Zwolnienie lekarskie e-ZLA na chore dziecko/członka rodziny',
        'Wniosek ZUS Z-15A lub Z-15B',
        'Zaświadczenie płatnika składek ZUS Z-3',
      ],
      kroki: [
        'Lekarz wystawia e-ZLA na opiekę nad chorym dzieckiem lub członkiem rodziny',
        'Wypełnij formularz ZUS Z-15A (dziecko) lub Z-15B (inny członek rodziny)',
        'Pracodawca przekazuje dokumenty do ZUS',
        'ZUS wypłaca zasiłek w ciągu 30 dni',
      ],
      terminRealizacji: '30 dni od złożenia kompletnych dokumentów',
      pulapki: [
        'Limit 60 dni na dziecko do 14 lat dotyczy łącznie obojga rodziców -- nie na każde dziecko osobno',
        'Na chore dziecko 14-18 lat (niepełnosprawne) -- limit 30 dni',
        'Na innego członka rodziny (np. małżonka, rodzica) -- limit 14 dni',
        'Zdrowe dziecko do lat 8: zasiłek przysługuje tylko w wyjątkowych sytuacjach (np. zamknięcie żłobka, szkoły)',
      ],
      odwolanie: 'Odwołanie do Sądu Pracy w ciągu 30 dni od decyzji ZUS',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/zasilki/zasilek-opiekunczy',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'swiadczenie-rehabilitacyjne', nazwa: 'Świadczenie rehabilitacyjne', kategoria: 'ZUS',
    kwota: '90% wynagrodzenia (pierwsze 3 mies.), 75% (pozostały okres), 100% (ciąża/wypadek przy pracy)',
    czestotliwosc: 'miesięcznie (max 12 miesięcy)',
    wymagania: {
      zatrudnienie: ['umowa_o_prace', 'umowa_zlecenie', 'dzialalnosc'],
    },
    wykluczenia: [
      { opis: 'Nie wyczerpano jeszcze okresu zasiłku chorobowego (182/270 dni)', sprawdz: 'wyczerpanie_zasilku_chorobowego' },
      { opis: 'Osoba ma ustalone prawo do emerytury, renty lub zasiłku dla bezrobotnych', sprawdz: 'inne_swiadczenia' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS Np-7 (wniosek o świadczenie rehabilitacyjne)',
      dokumenty: [
        'Wniosek ZUS Np-7',
        'Zaświadczenie o stanie zdrowia OL-9 (wypełnia lekarz prowadzący)',
        'Wywiad zawodowy z miejsca pracy N-10',
        'Zaświadczenie płatnika składek ZUS Z-3',
      ],
      kroki: [
        'Złóż wniosek ZUS Np-7 najlepiej 6 tygodni przed końcem zasiłku chorobowego',
        'Lekarz prowadzący wypełnia zaświadczenie OL-9',
        'Pracodawca wypełnia wywiad zawodowy N-10',
        'Lekarz orzecznik ZUS bada i wydaje orzeczenie',
        'ZUS wydaje decyzję -- wypłata świadczenia co miesiąc',
      ],
      terminRealizacji: '60 dni od złożenia wniosku (badanie przez lekarza orzecznika)',
      pulapki: [
        'Złóż wniosek 6 tygodni przed końcem zasiłku chorobowego -- żeby nie było przerwy w wypłatach',
        'Świadczenie przysługuje tylko jeśli dalsze leczenie rokuje odzyskanie zdolności do pracy',
        'Praca zarobkowa w trakcie pobierania = utrata świadczenia',
        'Odmowa poddania się badaniu lub rehabilitacji = utrata prawa do świadczenia',
      ],
      odwolanie: 'Sprzeciw do Komisji Lekarskiej ZUS w ciągu 14 dni od orzeczenia, potem odwołanie do Sądu Pracy',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/zasilki/swiadczenie-rehabilitacyjne',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'zasilek-pogrzebowy', nazwa: 'Zasiłek pogrzebowy', kategoria: 'ZUS',
    kwota: '7000 PLN jednorazowo (od 1 stycznia 2026; osobom spoza rodziny -- do wysokości poniesionych kosztów, max 7000 PLN)',
    kwotaMin: 7000, kwotaMax: 7000,
    czestotliwosc: 'jednorazowo',
    wymagania: {},
    wykluczenia: [
      { opis: 'Wniosek złożony po upływie 12 miesięcy od dnia śmierci (prawo wygasa)', sprawdz: 'termin_12_miesiecy' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS Z-12 (wniosek o zasiłek pogrzebowy)',
      dokumenty: [
        'Akt zgonu',
        'Rachunki/faktury potwierdzające poniesione koszty pogrzebu',
        'Dokument potwierdzający pokrewieństwo (akt małżeństwa, akt urodzenia)',
        'Dowód osobisty wnioskodawcy',
      ],
      kroki: [
        'Zbierz rachunki i faktury za koszty pogrzebu',
        'Wypełnij formularz ZUS Z-12',
        'Dołącz akt zgonu i dokumenty potwierdzające pokrewieństwo',
        'Złóż wniosek w oddziale ZUS lub przez PUE ZUS',
        'ZUS wypłaci zasiłek w ciągu 30 dni',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'Od 1 stycznia 2026 kwota wzrosła z 4000 PLN do 7000 PLN',
        'Data śmierci decyduje o kwocie -- nie data złożenia wniosku',
        'Wniosek trzeba złożyć w ciągu 12 miesięcy od dnia pogrzebu',
        'Jeśli pogrzeb opłacił zakład pogrzebowy na zlecenie -- zasiłek przysługuje tej osobie, która poniosła koszty',
      ],
      odwolanie: 'Odwołanie do Sądu Pracy w ciągu 30 dni od decyzji ZUS',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/zasilki/zasilek-pogrzebowy',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'renta-socjalna', nazwa: 'Renta socjalna', kategoria: 'ZUS',
    kwota: '1978,49 PLN brutto miesięcznie (od marca 2026, równa najniższej rencie)',
    kwotaMin: 1978, kwotaMax: 1978,
    czestotliwosc: 'miesięcznie',
    wymagania: {
      niepelnosprawnosc: ['umiarkowany', 'znaczny'],
    },
    wykluczenia: [
      { opis: 'Niezdolność do pracy nie powstała przed ukończeniem 18 roku życia, w trakcie nauki (do 25 lat) lub studiów doktoranckich', sprawdz: 'okres_powstania_niezdolnosci' },
      { opis: 'Osoba ma ustalone prawo do emerytury, renty z tytułu niezdolności do pracy lub renty strukturalnej', sprawdz: 'inne_swiadczenia_renta' },
      { opis: 'Pobiera świadczenie o charakterze rentowym z instytucji zagranicznej', sprawdz: 'swiadczenie_zagraniczne' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS ERN (wniosek o rentę socjalną)',
      dokumenty: [
        'Wniosek ZUS ERN',
        'Zaświadczenie o stanie zdrowia OL-9',
        'Dokumentacja medyczna potwierdzająca całkowitą niezdolność do pracy',
        'Zaświadczenie o uczęszczaniu do szkoły/uczelni (jeśli niezdolność powstała w trakcie nauki)',
        'Dowód osobisty',
      ],
      kroki: [
        'Przygotuj dokumentację medyczną potwierdzającą całkowitą niezdolność do pracy',
        'Lekarz prowadzący wypełnia zaświadczenie OL-9',
        'Wypełnij wniosek ZUS ERN',
        'Złóż wniosek w oddziale ZUS lub przez PUE ZUS',
        'Lekarz orzecznik ZUS zbada i wyda orzeczenie',
        'ZUS wyda decyzję w ciągu 30 dni od orzeczenia',
      ],
      terminRealizacji: '30-60 dni od złożenia wniosku (w tym badanie przez lekarza orzecznika)',
      pulapki: [
        'Renta socjalna wymaga całkowitej niezdolności do pracy -- umiarkowany stopień niepełnosprawności nie zawsze wystarcza',
        'Niezdolność musi powstać przed 18 r.ż., w trakcie nauki (do 25 lat) lub na studiach doktoranckich',
        'Można dorabiać do 6438,50 PLN brutto miesięcznie (od marca 2026) bez wpływu na świadczenie',
        'Przekroczenie granicy przychodu powoduje zawieszenie renty',
      ],
      odwolanie: 'Sprzeciw do Komisji Lekarskiej ZUS w ciągu 14 dni, potem odwołanie do Sądu Pracy w ciągu 30 dni',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/renty/renta-socjalna',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'emerytura-pomostowa', nazwa: 'Emerytura pomostowa', kategoria: 'ZUS',
    kwota: 'Obliczana indywidualnie -- minimalna 1978,49 PLN brutto (od marca 2026)',
    kwotaMin: 1978, kwotaMax: 3200,
    czestotliwosc: 'miesięcznie',
    wymagania: {
      wiekMin: 55,
      zatrudnienie: ['umowa_o_prace'],
    },
    wykluczenia: [
      { opis: 'Brak pracy w szczególnych warunkach lub o szczególnym charakterze (wykaz w załączniku do ustawy)', sprawdz: 'praca_szczegolne_warunki' },
      { opis: 'Brak wymaganego stażu ubezpieczeniowego (20 lat kobiety, 25 lat mężczyźni)', sprawdz: 'staz_ubezpieczeniowy' },
      { opis: 'Nieosiągnięcie wieku: 55 lat kobiety, 60 lat mężczyźni', sprawdz: 'wiek_pomostowy' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS EPOM (wniosek o emeryturę pomostową)',
      dokumenty: [
        'Wniosek ZUS EPOM',
        'Świadectwa pracy potwierdzające pracę w szczególnych warunkach',
        'Zaświadczenie pracodawcy o pracy w szczególnych warunkach/charakterze',
        'Dokumenty potwierdzające okresy składkowe i nieskładkowe',
        'Dowód osobisty',
      ],
      kroki: [
        'Sprawdź czy Twój zawód figuruje w wykazie prac w szczególnych warunkach (załącznik 1 i 2 ustawy o emeryturach pomostowych)',
        'Zbierz świadectwa pracy i zaświadczenia od pracodawców',
        'Wypełnij wniosek ZUS EPOM',
        'Złóż wniosek w oddziale ZUS lub przez PUE ZUS',
        'ZUS zweryfikuje staż i wyda decyzję',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'Od 2024 r. zniesiono wymóg pracy w szczególnych warunkach przed 31.12.1998 -- teraz dostępna także dla młodszych pracowników',
        'Nie musisz rozwiązywać stosunku pracy przed złożeniem wniosku, ale musisz to zrobić przed przyznaniem emerytury pomostowej',
        'Emerytura pomostowa jest bezterminowa -- przysługuje do osiągnięcia powszechnego wieku emerytalnego',
        'Można dorabiać, ale po przekroczeniu progu ZUS zmniejszy lub zawiesi świadczenie',
      ],
      odwolanie: 'Odwołanie do Sądu Pracy w ciągu 30 dni od decyzji ZUS',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/emerytury/emerytury-pomostowe',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'swiadczenie-przedemerytalne', nazwa: 'Świadczenie przedemerytalne', kategoria: 'ZUS',
    kwota: '1993,76 PLN brutto miesięcznie (od marca 2026)',
    kwotaMin: 1994, kwotaMax: 1994,
    czestotliwosc: 'miesięcznie',
    wymagania: {
      wiekMin: 55,
      bezrobotnyZarejestrowany: true,
    },
    wykluczenia: [
      { opis: 'Brak 180-dniowego okresu pobierania zasiłku dla bezrobotnych', sprawdz: 'zasilek_bezrobotnych_180' },
      { opis: 'Rozwiązanie umowy z winy pracownika (dyscyplinarka)', sprawdz: 'przyczyna_rozwiazania' },
      { opis: 'Niespełnienie warunków stażowych (20/25 lat) i wiekowych (56/61 lat) -- różne progi w zależności od przyczyny utraty pracy', sprawdz: 'warunki_staz_wiek' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS ESP (wniosek o świadczenie przedemerytalne)',
      dokumenty: [
        'Wniosek ZUS ESP',
        'Zaświadczenie z PUP o 180-dniowym okresie pobierania zasiłku dla bezrobotnych',
        'Świadectwo pracy z ostatniego zatrudnienia',
        'Dokumenty potwierdzające przyczynę rozwiązania umowy (np. wypowiedzenie z przyczyn pracodawcy, likwidacja)',
        'Dowód osobisty',
      ],
      kroki: [
        'Zarejestruj się w PUP jako bezrobotny i pobieraj zasiłek przez 180 dni',
        'Po 180 dniach PUP wydaje zaświadczenie',
        'W ciągu 30 dni od wydania zaświadczenia złóż wniosek ZUS ESP',
        'Dołącz świadectwa pracy i dokumenty potwierdzające przyczynę utraty pracy',
        'ZUS wyda decyzję w ciągu 30 dni',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'Termin 30 dni od zaświadczenia PUP jest bezwzględny -- po nim tracisz prawo',
        'Umowa musi być rozwiązana z przyczyn leżących po stronie pracodawcy (likwidacja, upadłość, zwolnienia grupowe)',
        'Można dorabiać do 2225,90 PLN brutto miesięcznie bez wpływu na świadczenie (od marca 2026)',
        'Przekroczenie 6232,50 PLN brutto miesięcznie = zawieszenie świadczenia',
      ],
      odwolanie: 'Odwołanie do Sądu Pracy w ciągu 30 dni od decyzji ZUS',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/swiadczenia-przedemerytalne',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'mama-4-plus', nazwa: 'Rodzicielskie świadczenie uzupełniające (Mama 4+)', kategoria: 'ZUS',
    kwota: 'Do 1978,49 PLN brutto miesięcznie (od marca 2026, uzupełnienie do minimalnej emerytury)',
    kwotaMin: 0, kwotaMax: 1978,
    czestotliwosc: 'miesięcznie',
    wymagania: {
      wiekMin: 60,
      plec: 'dowolna',
      dzieci: { min: 4 },
    },
    wykluczenia: [
      { opis: 'Wychowanie mniej niż czworga dzieci', sprawdz: 'liczba_dzieci_4' },
      { opis: 'Pozbawienie władzy rodzicielskiej lub ograniczenie władzy przez umieszczenie dziecka w pieczy zastępczej', sprawdz: 'wladza_rodzicielska' },
      { opis: 'Długotrwałe zaprzestanie wychowania dzieci', sprawdz: 'zaprzestanie_wychowania' },
      { opis: 'Tymczasowe aresztowanie lub pozbawienie wolności', sprawdz: 'pozbawienie_wolnosci' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS ERSU (wniosek o rodzicielskie świadczenie uzupełniające)',
      dokumenty: [
        'Wniosek ZUS ERSU',
        'Akty urodzenia dzieci',
        'Dowód osobisty',
        'Oświadczenie o sytuacji osobistej, rodzinnej, majątkowej i materialnej',
        'Informacja o numerach PESEL dzieci',
        'Dokumenty potwierdzające okresy zatrudnienia (jeśli były)',
      ],
      kroki: [
        'Upewnij się że spełniasz warunki wiekowe: 60 lat (kobiety) lub 65 lat (mężczyźni)',
        'Wypełnij wniosek ZUS ERSU',
        'Dołącz akty urodzenia co najmniej czworga dzieci',
        'Złóż wniosek w oddziale ZUS lub przez PUE ZUS',
        'Prezes ZUS wyda decyzję po analizie sytuacji',
      ],
      terminRealizacji: '30 dni od złożenia wniosku (decyzja Prezesa ZUS)',
      pulapki: [
        'Świadczenie jest uznaniowe -- Prezes ZUS może odmówić',
        'Dla kobiet wiek minimalny to 60 lat, dla mężczyzn 65 lat',
        'Jeśli masz już emeryturę lub rentę niższą niż minimalna -- świadczenie uzupełnia do kwoty minimalnej',
        'Jeśli nie masz żadnej emerytury -- możesz dostać pełną kwotę 1978,49 PLN brutto',
        'Mężczyźni też mogą się ubiegać (mimo nazwy "Mama 4+")',
      ],
      odwolanie: 'Wniosek o ponowne rozpatrzenie sprawy do Prezesa ZUS, potem skarga do WSA',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/rodzicielskie-swiadczenie-uzupelniajace',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: '13-emerytura', nazwa: '13. emerytura (trzynastka)', kategoria: 'ZUS',
    kwota: '1978,49 PLN brutto jednorazowo (kwiecień 2026, równa minimalnej emeryturze)',
    kwotaMin: 1978, kwotaMax: 1978,
    czestotliwosc: 'rocznie (wypłata w kwietniu)',
    wymagania: {
      emeryt: true,
    },
    wykluczenia: [
      { opis: 'Prawo do emerytury lub renty zawieszone na dzień 31 marca danego roku', sprawdz: 'zawieszenie_emerytury_marzec' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      dokumenty: ['Brak -- świadczenie wypłacane automatycznie (nie trzeba składać wniosku)'],
      kroki: [
        'Świadczenie jest wypłacane z urzędu -- nie trzeba składać wniosku',
        'ZUS wypłaca trzynastkę razem z emeryturą lub rentą w kwietniu',
        'Sprawdź czy Twoje świadczenie nie jest zawieszone na dzień 31 marca',
      ],
      terminRealizacji: 'Automatyczna wypłata w kwietniu każdego roku',
      pulapki: [
        'Brak progu dochodowego -- przysługuje wszystkim emerytom i rencistom',
        'Świadczenie musi być aktywne (nie zawieszone) na 31 marca',
        'Przysługuje również osobom pobierającym rentę socjalną, świadczenie przedemerytalne, rentę rodzinną',
        'Kwota odpowiada minimalnej emeryturze po marcowej waloryzacji',
      ],
      odwolanie: 'Odwołanie do Sądu Pracy w ciągu 30 dni od decyzji (jeśli ZUS odmówi)',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/emerytury/dodatkowe-roczne-swiadczenie-pieniezne',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: '14-emerytura', nazwa: '14. emerytura (czternastka)', kategoria: 'ZUS',
    kwota: 'Do 1978,49 PLN brutto jednorazowo (pełna kwota przy emeryturze do 2900 PLN brutto; powyżej -- pomniejszana o nadwyżkę)',
    kwotaMin: 50, kwotaMax: 1978,
    czestotliwosc: 'rocznie (wypłata we wrześniu)',
    wymagania: {
      emeryt: true,
    },
    wykluczenia: [
      { opis: 'Emerytura/renta brutto przekracza 4828,49 PLN (świadczenie nie przysługuje)', sprawdz: 'prog_14_emerytura' },
      { opis: 'Prawo do emerytury/renty zawieszone w dniu wypłaty', sprawdz: 'zawieszenie_emerytury_wrzesien' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      dokumenty: ['Brak -- świadczenie wypłacane automatycznie (nie trzeba składać wniosku)'],
      kroki: [
        'Świadczenie jest wypłacane z urzędu -- nie trzeba składać wniosku',
        'ZUS wypłaca czternastkę razem z emeryturą/rentą we wrześniu',
        'Pełna kwota przysługuje przy emeryturze do 2900 PLN brutto',
        'Powyżej 2900 PLN -- stosowana zasada "złotówka za złotówkę" (każdy złoty powyżej progu zmniejsza czternastkę)',
      ],
      terminRealizacji: 'Automatyczna wypłata we wrześniu każdego roku',
      pulapki: [
        'Próg dochodowy 2900 PLN brutto -- powyżej tej kwoty czternastka jest pomniejszana',
        'Przy emeryturze powyżej 4828,49 PLN brutto czternastka nie przysługuje wcale',
        'Minimalna wypłata to 50 PLN brutto -- poniżej ZUS nie wypłaca',
        'W odróżnieniu od trzynastki, czternastka MA próg dochodowy',
        'Czternastka przysługuje również rencistom, osobom na świadczeniu przedemerytalnym',
      ],
      odwolanie: 'Odwołanie do Sądu Pracy w ciągu 30 dni od decyzji (jeśli ZUS odmówi)',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/emerytury/kolejne-dodatkowe-roczne-swiadczenie-pieniezne',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
];
