import { Benefit } from '../types';

export const ZUS: Benefit[] = [
  {
    id: 'zasilek-chorobowy', nazwa: 'Zasilek chorobowy (L4)', kategoria: 'ZUS',
    kwota: '80% wynagrodzenia (100% w ciazy, wypadek przy pracy lub badania dawcow)',
    czestotliwosc: 'dziennie (max 182 dni, 270 dni w ciazy/gruzlica)',
    wymagania: {
      zatrudnienie: ['umowa_o_prace', 'umowa_zlecenie', 'dzialalnosc'],
    },
    wykluczenia: [
      { opis: 'Brak ubezpieczenia chorobowego (np. umowa o dzielo)', sprawdz: 'ubezpieczenie_chorobowe' },
      { opis: 'Niezdolnosc do pracy powstala w pierwszych 30 dniach ubezpieczenia (pracownik) lub 90 dniach (dobrowolne)', sprawdz: 'okres_wyczekiwania' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS Z-3 (pracownik) / ZUS Z-3a (zleceniobiorca) / ZUS Z-3b (dzialalnosc)',
      dokumenty: [
        'Zwolnienie lekarskie e-ZLA (wystawiane elektronicznie przez lekarza)',
        'Zaswiadczenie platnika skladek ZUS Z-3/Z-3a/Z-3b',
        'Dowod osobisty',
      ],
      kroki: [
        'Lekarz wystawia e-ZLA -- trafia automatycznie do ZUS i pracodawcy',
        'Pracodawca wypelnia ZUS Z-3 i przekazuje do ZUS (jesli zasilek wyplaca ZUS)',
        'Pierwsze 33 dni choroby w roku (14 dni dla osob 50+) placi pracodawca jako wynagrodzenie chorobowe',
        'Od 34. dnia (15. dnia dla 50+) zasilek chorobowy wyplaca ZUS',
        'Osoby prowadzace dzialalnosc skladaja wniosek ZUS Z-3b na PUE ZUS',
      ],
      terminRealizacji: '30 dni od zlozenia kompletnej dokumentacji',
      pulapki: [
        'Pierwsze 33 dni to wynagrodzenie chorobowe od pracodawcy -- nie zasilek ZUS',
        'Okres wyczekiwania: 30 dni ciaglego ubezpieczenia (pracownik) lub 90 dni (dobrowolne)',
        'Maksymalnie 182 dni zasilku (270 dni przy ciazy lub gruzlicy)',
        'Kontrola ZUS moze skutkowac utrata zasilku -- nie wykonuj pracy zarobkowej na L4',
      ],
      odwolanie: 'Sprzeciw do Komisji Lekarskiej ZUS w ciagu 14 dni, potem odwolanie do Sadu Pracy',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/zasilki/zasilek-chorobowy',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'zasilek-macierzynski', nazwa: 'Zasilek macierzynski', kategoria: 'ZUS',
    kwota: '81,5% wynagrodzenia (wniosek do 21 dni po porodzie) lub 100%/70% (bez wczesniejszego wniosku)',
    czestotliwosc: 'miesiecznie (20-37 tygodni urlop macierzynski + do 32-34 tygodni urlop rodzicielski)',
    wymagania: {
      ciaza: true,
      zatrudnienie: ['umowa_o_prace', 'umowa_zlecenie', 'dzialalnosc'],
    },
    wykluczenia: [
      { opis: 'Brak ubezpieczenia chorobowego w dniu porodu', sprawdz: 'ubezpieczenie_chorobowe_porod' },
      { opis: 'Osoby bez tytulu do ubezpieczenia -- moga ubiegac sie o kosiniakowe zamiast zasilku macierzynskiego', sprawdz: 'brak_ubezpieczenia' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS Z-3 / ZUS Z-3a / ZUS Z-3b + wniosek do pracodawcy',
      dokumenty: [
        'Akt urodzenia dziecka lub zaswiadczenie lekarskie o przewidywanej dacie porodu',
        'Wniosek o urlop macierzynski i rodzicielski (do pracodawcy)',
        'Zaswiadczenie platnika skladek ZUS Z-3',
      ],
      kroki: [
        'Zloz wniosek o urlop macierzynski u pracodawcy',
        'W ciagu 21 dni po porodzie zloz wniosek o zasilek za caly okres (macierzynski + rodzicielski) -- stawka 81,5%',
        'Jesli nie zlozysz w 21 dni: 100% za urlop macierzynski, potem 70% za rodzicielski',
        'Pracodawca przekazuje ZUS Z-3 do ZUS',
        'ZUS wyplaca zasilek co miesiac',
      ],
      terminRealizacji: '30 dni od zlozenia wniosku',
      pulapki: [
        'Termin 21 dni po porodzie jest kluczowy -- decyduje o stawce 81,5% vs 100%/70%',
        'Ojciec moze przejac czesc urlopu rodzicielskiego (9 tygodni zarezerwowane wylacznie dla drugiego rodzica)',
        'Na dzialalnosci: podstawa zasilku zalezy od oplacanych skladek przez min. 12 miesiecy',
        'Zasilek macierzynski nie moze byc nizszy niz 1000 PLN miesiecznie (dopelnienie do kosiniakowego)',
      ],
      odwolanie: 'Odwolanie do Sadu Pracy w ciagu 30 dni od decyzji ZUS',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/zasilki/zasilek-macierzynski',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'zasilek-opiekunczy', nazwa: 'Zasilek opiekunczy', kategoria: 'ZUS',
    kwota: '80% wynagrodzenia',
    czestotliwosc: 'dziennie (max 60 dni/rok -- dziecko do 14 lat; 14 dni/rok -- inny czlonek rodziny)',
    wymagania: {
      zatrudnienie: ['umowa_o_prace', 'umowa_zlecenie', 'dzialalnosc'],
    },
    wykluczenia: [
      { opis: 'Brak ubezpieczenia chorobowego', sprawdz: 'ubezpieczenie_chorobowe' },
      { opis: 'Inny czlonek rodziny moze zapewnic opieke (nie dotyczy opieki nad chorym dzieckiem do lat 2)', sprawdz: 'inny_opiekun' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS Z-15A (dziecko) / ZUS Z-15B (inny czlonek rodziny)',
      dokumenty: [
        'Zwolnienie lekarskie e-ZLA na chore dziecko/czlonka rodziny',
        'Wniosek ZUS Z-15A lub Z-15B',
        'Zaswiadczenie platnika skladek ZUS Z-3',
      ],
      kroki: [
        'Lekarz wystawia e-ZLA na opieke nad chorym dzieckiem lub czlonkiem rodziny',
        'Wypelnij formularz ZUS Z-15A (dziecko) lub Z-15B (inny czlonek rodziny)',
        'Pracodawca przekazuje dokumenty do ZUS',
        'ZUS wyplaca zasilek w ciagu 30 dni',
      ],
      terminRealizacji: '30 dni od zlozenia kompletnych dokumentow',
      pulapki: [
        'Limit 60 dni na dziecko do 14 lat dotyczy lacznie obojga rodzicow -- nie na kazde dziecko osobno',
        'Na chore dziecko 14-18 lat (niepelnosprawne) -- limit 30 dni',
        'Na innego czlonka rodziny (np. malzonka, rodzica) -- limit 14 dni',
        'Zdrowe dziecko do lat 8: zasilek przyslugujetylko w wyjatkowych sytuacjach (np. zamkniecie zlobka, szkoly)',
      ],
      odwolanie: 'Odwolanie do Sadu Pracy w ciagu 30 dni od decyzji ZUS',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/zasilki/zasilek-opiekunczy',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'swiadczenie-rehabilitacyjne', nazwa: 'Swiadczenie rehabilitacyjne', kategoria: 'ZUS',
    kwota: '90% wynagrodzenia (pierwsze 3 mies.), 75% (pozostaly okres), 100% (ciaza/wypadek przy pracy)',
    czestotliwosc: 'miesiecznie (max 12 miesiecy)',
    wymagania: {
      zatrudnienie: ['umowa_o_prace', 'umowa_zlecenie', 'dzialalnosc'],
    },
    wykluczenia: [
      { opis: 'Nie wyczerpano jeszcze okresu zasilku chorobowego (182/270 dni)', sprawdz: 'wyczerpanie_zasilku_chorobowego' },
      { opis: 'Osoba ma ustalone prawo do emerytury, renty lub zasilku dla bezrobotnych', sprawdz: 'inne_swiadczenia' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS Np-7 (wniosek o swiadczenie rehabilitacyjne)',
      dokumenty: [
        'Wniosek ZUS Np-7',
        'Zaswiadczenie o stanie zdrowia OL-9 (wypelnia lekarz prowadzacy)',
        'Wywiad zawodowy z miejsca pracy N-10',
        'Zaswiadczenie platnika skladek ZUS Z-3',
      ],
      kroki: [
        'Zloz wniosek ZUS Np-7 najlepiej 6 tygodni przed koncem zasilku chorobowego',
        'Lekarz prowadzacy wypelnia zaswiadczenie OL-9',
        'Pracodawca wypelnia wywiad zawodowy N-10',
        'Lekarz orzecznik ZUS bada i wydaje orzeczenie',
        'ZUS wydaje decyzje -- wyplata swiadczenia co miesiac',
      ],
      terminRealizacji: '60 dni od zlozenia wniosku (badanie przez lekarza orzecznika)',
      pulapki: [
        'Zloz wniosek 6 tygodni przed koncem zasilku chorobowego -- zeby nie bylo przerwy w wyplatach',
        'Swiadczenie przysluguje tylko jesli dalsze leczenie rokuje odzyskanie zdolnosci do pracy',
        'Praca zarobkowa w trakcie pobierania = utrata swiadczenia',
        'Odmowa poddania sie badaniu lub rehabilitacji = utrata prawa do swiadczenia',
      ],
      odwolanie: 'Sprzeciw do Komisji Lekarskiej ZUS w ciagu 14 dni od orzeczenia, potem odwolanie do Sadu Pracy',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/zasilki/swiadczenie-rehabilitacyjne',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'zasilek-pogrzebowy', nazwa: 'Zasilek pogrzebowy', kategoria: 'ZUS',
    kwota: '7000 PLN jednorazowo (od 1 stycznia 2026; osobom spoza rodziny -- do wysokosci poniesionych kosztow, max 7000 PLN)',
    kwotaMin: 7000, kwotaMax: 7000,
    czestotliwosc: 'jednorazowo',
    wymagania: {},
    wykluczenia: [
      { opis: 'Wniosek zlozony po uplywie 12 miesiecy od dnia smierci (prawo wygasa)', sprawdz: 'termin_12_miesiecy' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS Z-12 (wniosek o zasilek pogrzebowy)',
      dokumenty: [
        'Akt zgonu',
        'Rachunki/faktury potwierdzajace poniesione koszty pogrzebu',
        'Dokument potwierdzajacy pokrewienstwo (akt malzenstwa, akt urodzenia)',
        'Dowod osobisty wnioskodawcy',
      ],
      kroki: [
        'Zbierz rachunki i faktury za koszty pogrzebu',
        'Wypelnij formularz ZUS Z-12',
        'Dolacz akt zgonu i dokumenty potwierdzajace pokrewienstwo',
        'Zloz wniosek w oddziale ZUS lub przez PUE ZUS',
        'ZUS wyplaci zasilek w ciagu 30 dni',
      ],
      terminRealizacji: '30 dni od zlozenia kompletnego wniosku',
      pulapki: [
        'Od 1 stycznia 2026 kwota wzrosla z 4000 PLN do 7000 PLN',
        'Data smierci decyduje o kwocie -- nie data zlozenia wniosku',
        'Wniosek trzeba zlozyc w ciagu 12 miesiecy od dnia pogrzebu',
        'Jesli pogrzeb oplacil zaklad pogrzebowy na zlecenie -- zasilek przyslugujectej osobie, ktora poniosla koszty',
      ],
      odwolanie: 'Odwolanie do Sadu Pracy w ciagu 30 dni od decyzji ZUS',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/zasilki/zasilek-pogrzebowy',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'renta-socjalna', nazwa: 'Renta socjalna', kategoria: 'ZUS',
    kwota: '1978,49 PLN brutto miesiecznie (od marca 2026, rowna najnizszej rencie)',
    kwotaMin: 1978, kwotaMax: 1978,
    czestotliwosc: 'miesiecznie',
    wymagania: {
      niepelnosprawnosc: ['umiarkowany', 'znaczny'],
    },
    wykluczenia: [
      { opis: 'Niezdolnosc do pracy nie powstala przed ukonczeniem 18 roku zycia, w trakcie nauki (do 25 lat) lub studiow doktoranckich', sprawdz: 'okres_powstania_niezdolnosci' },
      { opis: 'Osoba ma ustalone prawo do emerytury, renty z tytulu niezdolnosci do pracy lub renty strukturalnej', sprawdz: 'inne_swiadczenia_renta' },
      { opis: 'Pobiera swiadczenie o charakterze rentowym z instytucji zagranicznej', sprawdz: 'swiadczenie_zagraniczne' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS ERN (wniosek o rente socjalna)',
      dokumenty: [
        'Wniosek ZUS ERN',
        'Zaswiadczenie o stanie zdrowia OL-9',
        'Dokumentacja medyczna potwierdzajaca calkowita niezdolnosc do pracy',
        'Zaswiadczenie o uczeszczaniu do szkoly/uczelni (jesli niezdolnosc powstala w trakcie nauki)',
        'Dowod osobisty',
      ],
      kroki: [
        'Przygotuj dokumentacje medyczna potwierdzajaca calkowita niezdolnosc do pracy',
        'Lekarz prowadzacy wypelnia zaswiadczenie OL-9',
        'Wypelnij wniosek ZUS ERN',
        'Zloz wniosek w oddziale ZUS lub przez PUE ZUS',
        'Lekarz orzecznik ZUS zbada i wyda orzeczenie',
        'ZUS wyda decyzje w ciagu 30 dni od orzeczenia',
      ],
      terminRealizacji: '30-60 dni od zlozenia wniosku (w tym badanie przez lekarza orzecznika)',
      pulapki: [
        'Renta socjalna wymaga calkowitej niezdolnosci do pracy -- umiarkowany stopien niepelnosprawnosci nie zawsze wystarcza',
        'Niezdolnosc musi powstac przed 18 r.z., w trakcie nauki (do 25 lat) lub na studiach doktoranckich',
        'Mozna dorabiac do 6438,50 PLN brutto miesiecznie (od marca 2026) bez wplywu na swiadczenie',
        'Przekroczenie granicy przychodu powoduje zawieszenie renty',
      ],
      odwolanie: 'Sprzeciw do Komisji Lekarskiej ZUS w ciagu 14 dni, potem odwolanie do Sadu Pracy w ciagu 30 dni',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/renty/renta-socjalna',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'emerytura-pomostowa', nazwa: 'Emerytura pomostowa', kategoria: 'ZUS',
    kwota: 'Obliczana indywidualnie -- minimalna 1978,49 PLN brutto (od marca 2026)',
    kwotaMin: 1978, kwotaMax: 3200,
    czestotliwosc: 'miesiecznie',
    wymagania: {
      wiekMin: 55,
      zatrudnienie: ['umowa_o_prace'],
    },
    wykluczenia: [
      { opis: 'Brak pracy w szczegolnych warunkach lub o szczegolnym charakterze (wykaz w zalaczniku do ustawy)', sprawdz: 'praca_szczegolne_warunki' },
      { opis: 'Brak wymaganego stazu ubezpieczeniowego (20 lat kobiety, 25 lat mezczyzni)', sprawdz: 'staz_ubezpieczeniowy' },
      { opis: 'Nieosiagniecie wieku: 55 lat kobiety, 60 lat mezczyzni', sprawdz: 'wiek_pomostowy' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS EPOM (wniosek o emeryture pomostowa)',
      dokumenty: [
        'Wniosek ZUS EPOM',
        'Swiadectwa pracy potwierdzajace prace w szczegolnych warunkach',
        'Zaswiadczenie pracodawcy o pracy w szczegolnych warunkach/charakterze',
        'Dokumenty potwierdzajace okresy skladkowe i nieskladkowe',
        'Dowod osobisty',
      ],
      kroki: [
        'Sprawdz czy Twoj zawod figuruje w wykazie prac w szczegolnych warunkach (zalacznik 1 i 2 ustawy o emeryturach pomostowych)',
        'Zbierz swiadectwa pracy i zaswiadczenia od pracodawcow',
        'Wypelnij wniosek ZUS EPOM',
        'Zloz wniosek w oddziale ZUS lub przez PUE ZUS',
        'ZUS zweryfikuje staz i wyda decyzje',
      ],
      terminRealizacji: '30 dni od zlozenia kompletnego wniosku',
      pulapki: [
        'Od 2024 r. zniesiono wymog pracy w szczegolnych warunkach przed 31.12.1998 -- teraz dostepna takze dla mlodszych pracownikow',
        'Nie musisz rozwiazywac stosunku pracy przed zlozeniem wniosku, ale musisz to zrobic przed przyznaniem emerytury pomostowej',
        'Emerytura pomostowa jest bezterminowa -- przyslugujedoosiaagnieccia powszechnego wieku emerytalnego',
        'Mozna dorabiac, ale po przekroczeniu progu ZUS zmniejszy lub zawiesi swiadczenie',
      ],
      odwolanie: 'Odwolanie do Sadu Pracy w ciagu 30 dni od decyzji ZUS',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/emerytury/emerytury-pomostowe',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'swiadczenie-przedemerytalne', nazwa: 'Swiadczenie przedemerytalne', kategoria: 'ZUS',
    kwota: '1993,76 PLN brutto miesiecznie (od marca 2026)',
    kwotaMin: 1994, kwotaMax: 1994,
    czestotliwosc: 'miesiecznie',
    wymagania: {
      wiekMin: 55,
      bezrobotnyZarejestrowany: true,
    },
    wykluczenia: [
      { opis: 'Brak 180-dniowego okresu pobierania zasilku dla bezrobotnych', sprawdz: 'zasilek_bezrobotnych_180' },
      { opis: 'Rozwiazanie umowy z winy pracownika (dyscyplinarka)', sprawdz: 'przyczyna_rozwiazania' },
      { opis: 'Niespelnienie warunkow stazowych (20/25 lat) i wiekowych (56/61 lat) -- rozne progi w zaleznosci od przyczyny utraty pracy', sprawdz: 'warunki_staz_wiek' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS ESP (wniosek o swiadczenie przedemerytalne)',
      dokumenty: [
        'Wniosek ZUS ESP',
        'Zaswiadczenie z PUP o 180-dniowym okresie pobierania zasilku dla bezrobotnych',
        'Swiadectwo pracy z ostatniego zatrudnienia',
        'Dokumenty potwierdzajace przyczyne rozwiazania umowy (np. wypowiedzenie z przyczyn pracodawcy, likwidacja)',
        'Dowod osobisty',
      ],
      kroki: [
        'Zarejestruj sie w PUP jako bezrobotny i pobieraj zasilek przez 180 dni',
        'Po 180 dniach PUP wydaje zaswiadczenie',
        'W ciagu 30 dni od wydania zaswiadczenia zloz wniosek ZUS ESP',
        'Dolacz swiadectwa pracy i dokumenty potwierdzajace przyczyne utraty pracy',
        'ZUS wyda decyzje w ciagu 30 dni',
      ],
      terminRealizacji: '30 dni od zlozenia kompletnego wniosku',
      pulapki: [
        'Termin 30 dni od zaswiadczenia PUP jest bezwzgledny -- po nim tracisz prawo',
        'Umowa musi byc rozwiazana z przyczyn lezacych po stronie pracodawcy (likwidacja, upadlosc, zwolnienia grupowe)',
        'Mozna dorabiac do 2225,90 PLN brutto miesiecznie bez wplywu na swiadczenie (od marca 2026)',
        'Przekroczenie 6232,50 PLN brutto miesiecznie = zawieszenie swiadczenia',
      ],
      odwolanie: 'Odwolanie do Sadu Pracy w ciagu 30 dni od decyzji ZUS',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/swiadczenia-przedemerytalne',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: 'mama-4-plus', nazwa: 'Rodzicielskie swiadczenie uzupelniajace (Mama 4+)', kategoria: 'ZUS',
    kwota: 'Do 1978,49 PLN brutto miesiecznie (od marca 2026, uzupelnienie do minimalnej emerytury)',
    kwotaMin: 0, kwotaMax: 1978,
    czestotliwosc: 'miesiecznie',
    wymagania: {
      wiekMin: 60,
      plec: 'dowolna',
      dzieci: { min: 4 },
    },
    wykluczenia: [
      { opis: 'Wychowanie mniej niz czworga dzieci', sprawdz: 'liczba_dzieci_4' },
      { opis: 'Pozbawienie wladzy rodzicielskiej lub ograniczenie wladzy przez umieszczenie dziecka w pieczy zastepczej', sprawdz: 'wladza_rodzicielska' },
      { opis: 'Dlugotrwale zaprzestanie wychowania dzieci', sprawdz: 'zaprzestanie_wychowania' },
      { opis: 'Tymczasowe aresztowanie lub pozbawienie wolnosci', sprawdz: 'pozbawienie_wolnosci' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS ERSU (wniosek o rodzicielskie swiadczenie uzupelniajace)',
      dokumenty: [
        'Wniosek ZUS ERSU',
        'Akty urodzenia dzieci',
        'Dowod osobisty',
        'Oswiadczenie o sytuacji osobistej, rodzinnej, majatkowej i materialnej',
        'Informacja o numerach PESEL dzieci',
        'Dokumenty potwierdzajace okresy zatrudnienia (jesli byly)',
      ],
      kroki: [
        'Upewnij sie ze spelniasz warunki wiekowe: 60 lat (kobiety) lub 65 lat (mezczyzni)',
        'Wypelnij wniosek ZUS ERSU',
        'Dolacz akty urodzenia co najmniej czworga dzieci',
        'Zloz wniosek w oddziale ZUS lub przez PUE ZUS',
        'Prezes ZUS wyda decyzje po analizie sytuacji',
      ],
      terminRealizacji: '30 dni od zlozenia wniosku (decyzja Prezesa ZUS)',
      pulapki: [
        'Swiadczenie jest uznaniowe -- Prezes ZUS moze odmowic',
        'Dla kobiet wiek minimalny to 60 lat, dla mezczyzn 65 lat',
        'Jesli masz juz emeryture lub rente nizsza niz minimalna -- swiadczenie uzupelnia do kwoty minimalnej',
        'Jesli nie masz zadnej emerytury -- mozesz dostac pelna kwote 1978,49 PLN brutto',
        'Mezczyzni tez moga sie ubiegac (mimo nazwy "Mama 4+")',
      ],
      odwolanie: 'Wniosek o ponowne rozpatrzenie sprawy do Prezesa ZUS, potem skarga do WSA',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/rodzicielskie-swiadczenie-uzupelniajace',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: '13-emerytura', nazwa: '13. emerytura (trzynastka)', kategoria: 'ZUS',
    kwota: '1978,49 PLN brutto jednorazowo (kwiecien 2026, rowna minimalnej emeryturze)',
    kwotaMin: 1978, kwotaMax: 1978,
    czestotliwosc: 'rocznie (wyplata w kwietniu)',
    wymagania: {
      emeryt: true,
    },
    wykluczenia: [
      { opis: 'Prawo do emerytury lub renty zawieszone na dzien 31 marca danego roku', sprawdz: 'zawieszenie_emerytury_marzec' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      dokumenty: ['Brak -- swiadczenie wyplacane automatycznie (nie trzeba skladac wniosku)'],
      kroki: [
        'Swiadczenie jest wyplacane z urzedu -- nie trzeba skladac wniosku',
        'ZUS wyplaca trzynastke razem z emerytura lub renta w kwietniu',
        'Sprawdz czy Twoje swiadczenie nie jest zawieszone na dzien 31 marca',
      ],
      terminRealizacji: 'Automatyczna wyplata w kwietniu kazdego roku',
      pulapki: [
        'Brak progu dochodowego -- przysluguje wszystkim emerytom i rencistom',
        'Swiadczenie musi byc aktywne (nie zawieszone) na 31 marca',
        'Przysluguje rowniez osobom pobierajacym rente socjalna, swiadczenie przedemerytalne, rente rodzinna',
        'Kwota odpowiada minimalnej emeryturze po marcowej waloryzacji',
      ],
      odwolanie: 'Odwolanie do Sadu Pracy w ciagu 30 dni od decyzji (jesli ZUS odmowi)',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/emerytury/dodatkowe-roczne-swiadczenie-pieniezne',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
  {
    id: '14-emerytura', nazwa: '14. emerytura (czternastka)', kategoria: 'ZUS',
    kwota: 'Do 1978,49 PLN brutto jednorazowo (pelna kwota przy emeryturze do 2900 PLN brutto; powyzej -- pomniejszana o nadwyzke)',
    kwotaMin: 50, kwotaMax: 1978,
    czestotliwosc: 'rocznie (wyplata we wrzesniu)',
    wymagania: {
      emeryt: true,
    },
    wykluczenia: [
      { opis: 'Emerytura/renta brutto przekracza 4828,49 PLN (swiadczenie nie przysluguje)', sprawdz: 'prog_14_emerytura' },
      { opis: 'Prawo do emerytury/renty zawieszone w dniu wyplaty', sprawdz: 'zawieszenie_emerytury_wrzesien' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      dokumenty: ['Brak -- swiadczenie wyplacane automatycznie (nie trzeba skladac wniosku)'],
      kroki: [
        'Swiadczenie jest wyplacane z urzedu -- nie trzeba skladac wniosku',
        'ZUS wyplaca czternastke razem z emerytura/renta we wrzesniu',
        'Pelna kwota przyslugujeprzy emeryturze do 2900 PLN brutto',
        'Powyzej 2900 PLN -- stosowana zasada "zlotowka za zlotowke" (kazdy zloty powyzej progu zmniejsza czternastke)',
      ],
      terminRealizacji: 'Automatyczna wyplata we wrzesniu kazdego roku',
      pulapki: [
        'Prog dochodowy 2900 PLN brutto -- powyzej tej kwoty czternastka jest pomniejszana',
        'Przy emeryturze powyzej 4828,49 PLN brutto czternastka nie przysluguje wcale',
        'Minimalna wyplata to 50 PLN brutto -- ponizej ZUS nie wyplaca',
        'W odroznieniu od trzynastki, czternastka MA prog dochodowy',
        'Czternastka przysluguje rowniez rencistom, osobom na swiadczeniu przedemerytalnym',
      ],
      odwolanie: 'Odwolanie do Sadu Pracy w ciagu 30 dni od decyzji (jesli ZUS odmowi)',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/emerytury/kolejne-dodatkowe-roczne-swiadczenie-pieniezne',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-10', dataWaznosci: '2026-12-31',
  },
];
