import { Benefit } from '../types';

export const ZUS: Benefit[] = [
  {
    id: 'zasilek-chorobowy', nazwa: 'Zasiłek chorobowy (L4)',
    opis: 'Zasiłek chorobowy to świadczenie wypłacane osobom niezdolnym do pracy z powodu choroby, które posiadają ubezpieczenie chorobowe (obowiązkowe przy umowie o pracę, dobrowolne przy zleceniu i działalności gospodarczej). Wynosi 80% podstawy wymiaru wynagrodzenia, a 100% w przypadku ciąży, wypadku przy pracy, wypadku w drodze do/z pracy lub dla dawców narządów. Uwaga: pierwsze 33 dni choroby w roku kalendarzowym (14 dni dla osób powyżej 50 roku życia) to wynagrodzenie chorobowe płacone przez pracodawcę, nie zasiłek ZUS. Zasiłek chorobowy z ZUS zaczyna się dopiero od 34. dnia (15. dnia dla 50+). Maksymalny okres pobierania to 182 dni, a w przypadku ciąży lub gruźlicy: 270 dni. Obowiązuje okres wyczekiwania: 30 dni ciągłego ubezpieczenia dla pracowników lub 90 dni dla ubezpieczenia dobrowolnego (zlecenie, działalność). Lekarz wystawia e-ZLA elektronicznie, które automatycznie trafia do ZUS i pracodawcy. Wykonywanie pracy zarobkowej podczas L4 może skutkować utratą zasiłku i obowiązkiem zwrotu. ZUS przeprowadza kontrole. Na działalności gospodarczej trzeba samodzielnie złożyć ZUS Z-3b przez PUE ZUS.',
    kategoria: 'ZUS',
    kwota: '80% wynagrodzenia (100% w ciąży, wypadek przy pracy lub badania dawców)',
    czestotliwosc: 'dziennie (max 182 dni, 270 dni w ciąży/gruźlica)',
    wymagania: {
      zatrudnienie: ['umowa_o_prace', 'umowa_zlecenie', 'dzialalnosc'],
    },
    wykluczenia: [
      { opis: 'Brak ubezpieczenia chorobowego (np. umowa o dzieło)', sprawdz: 'ubezpieczenie_chorobowe' },
      { opis: 'Niezdolność do pracy powstała w pierwszych 30 dniach ubezpieczenia (pracownik) lub 90 dniach (dobrowolne)', sprawdz: 'okres_wyczekiwania' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS Z-3 (pracownik) / ZUS Z-3a (zleceniobiorca) / ZUS Z-3b (działalność)',
      dokumenty: [
        'Zwolnienie lekarskie e-ZLA (wystawiane elektronicznie przez lekarza)',
        'Zaświadczenie płatnika składek ZUS Z-3/Z-3a/Z-3b',
        'Dowód osobisty',
      ],
      kroki: [
        'Lekarz wystawia e-ZLA, trafia automatycznie do ZUS i pracodawcy',
        'Pracodawca wypełnia ZUS Z-3 i przekazuje do ZUS (jeśli zasiłek wypłaca ZUS)',
        'Pierwsze 33 dni choroby w roku (14 dni dla osób 50+) płaci pracodawca jako wynagrodzenie chorobowe',
        'Od 34. dnia (15. dnia dla 50+) zasiłek chorobowy wypłaca ZUS',
        'Osoby prowadzące działalność składają wniosek ZUS Z-3b na PUE ZUS',
      ],
      terminRealizacji: '30 dni od złożenia kompletnej dokumentacji',
      pulapki: [
        'Pierwsze 33 dni to wynagrodzenie chorobowe od pracodawcy, nie zasiłek ZUS',
        'Okres wyczekiwania: 30 dni ciągłego ubezpieczenia (pracownik) lub 90 dni (dobrowolne)',
        'Maksymalnie 182 dni zasiłku (270 dni przy ciąży lub gruźlicy)',
        'Kontrola ZUS może skutkować utratą zasiłku. Nie wykonuj pracy zarobkowej na L4',
      ],
      odwolanie: 'Sprzeciw do Komisji Lekarskiej ZUS w ciągu 14 dni, potem odwołanie do Sądu Pracy',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/zasilki/zasilek-chorobowy',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'zasilek-macierzynski', nazwa: 'Zasiłek macierzyński',
    opis: 'Zasiłek macierzyński przysługuje osobom objętym ubezpieczeniem chorobowym w dniu porodu, przyjęcia dziecka na wychowanie lub przysposobienia. Obejmuje okres urlopu macierzyńskiego (20 tygodni przy jednym dziecku, do 37 tygodni przy pięcioraczku i więcej) oraz urlopu rodzicielskiego (do 32-34 tygodni). Kluczowy termin: jeśli w ciągu 21 dni po porodzie złożysz wniosek o zasiłek za cały okres (macierzyński + rodzicielski), stawka wyniesie 81,5% wynagrodzenia przez cały czas. Jeśli nie zmieścisz się w 21 dniach, za urlop macierzyński dostaniesz 100%, ale za rodzicielski tylko 70%. Ojciec może przejąć część urlopu rodzicielskiego, przy czym 9 tygodni jest zarezerwowanych wyłącznie dla drugiego rodzica (nie można ich przenieść). Osoby prowadzące działalność gospodarczą: podstawa zasiłku zależy od opłacanych składek przez minimum 12 miesięcy, jeśli opłacałeś minimalne składki, zasiłek będzie niski. Zasiłek macierzyński nie może być niższy niż 1000 PLN miesięcznie (w razie potrzeby ZUS dopełnia do kwoty kosiniakowego). Osoby bez ubezpieczenia chorobowego (np. umowa o dzieło, brak pracy) nie kwalifikują się na zasiłek macierzyński, ale mogą ubiegać się o kosiniakowe (1000 PLN/mies.).',
    kategoria: 'ZUS',
    kwota: '81,5% wynagrodzenia (wniosek do 21 dni po porodzie) lub 100%/70% (bez wcześniejszego wniosku)',
    czestotliwosc: 'miesięcznie (20-37 tygodni urlop macierzyński + do 32-34 tygodni urlop rodzicielski)',
    wymagania: {
      ciaza: true,
      zatrudnienie: ['umowa_o_prace', 'umowa_zlecenie', 'dzialalnosc'],
    },
    wykluczenia: [
      { opis: 'Brak ubezpieczenia chorobowego w dniu porodu', sprawdz: 'ubezpieczenie_chorobowe_porod' },
      { opis: 'Osoby bez tytułu do ubezpieczenia mogą ubiegać się o kosiniakowe zamiast zasiłku macierzyńskiego', sprawdz: 'brak_ubezpieczenia' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS Z-3 / ZUS Z-3a / ZUS Z-3b + wniosek do pracodawcy',
      dokumenty: [
        'Akt urodzenia dziecka lub zaświadczenie lekarskie o przewidywanej dacie porodu',
        'Wniosek o urlop macierzyński i rodzicielski (do pracodawcy)',
        'Zaświadczenie płatnika składek ZUS Z-3',
      ],
      kroki: [
        'Złóż wniosek o urlop macierzyński u pracodawcy',
        'W ciągu 21 dni po porodzie złóż wniosek o zasiłek za cały okres (macierzyński + rodzicielski), stawka 81,5%',
        'Jeśli nie złożysz w 21 dni: 100% za urlop macierzyński, potem 70% za rodzicielski',
        'Pracodawca przekazuje ZUS Z-3 do ZUS',
        'ZUS wypłaca zasiłek co miesiąc',
      ],
      terminRealizacji: '30 dni od złożenia wniosku',
      pulapki: [
        'Termin 21 dni po porodzie jest kluczowy, decyduje o stawce 81,5% vs 100%/70%',
        'Ojciec może przejąć część urlopu rodzicielskiego (9 tygodni zarezerwowane wyłącznie dla drugiego rodzica)',
        'Na działalności: podstawa zasiłku zależy od opłacanych składek przez min. 12 miesięcy',
        'Zasiłek macierzyński nie może być niższy niż 1000 PLN miesięcznie (dopełnienie do kosiniakowego)',
      ],
      odwolanie: 'Odwołanie do Sądu Pracy w ciągu 30 dni od decyzji ZUS',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/zasilki/zasilek-macierzynski',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'zasilek-opiekunczy', nazwa: 'Zasiłek opiekuńczy',
    opis: 'Zasiłek opiekuńczy to świadczenie w wysokości 80% wynagrodzenia za czas opieki nad chorym dzieckiem lub innym członkiem rodziny. Przysługuje osobom objętym ubezpieczeniem chorobowym. Limity roczne: 60 dni na chore dziecko do 14 lat, 30 dni na niepełnosprawne dziecko w wieku 14-18 lat, 14 dni na innego członka rodziny (małżonka, rodzica). Uwaga: limit 60 dni dotyczy łącznie obojga rodziców, nie na każde dziecko osobno. Na zdrowe dziecko do 8 lat zasiłek przysługuje tylko w wyjątkowych sytuacjach: niespodziewane zamknięcie żłobka, przedszkola lub szkoły, choroba lub poród małżonka stale opiekującego się dzieckiem. Warunek: inny członek rodziny zamieszkujący w tym samym gospodarstwie domowym nie może zapewnić opieki (ten warunek nie dotyczy opieki nad chorym dzieckiem do lat 2). Nie obowiązuje okres wyczekiwania, prawo do zasiłku przysługuje od pierwszego dnia ubezpieczenia. Lekarz wystawia e-ZLA, a ubezpieczony wypełnia formularz ZUS Z-15A (opieka nad dzieckiem) lub ZUS Z-15B (opieka nad innym członkiem rodziny).',
    kategoria: 'ZUS',
    kwota: '80% wynagrodzenia',
    czestotliwosc: 'dziennie (max 60 dni/rok, dziecko do 14 lat; 14 dni/rok, inny członek rodziny)',
    wymagania: {
      zatrudnienie: ['umowa_o_prace', 'umowa_zlecenie', 'dzialalnosc'],
    },
    wykluczenia: [
      { opis: 'Brak ubezpieczenia chorobowego', sprawdz: 'ubezpieczenie_chorobowe' },
      { opis: 'Inny członek rodziny może zapewnić opiekę (nie dotyczy opieki nad chorym dzieckiem do lat 2)', sprawdz: 'inny_opiekun' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS Z-15A (dziecko) / ZUS Z-15B (inny członek rodziny)',
      dokumenty: [
        'Zwolnienie lekarskie e-ZLA na chore dziecko/członka rodziny',
        'Wniosek ZUS Z-15A lub Z-15B',
        'Zaświadczenie płatnika składek ZUS Z-3',
      ],
      kroki: [
        'Lekarz wystawia e-ZLA na opiekę nad chorym dzieckiem lub członkiem rodziny',
        'Wypełnij formularz ZUS Z-15A (dziecko) lub Z-15B (inny członek rodziny)',
        'Pracodawca przekazuje dokumenty do ZUS',
        'ZUS wypłaca zasiłek w ciągu 30 dni',
      ],
      terminRealizacji: '30 dni od złożenia kompletnych dokumentów',
      pulapki: [
        'Limit 60 dni na dziecko do 14 lat dotyczy łącznie obojga rodziców, nie na każde dziecko osobno',
        'Na chore dziecko 14-18 lat (niepełnosprawne), limit 30 dni',
        'Na innego członka rodziny (np. małżonka, rodzica), limit 14 dni',
        'Zdrowe dziecko do lat 8: zasiłek przysługuje tylko w wyjątkowych sytuacjach (np. zamknięcie żłobka, szkoły)',
      ],
      odwolanie: 'Odwołanie do Sądu Pracy w ciągu 30 dni od decyzji ZUS',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/zasilki/zasilek-opiekunczy',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'swiadczenie-rehabilitacyjne', nazwa: 'Świadczenie rehabilitacyjne',
    opis: 'Świadczenie rehabilitacyjne przysługuje osobom, które wyczerpały okres zasiłku chorobowego (182 lub 270 dni) i nadal są niezdolne do pracy, ale dalsze leczenie lub rehabilitacja rokuje odzyskanie zdolności do pracy. Wypłacane przez maksymalnie 12 miesięcy: 90% wynagrodzenia przez pierwsze 3 miesiące, 75% przez pozostały okres, 100% w przypadku ciąży lub wypadku przy pracy. Wniosek (ZUS Np-7) najlepiej złożyć 6 tygodni przed końcem zasiłku chorobowego, żeby uniknąć przerwy w wypłatach. Lekarz orzecznik ZUS bada ubezpieczonego i wydaje orzeczenie. Świadczenie nie przysługuje osobom, które mają ustalone prawo do emerytury, renty z tytułu niezdolności do pracy lub zasiłku dla bezrobotnych. Praca zarobkowa w trakcie pobierania świadczenia rehabilitacyjnego oznacza jego utratę. Odmowa poddania się badaniu lekarskiemu lub rehabilitacji również skutkuje utratą prawa do świadczenia. Od orzeczenia lekarza orzecznika ZUS przysługuje sprzeciw do Komisji Lekarskiej ZUS w ciągu 14 dni, a od decyzji ZUS: odwołanie do Sądu Pracy.',
    kategoria: 'ZUS',
    kwota: '90% wynagrodzenia (pierwsze 3 mies.), 75% (pozostały okres), 100% (ciąża/wypadek przy pracy)',
    czestotliwosc: 'miesięcznie (max 12 miesięcy)',
    wymagania: {
      zatrudnienie: ['umowa_o_prace', 'umowa_zlecenie', 'dzialalnosc'],
    },
    wykluczenia: [
      { opis: 'Nie wyczerpano jeszcze okresu zasiłku chorobowego (182/270 dni)', sprawdz: 'wyczerpanie_zasilku_chorobowego' },
      { opis: 'Osoba ma ustalone prawo do emerytury, renty lub zasiłku dla bezrobotnych', sprawdz: 'inne_swiadczenia' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS Np-7 (wniosek o świadczenie rehabilitacyjne)',
      dokumenty: [
        'Wniosek ZUS Np-7',
        'Zaświadczenie o stanie zdrowia OL-9 (wypełnia lekarz prowadzący)',
        'Wywiad zawodowy z miejsca pracy N-10',
        'Zaświadczenie płatnika składek ZUS Z-3',
      ],
      kroki: [
        'Złóż wniosek ZUS Np-7 najlepiej 6 tygodni przed końcem zasiłku chorobowego',
        'Lekarz prowadzący wypełnia zaświadczenie OL-9',
        'Pracodawca wypełnia wywiad zawodowy N-10',
        'Lekarz orzecznik ZUS bada i wydaje orzeczenie',
        'ZUS wydaje decyzję, wypłata świadczenia co miesiąc',
      ],
      terminRealizacji: '60 dni od złożenia wniosku (badanie przez lekarza orzecznika)',
      pulapki: [
        'Złóż wniosek 6 tygodni przed końcem zasiłku chorobowego, żeby nie było przerwy w wypłatach',
        'Świadczenie przysługuje tylko jeśli dalsze leczenie rokuje odzyskanie zdolności do pracy',
        'Praca zarobkowa w trakcie pobierania = utrata świadczenia',
        'Odmowa poddania się badaniu lub rehabilitacji = utrata prawa do świadczenia',
      ],
      odwolanie: 'Sprzeciw do Komisji Lekarskiej ZUS w ciągu 14 dni od orzeczenia, potem odwołanie do Sądu Pracy',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/zasilki/swiadczenie-rehabilitacyjne',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'zasilek-pogrzebowy', nazwa: 'Zasiłek pogrzebowy',
    opis: 'Zasiłek pogrzebowy to jednorazowe świadczenie w kwocie 7000 PLN (od 1 stycznia 2026, wcześniej 4000 PLN) na pokrycie kosztów pogrzebu. Przysługuje osobie, która poniosła koszty pogrzebu ubezpieczonego, emeryta, rencisty lub członka ich rodziny. Dla członka rodziny zmarłego (małżonek, rodzic, dziecko, wnuk, rodzeństwo) kwota wynosi 7000 PLN ryczałtem, niezależnie od faktycznych kosztów. Dla osób spoza rodziny lub instytucji,zwrot udokumentowanych kosztów, ale nie więcej niż 7000 PLN. O kwocie decyduje data śmierci, nie data złożenia wniosku. Wniosek (formularz ZUS Z-12) trzeba złożyć w ciągu 12 miesięcy od dnia pogrzebu,po tym terminie prawo wygasa bezpowrotnie. Do wniosku dołącza się akt zgonu, rachunki/faktury za pogrzeb oraz dokument potwierdzający pokrewieństwo. Jeśli pogrzeb organizował zakład pogrzebowy na zlecenie rodziny, zasiłek przysługuje osobie, która faktycznie poniosła koszty, nie zakładowi pogrzebowemu. Wniosek można złożyć w oddziale ZUS lub przez PUE ZUS.',
    kategoria: 'ZUS',
    kwota: '7000 PLN jednorazowo (od 1 stycznia 2026; osobom spoza rodziny, do wysokości poniesionych kosztów, max 7000 PLN)',
    kwotaMin: 7000, kwotaMax: 7000,
    czestotliwosc: 'jednorazowo',
    wymagania: { wiekMin: 18 },
    wykluczenia: [
      { opis: 'Świadczenie sytuacyjne - przysługuje tylko gdy poniosłeś koszty pogrzebu osoby ubezpieczonej w ZUS lub członka jej rodziny', sprawdz: 'zdarzenie_smierci' },
      { opis: 'Wniosek złożony po upływie 12 miesięcy od dnia pogrzebu (prawo wygasa)', sprawdz: 'termin_12_miesiecy' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS Z-12 (wniosek o zasiłek pogrzebowy)',
      dokumenty: [
        'Akt zgonu',
        'Rachunki/faktury potwierdzające poniesione koszty pogrzebu',
        'Dokument potwierdzający pokrewieństwo (akt małżeństwa, akt urodzenia)',
        'Dowód osobisty wnioskodawcy',
      ],
      kroki: [
        'Zbierz rachunki i faktury za koszty pogrzebu',
        'Wypełnij formularz ZUS Z-12',
        'Dołącz akt zgonu i dokumenty potwierdzające pokrewieństwo',
        'Złóż wniosek w oddziale ZUS lub przez PUE ZUS',
        'ZUS wypłaci zasiłek w ciągu 30 dni',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'Od 1 stycznia 2026 kwota wzrosła z 4000 PLN do 7000 PLN',
        'Data śmierci decyduje o kwocie, nie data złożenia wniosku',
        'Wniosek trzeba złożyć w ciągu 12 miesięcy od dnia pogrzebu',
        'Jeśli pogrzeb opłacił zakład pogrzebowy na zlecenie, zasiłek przysługuje tej osobie, która poniosła koszty',
      ],
      odwolanie: 'Odwołanie do Sądu Pracy w ciągu 30 dni od decyzji ZUS',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/zasilki/zasilek-pogrzebowy',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'renta-socjalna', nazwa: 'Renta socjalna',
    opis: 'Renta socjalna to comiesięczne świadczenie w wysokości 1978,49 PLN brutto (od marca 2026, równa najniższej rencie) dla osób całkowicie niezdolnych do pracy, u których niezdolność powstała przed ukończeniem 18 roku życia, w trakcie nauki w szkole lub na uczelni (do 25 lat) albo w trakcie studiów doktoranckich. Samo posiadanie orzeczenia o umiarkowanym lub znacznym stopniu niepełnosprawności nie wystarczy,lekarz orzecznik ZUS musi stwierdzić całkowitą niezdolność do pracy. Renta socjalna nie przysługuje osobom, które mają ustalone prawo do emerytury, renty z tytułu niezdolności do pracy, renty strukturalnej lub pobierają świadczenie rentowe z zagranicy. Można dorabiać do 6438,50 PLN brutto miesięcznie (70% przeciętnego wynagrodzenia, od marca 2026) bez wpływu na wysokość renty. Przekroczenie tego progu powoduje zawieszenie renty. Wniosek (ZUS ERN) składa się w oddziale ZUS lub przez PUE ZUS, z dokumentacją medyczną i zaświadczeniem OL-9 od lekarza prowadzącego. Od orzeczenia lekarza orzecznika przysługuje sprzeciw do Komisji Lekarskiej ZUS w ciągu 14 dni.',
    kategoria: 'ZUS',
    kwota: '1978,49 PLN brutto miesięcznie (od marca 2026, równa najniższej rencie)',
    kwotaMin: 1978, kwotaMax: 1978,
    czestotliwosc: 'miesięcznie',
    wymagania: {
      niepelnosprawnosc: ['umiarkowany', 'znaczny'],
    },
    wykluczenia: [
      { opis: 'Niezdolność do pracy nie powstała przed ukończeniem 18 roku życia, w trakcie nauki (do 25 lat) lub studiów doktoranckich', sprawdz: 'okres_powstania_niezdolnosci' },
      { opis: 'Osoba ma ustalone prawo do emerytury, renty z tytułu niezdolności do pracy lub renty strukturalnej', sprawdz: 'inne_swiadczenia_renta' },
      { opis: 'Pobiera świadczenie o charakterze rentowym z instytucji zagranicznej', sprawdz: 'swiadczenie_zagraniczne' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS ERN (wniosek o rentę socjalną)',
      dokumenty: [
        'Wniosek ZUS ERN',
        'Zaświadczenie o stanie zdrowia OL-9',
        'Dokumentacja medyczna potwierdzająca całkowitą niezdolność do pracy',
        'Zaświadczenie o uczęszczaniu do szkoły/uczelni (jeśli niezdolność powstała w trakcie nauki)',
        'Dowód osobisty',
      ],
      kroki: [
        'Przygotuj dokumentację medyczną potwierdzającą całkowitą niezdolność do pracy',
        'Lekarz prowadzący wypełnia zaświadczenie OL-9',
        'Wypełnij wniosek ZUS ERN',
        'Złóż wniosek w oddziale ZUS lub przez PUE ZUS',
        'Lekarz orzecznik ZUS zbada i wyda orzeczenie',
        'ZUS wyda decyzję w ciągu 30 dni od orzeczenia',
      ],
      terminRealizacji: '30-60 dni od złożenia wniosku (w tym badanie przez lekarza orzecznika)',
      pulapki: [
        'Renta socjalna wymaga całkowitej niezdolności do pracy, umiarkowany stopień niepełnosprawności nie zawsze wystarcza',
        'Niezdolność musi powstać przed 18 r.ż., w trakcie nauki (do 25 lat) lub na studiach doktoranckich',
        'Można dorabiać do 6438,50 PLN brutto miesięcznie (od marca 2026) bez wpływu na świadczenie',
        'Przekroczenie granicy przychodu powoduje zawieszenie renty',
      ],
      odwolanie: 'Sprzeciw do Komisji Lekarskiej ZUS w ciągu 14 dni, potem odwołanie do Sądu Pracy w ciągu 30 dni',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/renty/renta-socjalna',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'emerytura-pomostowa', nazwa: 'Emerytura pomostowa',
    opis: 'Emerytura pomostowa to wcześniejsze świadczenie emerytalne dla osób, które pracowały w szczególnych warunkach lub o szczególnym charakterze (wykaz zawodów w załącznikach 1 i 2 do ustawy o emeryturach pomostowych). Dotyczy m.in. hutników, górników, ratowników, pilotów, kierowców komunikacji publicznej, pracowników w warunkach podwyższonego ciśnienia, narażonych na działanie promieniowania. Minimalna kwota to 1978,49 PLN brutto (od marca 2026), ale rzeczywista wysokość obliczana jest indywidualnie na podstawie zgromadzonych składek. Warunki: wiek co najmniej 55 lat (kobiety) lub 60 lat (mężczyźni), staż ubezpieczeniowy co najmniej 20 lat (kobiety) lub 25 lat (mężczyźni), w tym odpowiedni okres pracy w szczególnych warunkach. Od 2024 roku zniesiono wymóg pracy w szczególnych warunkach przed 31.12.1998, co otworzyło dostęp także dla młodszych pracowników. Nie trzeba rozwiązywać stosunku pracy przed złożeniem wniosku, ale trzeba to zrobić przed przyznaniem emerytury. Emerytura pomostowa jest bezterminowa,przysługuje do osiągnięcia powszechnego wieku emerytalnego (60/65 lat). Można dorabiać, ale po przekroczeniu progu przychodu ZUS zmniejszy lub zawiesi świadczenie.',
    kategoria: 'ZUS',
    kwota: 'Obliczana indywidualnie, minimalna 1978,49 PLN brutto (od marca 2026)',
    kwotaMin: 1978, kwotaMax: 3200,
    czestotliwosc: 'miesięcznie',
    wymagania: {
      wiekMin: 55,
      zatrudnienie: ['umowa_o_prace'],
    },
    wykluczenia: [
      { opis: 'Brak pracy w szczególnych warunkach lub o szczególnym charakterze (wykaz w załączniku do ustawy)', sprawdz: 'praca_szczegolne_warunki' },
      { opis: 'Brak wymaganego stażu ubezpieczeniowego (20 lat kobiety, 25 lat mężczyźni)', sprawdz: 'staz_ubezpieczeniowy' },
      { opis: 'Nieosiągnięcie wieku: 55 lat kobiety, 60 lat mężczyźni', sprawdz: 'wiek_pomostowy' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS EPOM (wniosek o emeryturę pomostową)',
      dokumenty: [
        'Wniosek ZUS EPOM',
        'Świadectwa pracy potwierdzające pracę w szczególnych warunkach',
        'Zaświadczenie pracodawcy o pracy w szczególnych warunkach/charakterze',
        'Dokumenty potwierdzające okresy składkowe i nieskładkowe',
        'Dowód osobisty',
      ],
      kroki: [
        'Sprawdź czy Twój zawód figuruje w wykazie prac w szczególnych warunkach (załącznik 1 i 2 ustawy o emeryturach pomostowych)',
        'Zbierz świadectwa pracy i zaświadczenia od pracodawców',
        'Wypełnij wniosek ZUS EPOM',
        'Złóż wniosek w oddziale ZUS lub przez PUE ZUS',
        'ZUS zweryfikuje staż i wyda decyzję',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'Od 2024 r. zniesiono wymóg pracy w szczególnych warunkach przed 31.12.1998, teraz dostępna także dla młodszych pracowników',
        'Nie musisz rozwiązywać stosunku pracy przed złożeniem wniosku, ale musisz to zrobić przed przyznaniem emerytury pomostowej',
        'Emerytura pomostowa jest bezterminowa, przysługuje do osiągnięcia powszechnego wieku emerytalnego',
        'Można dorabiać, ale po przekroczeniu progu ZUS zmniejszy lub zawiesi świadczenie',
      ],
      odwolanie: 'Odwołanie do Sądu Pracy w ciągu 30 dni od decyzji ZUS',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/emerytury/emerytura-dla-osob-urodzonych-po-31-grudnia-1948/emerytury-wczesniejsze/emerytura-pomostowa',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'swiadczenie-przedemerytalne', nazwa: 'Świadczenie przedemerytalne',
    opis: 'Świadczenie przedemerytalne to comiesięczna wypłata 1993,76 PLN brutto (od marca 2026) dla osób, które straciły pracę z przyczyn leżących po stronie pracodawcy (likwidacja zakładu, upadłość, zwolnienia grupowe) i spełniają warunki wiekowe i stażowe. Kluczowy wymóg: trzeba najpierw zarejestrować się w PUP jako bezrobotny i pobierać zasiłek dla bezrobotnych przez co najmniej 180 dni. Po upływie 180 dni PUP wydaje zaświadczenie, a ubezpieczony ma tylko 30 dni na złożenie wniosku ZUS ESP,po tym terminie prawo przepada bezpowrotnie. Warunki różnią się w zależności od przyczyny utraty pracy, ale ogólnie wymagany jest wiek co najmniej 56 lat (kobiety) lub 61 lat (mężczyźni) i staż ubezpieczeniowy 20 lat (kobiety) lub 25 lat (mężczyźni). Przy likwidacji lub upadłości pracodawcy progi wiekowe mogą być niższe. Umowa musi być rozwiązana z przyczyn pracodawcy,dyscyplinarka lub odejście z własnej woli dyskwalifikuje. Można dorabiać do 2225,90 PLN brutto miesięcznie (od marca 2026) bez wpływu na świadczenie. Przekroczenie 6232,50 PLN brutto miesięcznie powoduje zawieszenie świadczenia.',
    kategoria: 'ZUS',
    kwota: '1993,76 PLN brutto miesięcznie (od marca 2026)',
    kwotaMin: 1994, kwotaMax: 1994,
    czestotliwosc: 'miesięcznie',
    wymagania: {
      wiekMin: 55,
      bezrobotnyZarejestrowany: true,
    },
    wykluczenia: [
      { opis: 'Brak 180-dniowego okresu pobierania zasiłku dla bezrobotnych', sprawdz: 'zasilek_bezrobotnych_180' },
      { opis: 'Rozwiązanie umowy z winy pracownika (dyscyplinarka)', sprawdz: 'przyczyna_rozwiazania' },
      { opis: 'Niespełnienie warunków stażowych (20/25 lat) i wiekowych (56/61 lat), różne progi w zależności od przyczyny utraty pracy', sprawdz: 'warunki_staz_wiek' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS ESP (wniosek o świadczenie przedemerytalne)',
      dokumenty: [
        'Wniosek ZUS ESP',
        'Zaświadczenie z PUP o 180-dniowym okresie pobierania zasiłku dla bezrobotnych',
        'Świadectwo pracy z ostatniego zatrudnienia',
        'Dokumenty potwierdzające przyczynę rozwiązania umowy (np. wypowiedzenie z przyczyn pracodawcy, likwidacja)',
        'Dowód osobisty',
      ],
      kroki: [
        'Zarejestruj się w PUP jako bezrobotny i pobieraj zasiłek przez 180 dni',
        'Po 180 dniach PUP wydaje zaświadczenie',
        'W ciągu 30 dni od wydania zaświadczenia złóż wniosek ZUS ESP',
        'Dołącz świadectwa pracy i dokumenty potwierdzające przyczynę utraty pracy',
        'ZUS wyda decyzję w ciągu 30 dni',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'Termin 30 dni od zaświadczenia PUP jest bezwzględny, po nim tracisz prawo',
        'Umowa musi być rozwiązana z przyczyn leżących po stronie pracodawcy (likwidacja, upadłość, zwolnienia grupowe)',
        'Można dorabiać do 2225,90 PLN brutto miesięcznie bez wpływu na świadczenie (od marca 2026)',
        'Przekroczenie 6232,50 PLN brutto miesięcznie = zawieszenie świadczenia',
      ],
      odwolanie: 'Odwołanie do Sądu Pracy w ciągu 30 dni od decyzji ZUS',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/swiadczenia-przedemerytalne',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'mama-4-plus', nazwa: 'Rodzicielskie świadczenie uzupełniające (Mama 4+)',
    opis: 'Rodzicielskie świadczenie uzupełniające (potocznie "Mama 4+") to comiesięczne świadczenie uzupełniające dochód do poziomu minimalnej emerytury (1978,49 PLN brutto od marca 2026) dla osób, które wychowały co najmniej czworo dzieci i z tego powodu nie wypracowały wystarczającego stażu emerytalnego. Mimo nazwy, świadczenie przysługuje nie tylko matkom, ale także ojcom, którzy wychowywali dzieci. Warunki wiekowe: 60 lat dla kobiet, 65 lat dla mężczyzn. Jeśli ubezpieczony ma już emeryturę lub rentę niższą niż minimalna, świadczenie uzupełnia do kwoty minimalnej. Jeśli nie ma żadnej emerytury, może otrzymać pełną kwotę 1978,49 PLN brutto. Uwaga: świadczenie jest uznaniowe,decyzję podejmuje Prezes ZUS i może odmówić, nawet jeśli warunki formalne są spełnione. Pozbawienie lub ograniczenie władzy rodzicielskiej (umieszczenie dziecka w pieczy zastępczej), długotrwałe zaprzestanie wychowania dzieci, tymczasowe aresztowanie lub pozbawienie wolności dyskwalifikują. Wniosek (ZUS ERSU) składa się z aktami urodzenia co najmniej czworga dzieci i oświadczeniem o sytuacji osobistej. Od decyzji Prezesa ZUS przysługuje wniosek o ponowne rozpatrzenie, a następnie skarga do WSA.',
    kategoria: 'ZUS',
    kwota: 'Do 1978,49 PLN brutto miesięcznie (od marca 2026, uzupełnienie do minimalnej emerytury)',
    kwotaMin: 0, kwotaMax: 1978,
    czestotliwosc: 'miesięcznie',
    wymagania: {
      wiekMin: 60,
      plec: 'dowolna',
      dzieci: { min: 4 },
    },
    wykluczenia: [
      { opis: 'Wychowanie mniej niż czworga dzieci', sprawdz: 'liczba_dzieci_4' },
      { opis: 'Pozbawienie władzy rodzicielskiej lub ograniczenie władzy przez umieszczenie dziecka w pieczy zastępczej', sprawdz: 'wladza_rodzicielska' },
      { opis: 'Długotrwałe zaprzestanie wychowania dzieci', sprawdz: 'zaprzestanie_wychowania' },
      { opis: 'Tymczasowe aresztowanie lub pozbawienie wolności', sprawdz: 'pozbawienie_wolnosci' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS ERSU (wniosek o rodzicielskie świadczenie uzupełniające)',
      dokumenty: [
        'Wniosek ZUS ERSU',
        'Akty urodzenia dzieci',
        'Dowód osobisty',
        'Oświadczenie o sytuacji osobistej, rodzinnej, majątkowej i materialnej',
        'Informacja o numerach PESEL dzieci',
        'Dokumenty potwierdzające okresy zatrudnienia (jeśli były)',
      ],
      kroki: [
        'Upewnij się że spełniasz warunki wiekowe: 60 lat (kobiety) lub 65 lat (mężczyźni)',
        'Wypełnij wniosek ZUS ERSU',
        'Dołącz akty urodzenia co najmniej czworga dzieci',
        'Złóż wniosek w oddziale ZUS lub przez PUE ZUS',
        'Prezes ZUS wyda decyzję po analizie sytuacji',
      ],
      terminRealizacji: '30 dni od złożenia wniosku (decyzja Prezesa ZUS)',
      pulapki: [
        'Świadczenie jest uznaniowe, Prezes ZUS może odmówić',
        'Dla kobiet wiek minimalny to 60 lat, dla mężczyzn 65 lat',
        'Jeśli masz już emeryturę lub rentę niższą niż minimalna, świadczenie uzupełnia do kwoty minimalnej',
        'Jeśli nie masz żadnej emerytury, możesz dostać pełną kwotę 1978,49 PLN brutto',
        'Mężczyźni też mogą się ubiegać (mimo nazwy "Mama 4+")',
      ],
      odwolanie: 'Wniosek o ponowne rozpatrzenie sprawy do Prezesa ZUS, potem skarga do WSA',
    },
    zrodloUrl: 'https://www.gov.pl/web/rodzina/mama-4-plus-rodzicielskie-swiadczenie-uzupelniajace',
    zrodloNazwa: 'gov.pl', dataWeryfikacji: '2026-05-25', dataWaznosci: '2026-12-31',
  },
  {
    id: '13-emerytura', nazwa: '13. emerytura (trzynastka)',
    opis: 'Trzynasta emerytura (trzynastka) to dodatkowe roczne świadczenie pieniężne wypłacane automatycznie w kwietniu każdego roku wszystkim emerytom i rencistom. Kwota odpowiada minimalnej emeryturze po marcowej waloryzacji,w 2026 roku wynosi 1978,49 PLN brutto. Nie trzeba składać żadnego wniosku,ZUS wypłaca trzynastkę z urzędu razem z regularną emeryturą lub rentą. Nie ma progu dochodowego,przysługuje wszystkim, niezależnie od wysokości emerytury. Jedyny warunek: świadczenie nie może być zawieszone na dzień 31 marca danego roku. Jeśli emerytura jest zawieszona (np. z powodu przekroczenia limitu przychodu), trzynastka nie zostanie wypłacona. Przysługuje nie tylko emerytom, ale również osobom pobierającym rentę socjalną, rentę rodzinną, świadczenie przedemerytalne, zasiłek przedemerytalny, nauczycielskie świadczenie kompensacyjne i emeryturę pomostową. Trzynastka jest opodatkowana podatkiem dochodowym i podlega składce zdrowotnej.',
    kategoria: 'ZUS',
    kwota: '1978,49 PLN brutto jednorazowo (kwiecień 2026, równa minimalnej emeryturze)',
    kwotaMin: 1978, kwotaMax: 1978,
    czestotliwosc: 'rocznie (wypłata w kwietniu)',
    wymagania: {
      emeryt: true,
    },
    wykluczenia: [
      { opis: 'Prawo do emerytury lub renty zawieszone na dzień 31 marca danego roku', sprawdz: 'zawieszenie_emerytury_marzec' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      dokumenty: ['Brak, świadczenie wypłacane automatycznie (nie trzeba składać wniosku)'],
      kroki: [
        'Świadczenie jest wypłacane z urzędu, nie trzeba składać wniosku',
        'ZUS wypłaca trzynastkę razem z emeryturą lub rentą w kwietniu',
        'Sprawdź czy Twoje świadczenie nie jest zawieszone na dzień 31 marca',
      ],
      terminRealizacji: 'Automatyczna wypłata w kwietniu każdego roku',
      pulapki: [
        'Brak progu dochodowego, przysługuje wszystkim emerytom i rencistom',
        'Świadczenie musi być aktywne (nie zawieszone) na 31 marca',
        'Przysługuje również osobom pobierającym rentę socjalną, świadczenie przedemerytalne, rentę rodzinną',
        'Kwota odpowiada minimalnej emeryturze po marcowej waloryzacji',
      ],
      odwolanie: 'Odwołanie do Sądu Pracy w ciągu 30 dni od decyzji (jeśli ZUS odmówi)',
    },
    zrodloUrl: 'https://www.zus.pl/-/trzynasta-emerytura-czyli-dodatkowe-roczne-swiadczenie-pieniez-1',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: '14-emerytura', nazwa: '14. emerytura (czternastka)',
    opis: 'Czternasta emerytura (czternastka) to dodatkowe roczne świadczenie wypłacane automatycznie we wrześniu. W odróżnieniu od trzynastki, czternastka ma próg dochodowy. Pełna kwota (1978,49 PLN brutto w 2026) przysługuje emerytom i rencistom, których emerytura brutto nie przekracza 2900 PLN. Powyżej tego progu stosowana jest zasada "złotówka za złotówkę",każdy złoty emerytury powyżej 2900 PLN zmniejsza czternastkę o złotówkę. Przy emeryturze powyżej 4828,49 PLN brutto czternastka nie przysługuje wcale. Minimalna wypłata to 50 PLN brutto,jeśli po zastosowaniu pomniejszenia kwota spadnie poniżej 50 PLN, ZUS nie wypłaca nic. Nie trzeba składać wniosku,ZUS wypłaca świadczenie automatycznie razem z regularną emeryturą/rentą we wrześniu. Świadczenie musi być aktywne (nie zawieszone) w dniu wypłaty. Czternastka przysługuje również rencistom, osobom na rencie socjalnej, świadczeniu przedemerytalnym i rencie rodzinnej. Jest opodatkowana i podlega składce zdrowotnej.',
    kategoria: 'ZUS',
    kwota: 'Do 1978,49 PLN brutto jednorazowo (pełna kwota przy emeryturze do 2900 PLN brutto; powyżej, pomniejszana o nadwyżkę)',
    kwotaMin: 50, kwotaMax: 1978,
    czestotliwosc: 'rocznie (wypłata we wrześniu)',
    wymagania: {
      emeryt: true,
    },
    wykluczenia: [
      { opis: 'Emerytura/renta brutto przekracza 4828,49 PLN (świadczenie nie przysługuje)', sprawdz: 'prog_14_emerytura' },
      { opis: 'Prawo do emerytury/renty zawieszone w dniu wypłaty', sprawdz: 'zawieszenie_emerytury_wrzesien' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      dokumenty: ['Brak, świadczenie wypłacane automatycznie (nie trzeba składać wniosku)'],
      kroki: [
        'Świadczenie jest wypłacane z urzędu, nie trzeba składać wniosku',
        'ZUS wypłaca czternastkę razem z emeryturą/rentą we wrześniu',
        'Pełna kwota przysługuje przy emeryturze do 2900 PLN brutto',
        'Powyżej 2900 PLN, stosowana zasada "złotówka za złotówkę" (każdy złoty powyżej progu zmniejsza czternastkę)',
      ],
      terminRealizacji: 'Automatyczna wypłata we wrześniu każdego roku',
      pulapki: [
        'Próg dochodowy 2900 PLN brutto, powyżej tej kwoty czternastka jest pomniejszana',
        'Przy emeryturze powyżej 4828,49 PLN brutto czternastka nie przysługuje wcale',
        'Minimalna wypłata to 50 PLN brutto, poniżej ZUS nie wypłaca',
        'W odróżnieniu od trzynastki, czternastka MA próg dochodowy',
        'Czternastka przysługuje również rencistom, osobom na świadczeniu przedemerytalnym',
      ],
      odwolanie: 'Odwołanie do Sądu Pracy w ciągu 30 dni od decyzji (jeśli ZUS odmówi)',
    },
    zrodloUrl: 'https://www.zus.pl/-/czternasta-emerytura-bez-wniosku-1',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'renta-wdowia', nazwa: 'Renta wdowia (zbieg świadczeń)',
    opis: 'Renta wdowia to możliwość łączenia własnej emerytury/renty z rentą rodzinną po zmarłym małżonku. Obowiązuje od 1 lipca 2025 r. W 2026 wdowiec/wdowa może pobierać 100% jednego świadczenia + 15% drugiego (od 1 stycznia 2027 r. drugie świadczenie wzrośnie do 25%). Limit łączny: 5935,47 PLN brutto miesięcznie (3-krotność minimalnej emerytury 1978,49 PLN po waloryzacji 5,3% z marca 2026). Powyżej tego limitu drugie świadczenie jest pomniejszane. Warunki łącznie: minimum 60 lat dla kobiet / 65 dla mężczyzn, pozostawanie w małżeństwie do dnia śmierci współmałżonka, nabycie prawa do renty rodzinnej nie wcześniej niż 5 lat przed osiągnięciem wieku emerytalnego, brak ponownego małżeństwa po śmierci współmałżonka. Wniosek ZUS-Rwd składa się w ZUS osobiście, pocztą, przez PUE ZUS albo Empatia. Decyzja w ciągu 30 dni. Świadczenie wypłacane od miesiąca złożenia wniosku (nie ma wyrównania wstecz). Waloryzacja 1 marca każdego roku z urzędu (bez wniosku). Częsty błąd: składanie wniosku tylko o świadczenie wyższe – nie ma to sensu, ZUS sam wybiera korzystniejszy wariant. Korzysta ok. 1,6 mln osób.',
    kategoria: 'ZUS',
    kwota: 'do 5935,47 PLN brutto miesięcznie (100% wyższego + 15% niższego)',
    kwotaMin: 297, kwotaMax: 5935,
    czestotliwosc: 'miesięcznie',
    wymagania: { wiekMin: 60, statusWdowiec: true, emeryt: true },
    wykluczenia: [
      { opis: 'Brak prawa do renty rodzinnej po małżonku', sprawdz: 'renta_rodzinna' },
      { opis: 'Ponowne małżeństwo po śmierci współmałżonka', sprawdz: 'stan_cywilny' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS', 'EMPATIA', 'ePUAP'], formularz: 'ZUS-Rwd',
      dokumenty: [
        'Akt zgonu współmałżonka',
        'Akt małżeństwa',
        'Decyzja o przyznaniu renty rodzinnej',
        'Decyzja o przyznaniu własnej emerytury/renty',
      ],
      kroki: [
        'Sprawdź czy pobierasz jednocześnie własną emeryturę/rentę i rentę rodzinną',
        'Pobierz formularz ZUS-Rwd ze strony ZUS lub złóż przez PUE ZUS',
        'Załącz akt zgonu współmałżonka i akt małżeństwa',
        'Złóż wniosek elektronicznie (PUE ZUS), w oddziale ZUS lub pocztą',
        'Czekaj na decyzję ZUS - max 30 dni',
        'Wypłata od miesiąca złożenia wniosku',
      ],
      terminRealizacji: '30 dni od złożenia wniosku',
      pulapki: [
        'Nie ma wyrównania wstecz - wypłata od miesiąca wniosku',
        'Limit 5935,47 PLN brutto łącznie, powyżej pomniejszenie drugiego świadczenia',
        'Ponowne małżeństwo po śmierci małżonka wyklucza świadczenie',
        'Renta rodzinna musiała być nabyta najpóźniej 5 lat przed osiągnięciem wieku emerytalnego',
        'Od 2027 drugie świadczenie wzrośnie do 25% (z 15% w 2026)',
      ],
      odwolanie: 'Odwołanie do sądu okręgowego w ciągu 30 dni od decyzji',
    },
    zrodloUrl: 'https://www.zus.pl/-/wyp%C5%82ata-%C5%9Bwiadcze%C5%84-%C5%82%C4%85cznie-z-rent%C4%85-rodzinn%C4%85-czyli-tzw.-renta-wdowia',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-05-23', dataWaznosci: '2026-12-31',
  },
  {
    id: 'renta-niezdolnosc-pracy', nazwa: 'Renta z tytułu niezdolności do pracy',
    opis: 'Renta z tytułu niezdolności do pracy to comiesięczne świadczenie ZUS dla osób, które utraciły zdolność do pracy z powodu choroby lub utraty sił, a wcześniej opłacały składki. Lekarz orzecznik ZUS orzeka jeden z trzech stopni: całkowita niezdolność (utrata zdolności do jakiejkolwiek pracy), całkowita niezdolność z niezdolnością do samodzielnej egzystencji, albo częściowa niezdolność (utrata zdolności do pracy zgodnej z kwalifikacjami). Kwoty minimalne od 1 marca 2026 (po waloryzacji 5,3%): renta z tytułu całkowitej niezdolności 1978,49 PLN brutto, renta z tytułu częściowej niezdolności 1483,87 PLN brutto. Rzeczywista wysokość obliczana indywidualnie na podstawie zgromadzonych składek i stażu. Warunek stażowy zależy od wieku powstania niezdolności (od 1 roku do 5 lat składkowych i nieskładkowych w ostatnim dziesięcioleciu). Renta może być przyznana na stałe lub okresowo (na czas określony, z koniecznością ponownego badania). Można dorabiać: do 70% przeciętnego wynagrodzenia bez wpływu na świadczenie, między 70% a 130% renta jest zmniejszana, powyżej 130% zawieszana. Wniosek ERN składa się przez PUE ZUS lub w oddziale ZUS z zaświadczeniem OL-9 od lekarza prowadzącego i dokumentacją medyczną. Nie myl jej z rentą socjalną (dla niezdolności powstałej przed 18 r.ż.) ani rentą rodzinną (po zmarłym).',
    kategoria: 'ZUS',
    kwota: 'min. 1978,49 PLN brutto (całkowita) lub 1483,87 PLN brutto (częściowa) miesięcznie, od marca 2026',
    kwotaMin: 1484, kwotaMax: 1978,
    czestotliwosc: 'miesięcznie',
    wymagania: {
      niepelnosprawnosc: ['lekki', 'umiarkowany', 'znaczny'],
      zatrudnienie: ['umowa_o_prace', 'umowa_zlecenie', 'dzialalnosc'],
    },
    wykluczenia: [
      { opis: 'Lekarz orzecznik ZUS nie stwierdził niezdolności do pracy (samo orzeczenie o niepełnosprawności nie wystarcza)', sprawdz: 'orzeczenie_niezdolnosci' },
      { opis: 'Brak wymaganego okresu składkowego i nieskładkowego (od 1 do 5 lat zależnie od wieku powstania niezdolności)', sprawdz: 'staz_skladkowy' },
      { opis: 'Ustalone prawo do emerytury', sprawdz: 'prawo_do_emerytury' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS ERN (wniosek o rentę z tytułu niezdolności do pracy)',
      dokumenty: [
        'Wniosek ZUS ERN',
        'Zaświadczenie o stanie zdrowia OL-9 (wypełnia lekarz prowadzący, ważne 30 dni)',
        'Dokumentacja medyczna potwierdzająca niezdolność do pracy',
        'Wywiad zawodowy OL-10 z miejsca pracy',
        'Dokumenty potwierdzające okresy składkowe i nieskładkowe',
      ],
      kroki: [
        'Lekarz prowadzący wypełnia zaświadczenie OL-9 (nie starsze niż 30 dni w dniu złożenia)',
        'Zbierz dokumentację medyczną i dokumenty potwierdzające staż',
        'Wypełnij wniosek ZUS ERN przez PUE ZUS lub w oddziale ZUS',
        'Lekarz orzecznik ZUS bada i wydaje orzeczenie o stopniu niezdolności',
        'ZUS wydaje decyzję i wypłaca rentę co miesiąc',
      ],
      terminRealizacji: '30-60 dni od złożenia wniosku (w tym badanie przez lekarza orzecznika)',
      pulapki: [
        'Samo orzeczenie o niepełnosprawności to nie to samo co orzeczenie o niezdolności do pracy ZUS',
        'Renta okresowa wygasa, trzeba złożyć wniosek o ponowne ustalenie przed końcem okresu',
        'Dorabianie powyżej 70% przeciętnego wynagrodzenia zmniejsza rentę, powyżej 130% zawiesza',
        'Zaświadczenie OL-9 jest ważne tylko 30 dni, nie składaj wniosku ze starym',
      ],
      odwolanie: 'Sprzeciw do Komisji Lekarskiej ZUS w ciągu 14 dni od orzeczenia, potem odwołanie do Sądu Pracy w ciągu 30 dni od decyzji',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/renty/renty-z-tytulu-niezdolnosci-do-pracy',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-06-29', dataWaznosci: '2026-12-31',
  },
  {
    id: 'swiadczenie-uzupelniajace-500', nazwa: 'Świadczenie uzupełniające 500+ dla niesamodzielnych',
    opis: 'Świadczenie uzupełniające (potocznie "500+ dla niepełnosprawnych" lub "500+ dla niesamodzielnych") to dodatek do 500 PLN miesięcznie dla osób, które ukończyły 18 lat i mają orzeczenie o niezdolności do samodzielnej egzystencji. Kluczowy mechanizm to próg dochodowy działający na zasadzie "złotówka za złotówkę". Od 1 marca 2026 (po waloryzacji): pełne 500 PLN przysługuje, jeśli Twój dochód z innych świadczeń (renta, emerytura) nie przekracza 2187,67 PLN brutto. Jeśli dochód mieści się między 2187,67 a 2687,67 PLN, świadczenie jest pomniejszane o nadwyżkę ponad 2187,67 PLN. Przy dochodzie powyżej 2687,67 PLN świadczenie nie przysługuje wcale. Do progu dochodowego wlicza się większość świadczeń pieniężnych z ZUS, KRUS i innych organów, ale NIE wlicza się m.in. renty rodzinnej dla dziecka, zasiłku pielęgnacyjnego, dodatku pielęgnacyjnego ani świadczenia wspierającego. Wymagane orzeczenie o niezdolności do samodzielnej egzystencji (lub dawne orzeczenie o całkowitej niezdolności do pracy i samodzielnej egzystencji). Wniosek ESUN składa się w ZUS (lub KRUS, jeśli tam jesteś ubezpieczony). Świadczenie jest wolne od podatku i nie podlega egzekucji.',
    kategoria: 'ZUS',
    kwota: 'do 500 PLN miesięcznie (zasada złotówka za złotówkę, próg 2687,67 PLN od marca 2026)',
    kwotaMin: 0, kwotaMax: 500,
    czestotliwosc: 'miesięcznie',
    wymagania: {
      wiekMin: 18,
      niepelnosprawnosc: ['znaczny'],
    },
    wykluczenia: [
      { opis: 'Brak orzeczenia o niezdolności do samodzielnej egzystencji', sprawdz: 'niezdolnosc_samodzielna_egzystencja' },
      { opis: 'Dochód z innych świadczeń przekracza 2687,67 PLN brutto (od marca 2026)', sprawdz: 'prog_dochodowy_500' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS ESUN (wniosek o świadczenie uzupełniające)',
      dokumenty: [
        'Wniosek ZUS ESUN',
        'Orzeczenie o niezdolności do samodzielnej egzystencji (lub orzeczenie o znacznym stopniu niepełnosprawności jako podstawa do wydania orzeczenia ZUS)',
        'Zaświadczenie o stanie zdrowia OL-9 (jeśli orzeczenie wydaje lekarz orzecznik ZUS)',
        'Dowód osobisty',
      ],
      kroki: [
        'Sprawdź, czy masz orzeczenie o niezdolności do samodzielnej egzystencji (jeśli nie, ZUS wyda je w trakcie postępowania)',
        'Wypełnij wniosek ZUS ESUN przez PUE ZUS lub w oddziale ZUS',
        'Jeśli ubezpieczenie masz w KRUS, wniosek złóż w KRUS',
        'ZUS sprawdzi Twój dochód z innych świadczeń i ustali kwotę',
        'Świadczenie wypłacane co miesiąc razem z rentą/emeryturą lub osobno',
      ],
      terminRealizacji: '30 dni od wyjaśnienia ostatniej okoliczności (do 60 dni przy badaniu lekarskim)',
      pulapki: [
        'Zasada złotówka za złotówkę: im wyższa renta/emerytura, tym niższe świadczenie',
        'Do progu nie wlicza się m.in. zasiłku i dodatku pielęgnacyjnego ani świadczenia wspierającego',
        'Wymagane orzeczenie o niezdolności do SAMODZIELNEJ EGZYSTENCJI, nie samej niezdolności do pracy',
        'Świadczenie wspierające i to świadczenie to dwa różne tytuły, sprawdź co jest korzystniejsze',
      ],
      odwolanie: 'Sprzeciw do Komisji Lekarskiej ZUS w ciągu 14 dni od orzeczenia, potem odwołanie do Sądu Pracy',
    },
    zrodloUrl: 'https://www.zus.pl/ustalanie-uprawnien-do-swiadczen/swiadczenie-dla-osob-niezdolnych-do-samodzielnej-egzystencji',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-06-29', dataWaznosci: '2026-12-31',
  },
  {
    id: 'swiadczenie-honorowe-100', nazwa: 'Świadczenie honorowe dla stulatków (100+)',
    opis: 'Świadczenie honorowe to comiesięczna dożywotnia wypłata dla osób, które ukończyły 100 lat. Kwota jest ustalana w dniu ukończenia 100 lat na podstawie obowiązującej wtedy kwoty bazowej, a następnie waloryzowana co roku 1 marca razem z emeryturami (od 2025 r. wcześniej zamrożona kwota jest corocznie podnoszona). Dla osób, które kończą 100 lat po 1 marca 2026, świadczenie wynosi 6938,92 PLN brutto miesięcznie. Przysługuje niezależnie od tego, czy stulatek pobiera emeryturę lub rentę, i nie zależy od dochodu. Osoby pobierające emeryturę lub rentę z ZUS otrzymują świadczenie honorowe automatycznie, z urzędu, bez składania wniosku, ZUS przyznaje je od miesiąca ukończenia 100 lat. Osoby, które nie mają żadnego świadczenia z ZUS (np. nigdy nie pracowały), muszą złożyć wniosek z dokumentem potwierdzającym datę urodzenia. Świadczenie jest opodatkowane podatkiem dochodowym i podlega składce zdrowotnej, ale i tak stanowi znaczące wsparcie. Wypłacane razem z emeryturą lub rentą.',
    kategoria: 'ZUS',
    kwota: '6938,92 PLN brutto miesięcznie (osoby kończące 100 lat po 1 marca 2026; potem waloryzowane co roku)',
    kwotaMin: 6939, kwotaMax: 6939,
    czestotliwosc: 'miesięcznie (dożywotnio)',
    wymagania: { wiekMin: 100 },
    wykluczenia: [],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'Brak (z urzędu dla emerytów/rencistów) lub wniosek o świadczenie honorowe',
      dokumenty: [
        'Dla emerytów/rencistów: brak, ZUS przyznaje automatycznie',
        'Dla osób bez świadczenia ZUS: wniosek i dokument potwierdzający datę urodzenia',
        'Dowód osobisty',
      ],
      kroki: [
        'Jeśli pobierasz emeryturę lub rentę z ZUS, świadczenie jest przyznawane automatycznie od miesiąca ukończenia 100 lat',
        'Jeśli nie masz żadnego świadczenia z ZUS, złóż wniosek w oddziale ZUS',
        'Dołącz dokument potwierdzający datę urodzenia',
        'ZUS wypłaca świadczenie honorowe razem z emeryturą/rentą lub osobno',
      ],
      terminRealizacji: 'Automatycznie od miesiąca ukończenia 100 lat (emeryci/renciści) lub 30 dni od wniosku',
      pulapki: [
        'Kwotę ustala się w dniu ukończenia 100 lat, potem rośnie co roku przy marcowej waloryzacji',
        'Brak progu dochodowego, przysługuje każdemu stulatkowi',
        'Emeryci i renciści dostają z urzędu, bez wniosku',
        'Świadczenie jest opodatkowane i podlega składce zdrowotnej',
      ],
      odwolanie: 'Odwołanie do Sądu Pracy w ciągu 30 dni od decyzji ZUS',
    },
    zrodloUrl: 'https://www.zus.pl/ustalanie-uprawnien-do-swiadczen/wiadczenie-honorowe-dla-osob-ktore-skonczyly-100-lat',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-06-29', dataWaznosci: '2026-12-31',
  },
  {
    id: 'nauczycielskie-swiadczenie-kompensacyjne', nazwa: 'Nauczycielskie świadczenie kompensacyjne',
    opis: 'Nauczycielskie świadczenie kompensacyjne to wcześniejsze świadczenie dla nauczycieli, którzy chcą zakończyć pracę przed osiągnięciem powszechnego wieku emerytalnego. Odpowiednik emerytury pomostowej, ale dedykowany nauczycielom. Przysługuje nauczycielom szkół, przedszkoli, placówek opiekuńczo-wychowawczych i innych jednostek wymienionych w ustawie. Warunki łączne: osiągnięcie wymaganego wieku (rośnie etapowo, w 2026 to 56 lat dla kobiet i 61 lat dla mężczyzn, od 2027 odpowiednio 57 i 62 lata), staż ubezpieczeniowy co najmniej 30 lat, w tym co najmniej 20 lat pracy nauczycielskiej w wymiarze co najmniej połowy etatu, oraz rozwiązanie stosunku pracy na własny wniosek. Wysokość obliczana indywidualnie według tych samych zasad co emerytura (kapitał podzielony przez dalsze trwanie życia), nie może być niższa niż najniższa emerytura, czyli 1978,49 PLN brutto od marca 2026. Świadczenie przysługuje do osiągnięcia powszechnego wieku emerytalnego, potem przechodzi w zwykłą emeryturę. Po przyznaniu można podjąć pracę, ale nie w szkole ani placówce oświatowej, w przeciwnym razie świadczenie jest zawieszane. Wniosek ENSK składa się w ZUS.',
    kategoria: 'ZUS',
    kwota: 'obliczane indywidualnie, min. 1978,49 PLN brutto (od marca 2026, średnio ok. 4200 PLN)',
    kwotaMin: 1978, kwotaMax: 4200,
    czestotliwosc: 'miesięcznie',
    wymagania: {
      wiekMin: 55,
      zatrudnienie: ['umowa_o_prace'],
    },
    wykluczenia: [
      { opis: 'Brak co najmniej 30 lat stażu, w tym 20 lat pracy nauczycielskiej w wymiarze min. 1/2 etatu', sprawdz: 'staz_nauczycielski' },
      { opis: 'Stosunek pracy nie został rozwiązany na własny wniosek nauczyciela', sprawdz: 'rozwiazanie_stosunku_pracy' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS ENSK (wniosek o nauczycielskie świadczenie kompensacyjne)',
      dokumenty: [
        'Wniosek ZUS ENSK',
        'Świadectwa pracy potwierdzające okresy pracy nauczycielskiej',
        'Zaświadczenie o wymiarze zatrudnienia (min. 1/2 etatu)',
        'Dokumenty potwierdzające okresy składkowe i nieskładkowe',
        'Dowód osobisty',
      ],
      kroki: [
        'Sprawdź, czy spełniasz warunki wieku, stażu (30 lat) i stażu nauczycielskiego (20 lat)',
        'Rozwiąż stosunek pracy na własny wniosek',
        'Zbierz świadectwa pracy i zaświadczenia o wymiarze etatu',
        'Wypełnij wniosek ZUS ENSK przez PUE ZUS lub w oddziale ZUS',
        'ZUS zweryfikuje staż i wyda decyzję',
      ],
      terminRealizacji: '30 dni od złożenia kompletnego wniosku',
      pulapki: [
        'Wymóg wieku rośnie etapowo, sprawdź aktualny próg dla swojego rocznika',
        'Trzeba rozwiązać stosunek pracy z własnej inicjatywy, nie wystarczy wypowiedzenie przez szkołę',
        'Podjęcie pracy w szkole lub placówce oświatowej powoduje zawieszenie świadczenia',
        'Świadczenie przechodzi w zwykłą emeryturę po osiągnięciu wieku emerytalnego',
      ],
      odwolanie: 'Odwołanie do Sądu Pracy w ciągu 30 dni od decyzji ZUS',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/emerytury/emerytura-dla-osob-urodzonych-po-31-grudnia-1948/emerytury-wczesniejsze/nauczycielskie-swiadczenia-kompensacyjne',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-06-29', dataWaznosci: '2026-12-31',
  },
  {
    id: 'dodatek-sieroty-zupelnej', nazwa: 'Dodatek dla sieroty zupełnej',
    opis: 'Dodatek dla sieroty zupełnej to świadczenie doliczane do renty rodzinnej dla dziecka, które straciło oboje rodziców. Przysługuje uprawnionemu do renty rodzinnej, który jest sierotą zupełną, czyli zmarli oboje jego rodzice (lub jedno z rodziców nie żyje, a ojcostwo/macierzyństwo drugiego nigdy nie zostało ustalone). Kwota od 1 marca 2026 (po waloryzacji 5,3%) to 689,17 PLN miesięcznie. Dodatek jest wolny od podatku dochodowego i nie podlega składce zdrowotnej, więc wypłacany w pełnej kwocie. Doliczany jest do każdej renty rodzinnej osobno, więc jeśli kilkoro rodzeństwa pobiera rentę rodzinną, każde z nich otrzymuje własny dodatek. Przysługuje na tych samych zasadach wiekowych co renta rodzinna: do 16 roku życia, lub do 25 roku życia jeśli dziecko kontynuuje naukę (lub bezterminowo, jeśli niezdolność do pracy powstała przed 16 r.ż. lub w trakcie nauki). Dodatek przyznawany jest na wniosek, najczęściej składany razem z wnioskiem o rentę rodzinną. Jeśli sierota zupełna już pobiera rentę rodzinną bez dodatku, można złożyć wniosek o jego przyznanie osobno.',
    kategoria: 'ZUS',
    kwota: '689,17 PLN miesięcznie (od marca 2026, wolne od podatku)',
    kwotaMin: 689, kwotaMax: 689,
    czestotliwosc: 'miesięcznie',
    wymagania: { wiekMax: 25 },
    wykluczenia: [
      { opis: 'Brak prawa do renty rodzinnej', sprawdz: 'renta_rodzinna' },
      { opis: 'Co najmniej jedno z rodziców żyje (nie jest sierotą zupełną)', sprawdz: 'sierota_zupelna' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'Wniosek o rentę rodzinną ERR lub osobny wniosek o dodatek',
      dokumenty: [
        'Akty zgonu obojga rodziców',
        'Decyzja o przyznaniu renty rodzinnej (jeśli już przyznana)',
        'Zaświadczenie ze szkoły/uczelni (dla osób 16-25 lat)',
        'Dowód osobisty lub akt urodzenia',
      ],
      kroki: [
        'Przygotuj akty zgonu obojga rodziców',
        'Jeśli składasz wniosek o rentę rodzinną, zaznacz że jesteś sierotą zupełną',
        'Jeśli już pobierasz rentę rodzinną, złóż osobny wniosek o dodatek',
        'ZUS dolicza dodatek do renty rodzinnej co miesiąc',
      ],
      terminRealizacji: '30 dni od złożenia wniosku',
      pulapki: [
        'Dodatek jest wolny od podatku, wypłacany w pełnej kwocie',
        'Każde rodzeństwo pobierające rentę rodzinną dostaje własny dodatek',
        'Waloryzowany co roku 1 marca razem z rentami',
        'Jeśli ustalono ojcostwo/macierzyństwo żyjącego rodzica, nie jesteś już sierotą zupełną',
      ],
      odwolanie: 'Odwołanie do Sądu Pracy w ciągu 30 dni od decyzji ZUS',
    },
    zrodloUrl: 'https://www.zus.pl/swiadczenia/renty/renta-rodzinna',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-06-03', dataWaznosci: '2026-12-31',
  },
  {
    id: 'renta-szkoleniowa', nazwa: 'Renta szkoleniowa (na przekwalifikowanie)',
    opis: 'Renta szkoleniowa to czasowe świadczenie ZUS dla osób, które utraciły zdolność do pracy w dotychczasowym zawodzie, ale lekarz orzecznik ZUS uznał celowość przekwalifikowania zawodowego do innej pracy. To rozwiązanie pomostowe: zamiast renty z tytułu niezdolności do pracy ZUS finansuje okres, w którym osoba zdobywa nowe kwalifikacje. Renta szkoleniowa wynosi 75% podstawy wymiaru, ale nie mniej niż najniższa renta z tytułu częściowej niezdolności do pracy (1483,87 PLN brutto od marca 2026). Jeśli niezdolność powstała wskutek wypadku przy pracy lub choroby zawodowej, renta wynosi 100% podstawy (nie mniej niż 1978,49 PLN brutto). Przyznawana na 6 miesięcy, z możliwością przedłużenia do maksymalnie 36 miesięcy, jeśli wymaga tego proces przekwalifikowania. O przekwalifikowaniu i skierowaniu na szkolenie decyduje starosta (powiatowy urząd pracy), do którego ZUS kieruje informację. Renta szkoleniowa nie przysługuje osobie, która ma już ustalone prawo do emerytury lub osiąga przychód powodujący zawieszenie. Po zakończeniu przekwalifikowania osoba może podjąć nową pracę zgodną z nabytymi kwalifikacjami.',
    kategoria: 'ZUS',
    kwota: '75% podstawy (min. 1483,87 PLN) lub 100% przy wypadku/chorobie zawodowej (min. 1978,49 PLN), od marca 2026',
    kwotaMin: 1484, kwotaMax: 1978,
    czestotliwosc: 'miesięcznie (6-36 miesięcy)',
    wymagania: {
      zatrudnienie: ['umowa_o_prace', 'umowa_zlecenie', 'dzialalnosc'],
    },
    wykluczenia: [
      { opis: 'Lekarz orzecznik ZUS nie uznał celowości przekwalifikowania zawodowego', sprawdz: 'celowosc_przekwalifikowania' },
      { opis: 'Ustalone prawo do emerytury lub renty z tytułu niezdolności do pracy', sprawdz: 'inne_swiadczenia' },
    ],
    wniosek: {
      kanal: ['PUE_ZUS'],
      formularz: 'ZUS ERN (wniosek o rentę, z orzeczeniem o celowości przekwalifikowania)',
      dokumenty: [
        'Wniosek ZUS ERN',
        'Zaświadczenie o stanie zdrowia OL-9',
        'Dokumentacja medyczna',
        'Wywiad zawodowy OL-10',
        'Dowód osobisty',
      ],
      kroki: [
        'Lekarz prowadzący wypełnia zaświadczenie OL-9',
        'Złóż wniosek ZUS ERN przez PUE ZUS lub w oddziale ZUS',
        'Lekarz orzecznik ZUS ocenia niezdolność i celowość przekwalifikowania',
        'ZUS przyznaje rentę szkoleniową na 6 miesięcy i kieruje informację do starosty (PUP)',
        'PUP organizuje szkolenie zawodowe, okres można przedłużyć do 36 miesięcy',
      ],
      terminRealizacji: '30-60 dni od złożenia wniosku (w tym badanie przez lekarza orzecznika)',
      pulapki: [
        'To świadczenie czasowe, nie dożywotnia renta, służy zdobyciu nowego zawodu',
        'Wymaga orzeczenia o CELOWOŚCI PRZEKWALIFIKOWANIA, nie tylko niezdolności',
        'O szkoleniu decyduje starosta (PUP), nie ZUS',
        'Mało znane świadczenie, wielu uprawnionych o nim nie wie',
      ],
      odwolanie: 'Sprzeciw do Komisji Lekarskiej ZUS w ciągu 14 dni od orzeczenia, potem odwołanie do Sądu Pracy',
    },
    zrodloUrl: 'https://www.zus.pl/renta-szkoleniowa',
    zrodloNazwa: 'ZUS', dataWeryfikacji: '2026-06-29', dataWaznosci: '2026-12-31',
  },
];
